### ISSUE TITLE
Fix up readme, license, etc

### ISSUE THREAD

**Issue by bketelsen** [gomods/athens#1]
change to team ownership

**Comment by arschles** [comment]
I think this is done? @bketelsen can you close if so?

**Comment by leighmcculloch** [comment]
The license still reads personal copyright ownership.

https://github.com/gomods/athens/blob/097fde39570b17ca2c180257980050eaeb86e465/LICENSE#L3

Are there plans for Athens to be an official Go thing? Could Athens fall into the golang family of repos, and sport the standard Go contribution licensing/authorship model?

**Comment by robjloranger** [comment]
It should be community owned. Brian is working on getting an organisation set up, like a trust. So no one company has control of Athens.

**Comment by arschles** [comment]
+ 💯 - I completely overlooked the license file @leighmcculloch (for context, this codebase used to be in my personal repo way back when). I'll submit a PR to fix that but going to leave this issue open if anyone else finds stuff that needs updating

**Comment by robjloranger** [comment]
closed via #387
