### ISSUE TITLE
Feature: Module publishing API

### ISSUE THREAD

**Issue by bketelsen** [gomods/athens#10]
Create an API that allows module authors to publish modules from their CI/CD systems like Travis.

Possibly this could be as simple as a webhook integration.

**Comment by arschles** [comment]
In the case of Travis etc..., I'd say we have folks do it from the `athens` CLI (which effectively would call an a webhook with a bearer token)

**Comment by robjloranger** [comment]
cli is gone now, however see #106 for reference re: CI/CD

**Comment by arschles** [comment]
We're focusing on a pure proxy approach right now, where Athens fills its storage with code from the VCS only. I'm closing this now, and we can revisit a publishing API and/or webhook in the future. Closing
