### ISSUE TITLE
can't get new commit, when no version tag

### ISSUE THREAD

**Issue by zturning** [gomods/athens#1000]
use a no version tag, example: `github.com/kataras/pio`

run this when no `github.com/kataras/pio` in disk

```shell
# download commit: v0.0.0-20180502220154-1d218932f864
curl localhost:3000/github.com/kataras/pio/@v/v0.0.0-20180502220154-1d218932f864.info

# looking version, and will list v0.0.0-20180502220154-1d218932f864
curl localhost:3000/github.com/kataras/pio/@v/list

# actually, it has a new v0.0.0-20180511174041-a9733b5b6b83,
# so, when I do tidy on module(GO111MODULE=on go mod tidy), it can't pull this
```

**Comment by marpio** [comment]
Our `/list` endpoint returns merged results from the storage and from `go list -m -versions -json`. 
If a module has no version (like in this case) the json structure returned by go cmd doesn't contain the `Versions` field which we use for the `/list` endpoint.
```
go list -m -versions -json github.com/kataras/pio       
{
        "Path": "github.com/kataras/pio",
        "Version": "v0.0.0-20180511174041-a9733b5b6b83",
        "Time": "2018-05-11T17:40:41Z",
        "Indirect": true,
        "Dir": "/home/piotr/go/pkg/mod/github.com/kataras/pio@v0.0.0-20180511174041-a9733b5b6b83",
        "GoMod": "/home/piotr/go/pkg/mod/cache/download/github.com/kataras/pio/@v/v0.0.0-20180511174041-a9733b5b6b83.mod"
}
```
This means `/list` will only give the versions from the storage - in this case the one which was requested by `curl localhost:3000/github.com/kataras/pio/@v/v0.0.0-20180502220154-1d218932f864.info` and not necessary the most latest one.

We could theoretically use the `Version` field if no tag is present but I'm not sure what side effects this would have.

**Comment by marpio** [comment]
Since go 1.12 is there, I will take that.
