### ISSUE TITLE
Add defaults for Athens config values

### ISSUE THREAD

**Issue by arschles** [gomods/athens#1008]
**Is your feature request related to a problem? Please describe.**

If you don't pass Athens a config file, it won't have all the configuration values that it needs

**Describe the solution you'd like**

I'd like all of the default configurations that we see in the sample config file to be hard-coded into the binary, so that you only need to use the config file, or set environment variables, to override the defaults if you need to

**Describe alternatives you've considered**

None

**Additional context**

We discussed this during tghe Dec 20, 2018 dev meeting

**Comment by michalpristas** [comment]
sorry I missed the discussion during the syncup. my 0.02€: defaults may make you feel that everything is OK after you deploy to your prod cluster but the opposite is true. 
i would rather fail fast
