### ISSUE TITLE
Minio saver: wrong path for module  .info

### ISSUE THREAD

**Issue by Zyqsempai** [gomods/athens#1023]
**Describe the bug**
Minio saver sets extra version for a module `.info`, module path already contains version
Module path: `github.com/gomods/testCatalogModule/v1.2.0014`
Extra version: `v1.2.0014`
Result: `github.com/gomods/testCatalogModule/v1.2.0009/v1.2.0009.info`
https://github.com/gomods/athens/blob/master/pkg/storage/minio/saver.go#L20

I can solve it in the scope of https://github.com/gomods/athens/issues/996

**Comment by Zyqsempai** [comment]
@fedepaol Can you check this one?

**Comment by manugupt1** [comment]
@Zyqsempai I looked into it a bit. Seems like it can be done in its own PR. I would prefer to do it that way unless absolutely necessary.

Let me know what do you think.

**Comment by fedepaol** [comment]
Agree with that, unless it blocks the minio catalog.
In any case it could be fixed & merged before the other

**Comment by Zyqsempai** [comment]
Agree, opened PR to fix it. Better if we will merge it asap, cause catalog method implementation, related to this issue.

**Comment by arschles** [comment]
@Zyqsempai I wanted to let you know on this that we're going to hold off on it until after we release [v0.3.0](https://github.com/gomods/athens/projects/2), because it has a potential breaking change. We haven't forgotten about it though!

**Comment by Zyqsempai** [comment]
@arschles Ok, thanks!

**Comment by marpio** [comment]
@Zyqsempai I'm closing this since the change would require a breaking change.
