### ISSUE TITLE
Filter module version

### ISSUE THREAD

**Issue by bogdanbiv** [gomods/athens#1045]
**Is your feature request related to a problem? Please describe.**
Is it possible to set up filter rules based on version ranges / regexp?

**Describe the solution you'd like**

    # deny every version of my-first-ex-dependency... except
    - github.com/my-first-ex-dependency v0.0.*
    # except version 20180906233101
    + github.com/abc/my-other-mod v0.0.0-20180906233101-161cd47e91fd

**Describe alternatives you've considered**
The alternative is to mirror every dependency module used to be able to filter / lock to a few approved & tested versions.

**Additional context**
This comes out of the need for organizational compliance & the need to review every piece of dependency.

**Comment by michalpristas** [comment]
Hey @bogdanbiv thanks for reaching out.
All except {ver} is not supported at the moment. 
To be frank we haven't thought about at all but i like the idea and will add that to the meeting notes to see what we can do about it

**Comment by bogdanbiv** [comment]
could you give an example of how {ver} works, because it's not obvious in the doc page at https://docs.gomods.io/configuration/filter/ ?

**Comment by michalpristas** [comment]
right now, it is just as simple as prefix
so if some of the rules defined can be understood as a prefix of the module name, the rule is applied.
version filtering as said before, is not supported yet
