### ISSUE TITLE
Documentation: Clarify how git tag mutability is treated

### ISSUE THREAD

**Issue by MMulthaupt** [gomods/athens#1054]
**Is your feature request related to a problem? Please describe.**
I followed the `Shared Team Instance` guide at https://docs.gomods.io/install/shared-team-instance/ which is linked to indirectly from `README.md` by `try it out` through https://docs.gomods.io/install/
where I expected some words on git tag mutability. While `GOPROXY` addresses the threat posed by potential deletion or otherwise inaccessibility of remotely hosted go modules, there is a second big concern which is that the repository owner can change the git tags which Go uses for versioning.

**Describe the solution you'd like**
The `Shared Team Instance` guide – being the likely first document to be used by developers to give Athens a try – should mention how Athens deals with this scenario, i.e. does it update its storage with the remote commit if the tags changed, or does it not?

**Describe alternatives you've considered**
Disregard the issue and believe in the competence and goodwill of the open source community.

**Additional context**
Tag mutability is among the concerns of reproducible builds, so how it is dealt with should be mentioned.

**Comment by MMulthaupt** [comment]
Here is some motivation from a recent incident: https://github.com/go-ole/go-ole/issues/185

**Comment by arschles** [comment]
@MMulthaupt good catch, we should certainly have that information in the docs. I'll take this one and mention you on the PR when I submit it, so you can let us know if it answers your question.

**Comment by arschles** [comment]
@MMulthaupt I created https://github.com/gomods/athens/pull/1095 - let me know what you think!
