### ISSUE TITLE
Question/Help: Use Athens behind workspace proxy 

### ISSUE THREAD

**Issue by codingonHP** [gomods/athens#1055]
I have locally hosted Athens on my machine which is connected to office network behind a proxy.
How do I configure Athens to use workspace proxy so that it goes to internet to download dependencies?

**Comment by chriscoffee** [comment]
This was closed as @fedepaol ansnwered @codingonHP's question on slack. For those interested, the anwer is located here https://gophers.slack.com/archives/C9LRAQN8N/p1550137035029600

**Comment by codingonHP** [comment]
I should have mentioned the reason for close as well. For anyone interested
https://docs.docker.com/network/proxy/
So, the idea is to start the container with 

> --env HTTP_PROXY="http://127.0.0.1:3001"
 > --env HTTPS_PROXY="https://127.0.0.1:3001"
