### ISSUE TITLE
Add build caches to the Azure pipelines yaml file

### ISSUE THREAD

**Issue by arschles** [gomods/athens#1057]
**Is your feature request related to a problem? Please describe.**

In the past, we've done various things to make the azure pipelines CI builds run faster and they're still kinda slow. IIRC a lot of it was related to downloading mongo in order to run integration tests

**Describe the solution you'd like**

I think we can use the new Azure pipelines caching stuff they just released to speed things up

**Describe alternatives you've considered**

None

**Additional context**

Caching isn't released yet, but the spec is developing on Github. [Here](https://devblogs.microsoft.com/devops/adding-caching-to-azure-pipelines/) is the announcement and [here](https://github.com/Microsoft/azure-pipelines-yaml/pull/113) is the WIP PR for the spec updates to the yaml file.

cc/ @marpio since I know you, me and others were talking about the slowness of Az pipelines builds a while ago

**Comment by marpio** [comment]
@arschles I'm closing it since we do not use azure pipelines anymore.
