### ISSUE TITLE
Elaborate hooks for different CI

### ISSUE THREAD

**Issue by michalpristas** [gomods/athens#106]
Similiarly to VCS hook this will be used by most common CI tools (jenkins, travis etc.)

Elaborate possibilities of using webhook for different CIs like Jenkins, Travis etc

Output of this task is set of issues describing requirement for each CI

**Comment by robjloranger** [comment]
I this meant to be a way for projects to notify on new tagged releases?

**Comment by michalpristas** [comment]
Yes indeed @robjloranger

**Comment by arschles** [comment]
This is related to #10

**Comment by arschles** [comment]
As of #772 we're focusing on a global proxy and not a registry. Since this issue is a registry feature, I'm closing.
