### ISSUE TITLE
Perfomance issue on ListObject in minio client

### ISSUE THREAD

**Issue by Zyqsempai** [gomods/athens#1060]
**Describe the bug**
Exponential growth of the execution time on Minio-Go-client method `ListObjectsV2` or `ListObjects`

**To Reproduce**
Run minio test with more then 100 items.

**Expected behavior**
Linear growth of the execution time.

**Additional context**
Those issues already reported to minio:
https://github.com/minio/minio/issues/1516
https://github.com/minio/minio/issues/1735

PR which one introdiced those functions to Athens:
https://github.com/gomods/athens/pull/1040

**Comment by arschles** [comment]
@Zyqsempai do we still have this after minio/minio#1516 and minio/minio#1735 are both closed?

**Comment by DrPsychick** [comment]
Closing this as gone cold. Please create a new issue if the issue persists.
