### ISSUE TITLE
[Proposal] Investigate speeding up go list

### ISSUE THREAD

**Issue by manugupt1** [gomods/athens#1065]
**Is your feature request related to a problem? Please describe.**
Speed up  go list by determining successfully when all the versions have been fetched.

**Describe the solution you'd like**
https://github.com/gomods/athens/commit/0b2aece18d1b29b2a70cf707302b944a604097bd

The above commit speeds up go list.

**Describe alternatives you've considered**
We can think about speeding up by cancelling one of the go routines if the other one is guaranteed to fetch all the versions.

So, if go get can satisfy all versions and finishes before storage.List then we can safely ignore storage.List and vice versa

**Additional context**

**Comment by manugupt1** [comment]
Okay! I am convincing myself not to do this. 

Here is the scenario.
We do a
`go get module`
The module downloads v1, v2, v3
The VCS does a force push on tag and removes V2

If go get succeeds before storage.List on go list, then we would only get V1, V3; however the storage has V2

On the other hand, 
If did 
`go get module` in the past,
but a user has added a new tag ie: v4
and did a `go list` and if the storage finishes before v4, then would get V1, V2, V3 while V4 won't be fetched as the `go list` is cancelled.

Thus, we cannot guarantee until these two operations have completed that we can fetch the most comprehensive set of versions.

**Comment by marpio** [comment]
@manugupt1 yes, we need to wait for both results here for the reasons you mentioned above and also because we have to know if there was a failure and what kind of error it was.

**Comment by manugupt1** [comment]
I am closing this issue as this makes no sense to pursue this optimization anymore!
