### ISSUE TITLE
Incompatible checksums on Athens v0.2.0 docker with go.sum generated by Go >= 1.11.4

### ISSUE THREAD

**Issue by machiel** [gomods/athens#1080]
**Describe the bug**
My go.sum is generated using Go 1.11.5, however the Athens v0.2.0 image I pull from docker is running on Go 1.11.2. There has been a fix in 1.11.4 affecting the way checksums are calculated for modules, so now when pulling my dependencies from Athens there's a checksum mismatch, since Athens still uses the 1.11.2 way.

More about this here: https://github.com/golang/go/issues/27925

**Error Message**
```
go: verifying github.com/kylelemons/go-gypsy@v0.0.0-20160905020020-08cad365cd28: checksum mismatch
     downloaded: h1:SzHLOWB819X9aUXh2ct6krDIoIujoTsj5J1rDMjkRyo=
     go.sum:     h1:mkl3tvPHIuPaWsLtmHTybJeoVEW7cbePK73Ir8VtruA=
```

**To Reproduce**
Add for example `kylelemons/go-gypsy` to your go.mod file using go 1.11.5, then try building your application using the Athens v0.2.0 docker image running go 1.11.2.

When rebuilding the image with go 1.11.5 everything works as expected.

**Expected behavior**
To work with go 1.11.4 and higher generated go.sum's. A rebuild of the current docker file should be enough as it relies on 1.11, which is currently an alias for go 1.11.5

**Environment (please complete the following information):**
 - OS: [e.g. Linux 64bit] Linux 64bit
 - Go version : 1.11.2
 - Buffalo Version : -
 - Proxy version : v0.2.0
 - Storage (fs/mongodb/s3 etc.) : fs

**Comment by marwan-at-work** [comment]
@machiel thanks for reporting this. The `canary` version of the docker image uses `go1.12-rc` which should be compatible with 1.11.5. Feel free to give this a try and let us know if the issue still persists. The next releas `v0.3.0` will have 1.12 on by default. 

Also, don't forget to delete that module from your storage backend as it was compiled with pre1.11.5 and will need to be re-compiled with the new `go mod download` command. 

Thanks!

**Comment by machiel** [comment]
Perfect, thanks! I will await the `0.3.0` release, and in the mean time use the canary version.

Thanks!

**Comment by arschles** [comment]
@machiel just FYI, the [v0.3.1](https://github.com/gomods/athens/releases/tag/v0.3.1) release is out. I recommend using that instead of v0.3.0 because it has a fix for the minio storage driver in it

**Comment by machiel** [comment]
@arschles great! Thanks for the update! :)
