### ISSUE TITLE
Publish private module to athens

### ISSUE THREAD

**Issue by tomjamescn** [gomods/athens#1083]
**Is your feature request related to a problem? Please describe.**
In many companies, there are many private packages/modules, how to add these packages/modules to athens?

**Describe the solution you'd like**
Maybe athens have a simple admin ui to add private package/module file and version

**Describe alternatives you've considered**
like other soluntions in other lang such as  maven in java and toran proxy in php

**Additional context**
we need this feature, please!

**Comment by arschles** [comment]
@tomjamescn if you've given your Athens access to your private repository, you can do a `go get` against that Athens and it will store the private module. Did it work like that for you?

**Comment by tomjamescn** [comment]
@arschles  Thanks. does Athens support gerrit server ? I found nothing in doc.

**Comment by arschles** [comment]
@tomjamescn since Gerrit servers support git over SSH, Athens should support it (since it does similar to a `go get` on the backend)

**Comment by arschles** [comment]
@tomjamescn I'm going to close this issue now, but please feel free to open a new one if you have more questions!
😀

**Comment by arschles** [comment]
Also, I added https://github.com/gomods/athens/issues/1137 to remind us to add documentation for what VCS servers Athens supports. Thanks again @tomjamescn !
