### ISSUE TITLE
Get the gomods.io domain transferred to a registrar that maintainers can collectively administer

### ISSUE THREAD

**Issue by arschles** [gomods/athens#1100]
**Is your feature request related to a problem? Please describe.**

Right now, gomods.io is registered with godaddy, and we don't know who owns it, so we can't do much to add subdomains, etc...

**Describe the solution you'd like**

Let's find that person and get the domain transferred somewhere that core maintainers can jointly administer it

**Describe alternatives you've considered**

N/A

**Additional context**

This is a follow-up to https://github.com/gomods/athens/pull/1097#issuecomment-468836384

cc/ @carolynvs

**Comment by robjloranger** [comment]
is this still relevant? it looks like the domain is with namecheap now.

**Comment by arschles** [comment]
Yup, this is now done. It also caused some [downtime](https://twitter.com/gomodsio/status/1175447104363233280) in the process, so I double checked it 😆 

Closing
