### ISSUE TITLE
Support for fetching go supported VCSs

### ISSUE THREAD

**Issue by michalpristas** [gomods/athens#111]
Go tool currently supports:
- Git
- Mercurial
- Svn (Subversion)
- Fossil
- Bazaar

Athens currently provides support only for Git. We need to enhance this functionality to catch up with go tool.
Idea: think about reusing functionality from (v)go. 

edit: we currently use generic fetcher which uses go tooling for fetching packages. 
This task covers all specific implementations on top of that

**Comment by marpio** [comment]
@michalpristas right now Athens fetches the archive from Github; the repo pkg doesn't know anything about the VCS. Should that stay this way? That would imply that athens needs to support github, gitlab, vsts, gitea etc. just for git... What if i.e. gitea api doesn't provide an option to download the zip? git pull?

**Comment by arschles** [comment]
@marpio good points. I prefer downloading a zip because it'll be faster than `git clone` in many cases. Can we include support for specific VCS-es and then fall back to `git clone` (or the equivalent for other VCSs) for the rest?

**Comment by michalpristas** [comment]
we should be service independent and be able to fetch anything from any public git whether its bitbucket, git or something else.
But again the same point as aaron mentioned, downloading zip is less stressful skips the boring part when the network connection is warming up (which might delay whole repo download significantly) 
so I'm on the same page with aaron here, specific support for services and fallback to generic source control. 
go tooling explicitely supports these:

> github.com, bitbucket.org, hub.jazz.net, git.apache.org, git.openstack.org, chiselapp.com

and they have some sort of [pattern matching to detect the rest.](https://github.com/golang/vgo/blob/master/vendor/cmd/go/internal/get/vcs.go#L1007) 

So maybe a fallback of using git tooling so we don't reimplement this whole scenario would be also nice and worth investigation

**Comment by michalpristas** [comment]
even if it is so simple as executing go get with custom gopath to tmp directory. this would cover all cases and we can build some more optimized way using public API on top of that

**Comment by robjloranger** [comment]
for git, we could use source{d} go-git library, https://github.com/src-d/go-git

**Comment by marwan-at-work** [comment]
@robjloranger when I was experimenting with vcs stuff, I used src-d's go-git, and it's great. However, git itself does not implement fetching certain files AFAIK.

So when vgo asks for a `.mod` file, we'd have to clone the whole repo. Which is quite costly. I just wanted to mention this somewhere as I have been playing with vcs inside athens. 

On another note, if we're only working with tags, and if vgo implements Proxy -> VCS redirects, would we ever need to have any VCS logic in athens?

**Comment by robjloranger** [comment]
that's a great point. :crossed_fingers: for getting vcs redirects going

**Comment by marpio** [comment]
Can we close this @michalpristas ?

**Comment by michalpristas** [comment]
yes, thanks @marpio
