### ISSUE TITLE
Stasher: Implement Redis SingleFlight

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#1115]
Most cloud platforms provide a redis-compliant  in-memory store and so it's worth trying having a Stasher implementation that locks stashing modules. This way, users wouldn't have to maintain their own Etcd clusters.

**Comment by chriscoffee** [comment]
This is ace @marwan-at-work! We could also mention a few of the fun redis stuff you can do too, or atleast point people to the docs that show it can do `append-only` and persist to disk in our docs

**Comment by marwan-at-work** [comment]
@chriscoffee not too familiar with Redis but interested to know how any of those features you mentioned could help Athens (and the Stasher in particular)
