### ISSUE TITLE
[Proposal] GCS Distributed Locking

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#1123]
This is a proposal to alter the GCS backend storage implementation so it can support distributed locking. Related read: https://cloud.google.com/storage/docs/consistency

There's a pro and a con to this. I believe the pro outweighs the con significantly. 

### Pro
You can run multiple stateless Athens containers and hook them up to a GCS storage and never have to maintain any state at all. No etcd cluster, no redis server and so on. 

### Con 
We need to make sure that the storage.Saver implementation is synchronous and not upload all 3 parts in parallel. This is so that two concurrent requests don't upload parts of each other. 

I have this working locally so I'll be submitting a PR shortly, but I'd love to have this issue open for any discussions or concerns. 

**Important note**: some backend storages don't provide a way to synchronize concurrently. For example, AWS S3 does not provide strong consistency as I was told so if you're running against S3 at scale, you'll need a distributed lock.

**Comment by marpio** [comment]
Nice idea @marwan-at-work ! This should be also possible with Azure Storage.
One question - in a scenario where the upload i.e. succeeded for `mod` and `info` but failed for `zip` would we be able to somehow overwrite the `mod` and ìnfo` the next time we're saving the mod@ver?

Alternatively we could use GCS separately to implement the distributed lock.
Don't know if it's better or not but just wanted to throw in another idea.

This could work as follows:
- To acquire a Lock try to create a file `module@version.lock` (or similar). As long as we get 412 we know the module@version is currently stashed and so we wait a little and try again if we get 200 we can proceed.
- To unlock we try to delete the file until we get 204.

Of course we would need to think about setting some deadline.

Pros of this solution:
- we could leave the uploads parallel
- this implementation could be used independently with any other storage (admittedly it would not happen a lot)
Cons:
- it's not as straightforward as this solution
- also we could have a problem if athens crashes before it unlocks
-

**Comment by marwan-at-work** [comment]
@marpio 
> would we be able to somehow overwrite the mod and ìnfo the next time we're saving the mod@ver?

Yes, the `storage.Delete` method should still work and therefore if something goes wrong, we should be able to clean up with Delete then the next a save happens, we're alright again. 

>also we could have a problem if athens crashes before it unlocks. The minimum life span is 1 day so the module would be locked for the whole day. This might be a no-go.

I didn't know about this limitation, that would leave some unhappy users. 

I did think about just using GCS as a distributed lock like you suggested, but I find the current solution more elegant. We can also only save the first part of the module synchronously and the last two parts concurrently, but that's an optimization I'm not sure how much we need yet.

**Comment by marwan-at-work** [comment]
@marpio I also found a library that does what you suggested: https://github.com/marcacohen/gcslock

It's definitely worth keeping in mind. And I'm very curious to know about Azure's implementation as well. 

Thanks for reviewing!
