### ISSUE TITLE
Add feature about replacing modules

### ISSUE THREAD

**Issue by sevennt** [gomods/athens#1132]
**Is your feature request related to a problem? Please describe.**
Add feature about replacing modules, some modules like ``golang.org/x/tools`` are not easy to 
download because of CN bad network.

By replacing modules in athens, we can replace this modules' path with other reachable path (such as github.com), then we can ``go mod tidy`` smoothly. 

**Describe the solution you'd like**
User adds replacing rules to configuration toml, like [https://docs.gomods.io/configuration/filter/](https://docs.gomods.io/configuration/filter/).

**Describe alternatives you've considered**
none.

**Additional context**
none.

**Comment by arschles** [comment]
@sevennt are you thinking of something like an alias?

**Comment by sevennt** [comment]
@arschles yes

**Comment by arschles** [comment]
Sorry for the long delay @sevennt. There's a similar discussion going on at https://github.com/gomods/athens/issues/1315. Do you have a use case for this?

One possible solution would be to use the [new download mode configuration file](https://docs.gomods.io/configuration/download/) (this was added since we talked last) and introduce a syntax like this:

```hcl
alias "golang.org/x/tools" {
    name "https://github.com/golang/tools"
}
```

Could this work for you?

**Comment by daqingshu** [comment]
> Sorry for the long delay @sevennt. There's a similar discussion going on at #1315. Do you have a use case for this?
> 
> One possible solution would be to use the [new download mode configuration file](https://docs.gomods.io/configuration/download/) (this was added since we talked last) and introduce a syntax like this:
> 
> ```terraform
> alias "golang.org/x/tools" {
>     name "https://github.com/golang/tools"
> }
> ```
> 
> Could this work for you?

I think your idea is great, use alias  syntax is great

**Comment by sevennt** [comment]
@arschles that works, thanks.
