### ISSUE TITLE
failing to get some package

### ISSUE THREAD

**Issue by tfzxyinhao** [gomods/athens#1133]
**Describe the bug**
failing to get some package

**Error Message**
<pre>
```console
go: finding golang.org/x/crypto latest
go: finding golang.org/x/sys latest
go: finding honnef.co/go/tools latest
go: finding golang.org/x/lint latest
go: finding golang.org/x/exp latest
go get: upgrading github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b: Get http://192.168.32.100:3000/github.com/golang/glog/@v/list: read tcp 192.168.32.153:13959->192.168.32.100:3000: wsarecv: An exist
ing connection was forcibly closed by the remote host.
```
</pre>

**To Reproduce**
set ```goproxy=http://192.168.32.100:3000 ```
and then execute ```go get -u github.com/golang/protobuf/proto ```

**Expected behavior**

**Environment (please complete the following information):**
 - OS: windows 10
 - Go version : go1.12 windows/amd64
 - Buffalo Version :
 - Proxy version : 0.2.0
 - Storage (fs/mongodb/s3 etc.) : fs

**Comment by arschles** [comment]
@tfzxyinhao do you have any log output from the Athens server when you found this error?

**Comment by marpio** [comment]
@tfzxyinhao Can you provide more details?
Is it possible to go get the module without athens?

**Comment by arschles** [comment]
@tfzxyinhao I am going to close this issue now. If you still see problems, would you mind opening  a new issue in this repository? Thank you 😁
