### ISSUE TITLE
Add a "one liner" to the home page

### ISSUE THREAD

**Issue by arschles** [gomods/athens#1135]
Many OSS project sites include a quick command that someone can run to try the thing out. The foremost example of this in my mind is [Homebrew](https://brew.sh/) (see screenshot below)

![Screen Shot 2019-03-14 at 11 52 52 AM](https://user-images.githubusercontent.com/70865/54383642-c1d78b00-464f-11e9-8f4e-a1ba4ff7656e.png)

The command they give quickly gets you started and up and running.

I think we should have the `docker run` command featured prominently on the front page of our docs!

This is a follow-up on https://github.com/gomods/athens/pull/1082#pullrequestreview-214245155

**Comment by cByst** [comment]
I'd like to work on this. Are you think adding a section to the readme that looked something like:
# Running A Local Athens Proxy
## Starting Athens Proxy Locally
You will need  [docker](https://www.docker.com/products/docker-desktop) installed on your machine. Then run:
```sh
docker run -p '3000:3000' gomods/athens:latest
```
This command will pull the latest athens docker image and start the Athens proxy on port 3000.
## Pointing ```go get``` To The Local Proxy
```sh
GOPROXY=http://localhost:3000 go get github.com/pkg/errors@latest
```

If this is what you were looking for let me know and I can submit a PR.

**Comment by cByst** [comment]
@arschles is this is what you were thinking? I can submit a PR if it was.

**Comment by Kunde21** [comment]
I'd lean more towards an export over defining for each go command:

```
$ docker run -p '3000:3000' gomods/athens:latest
$ export GOPROXY=http://localhost:3000
```

or a true one-liner:

```
docker run -p '3000:3000' gomods/athens:latest && export GOPROXY=http://localhost:3000
```

**Comment by arschles** [comment]
I was thinking a one-liner for _installing_ and _running_ Athens. The using it part can come in subtext below. 

@cByst  @Kunde21 what about this:

## Run `docker run -p '3000:3000' gomods/athens:latest` to get started

(^^ is the one liner, then this could be a follow-up subtext below)

Then, set up your `GOPROXY` and `go get` going!

`export GOPROXY=http://localhost:3000 && go get module@v1`

**Comment by arschles** [comment]
@cByst sorry for the long delay there. If you'd still like to do this issue, let us know what you think about the `docker run` one-liner

**Comment by cByst** [comment]
@arschles no worries I lost track of this as well. Yeah I think that makes sense were you thinking just add a section to the current readme like:

# Getting Started
### Run `docker run -p '3000:3000' gomods/athens:latest`

Then, set up your `GOPROXY` and `go get` going!

`export GOPROXY=http://localhost:3000 && go get module@v1`

If you think that makes sense where in the readme do you think it fits in? I would assume somewhere near the top as we would want users first stumbling across the project to easily get up and running and trying Athens out.

**Comment by arschles** [comment]
@cByst definitely that makes sense! I think it would be really good on the `docs.gomods.io` site, right below the `Athens is a Server for Your Go Packages` text. Not sure about the readme. What do you think?

**Comment by cByst** [comment]
@arschles definitely agree it makes the most sense to go on docs.gomods.io for some reason I was thinking the issue had stated readme but must have been miss remembering. I agree after thinking about it I don't think the readme would be the right place as the readme is more around project status contributing in building from a dev/contributing perspective. Thanks for your help with this one I'll get a pr out adding this to docs.gomods.io. I am assuming I would just add this to the markdown files in the docs folder of this repo and that gets deployed to docs.gomods.io by CI or something?
