### ISSUE TITLE
List supported VCS repositories

### ISSUE THREAD

**Issue by arschles** [gomods/athens#1137]
**Is your feature request related to a problem? Please describe.**

In https://github.com/gomods/athens/issues/1083#issuecomment-472836213, @tomjamescn asked if Athens supports gerrit servers, and said that he didn't find anything that says what VCS servers Athens supports.

**Describe the solution you'd like**

We should add documentation that indicates what VCS servers Athens supports! Even better, we should explain that Athens uses `go mod download` on the backend, so anything that command supports (or that `go get` supports), Athens will support.

**Describe alternatives you've considered**
None

**Additional context**

Ref #1083

**Comment by tomjamescn** [comment]
Thank you! Greate job!

**Comment by vprasanth** [comment]
Hey I'd like to help get this done if no one else is already working on it. I'm new to go, so bare with me here :/ I've gone through the [go download source](https://github.com/golang/vgo/blob/master/vendor/cmd/go/internal/modcmd/download.go), and found [modfetch source](https://github.com/golang/vgo/tree/master/vendor/cmd/go/internal/modfetch/codehost) which seems to list out what it supports. Want to make sure I haven't gone off in the wrong direction. 

Regarding vcs support, besides git, I can see it supports fetching repos from svn, hg, bzr, and fossil.

Please let me know if this looks right.

**Comment by robjloranger** [comment]
@vprasanth that is correct. Thanks for doing this. :smiley:

**Comment by arschles** [comment]
@vprasanth are you still interested in doing this? If not, that's absolutely no problem. I just wanted to check in 😄

**Comment by vprasanth** [comment]
Oh crap, totally lost track of this. I'll get this wrapped up shortly. Sorry for the delay!
