### ISSUE TITLE
Azure Storage Distributed Locking

### ISSUE THREAD

**Issue by marpio** [gomods/athens#1140]
**Is your feature request related to a problem? Please describe.**
Azure storage supports [Lease Blob operation](https://docs.microsoft.com/en-us/rest/api/storageservices/lease-blob) which means we could use it similarly to GCS (issue #1123) to support `SingleFlight` on Azure storage.

**Comment by marpio** [comment]
I would like to take this one!

**Comment by arschles** [comment]
@marpio it's all yours 🎉

**Comment by arschles** [comment]
After this is done, I'd like to move our CI-based Athens runs (see #1138) to use Azure blob storage
