### ISSUE TITLE
"Some Additional Details" lacking a few details

### ISSUE THREAD

**Issue by chrispickard** [gomods/athens#116]
When I followed the steps in "Some Additional Details" I ran into a couple issues.
- I'm pretty sure the `athens` cli command is supposed to be `athens upload ./testmodule`
- I can't get `vgo get arschles.com/testmodule@v1.0.0` to work from a location outside the `$GOPATH` with a `go.mod` and a `main.go`. it says
```
❯ vgo get testmodule@v1.0.0
FindRepo: Get https://testmodule?go-get=1: dial tcp 198.105.254.228:443: connect: connection refused
vgo get testmodule: Get https://testmodule?go-get=1: dial tcp 198.105.254.228:443: connect: connection refused
```

I'm on ubuntu 16.04 with `go version go1.10 linux/amd64` and I ran athens with `cd cmd/proxy && buffalo dev`

**Comment by chrispickard** [comment]
I realized I need to set `$GOPROXY`, but I'm not sure what to set it to

**Comment by michalpristas** [comment]
you need to set it to: http://localhost:3000
beware or http

**Comment by arschles** [comment]
Hey Chris - to add to that, the docs are generally outdated and I’ll get
them back in shape. I’m out of town for the weekend but when I get back
next week I’ll give them a pass and clean things up. Thanks 😊

**Comment by robjloranger** [comment]
the cli is now gone
