### ISSUE TITLE
Dev Meetings: Adding a Time Rotation That's Friendly to Asia/Pacific Time Zones

### ISSUE THREAD

**Issue by arschles** [gomods/athens#1169]
We now have a rotation of times that are beginning to accommodate EU and North America time zones in https://github.com/gomods/athens/issues/954#issuecomment-472508105. 

As @Kunde21 mentioned in https://github.com/gomods/athens/issues/954#issuecomment-474677766, we don't yet have a time in the rotation that is friendly to Asia/Pacific time zones. 

This issue is for adding a time into the rotation that is friendly to those timezones.

**Comment by Kunde21** [comment]
Ideally, I think there would be a meeting on the odd weeks  ~11-13UTC, preceding one of the two US/EU time slots.  An EU/AF dev would become the "bridge" by attending at their lunch time and in the evening, to keep both regions informed.  Unfortunately, that means extra responsibility and duties piled upon a small number of devs in Europe/Africa, who are available at both times.

**Comment by arschles** [comment]
@Kunde21 I think we decided that a single, rotating meeting time each week is less bad than a separate meeting for other time zones each week (see https://github.com/gomods/athens/issues/852#issuecomment-435195602).

What do you think of an every three week rotation, with one of the weeks being 11-13UTC?

**Comment by arschles** [comment]
unfortunately, we are not doing dev meetings regularly anymore, partially because we can't find a good time for enough people to come. we have folks in GMT/CET time zones, North/South America time zones, and Asia/Pacific time zones! on the plus side, I'm proud that there are Athens users and developers all over the world. So, I am going to close this.

Sidenote: I do office hours and screencasts every once in a while, and I'm going to find some other ways for us to talk outside of GitHub.
