### ISSUE TITLE
cli needs work

### ISSUE THREAD

**Issue by chrispickard** [gomods/athens#117]
in the readme, it says "cli needs work." What work exactly does it need?
I can think of:
- additional docs
- not hardcoding the upload endpoint
- testing on the cmds?

**Comment by arschles** [comment]
Yes, those are three big ones. Top of my head I can’t think of more but
when I get back in town I’ll get a list together. Meanwhile, feel free to
PR any of those if you like. Thanks Chris

**Comment by michalpristas** [comment]
from my point of view, it depends where we take CLI. there are basically two options now
First one is to keep it as a tool which will help you with testing. Even then it would be fine not to have it hardcoded.
The second option is that CLI will provide alternative flow for uploading code to the private deployment of Athens. In this case, there will be much more work to do. 
But at this point we do not know whether people will like and use this flow, So we should stick with the things you mentioned.
If you need any help ping me

**Comment by chrispickard** [comment]
I added support for custom upload endpoints with #121

**Comment by chrispickard** [comment]
I'm not sure how to add tests for the upload cmd. What makes sense to me is end-to-end tests, not unit tests.

**Comment by arschles** [comment]
I am putting this on hold because I am not sure exactly how the CLI is going to look, or whether we are going to need one at all.

**Comment by robjloranger** [comment]
cli is gone, closing
