### ISSUE TITLE
Enable pprof/expvar/goroutine dumps

### ISSUE THREAD

**Issue by cep21** [gomods/athens#1177]
I would like to debug my current running athens proxy.  It would be great if [pprof](https://golang.org/pkg/net/http/pprof/) or [expvar](https://golang.org/pkg/expvar/) were exposed (at least optionally in the config).  This would allow me to collect goroutine dumps or inspect environment variables so I can debug the proxy.

**Comment by arschles** [comment]
@cep21 if you had to choose one to get first, which would it be? I'd like to split this one up into separate PRs...

**Comment by cep21** [comment]
For my case, the athen's proxy will frequently just "hang" without a response and slow "go get" commands for minutes at a time.  To debug this, I would need goroutine dumps and pprof info: so for me pprof would be the priority.

However, support for expvar is usually a single line of code: `import _ "expvar"`

**Comment by arschles** [comment]
@cep21 got it! would the opencensus infrastructure help you at all here? Regardless, we'll start with pprof.

**Comment by benjaminch** [comment]
Hey ! 
New comer to Athens here. This one looks interesting, would you mind if I give a shot on this one?

Thanks ;)

**Comment by marpio** [comment]
Welcome @benjaminch !
Please do! Let us know if you have any questions or need help.
