### ISSUE TITLE
Add CPU and memory resources section to helm chart

### ISSUE THREAD

**Issue by aplex** [gomods/athens#1179]
**Is your feature request related to a problem? Please describe.**

Current helm chart does not allow to set any resource requests or limitations. This can result in scheduling Athens on a Kubernetes node that does not have enough spare CPU and memory.

**Describe the solution you'd like**

Add resource section to values.yaml, similar to how it's done in stable helm charts:
https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L142
https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/controller-deployment.yaml#L162

**Comment by glb** [comment]
@arschles do you want it just like it's done in the examples?
