### ISSUE TITLE
Replace Filesystem operations with Afero

### ISSUE THREAD

**Issue by michalpristas** [gomods/athens#118]
Right now we use standard library for walking through filesystem as well as for modifications/reads/writes... 
As Karrick pointed out the standard library has some flaws when walk fn is used on Windows. 
Afero v0.10.0 provides full Windows compatibility

Goal is to replace all occurrences of Walk, Remove, Mkdir, Tmp.... operations.

**Comment by marpio** [comment]
I would like to do this.

**Comment by michalpristas** [comment]
I knew you would, that's why I created this issue ;) Please go ahead.

**Comment by michalpristas** [comment]
for some reason, i am not able to assign this issue to you @marpio 
I assigned this to myself so it is clear that somebody is working on it

**Comment by arschles** [comment]
@marpio what's left on this after https://github.com/gomods/athens/pull/70?

**Comment by michalpristas** [comment]
Repo fetcher I think. I'm on the phone but can't check but I think fetcher needs work

**Comment by arschles** [comment]
oh ok, thanks 😄

**Comment by marpio** [comment]
Didn't you just rewrite the whole repo package @michalpristas ? Should I wait until it is in master?

**Comment by marpio** [comment]
Or refactor what's in branch?

**Comment by michalpristas** [comment]
If you have time to refactor please go ahead. I won't be online till tomorrow evening so I won't touch the code

**Comment by marpio** [comment]
Me neither... Let's see tomorrow.

**Comment by michalpristas** [comment]
Ok let's sync tomorrow about this. 
Thank you @marpio

**Comment by michalpristas** [comment]
@marpio #114 went in so you should not be blocked

**Comment by marpio** [comment]
Great! Thanks.
