### ISSUE TITLE
add support for PORT environment variable

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#1182]
A lot of cloud providers won't recognize a custom PORT env var such as ATHENS_PORT. Furthermore, serverless platforms most often do not give you the PORT number ahead of time so you can't predict what port the server is going to run on. Most of them that I have noticed such GCF and GAE use the "PORT" env variable. So we should add it. 

However, in the future we should maybe add an ENV VAR to tell us what ENV VAR to look for so that we don't have to support multiple env vars to chase down the PORT.

**Comment by arschles** [comment]
>However, in the future we should maybe add an ENV VAR to tell us what ENV VAR to look for so that we don't have to support multiple env vars to chase down the PORT.

@marwan-at-work I think this would be confusing to folks configuring Athens. Would you be ok leaving it as you made it in #1181?
