### ISSUE TITLE
I can download pkg without repo permission

### ISSUE THREAD

**Issue by MaruHyl** [gomods/athens#1189]
There is a private repository `gitlab-xxx.com`, 
A only has the download permission for the project `gitlab-xxx.com/p1`, 
and B only has the download permission for the project `gitlab-xxx.com/p2`, 
`athens` configured an account in `.netrc` which has permissions to download `p1` and `p2` to provide `GOPROXY service` for A and B, 
there is a problem, B can download `p1` through `athens` by `GOPROXY=athens-addr go mod download gitlab-xxx.com/p1`,
A can download `p2` too

**Comment by marwan-at-work** [comment]
The use case of Athens is that you run it within your company, and employees of your company have access to all of your repositories. 

I imagine in super gigantic companies, you might want to limit code access between teams. Athens in this case can check certain headers but that's a bit of weird use case as of now for a couple of reasons: 

1. Go does not send any headers (until Go1.13 introduces GOAUTH) 
2. Athens will need to keep track of which credentials (headers) correspond to which modules which is weird. 

I think what we can do is be able to provide multiple Filter Files and have credentials be applied to different Filter Files. 

That said, I think we should probably not do this or only do it after Go1.13 (or even Go1.14) lands.

**Comment by marpio** [comment]
I don't think this should be Athens responsibility but maybe we could delegate that to some other system by using a hook which would send the headers and module.
We do something similar already with the [validation middleware](https://github.com/gomods/athens/blob/master/pkg/middleware/validation.go).

Of course, this would require at least go1.13 and GOAUTH

**Comment by storyicon** [comment]
Now use  [GOS](https://github.com/storyicon/gos)  to solve all these problems. It allows you to take the right privileges to pull private repositories, and to use GOPROXY at the right time. It also provides some additional shortcuts.

**Comment by arschles** [comment]
@storyicon following up here, GOS looks very interesting!

if you'd like to use the validation middleware that @marpio mentioned, we can certainly help you build an HTTP server that works with it, and does the auth that you need to do.

I am going to close this issue now. If you still have questions or are interested in building that HTTP server, please feel free to file another issue in here 😁
