### ISSUE TITLE
Workaround for api.github.com limits

### ISSUE THREAD

**Issue by michalpristas** [gomods/athens#119]
Using vgo fetching we are hitting limits set by github.com for anonymous users.
We need to find a way how to authenticate to github from Olympus. 
As we might event hit limits set for individual users some agreement with github would be nice. 

If the agreement is out of option we need to find a workaround.

**Comment by arschles** [comment]
>We need to find a way how to authenticate to github from Olympus

For now, let's put a token into our requests as the basic first step.

>some agreement with github would be nice

:+1:

**Comment by michalpristas** [comment]
do we need some shared account? what is the best practice here

**Comment by airylinus** [comment]
May be you can use Personal Access Code, find more on github.com [here](https://blog.github.com/2013-05-16-personal-api-tokens/)

**Comment by arschles** [comment]
Good question, I will look into this

**Comment by arschles** [comment]
I've added a preview label to this because we should at least look into a GH token to handle high volumes of `go get`s for "misses"

**Comment by arschles** [comment]
Currently if you set up a `.netrc` file on the machine that you run Athens from, the `go mod download` calls that Athens does on the backend will respect the token you set in the file.

Closing
