### ISSUE TITLE
Set open graph image for Athens project

### ISSUE THREAD

**Issue by chriscoffee** [gomods/athens#1191]
GitHub just released this feature and it'll help with sharing and outreach and the like.

https://github.blog/2019-04-17-custom-open-graph-images-for-repositories/

I'll take this

Edit: Bunch of edits as I can't type on a phone 😂

**Comment by chriscoffee** [comment]
<img width="710" alt="Screenshot 2019-04-18 19 37 34" src="https://user-images.githubusercontent.com/7100370/56383299-7184b780-6211-11e9-979d-8bf78e799ba0.png">

This has been set as the new og:image

**Comment by arschles** [comment]
Thanks @chriscoffee 🚀 🎉
