### ISSUE TITLE
"not a valid zip file" when failing to fetch a package due to merge conflicts?

### ISSUE THREAD

**Issue by ahmetb** [gomods/athens#1196]
**Describe the bug**

Something that fails with vanilla `go get` (due to some weird merge conflict error locally) is failing with "not a valid zip file" error while fetched via`GOPROXY=https://athens.azurefd.net`.

I'm not sure how/why the proxy is running into a conflict error as I'm running into it locally (for some reason I couldn't figure out).

**Error Message**
If applicable add error message to help explain your problem or console output enclose in triple back-ticks eg,

```console
....
....
go: finding github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf
go: finding github.com/julienschmidt/httprouter v1.2.0
go: finding gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: downloading google.golang.org/api v0.3.2
go get google.golang.org/api/cloudfunctions/v1: zip: not a valid zip file
```

**To Reproduce**

Just run this:

```
TMP=$(mktemp -d)

env -i PATH=$PATH \
  GOPROXY=https://athens.azurefd.net \
  HOME=$TMP/mock-home \
  GOCACHE=$TMP/go-cache \
  go get google.golang.org/api/cloudfunctions/v1
```

**Expected behavior**

I expect this go get to work, however actually vanilla go-get is failing with this error, too:

```
[13:22:01] ahmetb:~ $ go clean -modcache -cache
[13:22:04] ahmetb:~ $ go get google.golang.org/api/cloudfunctions/v1
# cd /Users/ahmetb/go/src/google.golang.org/genproto; git pull --ff-only
error: Your local changes to the following files would be overwritten by merge:
	googleapis/cloud/dialogflow/v2/session.pb.go
	googleapis/cloud/securitycenter/v1/asset.pb.go
	googleapis/cloud/securitycenter/v1/finding.pb.go
	googleapis/cloud/securitycenter/v1/organization_settings.pb.go
	googleapis/cloud/securitycenter/v1/security_marks.pb.go
	googleapis/cloud/securitycenter/v1/source.pb.go
	protobuf/ptype/type.pb.go
Please commit your changes or stash them before you merge.
Aborting
package google.golang.org/genproto/googleapis/rpc/status: exit status 1
```

So maybe the google.golang.org is messed up. Not sure why I'm getting pull conflicts (I'm doing a `go clean -modcache -cache`). But it looks like `GOPROXY=https://athens.azurefd.net` instance is seeing it too

**Environment (please complete the following information):**
 - OS: darwin/amd64
 - Go version: 1.12.1
 - Proxy version : N/A, using athens.azurefd.net

**Comment by marpio** [comment]
@ahmetb 
`athens.azurefd.net` isn't maintained that much and so it's possible that you're getting some weird errors.
Can you instead try this?
```
docker run -p '3000:3000' gomods/athens:latest
export GOPROXY=http://localhost:3000 && go get google.golang.org/api/cloudfunctions/v1
```

**Comment by ahmetb** [comment]
Thanks. Doesn't repro.
