### ISSUE TITLE
Add codecov.io integration

### ISSUE THREAD

**Issue by marpio** [gomods/athens#120]
It would make easier to spot untested execution paths. Missing test could be turned into nice 'good-first-issues'.
Example: https://codecov.io/gh/restic/restic

**Comment by michalpristas** [comment]
I just went through their docs. Looks nice and it is free for open source. 
:100:

**Comment by marpio** [comment]
I could extend travis.yml but someone would need to add the integration. A badge would be nice as well.

**Comment by bketelsen** [comment]
this is complete thank you!
