### ISSUE TITLE
Add CircleCI to this repo for chart linting and install testing

### ISSUE THREAD

**Issue by rimusz** [gomods/athens#1216]
As cloud.drone.io doesn't support `privileged` docker continuers need to run [kind](https://kind.sigs.k8s.io) for chart install tests, suggest to integrate the repo with CircleCI, where `kind` can be run at no problem.

**Comment by arschles** [comment]
@rimusz turns out CircleCI was enabled previously, but no builds have been running for ~2 months. This should be good to go for adding a circle yaml file. let me know what you find, and feel free to `@` me on slack as always, happy to help if I'm around!

**Comment by rimusz** [comment]
hmm, I don't see CircleCI kicking in for #1225

**Comment by arschles** [comment]
#1225 closed this one
