### ISSUE TITLE
cache upstream module locally for faster download

### ISSUE THREAD

**Issue by sify21** [gomods/athens#1220]
**Is your feature request related to a problem? Please describe.**
In my area, I can't download modules from `golang.org` directly. So I configured athens to use upstream module repository `https://athens.azurefd.net`. Those modules are not stored in athens local storage, and they're downloaded from internet every time.

**Describe the solution you'd like**
I want athens to have a switch to controll whether you want to cache modules from upstream locally or not. When I turn on the switch, athens will store the modules from upstream in its local storage, and later downloads will use local storage so that download can be faster.

**Comment by marpio** [comment]
@sify21 please take a look at #1211
Would that solve your problem?
Also a sidenote, athens.azurefd.net is awesome for trying out Athens but we don't put a lot of time into maintenance. If you face any issues with it you might consider using gocenter.io instead.

**Comment by sify21** [comment]
@marpio  It would be great If #1211 is implemented. The DownloadMode `async_redirect` will solve my problem. As I understand it, athens will return the module immediately if the module is found in local storage, and only download those that are not in local storage. Am I right?

**Comment by sify21** [comment]
Great! Then this issue can be closed, I'll subscribe for #1211

**Comment by arschles** [comment]
Related to https://github.com/gomods/athens/issues/1220#issuecomment-491696786, proxy.golang.org is another option 😄
