### ISSUE TITLE
Disable log buffering for fatal errors

### ISSUE THREAD

**Issue by ernado** [gomods/athens#1222]
**Describe the bug**
Seems like log output is buffered and application is closing before flushing
the buffer.

This leads to log message loss if application is closing too quickly, e.g. right after the start.

**To Reproduce**
1. Create systemd service with athens
2. Start it
3. Try to look at logs via `journalctl`

It will look like:
```
May 13 17:52:57 REDACTED systemd[1]: Started Athens proxy.
May 13 17:52:57 REDACTED proxy[10888]: time="2019-05-13T17:52:57+03:00" level=info msg="Exporter not specified. Traces won't be exported"
May 13 17:52:57 REDACTED systemd[1]: athens.service: main process exited, code=exited, status=1/FAILURE
May 13 17:52:57 REDACTED systemd[1]: Unit athens.service entered failed state.
May 13 17:52:57 REDACTED systemd[1]: athens.service failed.
```
No sign of failure cause.

**Expected behavior**
Error message is in logs.
```
May 13 17:54:16 REDACTED systemd[1]: Started Athens proxy.
May 13 17:54:16 REDACTED proxy[11242]: time="2019-05-13T17:54:16+03:00" level=info msg="Exporter not specified. Traces won't be exported"
May 13 17:54:16 REDACTED proxy[11242]: error adding proxy routes (exec: "go": executable file not found in $PATH)
May 13 17:54:16 REDACTED systemd[1]: athens.service: main process exited, code=exited, status=2/INVALIDARGUMENT
May 13 17:54:16 REDACTED systemd[1]: Unit athens.service entered failed state.
May 13 17:54:16 REDACTED systemd[1]: athens.service failed.
```

Note that following message appeared:
```
error adding proxy routes (exec: "go": executable file not found in $PATH)
```

**Environment (please complete the following information):**
 - OS: Linux 64bit
 - Go version: 1.12.4 
 - Proxy version : 33fdc92c487a2ad2984ccfcab1f2dc3005219500
 - Storage (fs/mongodb/s3 etc.): N/A

**Additional context**
During investigation, I've found a workaround.
The error that was failing to print was here:
https://github.com/gomods/athens/blob/33fdc92c487a2ad2984ccfcab1f2dc3005219500/cmd/proxy/main.go#L34-L37

I've just replaced `log.Fatal(err)` with `log.Panic(err)`, the result is in "Expected behavior" part. Also the `log.Fatalf("could not create app: %v", err)` works too for some reason, but seems like buffering still happens.

<details>
<summary>systemd service</summary>

```ini
[Unit]
Description=Athens proxy

[Service]
User=a.razumov
Group=a.razumov
CPUAccounting=yes
MemoryAccounting=yes
ExecStart=/src/athens/proxy -config_file config.dev.toml
WorkingDirectory=/home/a.razumov/athens

[Install]
WantedBy=multi-user.target
```
</details>

**Comment by marwan-at-work** [comment]
@ernado I can't seem to find any documentation (here https://golang.org/pkg/log/) on the difference in behavior between `log.Fatal` and `log.Panic` when it comes to buffering output. Especially that they both use the same way to print to Stdout. 

It'd be nice to figure out why, but I don't see a problem in replacing `log.Fatal` with `log.Panic` as a quick fix.

**Comment by ernado** [comment]
I've failed to find anything related to log buffering too, it is weird.
Will try to investigate it further, maybe that problem is specific to my environment.

**Comment by marwan-at-work** [comment]
@ernado sounds good. I'll keep the issue open for now, feel free to give us an update or close the issue. Thanks!

**Comment by manugupt1** [comment]
Can you try adding $GOROOT as an env var in the unit file @ernado and also see if WORKING_DIRECTORY has led to some unintended effects.

**Comment by ernado** [comment]
Seems like the issue is related to systemd.
Can't reproduce it on Ubuntu 18.04 (systemd 237), but it can be a side-effect of having a faster machine.

Ref: https://github.com/coreos/bugs/issues/373

I'm investigating further, but I'm not sure that this should be fixed in the scope of the project.
Maybe we can just apply workaround of just adding a log message prefix `log.Fatalf("could not create app: %v", err)` and journald will be able to correctly capture logs in most cases.

@manugupt1 I've added go binary to $PATH and athens worked well, I think that the exact error is unrelated.

**Comment by ernado** [comment]
Ref: https://github.com/etcd-io/etcd/issues/339

I think I'll just close it for now :/
