### ISSUE TITLE
Publish Athens server docker image for armv6

### ISSUE THREAD

**Issue by atomi** [gomods/athens#1227]
Since Athens is using Drone which also offers a plugin to publish manifest files can multi arches  be supported? 

http://plugins.drone.io/drone-plugins/drone-manifest/   

I was able to build 955929d just fine on a Raspberry Pi 3 with only a tiny change in the Dockerfile   

``` patch
diff --git a/cmd/proxy/Dockerfile b/cmd/proxy/Dockerfile
index fe2a691..88506ad 100644
--- a/cmd/proxy/Dockerfile
+++ b/cmd/proxy/Dockerfile
@@ -14,7 +14,7 @@ RUN DATE="$(date -u +%Y-%m-%d-%H:%M:%S-%Z)" && GO111MODULE=on CGO_ENABLED=0 go b
 
 # Add tini, see https://github.com/gomods/athens/issues/1155 for details.
 ENV TINI_VERSION v0.18.0
-ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-static /tini
+ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-static-armhf /tini
 RUN chmod +x /tini
 
 FROM alpine
```

Edit: Obviously this is not critical but it would be a nice to have for further updates. Thanks.

**Comment by atomi** [comment]
So for what it's worth, I've been playing around with Athens on the Pi and it does indeed work but it is pretty slow.    

So I'm not sure there will be many takers. 🤔

**Comment by Kunde21** [comment]
Is there a reason the Dockerfile doesn't use the alpine `tini` package directly?

**Comment by atomi** [comment]
> Is there a reason the Dockerfile doesn't use the alpine tini package directly?

I wasn't aware tini was available in alpine but probably not. 🤷    
It looks like it's the same version available as well.

**Comment by marpio** [comment]
I think it's interesting b/c it would potentially enable Athens to run on [AWS EC2 A1](https://aws.amazon.com/ec2/instance-types/a1/) or Scaleway ARM servers https://www.scaleway.com/en/arm-instances/

**Comment by Kunde21** [comment]
I've built athens on `arm`, `arm64`, and `amd64` with a multiarch manifest here:  hub.docker.com/r/kunde21/athens-arm

I'll be testing on my local hardware (rpi3 and odroid XU4), but it would be good to get others to test, too.  Main focus for testing in performance on different hardware, so we can give some general recommendations when it's released on the official gomods dockerhub.

**Comment by atomi** [comment]
By the way, according to the `tini` README an init is included in docker now by passing `--init` so I'm not sure `tini` is even necessary anymore.

**Comment by marpio** [comment]
@atomi no problem! 
The reason we have is #1155

**Comment by atomi** [comment]
@marpio Thank you!

**Comment by arschles** [comment]
@atomi @marpio @Kunde21 since we closed #1155 and we stick with running Athens under tini in our images, do you think we can close this?

**Comment by atomi** [comment]
Apologies. Yes!

**Comment by arschles** [comment]
No apologies necessary @atomi. Thanks for responding 😁
