### ISSUE TITLE
token is not passed in /catalog from URL

### ISSUE THREAD

**Issue by xytan0056** [gomods/athens#1236]
**Describe the bug**
token/pagesize is not passed to /catalog from URL.

**Error Message**
token == "" instead of passed in value

![image](https://user-images.githubusercontent.com/48696694/58139137-4e716d00-7bee-11e9-9f27-fd3537611cf8.png)

![image](https://user-images.githubusercontent.com/48696694/58139173-76f96700-7bee-11e9-8d54-427b63629c20.png)

**To Reproduce**
just pass any variable

**Expected behavior**
variables extracted from mux.Vars(r) is what's passed in URL

**Environment (please complete the following information):**
 - OS: [e.g. Linux 64bit]
 - Go version :1.12.4
 - Proxy version :master
 - Storage (fs/mongodb/s3 etc.) :

**Additional context**
https://stackoverflow.com/questions/31371111/mux-vars-not-working
Looks like shouldn't use `mux.Vars`

**Comment by 5onic** [comment]
I'll take a look at this and hopefully will send a PR in ~ 1 week.

**Comment by arschles** [comment]
@5onic thanks, you rock 🎉

**Comment by 5onic** [comment]
@arschles Np, thank you for a cool project, and again(!) for an amazing community 🍰
