### ISSUE TITLE
Set up a dev environment with sail?

### ISSUE THREAD

**Issue by arschles** [gomods/athens#1237]
**Is your feature request related to a problem? Please describe.**

Not really, this would be a pretty cool addition to our dev experience

**Describe the solution you'd like**

We already have a pretty good documentation page for how to set up your local development environment. I think it would be nice & convenience to provide another option for anyone looking to develop on Athens using [sail](https://github.com/cdr/sail) to preconfigure their dev environment.

**Describe alternatives you've considered**

We could of course not do this

**Additional context**

https://sail.dev/

**Comment by brainflake** [comment]
Has anybody taken a crack at this yet @arschles? I'd be happy to give it a shot

**Comment by robjloranger** [comment]
@brainflake it looks up for grabs still. Please do. 🤓

**Comment by brainflake** [comment]
Sounds good @robjloranger. Sail seems actually really easy to setup - is there anything in particular I should ensure is included in the dev environment (aside from enabling GO111MODULE)? The current go version is 1.12.4 in their base golang ubtuntu image, which I'm assuming works based on the Dockerfile currently in `cmd/proxy`.

Currently just seeing if i can get the unit tests to work from the console in the sail window...

**Comment by robjloranger** [comment]
Awesome, sorry for the delay @brainflake. How is it coming? Did you get tests working?

I'm not yet familiar with sail myself, I am very interested in giving it a shot though. It should really help with on boarding new contributors who may be unfamiliar with Go development.

I think if you can build and run Athens then you've got a great start for the sail environment set up.

**Comment by arschles** [comment]
+1 to what @robjloranger said. Any progress with Sail I think is a great win. @brainflake if you have something working for local dev and/or unit tests, we can PR and merge that and then improve from there in follow-ups!

**Comment by brainflake** [comment]
Sounds good @robjloranger @arschles 

I'll cut a PR with what I have. It's just a Dockerfile w/ a few lines at the moment but seems to work for building + running.

**Comment by arschles** [comment]
I think that #1248 fixed this, so I'm gonna close. @brainflake if I'm wrong, let me know please!

**Comment by brainflake** [comment]
Sounds good 🚀
