### ISSUE TITLE
Handle deprecated Olympus deployment

### ISSUE THREAD

**Issue by michalpristas** [gomods/athens#124]
On failed event log download from Olympus do not increase UUID of synchronization point and let it run on next pull.
Having UUID unchanged downloaded packages will not have hidden state and will be served by proxy while failed will be retried again

Remember retry count, when retry count hits a configured limit, reset:
- olympus_host
- sequence_id
- clears local db  - do not clear private repos.

ref: #93

**Comment by arschles** [comment]
As of #772, we're not going to try and build a registry for the time being, so I'm closing this issue
