### ISSUE TITLE
 Should not return 500 when pulling private repo failed

### ISSUE THREAD

**Issue by storyicon** [gomods/athens#1241]
In order to match the golang on the master branch, I think it should probably return `404`

Dilemma: https://github.com/storyicon/gos/blob/master/docs/on-goproxy.md
Related issue: https://github.com/golang/go/issues/31913

**Comment by marpio** [comment]
@storyicon 
Wouldn't that be covered by https://github.com/gomods/athens/issues/1211 and the `DownloadMode="async"` ?

> async: return 404, but asynchronously store the module in the storage backend.

cc: @marwan-at-work
