### ISSUE TITLE
Remove -mod=vendor from source and docs

### ISSUE THREAD

**Issue by marpio** [gomods/athens#1242]
https://github.com/gomods/athens/pull/1231 removed the vendor directory but there are still some ` -mod=vendor` left in our Makefile and docs.

We should remove those and use GOPROXY=https://proxy.golang.org instead to build Athens.

**Comment by penthaapatel** [comment]
Hi! New contributor here. :) I would like to work on this.

**Comment by marpio** [comment]
Please do @penthaapatel It's yours!

**Comment by marpio** [comment]
Let us know if you have any questions.

**Comment by penthaapatel** [comment]
Should I change all the occurrences that say "GOPROXY=http://127.0.0.1:3000" to "GOPROXY=https://proxy.golang.org" in docs/content?

**Comment by arschles** [comment]
@penthaapatel not everywhere, no. Many of the places in docs that say `GOPROXY=http://127.0.0.1:3000` are instructions for how to configure your machine to use an installed Athens, so don't change that. Only change the occurrences that talk about how to build Athens itself. Lots of them will be in development and testing docs

**Comment by penthaapatel** [comment]
@arschles Thanks! I got it.

**Comment by penthaapatel** [comment]
I removed `-mod=vendor` from Makefile, docs/content/install/build-from-source.md, and docs/content/walkthrough.md. Am I doing this right?

**Comment by arschles** [comment]
@penthaapatel sounds like it! Would you be able to submit this as a pull request and we can start giving feedback directly on the code? Or, did you already submit one and I missed it?

**Comment by penthaapatel** [comment]
@arschles Okay, I'll submit a PR now. :)
