### ISSUE TITLE
If GOPROXY is set, Athens unit tests will use them implicitly

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#1255]
If a developer runs `go test ./...` from within the Athens project and they have a GOPROXY environment set, our tests will actually use that variable because our tests run the `go` command internally. 

We have 4 options: 

1. Leave it be, and have the user figure out what's going on. 
2. Check GOPROXY, and warn the user that their tests might be affected (especially if their GOPROXY url is broken for any reason) 
3. Explicitly set GORPOXY to either off or proxy.golang.org so that our tests are more reproducible 
4. Run an Athens instance in the background and kill it

**Comment by Mark-Jung** [comment]
I might just take this haha.

**Comment by marwan-at-work** [comment]
@Mark-Jung thank you! I think the best thing to do is maybe temporarily set `GOPROXY=off` in `TestMain` for the tests that use the `GoGetFetcher` internally

**Comment by arschles** [comment]
I vote for reproducibility as much as possible, which IMO would be setting `GOPROXY=https://proxy.golang.org`.

On top of that, we would be testing Athens against another implementation of the download protocol, which helps us make sure that we work in the larger ecosystem.

**Comment by marpio** [comment]
@marwan-at-work 
Not sure I understand why go "knows" GOPROXY env var?
Aren't we creating a separate env here: https://github.com/gomods/athens/blob/a4cf4eb991f375724426d7b466c0705386ad7da3/pkg/module/go_get_fetcher.go#L139 ?
Why is GOPROXY leaked?

**Comment by marwan-at-work** [comment]
@marpio very good point, I totally forgot about that :) 

Looking back at the slack channel where the issue was [originally reported](https://gophers.slack.com/archives/C9LRAQN8N/p1559176353124500):

![image](https://user-images.githubusercontent.com/16294261/58659820-edcee800-82f1-11e9-9221-abfc5fa0a8c0.png)

I just realized that I misdiagnosed the issue, it's not that our unit tests were seeing the GOPROXY environment variables and using it, it's that @Mark-Jung had set the GOPROXY variable and that his local cache did not have the *Athens* dependencies yet, and it tried to download them *before* running the actual unit tests...Hah! 

I just locally ran `GOPROXY=<fake-domain> go test ./...` and everything worked normally 

Thanks again for bringing it up!
