### ISSUE TITLE
Dockerized Development Misses The Vendor Folder

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#1259]
Our `docker-compose up dev` command uses the same Dockerfile we use in our deployment pipeline which includes `-mod=vendor`...However, our deployment pipeline runs `go mod vendor` on the fly while our development environment doesn't

We therefore should expose the local cache to our Dockerfile build in our pipeline so that we can remove the `-mod=vendor` and also ensure that we don't re-download everything when building docker.

**Comment by paivagustavo** [comment]
Seems to be duplicated from #1242

**Comment by marwan-at-work** [comment]
Potentially :) this one is more concerned with making sure our CI/CD pipeline caches the GOPATH (or rebuilds with a public proxy)

**Comment by keremgocen** [comment]
Hey, I'm new here and still getting familiar with the system. This one looks like something I can start working on.

**Comment by marwan-at-work** [comment]
@keremgocen sounds good :v:

**Comment by arschles** [comment]
@keremgocen would you still be interested in taking this one? I'm happy to help out if you are. If not, absolutely no worries. I just wanted to check in.

**Comment by keremgocen** [comment]
@arschles feel free to take it, I recently started a new project so it's a bit hard for me to create extra time right now. I'm sure I can find something else to work on when I have a better schedule.

**Comment by chriscoffee** [comment]
Just so I understand you right with this one @marwan-at-work (it's rather late here):

Are you wanting the developer environment in docker-compose to be able to `depend_on` a second container, which does the `go mod download && go mod vendor` and uses it as a mounted volume shared between the two. i.e https://gist.github.com/chriscoffee/f7e6d7052c0a426eebaceaf1ab2c8218#file-docker-compose-yml

OR

You want to migrate `cmd/proxy/Dockerfile` to build with `download` and `vendor` and then pass from the builder so it can be used elsewhere? i.e https://gist.github.com/chriscoffee/f7e6d7052c0a426eebaceaf1ab2c8218#file-dockerfile
