### ISSUE TITLE
 get cloud.google.com/go@xxx timeout

### ISSUE THREAD

**Issue by snxq** [gomods/athens#1263]
**Describe the bug**

when I run `go get cloud.google.com/go@xxx` will no display and waiting...

And server had download this package.

I try to catch net package.

![WeChatWorkScreenshot_8892d270-0c08-4b11-acb9-a5def9ef7473](https://user-images.githubusercontent.com/22384359/58697292-e67c0d00-83cb-11e9-9198-217071a64b7c.png)
![WeChatWorkScreenshot_055af6b1-b72c-445b-9396-f5d2b00d64fc](https://user-images.githubusercontent.com/22384359/58697329-f85db000-83cb-11e9-853e-035a9cc5bd0e.png)

**Environment (please complete the following information):**

 - OS: debian
 - Go version : 1.12.5
 - Proxy version : v0.4.0
 - Storage (fs/mongodb/s3 etc.) : disk

**Comment by marpio** [comment]
@snxq 
Can you execute `go mod download cloud.google.com/go@xxx` without using Athens (without setting `GOPROXY`) and let us know if it worked?
If possible on the machine where Athens is running.

**Comment by snxq** [comment]
@marpio 
I did what you said. 

![image](https://user-images.githubusercontent.com/22384359/58698591-1c21f580-83ce-11e9-8f7d-1b3f7919355d.png)

**Comment by marpio** [comment]
@snxq 
hmm... `go mod download cloud.google.com/go@0.26.0` is what Athens is running to fetch the info, mod and zip parts so if it's working fine then Athens should too.
Are you using the 0.4.0 docker image?

**Comment by snxq** [comment]
@marpio 
yes.Its docker image v0.4.0. I also try to use v0.3.0, and get the same result.

I guass this is maybe a system problem.

**Comment by snxq** [comment]
@marpio 
Not solved yet, But this should be my client's problem.
I closed this issue. thanks a lot for answer.

**Comment by marpio** [comment]
@snxq let us know if you solved the issue.
