### ISSUE TITLE
Proxy should respond with 404 when unable to fetch source

### ISSUE THREAD

**Issue by jorng** [gomods/athens#1290]
**Is your feature request related to a problem? Please describe.**
Currently, if Athens is unable to download the source code of a project using `go get`, it results in a `500` error.  

This could be a variety of issues, including authentication/authorization issues, or no connection to the server (private repos?), but the result for clients is the same: the module cannot be found.

When Go 1.13 is released, it supports multiple module proxies via a comma separated list in the `GOPROXY` env variable. This only works if the proxy returns either a `404` or a `410`.

**Describe the solution you'd like**
The proxy should return a `404` in the specific instances of `go get` being unable to download the source.

**Comment by yittg** [comment]
@jorng it seems be fixed in #1299 and #1300, would you checkout the unreleased version to verify whether your scenario is fixed?

**Comment by arschles** [comment]
@jorng @yittg I am going to close this issue now. If you're still seeing the problem, can you talk to us in the `#athens` channel in the Gophers Slack, or open another issue in this repository?

**Comment by jorng** [comment]
Sorry for the delay. I was just able to get this setup earlier today to replicate. Yes, it appears to be fixed.
