### ISSUE TITLE
support fetch from proxy when download url provided

### ISSUE THREAD

**Issue by yittg** [gomods/athens#1294]
**Is your feature request related to a problem? Please describe.**
1. now download url is provided for redirect, when async redirect mode specified, and the fetcher still download module from original repo only. If the original repo is not reachable, the async fetch will always fail.
2. download rules is only applied to info/mod/zip apis, list is leave unconfigurable.

**Describe the solution you'd like**
provide a method to both tell `go mod download`/`go list` fetch from proxy(i.e. set GOPROXY=${download url})

**Comment by yittg** [comment]
cc @arschles @marwan-at-work 
does these feature request make sense, looking forward to your voices, :)

**Comment by marwan-at-work** [comment]
@yittg that sounds good to me. There are a couple of ways to pass `GOPROXY`: 
1. Either just set GOPROXY in the environment that Athens is running in 
2. Let the user pass it in through the Config (which would include no.1 above) 

In either cases, we'd have to explicitly pass that to `go_get_fetcher.go` and the Upstream Lister which should be an easy addition. 

Thanks!

**Comment by yittg** [comment]
yeah, for the bottom `go_get_fetcher.go`/`upstream_lister.go`, we should pass a `GOPROXY` to cmd(`go mod download`/`go list`) as env to execute, as you said.
for the user interface, both ways you mentioned are proposing a brand new global configuration/or env which is totally different from `GlobalEndpoint` or `DownloadURL`/download_hcl, right?
i think it's difficult to expand and maintain, especially we have rich download rules.
may we just make use of the `DownloadURL`/download_hcl to achieve it while maintaining consistency of module:

1. for mod/zip/info, when `DownloadMode` is `async_redirect` which means that tell user to fetch from `DownloadURL` while downloading the module asynchronously, `DownloadURL` can be passed to cmd as `GOPROXY`;
2. for list, when `DownloadMode` is `redirect`/`async_redirect`, `DownloadURL` can be passed to cmd as `GOPROXY` also, of course without *downloading* different from 1.
    > more about list, i noticed that short cache for list #893 is advancing, `DownloadURL` can also be told to user to redirect to it, while caching the list result asynchronously with `DownloadURL` as `GOPROXY`
