### ISSUE TITLE
Minio MakeBucket errors not being returned.

### ISSUE THREAD

**Issue by jamesnaftel** [gomods/athens#1295]
**Describe the bug**
[See code for minio MakeBucket](https://github.com/gomods/athens/blob/a5eba1812bc48a4df1d9e7868288ed8feb31cdfd/pkg/storage/minio/minio.go#L39-L47)
If MakeBucket fails, the BucketExists call will overwrite the real error.  The result is a generic error being logged.

**Error Message**

```console
error getting storage configuration (Internal Server Error)
```
**To Reproduce**
Set the minio bucket name to an invalid name like "bucket_test".  The underscore is not an acceptable character.

```console
$ make dev
$ ATHENS_STORAGE_TYPE=minio ATHENS_MINIO_BUCKET_NAME=bucket_test make run
```

**Expected behavior**
Return the "MakeBucket" error.  For this specific error, the message should be:

```console
error getting storage configuration (Bucket name contains invalid characters)
```

**Environment (please complete the following information):**
 - OS: Linux 64bit
 - Go version : go version go1.12.6 linux/amd64
 - Proxy version : N/A for this test case
 - Storage (fs/mongodb/s3 etc.) : Minio

I'll submit a pull request to address the issue in the next few days.  Will be away till Friday.

**Comment by arschles** [comment]
>I'll submit a pull request to address the issue in the next few days. Will be away till Friday.

@jamesnaftel sounds good! looking forward to it
