### ISSUE TITLE
aliyun oss 

### ISSUE THREAD

**Issue by opinionsDazzle** [gomods/athens#1296]
v0.3.1 version athens with storage aliyun oss
when put object to oss ,the oss server return an exception
<Error>
  <Code>NotImplemented</Code>
  <Message>Aws MultiChunkedEncoding is not supported.</Message>
  <RequestId>5D1D9AB1A9692A992EBF780C</RequestId>
  <HostId>oss-us-west-1-internal.aliyuncs.com</HostId>
</Error>

How is this going？How should I solve this problem?

**Comment by arschles** [comment]
@opinionsDazzle is this for Alibaba object storage? I'm not exactly sure how to fix this at the moment, but can you post a link to some documentation for the object storage you're using?

**Comment by marpio** [comment]
It's possible that since https://github.com/gomods/athens/pull/1107 (iirc 0.3.1 was a patch release containing that PR) we are using some features that aren't supported by Alibaba object storage.

@opinionsDazzle can you try if 0.3.0 is working for you so we can confirm that?

**Comment by yittg** [comment]
@arschles @marpio I may take a look if no one else is working on it.

**Comment by opinionsDazzle** [comment]
set EnableSSL = true can solve this problem. Because Aliyun hasn't supported this Aws MultiChunkedEncoding yet. Https can work around this problem.

**Comment by zhmq0124v** [comment]
> @arschles @marpio I may take a look if no one else is working on it.

Hi, we hit the same error when using jclouds library, any hints on how to solve this error? Thank you. https://jclouds.apache.org/
