### ISSUE TITLE
Configurable Olympus instances

### ISSUE THREAD

**Issue by michalpristas** [gomods/athens#130]
We keep the membership protocol as simple as it gets: each cloud deployment will store a static list of all of the cloud providers in the global deployment, other than itself. For example, the membership list for OM is [OA, OG].

A cloud deployment consults this list to communicate with another member of the Olympus global deployment.

Simple json configuration file will be sufficient for now.

**Comment by sahitpj** [comment]
May I work on this, If it hasn't been assigned yet?

**Comment by robjloranger** [comment]
Please do, let us know if you have questions.

**Comment by roy-michael** [comment]
@sahitpj are you still working on it?

**Comment by morfeo8marc** [comment]
Hi, I would like to start working on it to get used with the project

**Comment by michalpristas** [comment]
Hey @morfeo8marc 
i put this task on hold as the future of Olympus part of the code is uncertain

**Comment by morfeo8marc** [comment]
Ok I will try to find another issue to work one then

**Comment by arschles** [comment]
As of #772, we're not going to try and build a registry for the time being, so I'm closing this issue
