### ISSUE TITLE
Write a test for the new Mongo query function

### ISSUE THREAD

**Issue by arschles** [gomods/athens#1301]
**Is your feature request related to a problem? Please describe.**

This is a follow-up to https://github.com/gomods/athens/pull/1297#pullrequestreview-259171326

**Describe the solution you'd like**

We should have a test for the `query` function that was introduced in #1297. We probably will need to make it an integration test, since it will need to connect to a real MongoDB server

**Describe alternatives you've considered**

N/A

**Additional context**

This is a follow-up to #1297. I've talked to @bou1der about it, and he is going to try to do it soon

**Comment by bou1der** [comment]
When I looked into this, I double checked the tests under the compliance package. I think the tests in this package already do a good job of testing the interface and in turn the query function which is private.   

I feel like I am missing something. Should I be testing a private implementation? 

Sorry if this is a silly question - I'm still relatively new to Go and Athens :)
