### ISSUE TITLE
[helm-chart] Failed to deploy with basic auth

### ISSUE THREAD

**Issue by qiuyuzhou** [gomods/athens#1303]
https://github.com/gomods/athens/blob/8e8e886f84e9c84d69c00a32cdd5787c72c99ae8/charts/athens-proxy/templates/deployment.yaml#L139-L142

The value has been quoted twice.

**Comment by arschles** [comment]
Thanks @qiuyuzhou - I just submitted #1322. Can you let me know if that will solve it for you?
