### ISSUE TITLE
Health endpoint without basic authentication

### ISSUE THREAD

**Issue by cudle** [gomods/athens#1307]
**Is your feature request related to a problem? Please describe.**
We are currently running Athens with basic auth as an ECS Service on AWS. In addition there is an ALB which does a periodic health check on the root path. Since health checks don't support basic authentication, it gets a 401 response. In order to bypass this issue, we had to add the 401 status code to the allowed status codes but it is not ideal.

**Describe the solution you'd like**
It would be great if there is an arbitary endpoint, that could return a 200 status code that is not affected by the enabled basic authentication.

**Comment by manugupt1** [comment]
I wont be able to look until next month, anyone can take this issue.
Cheers,

Manu Gupta
