### ISSUE TITLE
There is a bug in the minior/lister.go that can cause get wrong versions.

### ISSUE THREAD

**Issue by opinionsDazzle** [gomods/athens#1311]
if moudule = "github.com/labstack/echo",objectCh will contains the version of module "github.com/labstack/echo/v4" ,  because list all the file related to searchPrefix.

![image](https://user-images.githubusercontent.com/20106076/61518465-2ced0000-aa3c-11e9-9731-0e0e1636cfb3.png)

**Comment by yittg** [comment]
@opinionsDazzle yeah, indeed it's a bug, thanks for your feedback. Actually, not just minio, the implementation of fs has similar problems. a straightforward idea is to add special separator like others, but may we can also just check the prefix after listing for backward compatibility. And for describing and reproducing issue clearly, i opened a pre-PR
@marwan-at-work @marpio what do you think?
