### ISSUE TITLE
github private repo

### ISSUE THREAD

**Issue by ramanvis** [gomods/athens#1319]
Issue:
Athens throwing a 500 Internal server error when the module repository is a private github repo.

Details:
I created a go module in a private github repo to experiment with athens. The module provides a simple utility to convert a map to slice of keys and values.

In another repo/module, I simply use this module's library and print values in a map.

This works fine without athens.

I saw this failure with athens:
Error:
```
➜  moddemo git:(master) ✗ go build github.com/ramanvis/moddemo/cmd/mapfun
go: finding github.com/ramanvis/demoutils v1.0.0
go: github.com/ramanvis/demoutils@v1.0.0: unexpected status (http://127.0.0.1:3000/github.com/ramanvis/demoutils/@v/v1.0.0.info): 500 Internal Server Error
go: error loading module requirements
```

When I make my repo public, I don't see the above error.
No Error:
```
➜  moddemo git:(master) ✗ go build github.com/ramanvis/moddemo/cmd/mapfun
go: finding github.com/ramanvis/demoutils v1.0.0
go: downloading github.com/ramanvis/demoutils v1.0.0
go: extracting github.com/ramanvis/demoutils v1.0.0
```

I made the repos public for your reference:
https://github.com/ramanvis/demoutils (Module providing the utility)
https://github.com/ramanvis/moddemo/settings (Module using the utility)

I am not sure if I am missing something.

**Comment by marpio** [comment]
@ramanvis
You will need to provide a .netrc or GitHub token to Athens in order for it to get access to your private repository.
Ref:
https://github.com/gomods/athens/blob/8240e720fdc7cc89d5b433e95025a1b1f1186343/config.dev.toml#L143

https://github.com/gomods/athens/blob/8240e720fdc7cc89d5b433e95025a1b1f1186343/config.dev.toml#L151

Let us know if you have any other questions!

**Comment by arschles** [comment]
@ramanvis https://docs.gomods.io/install/managing-private-repos/ also has some documentation on how to configure this file.

I'm going to close this issue now. If you have additional questions, can you contact us in the `#athens` channel in the [Gophers Slack](https://invite.slack.golangbridge.org/) or open a new issue here?

**Comment by ramanvis** [comment]
Thank you
