### ISSUE TITLE
sanity check version string that users provide

### ISSUE THREAD

**Issue by xyt0056** [gomods/athens#1320]
**Is your feature request related to a problem? Please describe.**
we take whatever version passed in for granted and return them unchecked 
for example `vx.x.x+incompatible`, if `vx.x.x` is compatible, we should error out instead of returning `vx.x.x+incompatible` as is

**Describe the solution you'd like**
user provided version is checked

**Describe alternatives you've considered**
check at fetcher.go

**Additional context**
something like this
https://proxy.golang.org/github.com/!shopify/toxiproxy/@v/v1.2.1+incompatible.info
https://proxy.golang.org/github.com/google/gvisor/@v/4a842836e560.zip

**Comment by arschles** [comment]
@xytan123 I don't see a reason not to error out on `/@v/list` and `/@latest` requests for both style versions, but I think it would be a good idea to allow them on `.info`, `.mod` and `.zip` requests, for the same reason I gave in https://github.com/gomods/athens/issues/1318

@marwan-at-work what do you think?

**Comment by xytan123** [comment]
`.info` :white_check_mark:
`.mod` `.zip` no need

**Comment by marwan-at-work** [comment]
@xytan123 if you try that same query against Athens you get the same error as proxy.golang.org: 

```
curl 'localhost:3000/github.com/!shopify/toxiproxy/@v/v1.2.1+incompatible.info'
```

Athens logs: 

```
INFO[0011] github.com/Shopify/toxiproxy@v1.2.1+incompatible: invalid version: +incompatible suffix not allowed: major version v1 is compatible
```

The only thing is that we're not passing the message all the way back to the client, we can do that as part of the response, but we don't need to manually parse/understand versions, that's `go mod download` and `go list`'s job internally

**Comment by xytan123** [comment]
@marwan-at-work 
Does it take whatever go binary on machine? I use `go version go1.12.6 darwin/amd64`. build from master 
```
curl 'localhost:3000/github.com/!shopify/toxiproxy/@v/v1.2.1+incompatible.info'
{"Version":"v1.2.1+incompatible","Time":"2015-07-24T18:56:29Z"}
```

**Comment by marwan-at-work** [comment]
@xytan123 can you try it with go1.13 beta (or go tip) and let me know? It seems that we can call it done if the underlying Go binary fixes this for us.

**Comment by xytan123** [comment]
yep, go 13 fixes.
```
2019-08-06 12:49:32.458441 I | Starting application at port :3000
INFO[0024] github.com/Shopify/toxiproxy@v1.2.1+incompatible: invalid version: +incompatible suffix not allowed: major version v1 is compatible
```
But can we make this hermetic? I feel it's a bit weird that the result is not reproducible on different machines

**Comment by arschles** [comment]
@xyt0056 if you run the Athens binary on your machine, it will pick up whatever `go` binary you have installed, by default. You can configure it to point to a custom binary, however.

We do have a [docker image](https://hub.docker.com/r/gomods/athens) that is pre-packaged with the right `go` binary, and we use that as our hermetic solution. It should work the same way on development machines and in production if you use the same image.

I am going to close this issue now. If you have another idea on how to make this hermetic, or you're still seeing an issue, can you please comment here? Even though it is closed, I will still get a notification and reopen the issue. 😄
