### ISSUE TITLE
Helm chart needs updating to use latest docker container

### ISSUE THREAD

**Issue by chriscoffee** [gomods/athens#1326]
**Describe the bug**
We need to update the docker container to use the latest build.

Whilst we were in the 2018-08-06 Office Hours @arschles noticed that the Helm chart was out of date of the latest v0.5.0 release.

Either bump the version manually or write a script to bump the version as we deploy out a release. That way we don't have to keep remembering to do this! 👍

**Comment by schafer14** [comment]
May I take this issue?
