### ISSUE TITLE
Write tests for error paths in Mongo query funtion

### ISSUE THREAD

**Issue by bobmaertz** [gomods/athens#1327]
**Is your feature request related to a problem? Please describe.**

This is a follow up to the conversation in #1314 

**Describe the solution you'd like**

The tests for the query function handle all of the good paths but not the error cases. There should be tests to verify that the error paths behave as expected. 

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by arschles** [comment]
Specific link to the start of the conversation in #1314 about error kinds is [here](https://github.com/gomods/athens/pull/1314#pullrequestreview-270959865)

**Comment by scriptonist** [comment]
@arschles Is this still relevant, can I make an attempt to add these tests?

**Comment by arschles** [comment]
@scriptonist yes, it looks like it. Please feel free!

**Comment by yatesliang** [comment]
@arschles Hi, is this issue still need to be resolved? I would like to try.
Recently we have deployed this project as our proxy server, I think we can try to help resolve issues and implement new features.

**Comment by yatesliang** [comment]
I found that we may need to start a local MongoDB server before running the MongoDB test.  Is it okay to introduce in-memory Mongo for unit tests (like [strikememongo](https://github.com/strikesecurity/strikememongo))? If ok I would like to do that too.
