### ISSUE TITLE
Check for errors generated by URL when initializing mongo client

### ISSUE THREAD

**Issue by bou1der** [gomods/athens#1328]
**Is your feature request related to a problem? Please describe.**

When creating a new Mongo client, athens doesn't check for error messages when providing the mongo client with the URI. The NewStorage function allows you to pass an empty string URL as the mongo URL. It does eventually error out later when trying to call the backend. 

**Describe the solution you'd like**

In the newClient function, use the (Mongo) options.Validate after calling the (Mongo) options.ApplyURI function to check that that the URI value didn't trigger an error. 

```
func (m *ModuleStore) newClient(conf *config.MongoConfig) (*mongo.Client, error) {
	tlsConfig := &tls.Config{}
	clientOptions := options.Client()
	// Maybe check for error using Validate()?
	clientOptions = clientOptions.ApplyURI(m.url)
	
        if m.certPath != "" {
```
**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by gowdabas** [comment]
Hi @bou1der , are you working on this? If not, I can take it up.

**Comment by bou1der** [comment]
Hi @gowdabas, I am working on it. Sorry about that, I submitted a PR right after I wrote this issue

**Comment by gowdabas** [comment]
@bou1der Np, that's great !!
