### ISSUE TITLE
docs: make it easy to compare vendoring and athens

### ISSUE THREAD

**Issue by frasercobb** [gomods/athens#1338]
**Is your feature request related to a problem? Please describe.**
My team found it difficult to compare and contrast vendoring with Athens.

**Describe the solution you'd like**
Documentation to make it easy to compare vendoring with go module proxies such as Athens.
Ideally the documentation would make it easy to compare the solutions on the users repo, with commands to copy and run to see the benefits of each solution (e.g. time and space considerations)
You could also consider explaining how to use the GOPRIVATE env var in this document.

**Describe alternatives you've considered**
A repo with examples of each solution (vendoring, go module proxy, neither) to compare and contrast each.

**Additional context**
My team had flakey builds as a result of errors resolving go modules.

**Comment by schafer14** [comment]
I prettied up some of the notes Aaron had made during office hours.
