### ISSUE TITLE
disk storage doesn't store anything to disk

### ISSUE THREAD

**Issue by kevin-cantwell** [gomods/athens#1339]
**Describe the bug**
Athens doesn't store to the configured location (or anywhere else, afaict).

**Error Message**
No errors, just no disk writes.

**To Reproduce**

1. `mkdir -p $HOME/.athens/storage`
1. `docker run -p '3000:3000' -v $HOME/.athens/storage:/athens/storage --env ATHENS_STORAGE_TYPE=disk --env ATHENS_DISK_STORAGE_ROOT=/athens/storage gomods/athens:v0.3.0`
1. `GO111MODULE=on GOPROXY=http://localhost:3000 go get github.com/kevin-cantwell/dotmatrix`
1. `$ ls -al ~/go/.athens`

**Expected behavior**
I expect the `$HOME/go/.athens` directory to be non-empty.

**Environment (please complete the following information):**
 - OS: OSX
 - Go version : go1.12.7 darwin/amd64
 - Proxy version : v0.3.0
 - Storage (fs/mongodb/s3 etc.) : disk

**Additional context**
If I'm misunderstanding how Athens is supposed to store packages, that's fine. Just need someone to point out what I'm doing wrong, if so.

**Comment by arschles** [comment]
Hi @kevin-cantwell - a few questions, and apologies if you've already done some/all of these. It'll help me understand what's going on:

- when you view the container logs after you do the `go get`, do you see Athens doing the downloads in the background? I'm assuming you already verified this but I want to make sure
- can you run `ls` on the `/athens/storage` directory in the container? I usually do this with `docker exec ...` but whatever method you prefer
- if you stop and restart the container, do your modules persist? If so, that might indicate that Athens is indeed writing to the wrong place on your system (which definitely sounds like a bug 😱 😆)

**Comment by leucos** [comment]
@kevin-cantwell it seems that you are looking into `$HOME/go/.athens` directory while you used `$HOME/.athens/storage`. Are they symlinked or do you have a type on line 2 ?

**Comment by robjloranger** [comment]
I followed your reproduction steps and found that the directory is populated as expected. Is it possible as mentioned, that you were checking the wrong directory?

**Comment by arschles** [comment]
@kevin-cantwell I am going to close this issue. If you get a chance to check out the comments from me, @leucos and @robjloranger can you let us know either in here or a new issue?

Thanks!
