### ISSUE TITLE
Host binaries that CI uses

### ISSUE THREAD

**Issue by arschles** [gomods/athens#134]
Our travis config file does several `go get` requests to get CLIs that it needs (i.e. `golint`)

As @marpio pointed out, this has caused flakes. There are two options I can think of:

1. Create a docker image with these CLIs in it, and use it in CI
2. Host the linux builds for these CLIs somewhere and download them from CI

(1) is overall harder than (2) because we have to run the CI build in `sudo`, which runs it in a dedicated VM. My vote is for (2)

**Comment by arschles** [comment]
@marpio we're using hosted CI services so can't use our own VMs right now

**Comment by robjloranger** [comment]
I think as part of #420 we can include this, I'm going to close and link back from there for reference.
