### ISSUE TITLE
Is there interest in SystemD installation?

### ISSUE THREAD

**Issue by rickb777** [gomods/athens#1354]
It's generally quite easy to install Go services on Linux systems that support [SystemD](https://en.wikipedia.org/wiki/Systemd). For such servers, Docker is an unnecessary dependency and unwanted overhead. For example, I already run [Caddy](https://caddyserver.com/) this way in Ubuntu.

Is there much interest in running Athens this way? If so, I can help get it started.

**Comment by manugupt1** [comment]
I would love to see systemd and other init based systems supported

Cheers
Manu

________________________________

**Comment by rugwirobaker** [comment]
Has anyone taken it? @arschles

**Comment by rickb777** [comment]
I have started preparing a PR. It works but only with Ubuntu >16 a.t.m

**Comment by rickb777** [comment]
w.i.p. https://github.com/rickb777/athens/commits/master

**Comment by robjloranger** [comment]
Hi @rickb777, just checking in. How is it going with your WIP?

**Comment by rickb777** [comment]
Hi, I have it working for latest Ubuntu and I have had similar scripts etc working for earlier (non-SystemD) versions. I could make a PR at this point, but it's incomplete. I haven't yet got good testing (e.g. via docker) and only really know for sure that the latest Ubuntu SystemD installation works. I can't yet demonstrate that other Linux flavours and/or version are ready.

**Comment by arschles** [comment]
@rickb777 that's awesome! if you like, you can submit the PR and we're happy to try it out and give feedback. if not, absolutely no worries. we'll be here when you're ready

**Comment by arschles** [comment]
Hey @rickb777 are you still interested in doing this? You had mentioned you have something but it's incomplete. I'd love to check it out if you're ok with PR-ing it. If not, absolutely no worrries and no pressure!

**Comment by rickb777** [comment]
Hi, I'm trying to get a PR together shortly.

**Comment by rickb777** [comment]
Sorry it took so long.

I have the outlines of SysV service management too, but Ubuntu has moved away from this some time ago. Is it worth doing?

**Comment by arschles** [comment]
@rickb777 if you think it would still be helpful to folks (even though ubuntu has moved away from this), then I think it's worth doing 😄. Up to you!
