### ISSUE TITLE
Make docker based unit tests and e2e tests use upstream proxy to download dependencies

### ISSUE THREAD

**Issue by gowdabas** [gomods/athens#1364]
**Is your feature request related to a problem? Please describe.**
Currently the unit tests and end-to-end tests that run within the docker container use VCS to download the dependencies required for Athens. We would like to change this to use an upstream proxy.

**Describe the solution you'd like**
Use proxy.golang.org instead of VCS to download the dependencies required for Athens to run the tests within docker.

**Describe alternatives you've considered**
N/A

**Comment by gowdabas** [comment]
Picking this up.

**Comment by robjloranger** [comment]
@gowdabas how are you doing with this? Just checking in to see if you ran into an issue.

**Comment by gowdabas** [comment]
Hi @robjloranger I made the changes to docker-compose.yml but like I mentioned on the slack channel ran into an issue while running e2e tests. I'll create a PR for now and I can either add to it on fixing the other issue or address it separately.

**Comment by gowdabas** [comment]
@robjloranger Actually looks like the issue was with my dev setup. Cleaned up things on my system and e2e tests are running fine.
