### ISSUE TITLE
introduce GOPRIVATE configuration for private modules

### ISSUE THREAD

**Issue by yittg** [gomods/athens#1373]
**Is your feature request related to a problem? Please describe.**
In #1294 #1304 , athens introduce a config to download from upstream proxy,
a approach to indicates module paths that are not publicly available and disable proxy is needed

**Describe the solution you'd like**
The go env `GOPRIVATE` is what we want, we should introduce it as configuration also.

**Comment by yittg** [comment]
cc @arschles

**Comment by arschles** [comment]
@yittg sorry for not responding sooner. I made a comment on this issue in the PR you submitted, [here](https://github.com/gomods/athens/pull/1374#issuecomment-530605760)
