### ISSUE TITLE
Cannot configure download mode for a whole domain

### ISSUE THREAD

**Issue by jorng** [gomods/athens#1375]
Nevermind. Ignore this.

**Comment by jorng** [comment]
Looks like `go` implements this via [`str.GlobsMatchPath`](https://golang.org/src/cmd/go/internal/str/path.go#L54) at `src/cmd/go/internal/str/path.go`.

**Comment by arschles** [comment]
😄

**Comment by jorng** [comment]
Sorry for the noise, I will need to follow up on this later, once I have company approval.
