### ISSUE TITLE
Fail in go mod download :  unable to access 'https://git.apache.org/thrift.git/'

### ISSUE THREAD

**Issue by wangkirin** [gomods/athens#1376]
**Describe the bug**
I try to clone the latest `athens` code and build from source. But when I run `go mod download`, 
it fails.

**Error Message**
```consle
go: finding git.apache.org/thrift.git v0.0.0-20180902110319-2566ecd5d999
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f https://git.apache.org/thrift.git refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/gopath/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
        fatal: unable to access 'https://git.apache.org/thrift.git/': The requested URL returned error: 502
``` 

**To Reproduce**

1. `git clone https://github.com/gomods/athens.git`
2.  `go mod download`

**Expected behavior**
go mod success

**Environment (please complete the following information):**
 - OS: Linux 64bit
 - Go version : go version go1.11.13 linux/amd64
 - Proxy version : latest

**Additional context**

I search the repository, this package is not used by `Athens` directly, it is imported by the 
`go.opencensus.io/exporter/jaeger`

and I also found the same issue problem in : 
https://github.com/google/go-cloud/issues/1635

from this issue, I test the solutions and it works 
```
// Append following line in the bottom of go.mod
replace git.apache.org/thrift.git => github.com/apache/thrift v0.12.0
```

**May be we can also add this in `go.mod`  of  `athens` ?**

**Comment by arschles** [comment]
@wangkirin yes, I think that would be a great idea. Would you be willing to submit a PR to update the `go.mod`?

**Comment by wangkirin** [comment]
> @wangkirin yes, I think that would be a great idea. Would you be willing to submit a PR to update the `go.mod`?

Sure, the PR already submitted.

**Comment by marwan-at-work** [comment]
@wangkirin this is actually fixed if you use `GOPROXY=proxy.golang.org`, otherwise all of our builds would fail. 

Can you not use the Go proxy in your builds?

**Comment by twexler** [comment]
It looks like git.apache.org is dead for good, and we should change the import anyway: https://blogs.apache.org/infra/entry/subversion-to-git-service-git

**Comment by wangkirin** [comment]
> It looks like git.apache.org is dead for good, and we should change the import anyway: https://blogs.apache.org/infra/entry/subversion-to-git-service-git

Agree! But it seems the `thrift` package is not directly imported by `athens` ,  it is imported by  `opencensus-go`  v0.17.0 (an old&archived version)
https://github.com/census-instrumentation/opencensus-go/blob/79993219becaa7e29e3b60cb67f5b8e82dee11d6/exporter/jaeger/jaeger.go#L28

@marwan-at-work @twexler 
I think if we want to solve it completely,  we may try to help `opencensus` change its import
Unfortunately，  I found its  `master` branch didn't contain jager exporter anyone. I will keep trying to find out what happened behind that.

**Comment by marwan-at-work** [comment]
It would be ideal if we fixed the go.mod file in opencensus, then we only need update our opencensus dependency in our go.mod file. 

For now, using GOPROXY=proxy.golang.org should be a valid workaround IMO, and if people can't get around that, please do say so here so we can accept the `replace` PR :) 

Thanks!

**Comment by twexler** [comment]
It looks like they're already tracking this: census-instrumentation/opencensus-go#1158

**Comment by twexler** [comment]
@wangkirin
>  I found its master branch didn't contain jager exporter anyone. I will keep trying to find out what happened behind that.

Looks like that got moved, see census-instrumentation/opencensus-go#1100

**Comment by wangkirin** [comment]
@twexler 
Thank you for reminding :) 
I will see how to update the athens code

**Comment by wangkirin** [comment]
@marwan-at-work @twexler 
I have submitted a new PR to solve this problem by update the  opencensus dependency :)
Please take a look

**Comment by marwan-at-work** [comment]
Fixed by https://github.com/gomods/athens/pull/1392
