### ISSUE TITLE
Add tests for proxy routes

### ISSUE THREAD

**Issue by marpio** [gomods/athens#138]
At the moment there are not tests for cmd/proxy/actions package.

**Comment by arschles** [comment]
I'm going to take this tomorrow 😄

**Comment by arschles** [comment]
@fedepaol I remember you mentioning that you have a PR that added some tests for proxy routes. was it #456?

**Comment by nclandrei** [comment]
Hi there, guys! I really want to start contributing to Athens so I thought this PR was a good start. 

I see the PR suggested by @fedepaol hasn’t been merged yet. Is this still available? Can I start working on a PR for it? 😁

**Comment by nclandrei** [comment]
Awesome, thanks! :) Awaiting reply then!

**Comment by fedepaol** [comment]
Sorry for not being helpful !

**Comment by nclandrei** [comment]
No problem at all, @fedepaol! 🙂

**Comment by robjloranger** [comment]
@nclandrei that PR is very out of date so feel free to start another, just comment here if you do and we can close the old one.

**Comment by xiaoyunyang** [comment]
I'd like to take this on if no one else is working on this right now.

**Comment by michalpristas** [comment]
Hey @xiaoyunyang feel free to start, in case of any questions just ping us on Athens slack channel on Gophers slack

**Comment by xiaoyunyang** [comment]
@michalpristas Thanks. I'm targeting submitting a PR by the end of this week.

**Comment by arschles** [comment]
@xiaoyunyang I'm going to close this issue now. If you'd still like to write more tests, please feel free to comment here or submit a PR. If you comment here, I'll still get the notification and we can continue the discussion. Cheers! 😄
