### ISSUE TITLE
Disable SUMDB

### ISSUE THREAD

**Issue by LukeMauldin** [gomods/athens#1383]
**Describe the bug**
In an airgapped scenario, when using the versions below and doing ‘go get github.com/foo/bar’, Athens tries to query the standard Go sumdb website which fails due to lacking external internet access. Cannot resolve this issue client side because Go 1.12 does not support Goprivate. This scenario works as expected in Athens 0.5.0 because that version does not query Go sumdb. 

**Expected behavior**
Athens 0.6.0 works like 0.5.0 for Go 1.12 clients accessing packages that are in local storage only.

**Environment (please complete the following information):**
 - OS: Linux 64bit
 - Go version : 1.12.9
 - Proxy version : 0.6.0
 - Storage (fs/mongodb/s3 etc.) : fs 

**Additional context**

**Comment by draeron** [comment]
Have you tried the `ATHENS_GONOSUM_PATTERNS` env ? I've tried it but athens keep doing request (which fail).

Ref: https://docs.gomods.io/configuration/sumdb/#why-proxy-a-checksum-db

**Comment by LukeMauldin** [comment]
I have multiple values for SumDBs and NoSumPatterns in the config file but Athens 0.6.0 always makes the sumdb request which fails in the airgapped scenario.

**Comment by svillars-bl** [comment]
I just ran into this as well, I _think_ the logic might be wrong. I have set a private repo in the environment variable and I'm getting 403's. According to the logic below, if the pattern matches then it issues a 403. Shouldn't it let it pass through if the pattern matches?

https://github.com/gomods/athens/blob/0cac0edbf1f4d59620e28268b8d242537a3e680e/cmd/proxy/actions/sumdb.go#L24-L36

**Comment by svillars-bl** [comment]
I just ran into this as well, I _think_ the logic might be wrong. I have set a private repo in the environment variable and I'm getting 403's. According to the logic below, if the pattern matches then it issues a 403. Shouldn't it let it pass through if the pattern matches?

If I don't put the repo name in `ATHENS_GONOSUM_PATTERNS` then I get 410s

https://github.com/gomods/athens/blob/0cac0edbf1f4d59620e28268b8d242537a3e680e/cmd/proxy/actions/sumdb.go#L24-L36

**Comment by marwan-at-work** [comment]
Can you please create reproducible steps, if a module is in Athens storage, Athens does not consult the sum database.

**Comment by marwan-at-work** [comment]
@svillars-bl the expected behavior is 403, not to let is pass. See https://github.com/gomods/athens/blob/master/docs/content/configuration/sumdb.md for motivation

**Comment by svillars-bl** [comment]
Ah I see, so if I understand correctly, the 403 is telling the client that it didn't reach out to the sumcheck service, *not* that the whole action failed.

**Comment by marwan-at-work** [comment]
@LukeMauldin we released `v0.6.1` can you give it a go and see if it resolves your issue?

**Comment by LukeMauldin** [comment]
Yes. I tested that version and it works with both 1.12.9 and 1.13 Go clients.

**Comment by arschles** [comment]
@LukeMauldin it seems like `v0.6.1` solved the problem. I'm going to close this, but if I got it wrong, please comment here and we can open it back up 😁
