### ISSUE TITLE
Athens hangs when receiving a request for a module that does not exist

### ISSUE THREAD

**Issue by ZHRen** [gomods/athens#1385]
**Describe the bug**
When go get a module which does not exist in origion repo through Athens, such as github.com/rzh/gotest, the Athens process will hang because you need to enter the username and password for github. 

**Expected behavior**
Athens responds with 404 or other error codes instead of hanging when receiving a request for a module that does not exist.

**Environment (please complete the following information):**
 - OS: Linux 64bit
 - Go version : 1.13
 - Proxy version : 0.6.0
 - Storage (fs/mongodb/s3 etc.) : disk

**Comment by arschles** [comment]
@ZHRen is Athens trying to fetch a module from a private github repository? If so, is it [configured to authenticate to a private github repository](https://docs.gomods.io/configuration/authentication/)?

**Comment by arschles** [comment]
@ZHRen I am going to close this issue now. Can you please comment here or open a new issue if you are still seeing it with the latest `v0.7.0` release of Athens?
