### ISSUE TITLE
NOSUMDB/ATHENS_GONOSUM_PATTERNS Being Ignored

### ISSUE THREAD

**Issue by tankbusta** [gomods/athens#1386]
**Describe the bug**

I'm setting `ATHENS_GONOSUM_PATTERNS` but I'm still seeing Athens attempt to reach out to `https://sum.golang.org/lookup` for the package that should be matched in the GONOSUM_PATTERNS

My Config:

`ATHENS_GONOSUM_PATTERNS: github.mycorp.local/*`

**Error Message**
```
time="2019-09-18T17:47:35Z" level=error msg="exit status 1: go: finding github.mycorp.local/chris-schmitt/mypkg v1.1.3\ngo: finding github.mycorp.local/chris-schmitt/mypkg v1.1.4\nverifying github.mycorp.local/chris-schmitt/mypkg@v1.1.3/go.mod: github.mycorp.local/chris-schmitt/mypkg@v1.1.3/go.mod: reading https://sum.golang.org/lookup/github.mycorp.local/chris-schmitt/mypkg@v1.1.3: 410 Gone\n" http-method=GET http-path=/github.mycorp.local/chris-schmitt/mypkg/@v/v1.1.3.info http-url=/github.mycorp.local/chris-schmitt/mypkg/@v/v1.1.3.info kind="Internal Server Error" module=github.mycorp.local/chris-schmitt/mypkg operation=download.InfoHandler ops="[download.InfoHandler pool.Info protocol.Info protocol.processDownload stash.Pool stasher.Stash stasher.fetchModule goGetFetcher.Fetch module.downloadModule]" version=v1.1.3
```
</pre>

**To Reproduce**

1. Set `ATHENS_GONOSUM_PATTERNS` to a pattern matching an internal GitHub/GitLab or private repo
2. Attempt to fetch the package locally with env `GOPROXY="https://myathens"` and `GONOSUMDB=github.mycorp.local`
3. Get failure message on compilation `go: github.mycorp.local/chris-schmitt/mypkg@v1.1.3: unexpected status (https://goproxy.mycorp.local/github.mycorp.local/chris-schmitt/mypkg/@v/v1.1.3.info): 500 Internal Server Error

**Expected behavior**

Working builds where Athens will fetch and cache packages that are in our internal GitHub instance while not reaching out to `https://sum.golang.org/lookup` (thus skipping the checksum database)

**Environment (please complete the following information):**
 - OS: Kubernetes (using your helm chart)
 - Go version : 1.13
 - Proxy version : v0.6.0
 - Storage (fs/mongodb/s3 etc.) : fs

**Comment by tankbusta** [comment]
This might be related to what @draeron mentioned in #1383

**Comment by robjloranger** [comment]
Have a look at [path.Match](https://golang.org/pkg/path/#Match) which is used to process these patterns.

In order to match against `github.mycorp.local/chris-schmitt/mypkg` you would need `github.mycorp.local/*/*` as in this example https://play.golang.org/p/4my0GowsEeJ.

Keep in mind though, that you would need another `/*` for each sub package deeper an import could be.

**Comment by tankbusta** [comment]
Ah, I didn't realize it was using path.Match

> Keep in mind though, that you would need another /* for each sub package deeper an import could be.

This is somewhat concerning since given the end users don't have much control over it? I don't want anything matching `github.mycorp.local` to ever hit the Public Checksum DB but at the same time I have no idea about my other users and their sub packages. It'd be nice if this used Regex (since `**` isn't supported) or a custom matcher that implemented a true wildcard for all sub-packages

**Comment by draeron** [comment]
maybe using a regexp instead of `path.Match` would make more sense ?

**Comment by robjloranger** [comment]
I agree, either solution would be awesome. I think with a custom matcher we could allow user's to supply a regex with less changes to existing code.

**Comment by iwittkau** [comment]
I have the same problem.

**Even setting a correct pattern does result in athens querying sum.golang.org** (internal server error).

My configuration is similar to this:

Pattern: `git.region.company.com/*/*`  
Module Name: `git.region.company.com/group/project`

which results in a positive (`true`) match for `path.Match`. But athens still tries to query sum.golang.org and returns an internal server error.

I think to avoid this, [the fetcher](https://github.com/gomods/athens/blob/master/pkg/module/go_get_fetcher.go#L110) needs to set `GONOSUMDB` in the environment for the underlying `go mod download` command?

**Comment by draeron** [comment]
i think the `ATHENS_GONOSUM_PATTERNS` use the same rule / parsing as the `GONOSUMDB`.

https://go.googlesource.com/proposal/+/master/design/25530-sumdb.md#command-client

**Comment by robjloranger** [comment]
interesting, it looks like it should just support prefixes and globs. perhaps we do just need to set the `GONOSUMDB`. If anyone has some time that would be awesome to see if the solution works. If not I can try later today.

**Comment by housejester** [comment]
I'm running into the same, and came to roughly the same conclusion today (ie, update the fetcher to pass through a GONOSUMDB env) before looking for existing issues here. 

It may also be worth passing through the GOPRIVATE env. The way we are using Athens is that we are cool with athens accessing our private repos, so that part is succeeding, but then it is failing to do the sum check. But even if we fix that by passing through the GONOSUMDB, wouldn't the fetcher still be first attempting to find the module in the default proxy (since the default is now "https://proxy.golang.org,direct"), thus leaking the repo location to the upstream?  If so, then allowing a pass-through for GOPRIVATE should fix that i think. That then could make reasoning about things from Athens perspective a bit simpler: i just tell athens what my private repos look like, and it can do the right thing when fetching from upstream as well as proxying sumdb calls.

**Comment by robjloranger** [comment]
update: #1388 is up for review and should fix this behavior

**Comment by housejester** [comment]
Hm, I'm not sure it fixes it though. As @iwittkau said, even with a correctly matching pattern, it still attempts to do the sum check, which i believe is actually happening as part of the module fetcher (vs the sumdb proxy action)

**Comment by robjloranger** [comment]
Ah yes, sorry. Got ahead of my self. Two similar issue going on.

**Comment by iwittkau** [comment]
I created a fork [which passes](https://github.com/iwittkau/athens/commit/339c38221ef384e61db68f1ca49f276baf727a60#diff-60cb5f85a375bf645ff29733ae285284) `ATHENS_GONOSUM_PATTERNS` in the fetcher. I'm not sure if I went a little too far with my implementation but I can submit a pull request if it's ok.

**Comment by marwan-at-work** [comment]
@housejester the GOSUM still being checked is a different issue. It's because we don't pass GOPRIVATE or GONOSUMDB to our internal `go mod download` command. I'm pushing another PR for this really soon :)

**Comment by marwan-at-work** [comment]
v0.6.1 is now released, please feel free to try it and re-open the issue if the error persists

**Comment by iwittkau** [comment]
I ran tests with two of our bigger projects. Now works as expected with private repos, no sums are checked. Thanks @marwan-at-work!
