### ISSUE TITLE
SingleFlight.Redis endpoint does not support setting passwords

### ISSUE THREAD

**Issue by ZHRen** [gomods/athens#1387]
**Describe the bug**
SingleFlight.Redis endpoint does not support setting passwords. I have tried "redis://:password@host:6379", but it didn't work. 

**Error Message**
2019-09-19 11:52:37.207681 I | error adding proxy routes (NOAUTH Authentication required.)
or
2019-09-19 14:42:06.649731 I | error adding proxy routes (dial tcp: address redis://:passrord@host:6379: too many colons in address)

**Expected behavior**
SingleFlight.Redis endpoint support setting passwords.

**Environment (please complete the following information):**
 - OS: Linux 64bit
 - Go version : 1.13
 - Proxy version : 0.6.0
 - Storage (fs/mongodb/s3 etc.) : disk

**Comment by arschles** [comment]
@ZHRen thanks for this catch! I think the best fix for doing this is adding a `[SingleFlight.Redis.Password]` field to the `config.toml` file and a corresponding `ATHENS_REDIS_PASSWORD` environment variable override, and then using that variable in https://github.com/gomods/athens/blob/master/pkg/stash/with_redis.go#L17.

Would you be up for submitting a PR for that? No pressure at all to do so - let me know and I'll do it if not.
