### ISSUE TITLE
Missing Mongo Configuration?

### ISSUE THREAD

**Issue by robjloranger** [gomods/athens#139]
Just trying to run the test suite without any changes to the source I'm getting an error about the mongo URL env variable.
`creating eventlog (missing mongo URL (could not find ENV var with ATHENS_MONGO_STORAGE_URL))`

Should there be some instructions on setting this? I have the docker images all running, `buffalo dev` works from `cmd/proxy`.
Is this even required or is this another issue masquerading?

**Comment by marpio** [comment]
@robjloranger 
Please try setting the env vars:
```
export POP_PATH=$PWD/cmd/proxy
export GO_ENV=test_postgres
export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=minio123
export ATHENS_MONGO_STORAGE_URL=mongodb://127.0.0.1:27017
```
You can also take a look at travis.yml for reference.

**Comment by robjloranger** [comment]
Should this be added to the readme? I'm happy to add it if so.
