### ISSUE TITLE
Support recursive glob patterns in download mode configuration

### ISSUE THREAD

**Issue by fsouza** [gomods/athens#1401]
When using a download mode config file, we've noticed that the glob pattern for paths doesn't support recursive globs. This ticket is a feature request for support it 😁  It's particularly useful for users of GitHub Enterprise or repositories with multiple modules (and can help ensure import paths don't leak when ``go get``ing a package inside a module). This is what the config would look like:

```hcl
downloadURL = "https://proxy.golang.org"

mode = "redirect"

download "ghe.example.com/**/*" {
    mode = "sync"
}
```

**Comment by arschles** [comment]
@fsouza can you remind me, did we merge a PR that fixed this?

**Comment by fsouza** [comment]
@arschles yes, sorry I should've tagged it 🙈 

It's #1409.

**Comment by arschles** [comment]
No worries - thanks for tagging it!
