### ISSUE TITLE
Missing self signed certificate

### ISSUE THREAD

**Issue by volker-raschek** [gomods/athens#1407]
I would like to add the companies self singed certificate over a volume mount into the container image. Otherwise, when downloading go models via the company's internal gitlab server, which is secured by a self signed ssl certificate, athens throws an ssl error and the build fails at the developers. 

How can add the self signed certificate into the container image of athens to trust the https connection to the internal ssl secured gitlab server? It there a special mountpoint or environment variable to add the self signed certificate?

```bash
go-proxy    | time="2019-10-01T15:29:31+02:00" level=info msg="gitlab.intranet.local/orbis-u/dockerutil@v0.0.0-20190408202246-0fd8246fbf3d: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /tmp/athens733478626/pkg/mod/cache/vcs/abb8d81d306d85d41231105a19ba3798187f029ef24f1b5062e5e89885fe1c77: exit status 128:\n\tfatal: unable to access 'https://gitlab.intranet.local/orbis-u/dockerutil.git/': SSL certificate problem: self signed certificate in certificate chain" http-method=GET http-path=/gitlab.intranet.local/orbis-u/dockerutil/@v/v0.0.0-20190408202246-0fd8246fbf3d.info http-url=/gitlab.intranet.local/orbis-u/dockerutil/@v/v0.0.0-20190408202246-0fd8246fbf3d.info kind="Not Found" module=gitlab.intranet.local/orbis-u/dockerutil operation=download.InfoHandler ops="[download.InfoHandler pool.Info protocol.Info protocol.processDownload stash.Pool stasher.Stash stasher.fetchModule goGetFetcher.Fetch module.downloadModule]" version=v0.0.0-20190408202246-0fd8246fbf3d
```

**Comment by arschles** [comment]
@volker-raschek forgive my ignorance because I've never done this in Athens, but is it possible to specify an `insteadOf` rule to use SSH instead of the https URL using a `.gitconfig` like [this](https://docs.gomods.io/configuration/authentication/#altassian-bitbucket-and-ssh-secured-git-vcs-s).

If I'm way off here, let's look into how to add self-signed certs.

**Comment by brian73286** [comment]
While the [athens config file](https://github.com/gomods/athens/blob/release-v0.7.0/config.dev.toml) allows configuring a TLS key and certificate it does not allow users to add or set certificate authority certificates (self-signed certificates). Therefore you'll be left with whatever CA cert stuff Go does which on Linux is defined in https://github.com/golang/go/blob/release-branch.go1.13/src/crypto/x509/root_unix.go

You should read the first 34 lines of that file and either set the appropriate environment variable inside your athens container to the file path of your self-signed certificate or add the self-signed certificate to one of the listed directories that is searched for certificates.

**Comment by arschles** [comment]
Thanks @brian73286. I think I see what you and @volker-raschek are saying much more clearly now.

Is this a matter of setting environment variables (`SSL_CERT_FILE` and `SSL_CERT_DIR`) that Athens will set when it invokes the `go` binary? If so, we do have an environment variable called [`ATHENS_GO_BINARY_ENV_VARS`](https://github.com/gomods/athens/blob/81102aa38d8999d370157e82f1260907b6d6d9e2/config.dev.toml#L38) that you could use.

Let me know if that will work.

**Comment by arschles** [comment]
@brian73286 @volker-raschek I am going to close this issue now, but I'm happy to continue the conversation. If you want, please feel free to come comment on this issue. I'll get the notification and come back to open it back up.

**Comment by jevgenis33** [comment]
Has anyone found a solution to this problem? How can I add a SSL certificate to athens proxy?

Error:
`SSL certificate problem: unable to get local issuer certificate`
