### ISSUE TITLE
Publish commit-tagged Docker images

### ISSUE THREAD

**Issue by bndw** [gomods/athens#1412]
It would be awesome if all commits in master had a corresponding Docker tag. 

For example, I'm affected by the bugfix in https://github.com/gomods/athens/commit/ed66d85f3fa7d8cef17aad567c0c3e719e76eba1 but it appears my only option for deploying that fix is to run `gomods/athens:canary`. There is a `:latest` tag but that seems to be the latest release, instead of the tip of master.

Suggestion:
- Publish all master commit tags, e.g. `gomods/athens:ed66d85f3fa7d8cef17aad567c0c3e719e76eba1`
- Publish the tip of master at `gomods/athens:latest`

For an example of this in the wild, [Envoy](https://github.com/envoyproxy/envoy) uses this tagging scheme.

It looks like it'd just take adding a `DRONE_COMMIT` tag to the `docker-latest` setup in the drone  config to get the per-commit tags. Let me know if that's a contribution you'd like.

**Comment by arschles** [comment]
@bndw I think this is a great idea!

One modification: would you be open to making the corresponding docker tag the first N (7 is a good choice IMO) characters in the git SHA?

We'd love a PR for this, if you're willing.

**Comment by marwan-at-work** [comment]
This can end up making our docker hub page look real gigantic in a year or so. 

If we actually do release once a month, then the current "canary" version and the latest stable release won't be too far off. 

However, if we want to do commit shas, then we should at least have a strategy of cleaning them up and warning the user about commit shas being eventually removed.

**Comment by bndw** [comment]
That's a good point, it will inflate Dockerhub and unfortunately they still don't have any filtering, search, etc.

I just looked at Envoy again and it looks like they've recently split this into two Dockerhub repos, one for [releases](https://hub.docker.com/r/envoyproxy/envoy/tags) and one for [commits on master](https://hub.docker.com/r/envoyproxy/envoy-dev/tags).

**Comment by marwan-at-work** [comment]
@bndw that might be a really good idea. If other maintainers are cool with it, then we can make a `gomods/athens-dev`

**Comment by robjloranger** [comment]
`gomods/athens-dev` has been created

**Comment by marwan-at-work** [comment]
@robjloranger thank you thank you thank you

**Comment by arschles** [comment]
late to the game, but 👍 to `gomods/athens-dev` from me too 😆
