### ISSUE TITLE
Cannot fetch modules from sources like "rsc.io" or "go.etcd.io" when using network that performs TLS MiTM

### ISSUE THREAD

**Issue by nmiyake** [gomods/athens#1417]
**Describe the bug**
Running commands like `go get rsc.io/sampler@v1.3.1` and `go get go.etcd.io/etcd@v3.4.1` using Athens as the module server fails.

**Error Message**
In the console:

```console
go: finding rsc.io/sampler v1.3.1
go: finding rsc.io v1.3.1
go get rsc.io/sampler@v1.3.1: unexpected status (http://localhost:3000/rsc.io/sampler/@v/v1.3.1.info): 404 Not Found
```

Logs:

```console
time="2019-10-09T23:23:14Z" level=info msg="rsc.io/sampler@v1.3.1: invalid version: unknown revision v1.3.1" http-method=GET http-path=/rsc.io/sampler/@v/v1.3.1.info http-url=/rsc.io/sampler/@v/v1.3.1.info kind="Not Found" module=rsc.io/sampler operation=download.InfoHandler ops="[download.InfoHandler pool.Info protocol.Info protocol.processDownload stash.Pool stasher.Stash stasher.fetchModule goGetFetcher.Fetch module.downloadModule]" version=v1.3.1
time="2019-10-09T23:23:15Z" level=info msg="rsc.io@v1.3.1: unrecognized import path \"rsc.io\" (parse https://rsc.io/?go-get=1: no go-import meta tags ())" http-method=GET http-path=/rsc.io/@v/v1.3.1.info http-url=/rsc.io/@v/v1.3.1.info kind="Not Found" module=rsc.io operation=download.InfoHandler ops="[download.InfoHandler pool.Info protocol.Info protocol.processDownload stash.Pool stasher.Stash stasher.fetchModule goGetFetcher.Fetch module.downloadModule]" version=v1.3.1
time="2019-10-09T23:23:44Z" level=info msg="rsc.io/sampler@v1.3.1: invalid version: unknown revision v1.3.1" http-method=GET http-path=/rsc.io/sampler/@v/v1.3.1.info http-url=/rsc.io/sampler/@v/v1.3.1.info kind="Not Found" module=rsc.io/sampler operation=download.InfoHandler ops="[download.InfoHandler pool.Info protocol.Info protocol.processDownload stash.Pool stasher.Stash stasher.fetchModule goGetFetcher.Fetch module.downloadModule]" version=v1.3.1
time="2019-10-09T23:23:44Z" level=info msg="rsc.io@v1.3.1: unrecognized import path \"rsc.io\" (parse https://rsc.io/?go-get=1: no go-import meta tags ())" http-method=GET http-path=/rsc.io/@v/v1.3.1.info http-url=/rsc.io/@v/v1.3.1.info kind="Not Found" module=rsc.io operation=download.InfoHandler ops="[download.InfoHandler pool.Info protocol.Info protocol.processDownload stash.Pool stasher.Stash stasher.fetchModule goGetFetcher.Fetch module.downloadModule]" version=v1.3.1
```

**To Reproduce**
```
docker run -p '3000:3000' gomods/athens:latest
```

Then:

```
GO111MODULE=on GOPROXY=http://localhost:3000 go get rsc.io/sampler@v1.3.1
```

**Expected behavior**
Operation should succeed, as running the operation without the proxy does succeed.

**Environment (please complete the following information):**
 - OS: macOS 10.14.6
 - Go version : 1.12.10
 - Proxy version : v0.6.1
 - Storage (fs/mongodb/s3 etc.) : fs

**Comment by marwan-at-work** [comment]
@nmiyake I'm unable to reproduce your bug.

On the client side, here's the command I ran: 

```
GOPATH=/tmp/dir GO111MODULE=on GOPROXY=http://localhost:3000 go get rsc.io/sampler@v1.3.1
go: finding rsc.io/sampler v1.3.1
go: finding rsc.io v1.3.1
go: downloading rsc.io/sampler v1.3.1
go: extracting rsc.io/sampler v1.3.1
go: downloading golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c
go: extracting golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c
go: finding golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c
```

On the Athens side, here are my logs: 


```
docker run -e 'GO_ENV=development' -p '3000:3000' gomods/athens:latest
time="2019-10-17T01:29:04Z" level=info msg="Exporter not specified. Traces won't be exported"
2019-10-17 01:29:04.172139 I | Starting application at port :3000
handler: GET /rsc.io/@v/v1.3.1.info [404]
time="2019-10-17T01:29:18Z" level=info msg="rsc.io@v1.3.1: unrecognized import path \"rsc.io\" (parse https://rsc.io/?go-get=1: no go-import meta tags ())" http-method=GET http-path=/rsc.io/@v/v1.3.1.info http-url=/rsc.io/@v/v1.3.1.info kind="Not Found" module=rsc.io operation=download.InfoHandler ops="[download.InfoHandler pool.Info protocol.Info protocol.processDownload stash.Pool stasher.Stash stasher.fetchModule goGetFetcher.Fetch module.downloadModule]" version=v1.3.1
handler: GET /rsc.io/sampler/@v/v1.3.1.info [200]
handler: GET /rsc.io/sampler/@v/v1.3.1.zip [200]
handler: GET /sumdb/sum.golang.org/supported [200]
handler: GET /sumdb/sum.golang.org/lookup/rsc.io/sampler@v1.3.1 [200]
handler: GET /sumdb/sum.golang.org/tile/8/1/004.p/222 [200]
handler: GET /sumdb/sum.golang.org/tile/8/1/000 [200]
handler: GET /sumdb/sum.golang.org/tile/8/2/000.p/4 [200]
handler: GET /sumdb/sum.golang.org/tile/8/0/x001/246.p/96 [200]
handler: GET /sumdb/sum.golang.org/tile/8/0/093 [200]
handler: GET /rsc.io/sampler/@v/v1.3.1.mod [200]
^[handler: GET /golang.org/x/text/@v/v0.0.0-20170915032832-14c0d48ead0c.mod [200]
handler: GET /sumdb/sum.golang.org/lookup/golang.org/x/text@v0.0.0-20170915032832-14c0d48ead0c [200]
handler: GET /sumdb/sum.golang.org/tile/8/0/001 [200]
handler: GET /golang.org/x/text/@v/v0.0.0-20170915032832-14c0d48ead0c.zip [200]
handler: GET /golang.org/x/text/@v/v0.0.0-20170915032832-14c0d48ead0c.info [200]
```

**Comment by nmiyake** [comment]
@marwan-at-work thanks for looking into this -- after doing some more debugging, I believe there's an environmental factor at work here.

I sometimes make network connections in an environment that uses a TLS MiTM proxy for all connections (it replaces the TLS cert provided by the server with one that uses an internal root CA). It appears that this issue only manifests when I use that connection. I verified by doing the following:

1. Use network that performs TLS MiTM
2. Start Athens in Docker container
3. Run `GOPATH=/tmp/dir GO111MODULE=on GOPROXY=http://localhost:3000 go get rsc.io/sampler@v1.3.1`
4. Fails with output posted in original issue
5. Switch to network that does not perform TLS MiTM
6. Run same command as step 3 again
7. Works -- shows same output that you posted

If this is an issue caused by the certificate with an unknown root authority, I'm not sure why the failure in step 4 doesn't indicate this.

I've renamed the issue, and will attempt to gather more information to help debug.

**Comment by nmiyake** [comment]
Further verified that the root cause seems to be the CA by adding the MiTM root CA to the Docker image and confirming that this workflow works, even in the MiTM environment.

Given this, I believe the issue here is that Athens is not properly reporting that it attempted to make a connection but that it failed due to receiving a certificate that couldn't be verified. I think this would be helpful information to have so that users that encounter this failure in these kinds of environments can have some idea of what went wrong.

Do you have a sense of what part of the code performs this operation? I know it may be hard to repro this without at TLS MiTM environment, and I'd be happy to take a look with some general guidance.

**Comment by marwan-at-work** [comment]
@nmiyake if the storage is empty, then Athens shells out to `go mod download` and `go list -m` to download/list modules and persist them to storage. And given the log you have originally pasted, it seems the error is in fact coming from this function: https://github.com/gomods/athens/blob/master/pkg/module/go_get_fetcher.go#L104

So this is likely a Go command issue :)

**Comment by marwan-at-work** [comment]
Please feel free to run athens locally to reproduce the issue and see if there's a slight chance of Athens swallowing the error, and if not def feel free to report it to upstream

**Comment by nmiyake** [comment]
Thanks for the pointer! Adding some debugging logic allowed me to run the command with the same environment that Athens did, and that helped to uncover the bug.

Your assessment was correct -- this issue is wholly contained in the `go mod download` call. Filed https://github.com/golang/go/issues/34998 to track the underlying issue. This may end up relating to https://github.com/golang/go/issues/30134 as well, but unless/until the Go command surfaces more information, there's not much that can be done for this on the Athens side, so closing out this issue.
