### ISSUE TITLE
how use ATHENS_GO_BINARY_ENV_VARS or config.dev.toml  in docker

### ISSUE THREAD

**Issue by awkj** [gomods/athens#1421]
**Is your feature request related to a problem? Please describe.**

how use config in docker?
how use ATHENS_GO_BINARY_ENV_VARS in docker, I don't know how to write it in yaml

**Describe the solution you'd like**

should have a varibale to specified config 
and can write a example about ATHENS_GO_BINARY_ENV_VARS in document?

**Describe alternatives you've considered**

**Additional context**

in config.dev.toml I write
GoBinaryEnvVars = ["GOPROXY=https://goproxy.cn","GOPROXY=direct"]

**Comment by brian73286** [comment]
`docker history --no-trunc gomods/athens:v0.7.0` shows the Dockerfile commands used to build the athens image. Athens also publishes their Dockerfile in git which you'll probably find to be more readable https://github.com/gomods/athens/blob/release-v0.7.0/config.dev.toml

You'll notice the command `CMD ["athens-proxy" "-config_file=/config/config.toml"]` specified the athens config file as a parameter to the executable. According to [Athen's config Load function](https://github.com/gomods/athens/blob/release-v0.7.0/pkg/config/config.go) loading a config file that way is tried first so trying to load your config file any other way would be ignored in favor of the default config file bundled inside the athens docker image. Therefore you must volume mount your config file in a way that overlays it over the default file at `/config/config.toml`. To do that please refer to the [docker volume documentation](https://docs.docker.com/storage/volumes/) or [kubernetes volume documentation](https://kubernetes.io/docs/concepts/storage/volumes/) as needed. You can verify your config file is correctly overlaid by `exec`ing into the container/pod following the [docker exec documentation](https://docs.docker.com/engine/reference/commandline/exec/) or [kubernetes exec documentation](https://kubernetes.io/docs/tasks/debug-application-cluster/get-shell-running-container/) and then viewing `/config/config.toml` inside the container to make sure it is your config, not the default.

**Comment by arschles** [comment]
@awkj would this solve the problem you are seeing? Otherwise, is there an easier way that would help you?

I am going to close this issue now, but please feel free to comment here. I will get the notifications if you do, and come back to respond.
