### ISSUE TITLE
Invalid multipart request with 0  with GCP storage

### ISSUE THREAD

**Issue by matejvelikonja** [gomods/athens#1432]
**Describe the bug**
When Athens is cloning some repos, it fails sometimes with bottom error.

**Error Message**

```json
{
  "http-method": "GET",
  "http-path": "/github.com/pmezard/go-difflib/@v/v1.0.0.zip",
  "http-url": "/github.com/pmezard/go-difflib/@v/v1.0.0.zip",
  "kind": "Bad Request",
  "level": "error",
  "module": "",
  "msg": "googleapi: got HTTP response code 400 with body: Invalid multipart request with 0 mime parts.",
  "operation": "download.ZipHandler",
  "ops": [
    "download.ZipHandler",
    "pool.Zip",
    "protocol.Zip",
    "protocol.processDownload",
    "gcslock.Stash",
    "stash.Pool",
    "stasher.Stash",
    "gcp.Save",
    "gcp.upload"
  ],
  "time": "2019-10-22T07:29:42Z",
  "version": ""
}
```

Could be related to https://github.com/googleapis/google-cloud-go/issues/1350, so basically only package update would be needed.

**Comment by arschles** [comment]
@matejvelikonja I was unable to reproduce this. Would you mind trying with the updated package version and let me know if it fixes? If so, we can do the update and release.

**Comment by matejvelikonja** [comment]
cannot reproduce it anymore. looks like it's fixed.
