### ISSUE TITLE
in go.1.13 how config private package 

### ISSUE THREAD

**Issue by awkj** [gomods/athens#1434]
**Is your feature request related to a problem? Please describe.**

in go 1.13, I can config GoBinaryEnvVars ='[xxxx,direct]', but if I wish config it to use CDN, and private use local ssh to get, I try to config Nosum, but no effect, if I config in local enviriment GOPRIVATE variable it's ok.

example my private project is github.com/mycompany/aaaa/bbb.git
I set 
NoSumPatterns = ["github.com/mycompany/*"] 
don't take effect
I see athens have issue report this problem, and it also closed https://github.com/gomods/athens/issues/1383 , so ,is it my config problem?

**Describe the solution you'd like**
how to setting a white list? let me check if project is white list, I use ssh to download and ignore sum, other to use goproxy

**Describe alternatives you've considered**

**Additional context**

**Comment by ferryvg** [comment]
I configure it with go env:
```
GONOSUMDB=git.example.com/*
GOPRIVATE=*.example.com
GONOPROXY=none
```
and `NoSumPatterns` is `git.example.com/*`

**Comment by awkj** [comment]
> I configure it with go env:
> 
> ```
> GONOSUMDB=git.example.com/*
> GOPRIVATE=*.example.com
> GONOPROXY=none
> ```
> 
> and `NoSumPatterns` is `git.example.com/*`

Yes, I try your advice, and can use the config in local, but want to know how to setting in athens

**Comment by Felyne** [comment]
try `docker run` to run `athens` with environment?
```
-e GOPRIVATE="*.example.top" \
```

**Comment by arschles** [comment]
Hi @awkj sorry, this issue slipped through my inbox. It sounds like you want to prompt Athens to download some modules from a CDN and others from a private VCS? If that's correct,  you can set `GoBinaryEnvVars = ["GOPRIVATE=github.com/mycompany/*"]` in the config file, or `export ATHENS_GO_BINARY_ENV_VARS="github.com/mycompany/*"` as an environment variable. See `https://github.com/gomods/athens/blob/master/config.dev.toml#L38 for details on that config setting.

Can you let me know if that works?

**Comment by awkj** [comment]
> Hi @awkj sorry, this issue slipped through my inbox. It sounds like you want to prompt Athens to download some modules from a CDN and others from a private VCS? If that's correct, you can set `GoBinaryEnvVars = ["GOPRIVATE=github.com/mycompany/*"]` in the config file, or `export ATHENS_GO_BINARY_ENV_VARS="github.com/mycompany/*"` as an environment variable. See https://github.com/gomods/athens/blob/master/config.dev.toml#L38 for details on that config setting.
> 
> Can you let me know if that works?

yes , perfect run, because I need Compatible with 1.12, so i must choose set goprivate in server,

if is china user, i suggest use this config 

ATHENS_GO_BINARY_ENV_VARS: "GOPROXY=goproxy.cn,goproxy.io,direct; GOPRIVATE=*.<your company domain>/*"

thanks arschles help

**Comment by arschles** [comment]
@awkj you're welcome, and I'm glad that this is working for you! 😄

Please always feel free to open a new issue if you have more questions or are finding problems
