### ISSUE TITLE
Consider removing 'GO_ENV=production' from proxy Dockerfile

### ISSUE THREAD

**Issue by davidpfarrell** [gomods/athens#1435]
**Is your feature request related to a problem? Please describe.**

Because the proxy Dockerfile adds `GO_ENV=production`, there is no way to override the setting via the config.

This prevents the user from being able to use the config to fully manage their installation.

**Describe the solution you'd like**

Since a permanent environment override (i.e baked into the Dockerfile) makes the related config file property essentially useless, we might consider avoiding them, leaving env overrides solely as a convenience to the user.

**Describe alternatives you've considered**

Alternate solutions could include:

* Remove the `GO_ENV` statement, leaving the default Go Environment settings as "development" as specified in `config-dev.toml`
 (See PR #1443)
* Create a docker-specific config file, i.e. `config-docker.toml` which contains settings deemed useful for the Dockerized use case.
 (See PR #1431)
* Add a step in the Dockerfile that changes the `GoEnv` property to `"production"` - A sed command should likely be able to pull it off easily.
 (See PR #1440)

**Additional context**

I do think there could be value in having opinionated settings for the Dockerized use case, but not sure if env overrides are better than configuration settings.

[edit: Adding links to PRs for each alternate solution mentioned - I think the `Let the default be "development"` option has the most traction per the various discussion threads]

**Comment by ferryvg** [comment]
You can override `GO_ENV` on `docker run` or in `docker-composer.yml`

**Comment by arschles** [comment]
@davidpfarrell it's tough to tell I'm not 100% sure about your use case, but would setting `GO_ENV` to `production` in our semver-tagged images be enough?

It's hard to definitively say what are the best default values to put in the `config.dev.toml` file, and the same goes for the Kubernetes chart, and so on.

**Comment by davidpfarrell** [comment]
> ... would setting `GO_ENV` to `development` in all of our images _except_ our semver-tagged ones be ok with you?

My feeling is that we shouldn't put any environment variables into the user-facing Dockerfiles and instead bake any image-specific configurations into the injected config file.

> It's hard to definitively say what are the best default values to put in the config.dev.toml file, and the same goes for the Kubernetes chart, and so on.

My initial thought (and the related PR) was that a separate config could be useful for the proxy docker use case.

Your comment helps me realize that each of the many docker use cases within the project could possibly benefit  (and maybe already do) from custom configurations.

Having a unique config file for each case doesn't scale well at all, so I'm leaning away from my initial idea of a `config-docker.toml` file.

Instead I'm now leaning toward the idea of modifying the default config file to taste as part of the Dockerfile build.

i.e. in this case, using *sed* (or similar) to change the `GoEnv` property to `"production"`

I'd be happy to modify my PR accordingly if you think its a good idea?

Thanks for chiming in !

-DF

**Comment by davidpfarrell** [comment]
I just submitted PR # 1440 with a `sed`-based solution for review.

**Comment by davidpfarrell** [comment]
I have submitted PR #1443 which simply removes the `GO_ENV=production` statement.

**Comment by davidpfarrell** [comment]
Greetings ! Just checking in to see if there's anything I can do help this along?

I know I have 3 PRs open for this (one for each potential fix idea), but I think #1443 has the most traction.

Please don't hesitate to let me know if you have any questions or suggestions.  Thanks!
