### ISSUE TITLE
While releasing a new tag / container image also release the updated helm chart.

### ISSUE THREAD

**Issue by damoon** [gomods/athens#1437]
**Is your feature request related to a problem? Please describe.**
Currently the helm chart uses a old version.

**Describe the solution you'd like**
Update the helm chart during the release process.

**Describe alternatives you've considered**
Selecting a different image tag for the chart kind of works, but (maybe silently) fail if new or changed configurations are needed.

**Additional context**
Great project. Thanks for all the work :D

**Comment by arschles** [comment]
@damoon awesome idea! we nearly always forget to update the version when we release. Would you be up for submitting a pull request to add this feature? Not a worry in the world if not, just let us know 😄

**Comment by damoon** [comment]
I was thinking about adding a automatic git commit to persist the updated Chart.yaml.
What do you think?

**Comment by damoon** [comment]
also i am not perfectly sure how to test it...

**Comment by arschles** [comment]
>Great project. Thanks for all the work :D

@damoon thanks so much for saying that 💚 

>I was thinking about adding a automatic git commit to persist the updated Chart.yaml.

What do you think about commiting to a branch and opening a pull request for this?

>also i am not perfectly sure how to test it...

Neither am I. Maybe if you write this as a script, we could try simulating it without actually making a new release.

**Comment by arschles** [comment]
@damoon are you still interested in this one? Absolutely no pressure either way, I just wanted to check in so I don't step on your toes. 😄

**Comment by DrPsychick** [comment]
@arschles can be closed with https://github.com/gomods/athens-charts, as it can use dependabot/renovate to check for new docker image releases of athens and create PRs automatically
