### ISSUE TITLE
Git Large File Storage (LFS) support

### ISSUE THREAD

**Issue by bahlo** [gomods/athens#1448]
**Is your feature request related to a problem? Please describe.**
Yes, Athens generates an invalid checksum for go packages that have files stored in [git-lfs](https://git-lfs.github.com) (as it's not downloading them and instead hashing the text file).

**Describe the solution you'd like**
Would be great if we could install `git-lfs` in the docker container.

**Describe alternatives you've considered**
Well we could stop using git-lfs in go packages. Not really a good alternative though.

**Additional context**
This happened in a private repository that is cloned by Athens directly.

**Comment by arschles** [comment]
@bahlo if git-lfs is not installed in the container, does `go mod download` (and I assume, the underlying `git clone`) just ignore the files?

**Comment by bahlo** [comment]
@arschles no, it‘s using the [git-lfs pointers](https://github.com/git-lfs/git-lfs/blob/master/docs/spec.md).

**Comment by arschles** [comment]
@bahlo got it! Would you be up for submitting a PR that adds `git-lfs` in the Dockerfile? That way, when the PR is merged, there will be a new image published to https://hub.docker.com/r/gomods/athens-dev immediately, and it will be published to the next tagged version of [`gomods/athens`](https://hub.docker.com/r/gomods/athens)

**Comment by arschles** [comment]
Oh, and it'll be published to the `canary` tag in `gomods/athens`

**Comment by bahlo** [comment]
Happy to, PR is up 👍

**Comment by arschles** [comment]
Thanks @bahlo, this is all merged 👍
