### ISSUE TITLE
Catalog request fails  for minio client with Dell EMC ECS S3 as storage

### ISSUE THREAD

**Issue by jabbrwcky** [gomods/athens#1453]
**Describe the bug**
We are currently deploying athens with a Dell ECS system as S3 storage using the minio client.

Catalog requests fail with an array index out of bounds exception because ECS returns the key as URL-Encoded value:

```
&minio.ObjectInfo{ETag:"\"d5fa08a78739671cc99b8c9aa6dbeae4\"", Key:"cloud.google.com%2Fgo%2Fv0.26.0%2Fv0.26.0.info", LastModified:time.Time{wall:0xf053700, ext:63704404906, loc:(*time.Location)(nil)}, Size:51, ContentType:"", Expires:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, Metadata:http.Header(nil), Owner:struct { DisplayName string "json:\"name\""; ID string "json:\"id\"" }{DisplayName:"", ID:""}, StorageClass:"STANDARD", Err:error(nil)}
```

A test with mino shows that the key is returned decoded already here:

```
&minio.ObjectInfo{ETag:"\"3614268b5afb93e21ed8f08ae273ca9f-1\"", Key:"github.com/minio/hdfs/v3/v3.0.0/v3.0.0.info", LastModified:time.Time{wall:0x2eca2640, ext:63708811839, loc:(*time.Location)(nil)}, Size:50, ContentType:"", Expires:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, Metadata:http.Header(nil), Owner:struct { DisplayName string "json:\"name\""; ID string "json:\"id\"" }{DisplayName:"", ID:""}, StorageClass:"STANDARD", Err:error(nil)}
```

**Error Message**

```console
2019-11-08 12:48:29.614332 I | http: panic serving [::1]:53575: runtime error: index out of range [-1]
goroutine 130 [running]:
net/http.(*conn).serve.func1(0xc000678000)
        /usr/local/Cellar/go/1.13.4/libexec/src/net/http/server.go:1767 +0x139
panic(0x2065380, 0xc000536ba0)
        /usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:679 +0x1b2
github.com/gomods/athens/pkg/storage/minio.parseMinioKey(0xc000825ad0, 0x213a048, 0x5, 0x2f19a01, 0xed5141434, 0x0, 0x25)
        /Users/jens.hausherr/src/athens/pkg/storage/minio/cataloger.go:73 +0x311
github.com/gomods/athens/pkg/storage/minio.fetchModsAndVersions(0xc000758000, 0x3e8, 0x400, 0x3e8, 0x0, 0x0, 0x0, 0x1, 0xc0004f9830)
        /Users/jens.hausherr/src/athens/pkg/storage/minio/cataloger.go:53 +0x1cb
github.com/gomods/athens/pkg/storage/minio.(*storageImpl).Catalog(0xc0006215e0, 0x249d660, 0xc00066c330, 0x0, 0x0, 0x3e8, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jens.hausherr/src/athens/pkg/storage/minio/cataloger.go:28 +0x2eb
github.com/gomods/athens/cmd/proxy/actions.catalogHandler.func1(0x2492d60, 0xc000664500, 0xc00011e700)
        /Users/jens.hausherr/src/athens/cmd/proxy/actions/catalog.go:41 +0x17f
...
```

**To Reproduce**
Run athens (tested 0.6.1/0.70) with Dell ECS as S3 storage and invoke `/catalog` once some modules are stored.

**Expected behavior**
I'd like to get the catalog even when key values are URL escaped paths.

**Environment (please complete the following information):**
 - OS: OSX 10.14
 - Go version : 1.13.4
 - Proxy version : 0.7.0/master
 - Storage (fs/mongodb/s3 etc.) : S3 @ Dell ECS

**Additional context**

The fix would be rather straightforward here: use `url.PathUnescape(key)` to unescape keys (optionally configurable to deal with misbehaving(?) servers).

As I did not find a reference defining the correct behaviour of the S3 API, I am not sure if this is the right place to fix it.

I'd be happy to contribute a patch, but I'd like some opinion first.

**Comment by jabbrwcky** [comment]
Did some further digging.

It is possible to use the AWS client with ECS but this requires some changes to aws configuration (Configuring endpoint, static credentials and enforce s3 path style).

I also fuound out the hard way that athens uses different incompatible keys the minio client and AWS:

* minio: github.com/minio/hdfs/v3/v3.0.0/v3.0.0.info
* AWS: github.com/minio/hdfs/@v/v3.0.0.info

Switching form the minio client to AWS causes `/catalog` to go into an infinite loop if more keys exist in the bucket, because the keys are rejected as invalid and isTruncated() of the AWS client returns true, but the proxy always repeats the initial offset (i.e. from begining)

**Comment by jabbrwcky** [comment]
So to resolve this I either see to add `PathDecoding` the key that is returned with the minio client or switch to AWS client with the extended configuration options including wiping the bucket because of differing key formats.

**Comment by arschles** [comment]
@jabbrwcky I think #1457 would be a better solution for this, just because it has fewer code changes. Are you ok with us merging just that one, and closing out #1456?

**Comment by jabbrwcky** [comment]
I'm fine with improving the minio client in #1457. I had some issues with minio complainig about continuation keys - it would not accept unescaped paths nor escaped ones as continuation token.

If you don't mind I would also extract the key extraction code to avoid having to update in two places (cataloger/lister)

**Comment by arschles** [comment]
@jabbrwcky sounds good. I am about to merge #1457, it looks great :)
