### ISSUE TITLE
[Meta] Implement drivers for the pointer registry

### ISSUE THREAD

**Issue by arschles** [gomods/athens#146]
https://github.com/gomods/athens/pull/144 added a "pointer registry" interface for use with the proxy (confusingly called "Athens" at the moment). Athens uses the pointers to store the last event log entry that it has fetched from Olympus, and of course it needs to persist them somewhere.

Right now there is only an interface, and we need implementations:

- ~~RDBMS's (the ones that pop supports)~~
- Mongo (done)
- File (done)
- Memory (for dev purposes)
    - need issue for this

This issue is "meta", meaning nobody needs to submit one PR that implements all the drivers.

**Comment by robjloranger** [comment]
Looking at the current interface, there is only a look up method. Should there be a set or update method as well?

**Comment by robjloranger** [comment]
I'm going to start work on the in memory implementation.

**Comment by robjloranger** [comment]
Mongo is complete

**Comment by arschles** [comment]
@robjloranger you are rad 🙌 

checked off mongo in the OP

**Comment by robjloranger** [comment]
I am starting on the FS driver.

**Comment by lcd1232** [comment]
I am starting RDBMS driver

**Comment by arschles** [comment]
👍

**Comment by michalpristas** [comment]
just pushed FS by @robjloranger

**Comment by lcd1232** [comment]
@robjloranger 1-2 days

**Comment by robjloranger** [comment]
Awesome, no rush @lcd1232. just wanted to touch base and see if you were still working on it.

**Comment by sadlil** [comment]
@lcd1232 Is the RDBMS driver still open? Or I can try to create one? if yes, @robjloranger @arschles any concern using gorm to implement a generic driver? So caller needs to import the DB specific driver and pass as configurations? Or implementations needs to be specifics? 

@arschles any other driver in mind? may be redis or else?

**Comment by michalpristas** [comment]
@sadlil  or we let RDBMS go. and wont support that - perf

**Comment by lcd1232** [comment]
@sadlil yes you can do it

**Comment by arschles** [comment]
This is highly related to the registry but as of #772, we're not going to try and build a registry for the time being, so I'm closing this issue
