### ISSUE TITLE
[0.7,minio] panic when retrieving certain packages

### ISSUE THREAD

**Issue by utrack** [gomods/athens#1464]
**Describe the bug**
An out-of-range panic that kills the proxy (v0.7) when go-getting `github.com/mailru/easyjson` via Athens using minio storage.

**Error Message**

stacktrace:
<pre>
2019-11-15 13:50:45.722658 I | Starting application at port :3000
panic: runtime error: index out of range [-1]

goroutine 1059 [running]:
github.com/gomods/athens/pkg/storage/minio.(*storageImpl).List(0xc00000c4a0, 0x18950a0, 0xc0005fe720, 0xc0000e0360, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/gomods/athens/pkg/storage/minio/lister.go:31 +0x97c
github.com/gomods/athens/pkg/download.(*protocol).List.func1(0xc0004b01a0, 0xc000270980, 0x18950a0, 0xc0005fe720, 0xc0000e0360, 0x11, 0xc0005d8160, 0xc000139450)
        /go/src/github.com/gomods/athens/pkg/download/protocol.go:84 +0xb7
created by github.com/gomods/athens/pkg/download.(*protocol).List
        /go/src/github.com/gomods/athens/pkg/download/protocol.go:82 +0x201
</pre>

**To Reproduce**
```
mkdir -p kill-athens && cd kill-athens
go mod init q.w/e
GOPROXY=<addr>  go get github.com/mailru/easyjson
```

output:
```
» GOPROXY=http://athens.infra.<redacted> go get github.com/mailru/easyjson                                                                                                                                           2019-11-15 17:17:57
go get github.com/mailru/easyjson: module github.com/mailru/easyjson: reading http://athens.infra.<redacted>/github.com/mailru/easyjson/@v/list: 502 Bad Gateway

λ ~/tmp/t
» GOPROXY=http://athens.infra.<redacted> go get github.com/mailru/easyjson                                                                                                                                           2019-11-15 17:18:11
go get github.com/mailru/easyjson: module github.com/mailru/easyjson: reading http://athens.infra.<redacted>/github.com/mailru/easyjson/@v/list: 503 Service Temporarily Unavailable
```

**Expected behavior**
Package should be downloaded

**Environment (please complete the following information):**
 - OS: Arch Linux rolling 64bit
 - Go version : go1.13.4
 - Proxy version : 0.7.0
 - Storage (fs/mongodb/s3 etc.) : minio

**Comment by codestation** [comment]
Same here,

 - OS: Ubuntu 18.04 64bit (host), Docker 19.03.4
 - Proxy version : gomods/athens:v0.7.0 or gomods/athens:canary 
 - Storage (fs/mongodb/s3 etc.) : Linode Object Storage (using ATHENS_STORAGE_TYPE=minio)

```
panic: runtime error: index out of range [-1]

goroutine 481 [running]:
github.com/gomods/athens/pkg/storage/minio.(*storageImpl).List(0xc00000d520, 0x18950a0, 0xc0005fbcb0, 0xc000633340, 0x1d, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/gomods/athens/pkg/storage/minio/lister.go:31 +0x97c
github.com/gomods/athens/pkg/download.(*protocol).List.func1(0xc00068d010, 0xc0003f6500, 0x18950a0, 0xc0005fbcb0, 0xc000633340, 0x1d, 0xc0006214a0, 0xc000663210)
	/go/src/github.com/gomods/athens/pkg/download/protocol.go:84 +0xb7
created by github.com/gomods/athens/pkg/download.(*protocol).List
	/go/src/github.com/gomods/athens/pkg/download/protocol.go:82 +0x201
```

```
go get github.com/gobuffalo/packr/v2/...: module github.com/gobuffalo/packr/v2:
reading http://goproxy.<redacted>/github.com/gobuffalo/packr/v2/@v/list: 502 Bad Gateway
```
