### ISSUE TITLE
[Meta] Implement CDN Metadata Drivers

### ISSUE THREAD

**Issue by arschles** [gomods/athens#147]
There are two pieces of CDN storage:

- Functionality that uploads stuff to the CDN itself ("storage drivers")
- Functionality that saves and fetches metadata about the CDN ("metadata drivers")

Storage drivers and metadata drivers can be mixed and matched. For example, you can use Azure CDN storage drivers with MySQL metadata drivers, Google Cloud Storage with Mongo, and so on...

The issue for adding more storage drivers is https://github.com/gomods/athens/issues/83. This issue is about adding more metadata drivers for CDNs. Including but not limited to:

- Mongo (done)
- The RDBMS's that pop supports (done)
- File (done)
- Memory (#334)

This issue is marked "meta" so one PR doesn't need to implement all of these

**Comment by marpio** [comment]
I will start with the rdbms if no one else is woking on it.

**Comment by marwan-at-work** [comment]
@arschles @marpio I think this issue is no longer relevant because we won't be storing Metadata HTML anymore right?

**Comment by michalpristas** [comment]
yep this is a CDN which is getting removed
