### ISSUE TITLE
sumdb problem: different behavior with athens:0.7 and proxy.golang.org downloading module

### ISSUE THREAD

**Issue by pjediny** [gomods/athens#1470]
Here is what I did,

clean local cache
tried to get the fabric module via athens proxy (fail)
tried to get the fabric module via https://proxy.golang.org (ok)
tried to get the fabric module via athens proxy (ok, it's already stored locally)
```
+ go mod init test
go mod init: go.mod already exists
+ go clean -modcache
+ GOPROXY=http://localhost:3333
+ go get github.com/hyperledger/fabric@v1.4.4
go: github.com/hyperledger/fabric@v1.4.4: reading http://localhost:3333/github.com/hyperledger/fabric/@v/v1.4.4.mod: 500 Internal Server Error
+ GOPROXY=https://proxy.golang.org
+ go get github.com/hyperledger/fabric@v1.4.4
go: finding github.com/hyperledger/fabric v1.4.4
go: downloading github.com/hyperledger/fabric v1.4.4
go: extracting github.com/hyperledger/fabric v1.4.4
+ GOPROXY=http://localhost:3333
+ go get github.com/hyperledger/fabric@v1.4.4
```

the Athens proxy logs this error:
```
time="2019-11-22T16:29:02Z" level=error msg="exit status 1: go: finding github.com/hyperledger/fabric v1.4.4\nverifying github.com/hyperledger/fabric@v1.4.4: checksum mismatch\n\tdownloaded: h1:2m+tDXB5QWyZL1UTyYs3fxUhkgvKD88yVE6sIwYf1KM=\n\tsum.golang.org: h1:Joa6eO9HEGnzcuZF5RD+dZBPeYqxGF+ehYb7OSs3glY=\n\nSECURITY ERROR\nThis download does NOT match the one reported by the checksum server.\nThe bits may have been replaced on the origin server, or an attacker may\nhave intercepted the download attempt.\n\nFor more information, see 'go help module-auth'.\n" http-method=GET http-path=/github.com/hyperledger/fabric/@v/v1.4.4.info http-url=/github.com/hyperledger/fabric/@v/v1.4.4.info kind="Internal Server Error" module=github.com/hyperledger/fabric operation=download.InfoHandler ops="[download.InfoHandler pool.Info protocol.Info protocol.processDownload stash.Pool stasher.Stash stasher.fetchModule goGetFetcher.Fetch module.downloadModule]" version=v1.4.4
```

This looks like a checksum error, but I only get in in the athens proxy, but it works with golang proxy.

**Comment by arschles** [comment]
@pjediny my apologies for letting you hang for so long. What version of Athens were you using when you hit this problem? There was a change to the checksum calculations between two releases of Go

**Comment by pjediny** [comment]
@arschles 
Versions:
- athens version 0.7 
- go  v1.13.8

same thing happens inside of the container:
```~ # GOPROXY=http://localhost:3000 go get github.com/hyperledger/fabric@v1.4.4
go: finding github.com v1.4.4
go: finding github.com/hyperledger/fabric v1.4.4
go: finding github.com/hyperledger v1.4.4
go get github.com/hyperledger/fabric@v1.4.4: github.com/hyperledger/fabric@v1.4.4: reading http://localhost:3000/github.com/hyperledger/fabric/@v/v1.4.4.info: 500 Internal Server Error
```

With `GOPROXY=direct`
```
~ # GOPROXY=direct go get github.com/hyperledger/fabric@v1.4.4
go: finding github.com/hyperledger/fabric v1.4.4
go: downloading github.com/hyperledger/fabric v1.4.4
verifying github.com/hyperledger/fabric@v1.4.4: checksum mismatch
	downloaded: h1:2m+tDXB5QWyZL1UTyYs3fxUhkgvKD88yVE6sIwYf1KM=
	sum.golang.org: h1:Joa6eO9HEGnzcuZF5RD+dZBPeYqxGF+ehYb7OSs3glY=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```
When I'm not using the proxy env var it defaults to `GOPROXY="https://proxy.golang.org,direct"` and it downloads with no problem, same behaviour as outside of the container.

I suspect the fabric 1.4.4 used go 1.11.?, maybe there is some problem with the checksum compatibility between the go versions.

**Comment by pjediny** [comment]
I have looked deeper into this and the cached version at proxy.golang.org is different from the github version. It looks like fabric moved the tag to fix some issues with their release. So this is not an issue at the athens proxy side.

One thing could be improved at the athens side in this case: 500 internal service error is not really descriptive.

**Comment by arschles** [comment]
@pjediny thanks for doing that investigation!

Regarding this:

>One thing could be improved at the athens side in this case: 500 internal service error is not really descriptive.

Since some `go` commands don't produce output that is easily machine readable, we would need to do string machine on failure outputs. We had discussed doing string matching previously and decided against it, but I agree with you that just returning 500 error codes is not informative and doesn't help with debugging.

I would be willing to consider string matching in certain cases, though. I can't speak for others though 😄 . What error code do you think Athens should return on `SECURITY ERROR`?
