### ISSUE TITLE
Expand the e2e tests

### ISSUE THREAD

**Issue by fedepaol** [gomods/athens#1474]
**Is your feature request related to a problem? Please describe.**
Right now the e2e tests we have are provided the test_e2e.sh file. We want to extend them, ideally using a code driven approach replacing the bash script.

**Describe the solution you'd like**
Having the script replaced by a test suite that can run e2e tests.

**Describe alternatives you've considered**
None

**Additional context**
This was discussed in https://github.com/gomods/athens/pull/1449

**Comment by arschles** [comment]
I am marking this on hold because we marked #1449 on hold also: https://github.com/gomods/athens/pull/1449#issuecomment-560962016

**Comment by fedepaol** [comment]
Not sure why this is on hold, as it should be meant to replace our current e2e tests with something more elaborate.
#1449 on the other hand, is about replacing the interaction with the go executable with a mocked one.

**Comment by arschles** [comment]
sorry @fedepaol, I meant to remove the on hold label before I merged #1514. I agree with what you said in https://github.com/gomods/athens/issues/1474#issuecomment-569676633
