### ISSUE TITLE
dial tcp: lookup xxx: no such host on windows 10

### ISSUE THREAD

**Issue by meilihao** [gomods/athens#1475]
**Describe the bug**
pull packages gets errors by  athens in company-internal network.

**Error Message**
<pre>
```console
$ env GOPROXY=http://192.168.0.233:3000 go mod vendor -v # on windows 10
my.com/go-my/my imports
github.com/gin-gonic/gin: module github.com/gin-gonic/gin: Get https://mirrors.aliyun.com/goproxy/github.com/gin-gonic/gin/@v/list: dial tcp: lookup mirrors.aliyun.com: no such host
...
```
</pre>

**But on linux is OK.**

**To Reproduce**
1. deploy athens in internal network
1. fetch packages on windows 10

**Expected behavior**
no error.

**Environment:**
 - OS: linux x64
 - Proxy version : docker athens:canary/latest

config.toml:
```
FilterFile="FilterFile"
GlobalEndpoint = "https://mirror.aliyun.com/goproxy/"
```

FilterFile:
```
D
```

cmd:
```sh
# export ATHENS_STORAGE=/dockerdir/athens
# docker run -d -v $ATHENS_STORAGE:/var/lib/athens -v $ATHENS_STORAGE/gitconfig/.gitconfig:/root/.gitconfig -v $ATHENS_STORAGE/ssh-keys:/root/.ssh -e ATHENS_DISK_STORAGE_ROOT=/var/lib/athens -e ATHENS_FILTER_FILE=/var/lib/athens/FilterFile -e ATHENS_GLOBAL_ENDPOINT=https://mirrors.aliyun.com/goproxy/ -e ATHENS_STORAGE_TYPE=disk --name athens-proxy --restart always -p 3000:3000 192.168.0.233:8083/gomods/athens:canary
```

> ping mirrors.aliyun.com is ok in docker container.

**Comment by arschles** [comment]
@meilihao it looks like Athens is redirecting to https://mirror.aliyun.com/goproxy/ according to your `GlobalEndpoint`, and then your Go tool is requesting the module from https://mirrors.aliyun.com as expected, but your local windows 10 machine can't access that URL. Can you try accessing that URL directly from your Windows 10 machine and see if that works?

**Comment by meilihao** [comment]
windows 10 machine is no access to the Internet, so we use Athens to proxy.

**Comment by arschles** [comment]
@meilihao I see, thanks for letting me kow. The `GlobalEndpoint` configuration redirects the client to the URL you set on the Athens config. So, in your case, it's redirecting the Go tool on your windows machine to https://mirror.aliyun.com/goproxy/. Right now, Athens doesn't support proxying any other upstreams except for VCS systems. Would you be able to stick with a VCS system, or do you definitely need to use the proxy you set in `GlobalEndpoint`?

**Comment by meilihao** [comment]
We use [Gitfor Windows](https://gitforwindows.org/) on windows 10. 

Yes, we need GlobalEndpoint. Because only the machine where Athens is deployed in the internal network can connect to the external network and we cannot directly access the packages on google servers.

**Comment by arschles** [comment]
Cool. @meilihao this functionality has been asked for before, so I've restarted that discussion in https://github.com/gomods/athens/issues/1488. As I wrote in there, I think that it's time for us to do it. Can we please move the discussion there so we can decide exactly how we're going to implement this?

**Comment by meilihao** [comment]
ok, thinks.

**Comment by arschles** [comment]
@meilihao in https://github.com/gomods/athens/issues/1488#issuecomment-567797640, @marwan-at-work mentioned another solution that could work now. You could set `GoBinaryEnvVars` in the config.toml file (or an environment variable `ATHENS_GO_BINARY_ENV_VARS`) to be `GoBinaryEnvVars = ["GOPROXY=https://mirrors.aliyun.com"]`, and then Athens would correctly download from mirrors.aliyun.com
