### ISSUE TITLE
Checksum mismatch

### ISSUE THREAD

**Issue by daxmc99** [gomods/athens#1476]
**Describe the bug**
A 500 error is returned for this module

**Error Message**

```
time="2019-12-03T20:51:49Z" level=error msg="exit status 1: go: finding gomodules.xyz/jsonpatch/v2 v2.0.0\ngo: finding gomodules.xyz/jsonpatch/v2 v2.0.1\nverifying gomodules.xyz/jsonpatch/v2@v2.0.0: checksum mismatch\n\tdownloaded: h1:OyHbl+7IOECpPKfVK42oFr6N7+Y2dR+Jsb/IiDV3hOo=\n\tsum.golang.org: h1:lHNQverf0+Gm1TbSbVIDWVXOhZ2FpZopxRqpr2uIjs4=\n\nSECURITY ERROR\nThis download does NOT match the one reported by the checksum server.\nThe bits may have been replaced on the origin server, or an attacker may\nhave intercepted the download attempt.\n\nFor more information, see 'go help module-auth'.\n" http-method=GET http-path=/gomodules.xyz/jsonpatch/v2/@v/v2.0.0.mod http-url=/gomodules.xyz/jsonpatch/v2/@v/v2.0.0.mod kind="Internal Server Error" module= operation=download.VersionModuleHandler ops="[download.VersionModuleHandler pool.GoMod protocol.GoMod protocol.processDownload stash.Pool stasher.Stash stasher.fetchModule goGetFetcher.Fetch module.downloadModule]" version=
```

**To Reproduce**
Go build this repo https://github.com/rancher/rio at fea4ad3806aa76f54e949622de297ef775537083 with a clean mod cache

**Expected behavior**
The Google proxy does not have this error and works correctly

**Environment (please complete the following information):**
 - OS: Darwin
 - Go version : 1.13.4
 - Proxy version : latest release
 - Storage (fs/mongodb/s3 etc.) : local file system via volume mounts

**Additional context**
Can I pass an insecure arg in order to skip the checksum verification?

**Comment by arschles** [comment]
@daxmc99 to answer your question about the insecure arg:

You can use the `NoSumPatters` configuration param in Athens to skip checksum verification (see the bottom of https://docs.gomods.io/configuration/sumdb/). This will still require that you set up `GONOSUMDB` on your local machine if you want to skip the sum DB altogether

Regarding the actual problem, can you tell me what Athens version you are using, and what versions of Athens you've used in the past?

**Comment by arschles** [comment]
@daxmc99 hopefully you got your setup working. If you have more questions, just let us know!

**Comment by daxmc99** [comment]
I did! 

Thank you!  Currently running latest over here and haven't had any issues

**Comment by arschles** [comment]
That's great news. Thanks for letting me know 😄
