### ISSUE TITLE
Upstream 404 results in 500 response

### ISSUE THREAD

**Issue by jabbrwcky** [gomods/athens#1487]
**Describe the bug**
Info lookup fails on a package (upstream 404), resulting in a 500 error.

**Error Message**
<pre>
```console
138949-time="2019-11-14T13:56:45Z" level=error msg="exit status 1: go: finding github.com/prometheus/prometheus v2.14.0+incompatible\nverifying github.com/prometheus/prometheus@v2.14.0+incompatible/go.mod: github.com/prometheus/prometheus@v2.14.0+incompatible/go.mod: reading https://gocenter.io/sumdb/sum.golang.org/lookup/github.com/prometheus/prometheus@v2.14.0+incompatible: 404 Not Found\n" http-method=GET http-path=/github.com/prometheus/prometheus/@v/v2.14.0+incompatible.info http-url=/github.com/prometheus/prometheus/@v/v2.14.0+incompatible.info kind="Internal Server Error" module=github.com/prometheus/prometheus operation=download.InfoHandler ops="[download.InfoHandler pool.Info protocol.Info protocol.processDownload redis.Stash stash.Pool stasher.Stash stasher.fetchModule goGetFetcher.Fetch module.downloadModule]" version=v2.14.0+incompatible
138950:handler: GET /github.com/prometheus/prometheus/@v/v2.14.0+incompatible.info [500]
```
</pre>

**To Reproduce**

Configure gocenter.io as upstream and get the mod info for the package in the log file.

**Expected behavior**
The proxy should return upstream 404s as 404s as well.

**Environment (please complete the following information):**
 - OS: Linux 64bit
 - Go version : 1.13
 - Proxy version :0.7.0
 - Storage (fs/mongodb/s3 etc.) : s3

**Additional context**

I had a short look at the code and think that the proxy should not assume that the go command returns a JSON response in every case:
https://github.com/gomods/athens/blob/246113c5d4acb74a76bbaf9eadc17b5da07d5364/pkg/module/go_get_fetcher.go#L117-L128

**Comment by arschles** [comment]
@jabbrwcky in the case that the Go tool doesn't return JSON, it seems like the challenge would be how to determine what the error code is. We would need something like a function `is404(jsonErr)`. I don't know of a way to do that without parsing human-readable output. Perhaps we could just use `strings.HasSuffix(output, "404 Not Found")` (where `output` is the string representation of `stdout`)

That is pretty fragile, but could work. What do you think? 

cc/ @gomods/maintainers

**Comment by jabbrwcky** [comment]
In my opinion the go tool is at fault here also, because its `-json` flag only returns json on the happy path, not consistently.

I think parsing the output would be too fragile; there (likely) will be other error states that woul not be parseable.

Another option might be to consider any unusuable response as not found. 

500 implies that there is something wrong with the proxy itself, which is not the case - it just got a bad upstream response.

**Comment by marwan-at-work** [comment]
@jabbrwcky @arschles I fixed this issue in Go itself a couple of months ago, you can see the fix here: https://github.com/golang/go/commit/6232dadc63dda3e6f8ce227ed7e003da80f5ba2e

I'm not sure if this was ever patch-released, but it should either way be fixed in Go 1.14 :)

**Comment by marwan-at-work** [comment]
to reproduce, build Go from tip and run `GO111MODULE=on GOPROXY=https://gocenter.io go mod download -json github.com/prometheus/prometheus@v2.14.0+incompatible`

**Comment by jabbrwcky** [comment]
@marwan-at-work Looking forward to go 1.14 then :)

**Comment by arschles** [comment]
Didn't know that, thanks @marwan-at-work !
