### ISSUE TITLE
Add a configuration for Athens to proxy to upstream proxies

### ISSUE THREAD

**Issue by arschles** [gomods/athens#1488]
**Is your feature request related to a problem? Please describe.**

We have had [two](https://github.com/gomods/athens/issues/1475) [requests](https://github.com/gomods/athens/pull/1131) that I know of that would like Athens to proxy to an HTTP upstream of some kind. @meilihao explicitly says in #1475 that the only machine in their organization that can access the external network is their Athens install. ~#1311~ #1131 proposes a new HTTP-based API that could be modified to use the standard module download protocol.

In short, we have had requests (I'm pretty sure more than just these two) for Athens to proxy to upstream proxies, not just VCS's. I think it's high time that we implement it.

**Describe the solution you'd like**

Ideally, I'd like us to add a configuration that indicates that Athens should fetch modules from an upstream proxy, instead of the VCS. The easiest way I can think of is to add a new configuration option to the download file that indicates that the module should be fetched from a proxy instead of VCS. We could start with a configuration value under `sync` that gives a URL to override the default, which is to get the module from VCS:

```hcl
download "github.com/gomods/*" {
    mode = "sync"
    from_url = "https://proxy.golang.org"
}
```

We could implement it by setting `GOPROXY=<url>` when a module that fits the given pattern is requested.

**Describe alternatives you've considered**

I think it would be possible to use an HTTP backend like ~#1311~ #1131 that implements the module download protocol, but given our current architecture, I think it would be tougher to implement filtering, both in code and configuration.

**Additional context**

This came from https://github.com/gomods/athens/issues/1475

_Edit: I got the HTTP backend issue wrong. It should be #1131, not #1311_

**Comment by marwan-at-work** [comment]
I believe Athens should already be able to download a module from an upstream proxy through this config: https://github.com/gomods/athens/blob/master/config.dev.toml#L38

Is there a use case or motivation to have to change this per module@version?

**Comment by arschles** [comment]
@marwan-at-work I have a motivation and a use case.

The use case is to effectively set `GOPROXY=https://myproxy.com` for a specific package glob. Setting `GOPROXY=https://proxy.golang.org,https://myproxy.com,direct` would work, but it's relying on the Go tool to failover to the second proxy in the list, which is suboptimal.

The motivation is to enable the same behavior as `GoBinaryEnvVars = ["GOPROXY=https://myproxy.com"]` in the download file, where much of the other configuration of this kind lives. Based on https://github.com/gomods/athens/issues/1475, https://github.com/gomods/athens/issues/1434 and others, I think having it all in one place would be easier to document and discover.

Also, in #1493 I proposed that we deprecate the `GlobalEndpoint`. Although we can replace the recommendation to use `GoBinaryEnvVars`, just a hunch that providing a replacement for that config in the download file would be an easier transition.

**Comment by arschles** [comment]
Also related: #1551 because that's all about writing custom storage drivers

**Comment by arschles** [comment]
I'm going to close this because it would be better done in an external storage driver
