### ISSUE TITLE
Bump aws-sdk-go to latest version 

### ISSUE THREAD

**Issue by RaymondKYLiu** [gomods/athens#1537]
Hello, 

I have deployed Athens in EKS, we need to enable s3 storage, but failed to assume role via an OIDC web identity token file.
Because aws-sdk-go v1.15.24 https://github.com/gomods/athens/blob/ba40b8f76daff911ac293bbdd0eb4d3b3b6acc23/go.mod#L15 is not supported.

This [article](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html) shows the minimum version is  1.23.13

**Comment by arschles** [comment]
@RaymondKYLiu thanks for bringing this up. Would you be up for creating a new PR to bump the version? If not, that's totally ok. Just let us know 😄

**Comment by rbrtl** [comment]
This is fixed in latest - v1.11.0

```
github.com/aws/aws-sdk-go v1.32.7
```

[https://github.com/gomods/athens/blob/release-v0.11.0/go.modL15](https://github.com/gomods/athens/blob/release-v0.11.0/go.modL15)

**Comment by arschles** [comment]
yes, sorry I forgot to close this issue. hope this helps @RaymondKYLiu. closing
