### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by arschles** [gomods/athens#156]
At least add line numbers to logs in server code.

The way to do this would be to create a new `log.Logger` with [`log.New()`](https://godoc.org/log#New). This would all be done in an `init.go` file in each package.

... and then this issue would also entail replacing `log.Abc()` calls with `logger.Abc()`

Here is an example `init.go`:

```go
...
var logger log.Logger
func init() {
    logger := log.New(os.Stdout, "", log.Lshortfile)
}
```

**Comment by marwan-at-work** [comment]
Happy to pick this up and give it a shot. Feel free to assign it to me :)

**Comment by michalpristas** [comment]
Feel free to start, I cannot assign it to anyone except few collaborators yet

**Comment by robjloranger** [comment]
@marwan-at-work it's the usual fork > branch > PR process
