### ISSUE TITLE
Athens runs for a bit then seems to stall, when running `go mod tidy`.

### ISSUE THREAD

**Issue by nathanhack** [gomods/athens#1568]
**Describe the bug**
When running `go mod tidy` on a project looking to grab the latest, it seems to work for a while but then seems to stall for a long time.  The `go mod tidy` never completes instead I have to kill it.

**Error Message**
The only messages that I see that may be related is one about `latest` and `list`
<pre>
INFO[5:11PM]: exit status 1: go list -m: github.com/gorilla/mux@latest: git ls-remote -q origin in /tmp/athens135158136/pkg/mod/cache/vcs/ebce69d65fcbb10d46c06b9a96d0b75cbef4f6fe72077ff7900bc6194bb0d703: exit status 128:
	ssh_exchange_identification: read: Connection reset by peer
	fatal: Could not read from remote repository.
	
	Please make sure you have the correct access rights
	and the repository exists.
	http-method=GET http-path=/github.com/gorilla/mux/@v/list kind=Not Found module= operation=download.ListHandler ops=[download.ListHandler pool.List protocol.List vcsLister.List] version=
</pre>
<pre>
INFO[5:19PM]: incoming request	http-method=GET http-path=/github.com/go-ldap/ldap/v3/@v/list http-status=404
</pre>
<pre>
INFO[5:17PM]: incoming request	http-method=GET http-path=/github.com/gorilla/websocket/@v/list http-status=404
</pre>

**To Reproduce**
After following the walkthrough. Set `StorageType = "disk"`.

Next create a `main.go` file in a new folder with the following imports

```
import (
        "golang.org/x/crypto/chacha20"
        "gonum.org/v1/gonum"
        "gonum.org/v1/plot"
        "github.com/sirupsen/logrus"
        "github.com/spf13/cobra"
        "github.com/spf13/viper"
        "github.com/spf13/afero"
        "github.com/spf13/pflag"
        "github.com/spf13/jwalterweatherman"
        "github.com/keepeye/logrus-filename"
        "github.com/xhebox/bstruct"
        "github.com/xeipuuv/gojsonschema"
        "go.uber.org/ratelimit"
        "google.golang.org/grpc"
        "github.com/go-sourcemap/sourcemap"
        "github.com/robertkrimen/otto"
        "gopkg.in/yaml.v2"
        "gopkg.in/yaml.v1"
        "gopkg.in/check.v1"
        "github.com/ledongthuc/pdf"
        "github.com/ajstarks/svgo"
        "github.com/alcortesm/tgz"
        "github.com/gorilla/mux"
        "github.com/gorilla/handlers"
        "github.com/gorilla/websocket"
        "github.com/gorilla/rpc"
        "github.com/gorilla/schema"
        "github.com/gopherjs/vecty"
        "github.com/NYTimes/gziphandler"
        "github.com/go-chi/chi"
        "github.com/nathanhack/binary"
        "github.com/webrpc/webrpc"
        "github.com/go-ldap/ldap/v3"
        "github.com/jtblin/go-ldap-client"
        "github.com/go-resty/resty/v2"
        "github.com/globalsign/mgo"
        "github.com/hidal-go/hidalgo"
        "github.com/cespare/xxhash"
        "github.com/sbwhitecap/tqdm"
        "github.com/cheggaaa/pb/v3"
        "github.com/pa-m/sklearn"
        "github.com/go-gota/gota/dataframe"
        "github.com/vdobler/chart"
        "github.com/src-d/enry/v2"
        "github.com/toqueteos/trie"
        "gopkg.in/toqueteos/substring.v1"
)
```

Next generate the go.mod file using `mod init example.com`
Remove the directory `$(go env GOPATH)/pkg` (to force all new downloads).
Then finally run `go mod tidy`

**Expected behavior**
I would have expected the latest versions of each of the lib to be download (to disk) if not already in athens storage. 

However instead it seems to be grabbing things for a bit but then stops.

**Environment (please complete the following information):**
 - OS: Ubuntu 19.04
 - Go version : 1.13.8 & 1.14
 - Proxy version : hash e1374be
 - Storage (fs/mongodb/s3 etc.) : disk

**Additional context**
Once I kill the `go mod tidy` I can immediately rerun it again without restarting Athens. 
However, Athens seems to respond the same way (running for a bit, then stopping).

**Comment by arschles** [comment]
@nathanhack I can't reproduce this behavior using Athens v0.7.2. I'm running with Docker with this command:

```bash
$ docker run -p 3000:3000 gomods/athens:v0.7.2
```

In case it helps, here are my `go.mod` and `go.sum` files: https://gist.github.com/arschles/82ecca84b2c7753546914de3e444c866

**Comment by nathanhack** [comment]
@arschles sorry for the long delay, I really appreciated your fast response!  I pull the v0.8 and it doesn't seem to be occurring.  The new version should have a similar problem but if it's not happening it must have been something with my environment.  I'm going to close this for now.  If it occurs again I'll reopen.

As a side note, the issue didn't occur when had a populated (with versions) go.mod file. It was only an issue when the go.mod file was newly created (without the list of repos and versions).

**Comment by arschles** [comment]
Ah, ok. Thanks for letting me know, @nathanhack. If the `go.mod` file is not present, then this issue is likely related to the "mutable" endpoints. These are the `.../@/list` and the `.../@latest` endpoints. Does `v0.8.0` work without a `go.mod` file too?

**Comment by nathanhack** [comment]
@arschles The new version seems to work when Athens has access to the internet. (However, with the older version it would stop responding to `go mod tidy` when the `go.mod` file had an empty imports section. Maybe this is still a problem but it doesn't seem to be occurring at the moment.)

But for my actual use case the Athens repo doesn't have access to the real internet. So the only way around it is to know _a priori_ which versions are available in the athens repo, which is quite tedious. 

Currently to update the repos in athens, I have a separate athens repo that is connected to the real internet and a fake project that contains all the imports that is needed. With that fake project I occasionally remove the imports from the `go.mod` file and do a `go mod tidy` on a it. Then I manually copy all the updated files to the private network.

My hope is Athens will eventually support my use case and make my development life a lot better.
