### ISSUE TITLE
error downloading module

### ISSUE THREAD

**Issue by publicocean0** [gomods/athens#1599]
go run .
go: github.com/athens-artifacts/samplelib@v1.0.0: reading http://sr-vm318-kubert.comune.intranet:3000/github.com/athens-artifacts/samplelib/@v/v1.0.0.mod: 404 Not Found

i cant understand ufffff

**Comment by arschles** [comment]
@publicocean0 if you have access to the log output of the Athens server, can you please post it here?

**Comment by publicocean0** [comment]
i solved , sorry.

**Comment by arschles** [comment]
@publicocean0 no problem. I'm glad you solved it 😄
