### ISSUE TITLE
proxy: add background worker to fetch requested modules that aren't present locally

### ISSUE THREAD

**Issue by bketelsen** [gomods/athens#16]

**Comment by arschles** [comment]
excellent idea. for production-like deployments we'll want the worker queue to be backed by not-memory. we should write a grift that we can run separately that consumes the queue

**Comment by arschles** [comment]
I talked to someone yesterday that uses https://github.com/gocraft/work a _lot_. If the standard buffalo background worker isn't enough for us, this would be a good option. Putting here as a reminder for later if we need it.

**Comment by robjloranger** [comment]
could this be solved by #132 or #182

**Comment by michalpristas** [comment]
closing
