### ISSUE TITLE
kubernetes helm chart ingress annotations mis-typed

### ISSUE THREAD

**Issue by philpennock** [gomods/athens#1612]
**Describe the bug**

The helm chart's `values.yaml`  defines `ingress.annotations:` without the `{}` after it. This causes Helm to expect a list-array instead of a key-value array.  I couldn't find a way to make that work.

Editing `values.yaml` to use `{}` for the ingress annotations, like all the other types' annotations entries, let my ingress annotations work.

**Error Message**
If applicable add error message to help explain your problem or console output enclose in triple back-ticks eg,

```
coalesce.go:199: warning: destination for annotations is a table. Ignoring non-table value <nil>
```

**To Reproduce**

Try the helm chart (current master branch, `90af973c3d`) with some ingress annotations.

**Expected behavior**
Able to provide annotations to Helm which propagate into the Ingress object.

**Environment (please complete the following information):**
Helm `v3.1.2`, Kubernetes server version `v1.17.4+k3s1`

**Additional context**
It's a one-line fix, adding two characters, not opening a PR for that.  :laughing:

**Comment by DrPsychick** [comment]
closed with new helm chart: https://github.com/gomods/athens-charts
