### ISSUE TITLE
Implement CDN file system storage

### ISSUE THREAD

**Issue by robjloranger** [gomods/athens#162]
Will be capable of in memory as well by use of `afero.Fs`'s

**Comment by robjloranger** [comment]
I will start on this tomorrow, will round out #147

**Comment by marpio** [comment]
Ups... sorry @robjloranger I've just submited a PR for this and saw this issue after that...

**Comment by robjloranger** [comment]
No problem 😁 one less to do

**Comment by marpio** [comment]
Solved by #164

**Comment by robjloranger** [comment]
#164 closes this
