### ISSUE TITLE
Please change `main` branch back into `master`! It's really terrible!

### ISSUE THREAD

**Issue by planear** [gomods/athens#1631]
# master!
# master!
# master!
# master!
# master!

**Comment by Kunde21** [comment]
We encourage all contributors to read the Code of Conduct before submitting issues.  

To clarify - 
Examples of behavior that contributes to creating a positive environment include:
- Using welcoming and inclusive language
- Being respectful of differing viewpoints and experiences
- Gracefully accepting constructive criticism
- Focusing on what is best for the community
- Showing empathy towards other community members
