### ISSUE TITLE
Adding an ExistingClaim to Chart

### ISSUE THREAD

**Issue by Locus99** [gomods/athens#1692]
Currently, the athens-proxy helm chart can create a pvc.  I have seen using the value of "existingClaim" on other charts to supply a pvc value rather than create one and suggest updating the deployment to use this value when available (and not create the pvc).  The pvc can still be created if this option is not available.

Is there a philosophical reason why this wasn't done before?

**Comment by arschles** [comment]
@Locus99 no, we don't have a philosophical reason for not doing that. I don't think any of us thought of it at all, to be honest. Is it something you need?

**Comment by Locus99** [comment]
I have a situation where I have an offline system and if I needed to redeploy this chart  the existing go modules in the repo would be lost (or at least would need to be moved from the archived storage back to the new PVC).  I am working on an update to the chart locally to see how it would work.  Wanted to know if this would be something accepted if I made it publicly available.

**Comment by arschles** [comment]
@Locus99 we would accept it, if it was opt-in

**Comment by DrPsychick** [comment]
@Locus99 if you have any changes you can contribute to the chart, I'm happy to review if you open a PR on https://github.com/SickHub/athens-proxy

**Comment by DrPsychick** [comment]
Update: the new helm chart has now an official home : https://github.com/gomods/athens-charts

@Locus99 please reopen a PR there if you still need it.

**Comment by DrPsychick** [comment]
closing as "gone cold", please reopen an issue in the new repo, if you still need it.
