### ISSUE TITLE
Docker: change /config/config.toml permissions so Athens can be ran as non-root user

### ISSUE THREAD

**Issue by tzvetkoff** [gomods/athens#1695]
**Problem**

Currently the `/config/config.toml` has permissions set to `0700`.
This makes it impossible to run Athens with a non-root user, and this is in turn needed so you can mount the filesystem storage directory with your UID/GID.

**Possible solution**
Changing the permissions to something sane, like `0644` (or `0755` and add a `#!/bin/athens-proxy` hashbang.)

**Alternative**
Building a wrapper image is indeed an option, yet it's not as simple as `docker run gomods/athens:latest -u $UID:$GID -v $PWD/data:/data -e...`

**Additional context**
I couldn't find the Dockerfile used to build https://hub.docker.com/r/gomods/athens, otherwise I would've sent a PR (even though it's a 1-line change.)

**Comment by endocrimes** [comment]
@tzvetkoff looks like this is the dockerfile they use for pushing those images https://github.com/gomods/athens/blob/main/cmd/proxy/Dockerfile

**Comment by arschles** [comment]
Thanks for the pointer @endocrimes 😊

@tzvetkoff feel free to send a pull request - we'd really appreciate that!
