### ISSUE TITLE
Error downloading github.com/google/flatbuffers v1.12.0

### ISSUE THREAD

**Issue by ceejatec** [gomods/athens#1696]
**Describe the bug**
When using Athens as a proxy, "go get github.com/google/flatbuffers@v1.12.0" fails with a 404 error.

**Error Message**
The following appears in the Athens logs:

<pre>
DEBUG[8:11AM]: saving github.com/google/flatbuffers@v1.12.0 to storage...	http-method=GET http-path=/github.com/google/flatbuffers/@v/v1.12.0.info request-id=c2ab8d62-401a-486c-b2d2-5c0e01734768 
INFO[8:11AM]: github.com/google/flatbuffers@v1.12.0: verifying module: checksum mismatch
	downloaded: h1:N8EguYFm2wwdpoNcpchQY0tPs85vOJkboFb2dPxmixo=
	sum.golang.org: h1:/PtAHvnBY4Kqnx/xCQ3OIV9uYcSFGScBsWI3Oogeh6w=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
	http-method=GET http-path=/github.com/google/flatbuffers/@v/v1.12.0.info kind=Not Found module=github.com/google/flatbuffers operation=download.InfoHandler ops=[download.InfoHandler pool.Info protocol.Info protocol.processDownload stash.Pool stasher.Stash stasher.fetchModule goGetFetcher.Fetch module.downloadModule] request-id=c2ab8d62-401a-486c-b2d2-5c0e01734768 version=v1.12.0 
INFO[8:11AM]: incoming request	http-method=GET http-path=/github.com/google/flatbuffers/@v/v1.12.0.info http-status=404 request-id=c2ab8d62-401a-486c-b2d2-5c0e01734768 
</pre>

**To Reproduce**

    docker run -d -p 3000:3000 gomods/athens:canary   # also occurs with :v0.10.0
    export GOPROXY=http://localhost:3000/
    mkdir /tmp/foo && cd /tmp/foo
    go mod init example.com/module
    go get github.com/google/flatbuffers@v1.12.0

**Expected behavior**
If you do the same steps as above except leave GOPROXY unset, then "go get" succeeds. The resulting go.sum contains:

<pre>
github.com/google/flatbuffers v1.12.0 h1:/PtAHvnBY4Kqnx/xCQ3OIV9uYcSFGScBsWI3Oogeh6w=
github.com/google/flatbuffers v1.12.0/go.mod h1:1AeVuKshWv4vARoZatz6mlQ0JxURH0Kv5+zNeJKJCa8=
</pre>

**Environment (please complete the following information):**
 - OS: Ubuntu 20
 - Go version : 1.14.4 (occurs with any version as the problem is inside the go container)
 - Proxy version : v0.10.0 or "canary"
 - Storage (fs/mongodb/s3 etc.) : default for Docker container (local filesystem?)

**Additional context**
I've seen this error message reported in other places such as [here](https://github.com/google/flatbuffers/issues/6466) and [here](https://github.com/google/flatbuffers/issues/5153). Those reports don't say they're using Athens, and indeed I do not know for certain that this is an Athens bug. But it does seem strange that this result happens consistently with Athens where it does not happen when going direct to Google's proxies and sumdb. I had initially thought that this was a case of somebody doing something "naughty" upstream (changing a tag, for instance) which resulted in Athens having stale cached data; however I now find that it happens even with a completely fresh Athens instance with no prior cache, which should be reading from the same upstream sources as the direct connections.

It only seems to happen with this exact version of this exact package. We've been running Athens for our production builds for quite some time, and the only other time we saw this kind of error was in fact a case where the upstream provider changed the tag. But in that case, the error happened even without Athens in the picture.

**Comment by ceejatec** [comment]
As a note, we're working around this by specifying the following in our go.mod files:

    github.com/google/flatbuffers v0.0.0-20200312223339-6df40a247173

which points to the same SHA as the tag "v1.12.0" does. This downloads fine via Athens.

**Comment by vatine** [comment]
I think I am seeing the same issue with a few other module/version tuples (inexplicable module download errors through Athens that seem to be working fine when going straight out).

**Comment by jgiannuzzi** [comment]
This issue can be reproduced outside of Athens by bypassing the Google Go proxy whilst still using their Sum DB:

```
$ GOPROXY=direct go mod download github.com/google/flatbuffers@v1.12.0
go mod download: github.com/google/flatbuffers@v1.12.0: verifying module: checksum mismatch
	downloaded: h1:N8EguYFm2wwdpoNcpchQY0tPs85vOJkboFb2dPxmixo=
	sum.golang.org: h1:/PtAHvnBY4Kqnx/xCQ3OIV9uYcSFGScBsWI3Oogeh6w=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

When comparing the version downloaded from the Google Go proxy to the current v1.12.0 tag, you can see that there are a bunch of (irrelevant to Go) version differences in Swift, Java, Kotlin, etc. files (1.11.1 instead of 1.12.0). So this seems to me like an actual case of someone changing the tag upstream, but only _after_ the module and its sum got cached by Google.

**Comment by vatine** [comment]
I could get this to work as I would have expected with the following configuration:

```
GoBinaryEnvVars = ["GOPROXY=proxy.golang.org,direct"]
```

That is, explicitly putting GOPROXY back to its default value.

**Comment by arschles** [comment]
Google likely stored this version at the same time as they calculated the checksum, so their version will pass validation but if you run Athens to download directly from VCS (it does this by [default](https://github.com/gomods/athens/blob/6991d6347b8247dc4f2323a2ac754e5c3ffd50ab/config.dev.toml#L54)) then it will download the version that doesn't match the checksum.

As @vatine said, changing `GoBinaryEnvVars` works because Athens will download everything from the Google proxy. If you don't want Athens to download everything from there, you can use the [download mode](https://docs.gomods.io/configuration/download/) file to set it to download just this module from the Google proxy.
