### ISSUE TITLE
Newest Helm chart versions are not published

### ISSUE THREAD

**Issue by gw0** [gomods/athens#1704]
**Describe the bug**
Latest two version of the Helm chart (`0.5.0` and `0.4.16`) are not published on the `gomods` chart repository.

**Error Message**

```bash
$ helm repo add gomods https://athens.blob.core.windows.net/charts
"gomods" has been added to your repositories
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "gomods" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
$ helm search repo athens
NAME               	CHART VERSION	APP VERSION	DESCRIPTION                    
gomods/athens-proxy	0.4.15       	0.9.0      	The proxy server for Go modules

$ helm install --debug athens gomods/athens-proxy --version 0.5.0
install.go:158: [debug] Original chart version: "0.5.0"
Error: chart "athens-proxy" matching 0.5.0 not found in gomods index. (try 'helm repo update'): no chart version found for athens-proxy-0.5.0
helm.go:75: [debug] no chart version found for athens-proxy-0.5.0
```

**To Reproduce**

```bash
$ helm repo add gomods https://athens.blob.core.windows.net/charts
$ helm repo update
$ helm install --debug athens gomods/athens-proxy --version 0.5.0
```

**Expected behavior**
A CI pipeline should build and publish new chart versions.

**Environment (please complete the following information):**
 - OS: Linux 64bit
 - Helm: 3.1.3

**Comment by chriscoffee** [comment]
Thanks for the ticket @gw0. I'll pick this one up and have peek why the push failed in the last release:https://cloud.drone.io/gomods/athens/2179/1/12) Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden)

**Comment by arschles** [comment]
@gw0 @chriscoffee - just merged https://github.com/gomods/drone-helm/pull/4 and restarted the drone job. 🤞

**Comment by arschles** [comment]
@gw0 @chriscoffee update - the latest build worked! https://cloud.drone.io/gomods/athens/2181/1/2 

thanks both of you :)
