### ISSUE TITLE
Cannot upload traces when using an Jaeger sidecar

### ISSUE THREAD

**Issue by c47gao** [gomods/athens#1722]
**Describe the bug**
I used an Jaeger agent sidecar to collect traces. But it fails for some reason

**Error Message**
The jaeger agent sidecar itself is working properly and it's been used in other apps. 
```
2021-06-29 20:40:04.014046 I | Endpoint has been deprecated. Please use CollectorEndpoint instead.
2021-06-29 20:40:04.020685 I | Starting application at port :3000
INFO[8:40PM]: incoming request	http-method=GET http-path=/readyz http-status=200 request-id=3b619ae1-0c2c-4c6a-8522-84366916ec0b 
2021-06-29 20:58:26.347798 I | Error when uploading spans to Jaeger: failed to upload traces; HTTP status code: 400
```

**To Reproduce**
Athens 0.11.0.

```
TraceExporter = "jaeger"

TraceExporterURL = "http://localhost:5778"
```
Jaeger agent sidecar uses the default setup:
```
{
                        "containerPort": 5775,
                        "protocol": "UDP"
},
{
                        "containerPort": 6831,
                        "protocol": "UDP"
},
{
                        "containerPort": 6832,
                        "protocol": "UDP"
 },
{
                        "containerPort": 5778,
                        "protocol": "TCP"
}
```

**Expected behavior**
Athens should be able to upload traces properly

**Environment (please complete the following information):**
 - OS: [e.g. Linux 64bit]
 - Go version : 1.16
 - Proxy version : 0.11.0
 - Storage (fs/mongodb/s3 etc.) : s3

**Additional context**

**Comment by arschles** [comment]
@c47gao are traces making it from Athens to the sidecar properly?

**Comment by DrPsychick** [comment]
I think this issue can be closed (gone cold).

If someone stumbles over this, below a working athens-proxy chart test setup with Jaeger. Not sure if it matters, but it uses port 14268

```
      ATHENS_TRACE_EXPORTER_URL:  http://athens-proxy-l5suia9ctw-jaeger:14268
      ATHENS_TRACE_EXPORTER:      jaeger
```
https://github.com/gomods/athens-charts/actions/runs/11454627570/job/31869119312
