### ISSUE TITLE
Thread contexts down the stack

### ISSUE THREAD

**Issue by arschles** [gomods/athens#174]
Ref: https://github.com/gomods/athens/pull/170#discussion_r195553351

This also greatly helps us with tracing. cc/ @bketelsen 

Here's an example on how to add a tracing span to a function:

```go
func foo(ctx context.Context) {
    sp, ctx := buffet.ChildSpan("storage.save",context)
    defer sp.Close()
    // do stuff with ctx
```

**Comment by arschles** [comment]
Definitely don't have to do this all in one PR. That would be a big refactor!

**Comment by robjloranger** [comment]
I'm thinking if we start with just threading the context, not adding tracing as well, it should be pretty easy. Start in each app and only change one interface per PR.

**Comment by bketelsen** [comment]
that's a nice logical way to do this 👍

**Comment by manugupt1** [comment]
https://github.com/gomods/athens/pull/346

The above PR fixes it!

**Comment by manugupt1** [comment]
Ref: https://github.com/gomods/athens/issues/392

**Comment by arschles** [comment]
@manugupt1 since #346 is done, do you think we can close this issue?
