### ISSUE TITLE
Log Escaped URL Paths based on CodeQL results

### ISSUE THREAD

**Issue by manugupt1** [gomods/athens#1749]
**Describe the bug**
CodeQL show that we are logging paths directly. We should instead escape and then log them.

**To Reproduce**
Results are shown here: https://github.com/gomods/athens/pull/1748/checks?check_run_id=4567576462

**Expected behavior**

We can simply log escaped paths provided by net/url: https://pkg.go.dev/net/url#URL.EscapedPath

**Additional context**

**Comment by enkeyz** [comment]
Would like to work on this. One question: what do you mean by "We should instead escape"?

**Comment by manugupt1** [comment]
Hello @enkeyz 

That should be awesome. I think this should be enough. 

One of the reviewers should be able to review and see if any other changes are required.

Also, have a great 2022.

**Comment by manugupt1** [comment]
I will close this as CodeQL is not red anymore.
