### ISSUE TITLE
Helm chart repository https://athens.blob.core.windows.net/charts not usable - returns 403 for all requests

### ISSUE THREAD

**Issue by pmalmsten** [gomods/athens#1795]
**Describe the bug**
The Helm chart repository `https://athens.blob.core.windows.net/charts` cannot be used, because it returns 403 for all requests.

**Error Message**

```console
PS C:\Users\paulmalmsten> helm repo add gomods https://athens.blob.core.windows.net/charts
Error: looks like "https://athens.blob.core.windows.net/charts" is not a valid chart repository or cannot be reached: failed to fetch https://athens.blob.core.windows.net/charts/index.yaml : 403 This request is not authorized to perform this operation.
```

**To Reproduce**
Execute `helm repo add gomods https://athens.blob.core.windows.net/charts`

**Expected behavior**
The repository is registered successfully with the helm CLI, and I am able to deploy the chart to a Kubernetes cluster.

**Environment (please complete the following information):**
 - OS: Windows 11, Ubuntu 20.04.5
 - Go version : None
 - Proxy version : None
 - Storage (fs/mongodb/s3 etc.) : None

**Additional context**

**Comment by arschles** [comment]
I had to remove public access to the azure blob store that backs the helm repository. I'll work on figuring out a solution, sorry

**Comment by damoon** [comment]
any progress on this?
i am blocked to install athens currently...

**Comment by DrPsychick** [comment]
@arschles Why not host it on GitHub meanwhile? Does not have to be permanent solution, but currently - for more than 2 weeks - one cannot pull the helm chart as far as I understand. I can offer support to do that, if that helps 🤷‍♂️

**Comment by draeron** [comment]
is there any way this can be worked around? This prevent us from updating our deployment.

**Comment by sabuhish** [comment]
we are still facing this issue, we cant update athens.

**Comment by arschles** [comment]
>I can offer support to do that, if that helps 🤷‍♂️

@DrPsychick hosting on GH is a fine solution, so yes please!

it looks like I'm not going to be able to find a clean, suitable solution anytime soon...

**Comment by DrPsychick** [comment]
Alright, @arschles , I'll try to find some time this weekend and will setup a repo for it. I'll join the gophers slack to chat about details.

**Comment by DrPsychick** [comment]
Please give this a try, dear community. And for those "listening" and having open PRs/contributions to the chart: please do take the time to resubmit the changes to this repo, I will do my best to review and approve them in a timely manner (in my spare time).
I would also be happy to see some contributions to test different chart setups/use-cases with the CircleCI pipeline.

https://github.com/SickHub/athens-proxy
