### ISSUE TITLE
Docker image contains stale Go version

### ISSUE THREAD

**Issue by awagner-iq** [gomods/athens#1797]
The [latest docker image](https://hub.docker.com/layers/gomods/athens/v0.11.0/images/sha256-efb811df7844779d4ca46d2fd1aaf830082e4229e8c947d983f5feedc53e8f1f?context=explore) uses Go 1.14.15:

```
$ docker run -it gomods/athens:latest go version
go version go1.14.15 linux/amd64
```

That version of Go is very old, currently we are on Go 1.19. There have been many changes, in particular for modules. I am having trouble setting up a module proxy at work. I believe a possible reason for that is that `.netrc` parsing has been made more robust since then.

The `canary` tag contains a newer Go version (though with Go 1.18.6 still not the newest).

It would be great if a new release could be cut. Also, long-term it might be beneficial to either version the image separately from the code, or at least do a bug-fix release every time a new Go version comes out - I would really like our athens installations to always use the latest stable Go version.

**Comment by awagner-iq** [comment]
Friendly ping?

**Comment by project0** [comment]
#1734 It seems there is currently no active maintainer :-(

**Comment by DrPsychick** [comment]
We've picked up work on bringing Athens back up to date and keep maintaining it. We'll create a RC tag soon with the changes accumulated over the last months.
