### ISSUE TITLE
Systemd setup has hard-coded ATHENS_DISK_STORAGE_ROOT 

### ISSUE THREAD

**Issue by Jeansen** [gomods/athens#1798]
`scripts/systemd.sh` has a hard-coded `ATHENS_DISK_STORAGE_ROOT=/var/run/athens`. That overwrites any setting in a config file (either default or provided with -config_file).

Before I create a PR, I wanted to make sure this is a bug and not intentional.

Otherwise I'd suggest do remedy this setting. The script forces a valid config file to be in place, anyway.

**Comment by DrPsychick** [comment]
@Jeansen I don't think this is intended. Please do create a PR if we can make Athens better with it :)
