### ISSUE TITLE
Helm Repository Not Reachable

### ISSUE THREAD

**Issue by smartinov** [gomods/athens#1803]
**Describe the bug**
The helm repository is not reachable

**Error Message**

Helm repository not reachable
<pre>
```console
│ Error: could not download chart: looks like "https://athens.blob.core.windows.net/charts" is not a valid chart repository or cannot be reached: failed to fetch https://athens.blob.core.windows.net/charts/index.yaml : 403 This request is not authorized to perform this operation.
```
</pre>

**To Reproduce**
➜  ~ helm repo add gomods https://athens.blob.core.windows.net/charts
Error: looks like "https://athens.blob.core.windows.net/charts" is not a valid chart repository or cannot be reached: failed to fetch https://athens.blob.core.windows.net/charts/index.yaml : 403 This request is not authorized to perform this operation.

**Expected behavior**
Getting the helm repository

**Environment (please complete the following information):**

**Additional context**

**Comment by benmoss** [comment]
Dup of https://github.com/gomods/athens/issues/1795

**Comment by DrPsychick** [comment]
In accordance with @arschles I setup a repo where download is possible again: https://sickhub.github.io/athens-proxy/
