### ISSUE TITLE
S3 List API use vsc

### ISSUE THREAD

**Issue by bp-jayce** [gomods/athens#1807]
**Describe the bug**
I use s3 to storage, and list api use vcsLister function

**Error Message**
```console
INFO[5:00AM]: exit status 1: go list -m: [my-proxy-url]/[package-path]@latest: unrecognized import path "[my-proxy-url]/[package-path]": https fetch: Get "[my-proxy-url]/[package-path]?go-get=1": dial tcp: lookup [my-proxy-url] on 10.100.0.10:53: no such host

	http-method=GET http-path=/[my-proxy-url]/[package-path]@v/list kind=Not Found module= operation=download.ListHandler ops=[download.ListHandler pool.List protocol.List vcsLister.List] request-id=44b4396f-5127-462d-9c2b-6a250bdb0c7f version=

INFO[5:00AM]: incoming request	http-method=GET http-path=/[my-proxy-url]/[package-path]@v/list http-status=404 request-id=44b4396f-5127-462d-9c2b-6a250bdb0c7f
```

**To Reproduce**
I use this config options

```yaml
  - name: ATHENS_GOGET_WORKERS
    value: '3'
  - name: ATHENS_GONOSUM_PATTERNS
    value: >-
      [my-proxy-url]/*,[my-proxy-url]/*/*,[my-proxy-url]/*/*/*,[my-proxy-url]/*/*/*/*
  - name: ATHENS_DOWNLOAD_MODE
    value: none
  - name: ATHENS_STORAGE_TYPE
    value: s3
  - name: AWS_REGION
    value: ap-northeast-2
  - name: ATHENS_S3_BUCKET_NAME
    value: go-mod-repo
  - name: AWS_USE_DEFAULT_CONFIGURATION
    value: 'true'
  - name: ATHENS_STORAGE_S3_AWS_FORCE_PATH_STYLE
    value: 'true'
```

**Expected behavior**
I thought [the storage lister](https://github.com/gomods/athens/blob/main/pkg/storage/s3/lister.go) should be used.

**Environment (please complete the following information):**
 - OS: [e.g. Linux 64bit] kubernetes and athens container
 - Go version :
 - Proxy version : docker.io/gomods/athens:v0.11.0
 - Storage (fs/mongodb/s3 etc.) : s3

**Additional context**

**Comment by bp-jayce** [comment]
any information?...

**Comment by project0** [comment]
> dial tcp: lookup [my-proxy-url] on 10.100.0.10:53: no such host

Looks like some DNS resolving issue in your case

**Comment by bp-jayce** [comment]
Ok... I thought that the athens used wrong protocol for searching list of packages. I'll research more. Thanks by the way.
