### ISSUE TITLE
Remove DRONE CI

### ISSUE THREAD

**Issue by manugupt1** [gomods/athens#1833]
**Describe the bug**
We remove DRONE CI; but it is not completely removed.
It has several references. 
https://github.com/search?q=repo%3Agomods%2Fathens%20drone&type=code

We should fix it.

Further we should remove it from: 
Automated workflows
https://github.com/gomods/athens/pull/1832

**Comment by r-ashish** [comment]
Also, drone is still showing up on PRs & is marked as required. Not sure where’s that coming from.

There’s also a drone webhook that should now be safe to remove.

**Comment by r-ashish** [comment]
> Also, drone is still showing up on PRs & is marked as required. Not sure where’s that coming from.

Managed to get rid of this.

For posterity, it was under branch protection rules: https://github.com/gomods/athens/settings/branches.
