### ISSUE TITLE
Problem with link in README.MD

### ISSUE THREAD

**Issue by ColumbiaMancera** [gomods/athens#1863]
On the section titled "More Details Please!" and specifically the sentence "There is currently an experimental public proxy (at https://athens.azurefd.net/) that you can use to try out Athens", whenever I try to access the page it gives me a blank page with the message "Welcome to The Athens Proxy". I'd currently change this message to "There is currently an [experimental public proxy](https://athens.azurefd.net/) in development that you can use to try out Athens...". I'd like to be assigned to this issue and I'll be submitting a PR to solve it.

**Comment by nrwiersma** [comment]
Hi,

"Welcome to The Athens Proxy" is the correct response for accessing Athens on path `/`. It is unclear to me why this requires a change in the README? Could you explain what the proposed change achieves?
