### ISSUE TITLE
Don't check TLS key file permissions

### ISSUE THREAD

**Issue by uhthomas** [gomods/athens#1879]
**Describe the bug**

Athens checks the permission bits of the TLS key file and fails to start if it fails the check.

https://github.com/gomods/athens/blob/cac9c754cb616fbeb6f25ad5e7a20b4cd6a89321/pkg/config/config.go#L235-L237

This is a bit annoying for environments where it doesn't matter, like in Kubernetes where secrets are written with 0o644. There is nothing else in the container - this check does not help.

**Error Message**

```console
2023/09/01 09:54:19 TLSKeyFile should not be accessible by others
```

**To Reproduce**

Run Athens with TLS.

**Expected behavior**

Athens should not check the permission bits of the file.

**Environment (please complete the following information):**
 - OS: Linux (Kubernetes)
 - Go version: N/A
 - Proxy version: v0.12.1
 - Storage: N/A

**Additional context**

I understand the intent behind the check, but I'm not sure it really helps and just makes deployment more fragile than it needs to be.

**Comment by terinjokes** [comment]
This check also makes it difficult to use tools like [lego](https://github.com/go-acme/lego) to manage the ACME lifecycle. This is commonly deployed where the application and lego are running as separate users, but share a group membership that's on the certificate and key.
