### ISSUE TITLE
Athens leaks etcd leases

### ISSUE THREAD

**Issue by uhthomas** [gomods/athens#1886]
**Describe the bug**

Athens [creates a new session (lease) for each stash request](https://github.com/gomods/athens/blob/e248d228921243998aca56dab01786e3cb938919/pkg/stash/with_etcd.go#L59), and then never closes the session. The leases are then held indefinitely, or until the process is restarted, which causes excessive load on the etcd cluster and eventually overloads it.

<img width="1448" alt="Screenshot 2023-09-11 at 22 31 10" src="https://github.com/gomods/athens/assets/9749173/fb8f298a-2e5f-4f8e-a6fd-446f2963bbef">

<img width="1462" alt="Screenshot 2023-09-11 at 22 32 27" src="https://github.com/gomods/athens/assets/9749173/7429715b-551f-482e-9624-bc0b1143db02">

The spikes are from restarting Athens.

**Error Message**

N/A

**To Reproduce**

1. Run Athens with etcd configured for singleflight.
2. Make a few thousands requests for modules which aren't already cached.
3. Observe the number of leases increases indefinitely.

**Expected behavior**

Athens should either create a single session for all locks, or close the session. I am not sure which is correct as I could not find great documentation on what is recommended by the etcd authors. I imagine it's probably best just to make sure the session is closed.

**Environment (please complete the following information):**
 - OS: Linux
 - Go version: N/A
 - Proxy version: https://github.com/gomods/athens/commit/e248d228921243998aca56dab01786e3cb938919
 - Storage (fs/mongodb/s3 etc.): etcd and s3

**Additional context**

**Comment by santiagoPinzonD** [comment]
Hello, @uhthomas  wanted to know how did you solve this problem ?
I know that the fix is already in the code but not yet released.
this is my singleflight config, I have a lot of traffic and I have to restart constantly because it consumes the machine's memory.
![image](https://github.com/gomods/athens/assets/66101364/58d52597-dcf4-4c16-b684-c1ff819c0904)

**Comment by uhthomas** [comment]
@santiagoPinzonD You will have to build Athens from source.

```Dockerfile
FROM golang:1.21.3-alpine AS build

RUN apk update && apk add git

RUN go install github.com/gomods/athens/cmd/proxy@main

FROM gomods/athens:v0.12.1

COPY --from=build /go/bin/proxy /bin/athens-proxy
```

**Comment by manugupt1** [comment]
Please use canary tag which has more fixes

**Comment by r-ashish** [comment]
We do have tags for every commit but under a separate registry: https://hub.docker.com/r/gomods/athens-dev/tags. Feel free to use it if you wanna pin to a specific commit until the next stable version is released.

**Comment by santiagoPinzonD** [comment]
Done, thanks guys
yesterday I put in production the canary, let's see if it manages to solve the memory problem, I take this opportunity to ask you, we currently have two organizations in github, so we are running two athens container on the same server, this apparently has not been a problem, until we doubled the traffic an average of 20 million request, I opened another issue regarding this issue and commented that you can outsource the database.
is there any guide about this? and how can I improve the performance?

**Comment by uhthomas** [comment]
What specifically are you asking, sorry? There is no database required for Athens. Just use an S3-compatible storage system and the existing etcd cluster. You shouldn't need a separate instance of Athens per GitHub organisation either.
