### ISSUE TITLE
How do I scale the athens container for better performance?

### ISSUE THREAD

**Issue by santiagoPinzonD** [gomods/athens#1895]
Currently I use the athens container, and we have a 5M request, this apparently has been going well until now that we have doubled the traffic, with this doubling comes moments that simply saturates the container, thus saturating the instance where it runs and fixing it with a restart.

We want to know what configuration or what we could do to make a kind of tuning to the container so that it can handle this large amount of traffic.

Regarding the instance where the container runs is a c5.4xlarge.
we do not see it saturating metrics like cpu or memory usage.
we have no problem in putting a c5.18x large for example, but the issue is that the container would not take advantage of all those resources.

We don't have any kind of limit in the docker-compose, we have a sonatype nexus that points to the athens proxy and this in turn hits the organization we have in github.

We are testing to make a scaling of instances, so that it does not handle all this traffic a single instance, but for now we are looking for a solution so that athens can manage to handle this traffic.
 

```
GoGetWorkers` = 10
GoGetDir = ""
ProtocolWorkers = 30
LogLevel = "info"
CloudRuntime = "none"
EnablePprof = false
PprofPort = ":3001"
FilterFile = ""
RobotsFile = "robots.txt"
Timeout = 300
StorageType = "s3"
Port = ":3000"
GlobalEndpoint = ""
BasicAuthUser = ""
BasicAuthPass = ""
PropagateAuthHost = ""
ForceSSL = false
ValidatorHook = ""
PathPrefix = ""
NETRCPath = ""
GithubToken = "${athens_github_token}"
HGRCPath = ""
TraceExporter = ""
TraceExporterURL = "http://localhost:14268"
StatsExporter = "prometheus"
SumDBs = ["https://sum.golang.org"]
NoSumPatterns = ["github.com/*"]
DownloadMode = "file:/config/rules.hcl"
DownloadURL = ""
SingleFlightType = "memory"
IndexType = "none"
```

**Comment by uhthomas** [comment]
I believe you've already figured this out - but Athens will scale horizontally with external storage and single flight services. Athens happily serves millions of requests per hour with a few pods in Kubernetes, [R2](https://www.cloudflare.com/en-gb/developer-platform/r2/) and [etcd](https://etcd.io/). Resource usage is surprisingly low at 100m cpu, 128Mi (mean) per pod. We allocate much more than that though.
