### ISSUE TITLE
Consolidate all environment variable fetching at the top of the stack

### ISSUE THREAD

**Issue by arschles** [gomods/athens#190]
I was figuring out how to deploy Olympus and it was pretty hard to find all the env vars it uses, and which of those it requires. It'll be easier when we have docs but even then it's nicer to have things in one place.

Everything uses `envy.Get` or `envy.MustGet`, so we need to:

1. Move all those commands to the top of the stack (i.e. near the `main`)
2. ... possibly create a utility function to get all the env vars (consider using [envconfig](https://github.com/kelseyhightower/envconfig) instead of envy for consolidating)
3. Pass env vars down the stack

**Comment by marpio** [comment]
I would like to start this one

**Comment by marpio** [comment]
Does #209 close this?

**Comment by michalpristas** [comment]
I believe it does, to some extent. Next step is documenting all the things necessary to setup preferably with a script setting it for you.
Then I would consider this issue closed.
