### ISSUE TITLE
Use AWS SDK v2 for Go

### ISSUE THREAD

**Issue by matt0x6F** [gomods/athens#1938]
**Is your feature request related to a problem? Please describe.**

The [existing AWS SDK we use](https://github.com/aws/aws-sdk-go?tab=readme-ov-file) is in maintenance mode. We should migrate to [v2](https://aws.github.io/aws-sdk-go-v2/docs/) when we can. No official dates for migration have been issued at the time of writing.

**Describe the solution you'd like**

Reimplement the AWS SDK with the new version.

**Describe alternatives you've considered**

- Not upgrading

**Additional context**

N/A

**Comment by k124k3n** [comment]
Can I assigned to this issue?

**Comment by matt0x6F** [comment]
> Can I assigned to this issue?

Yeap! Go for it.

**Comment by matt0x6F** [comment]
@k124k3n try the docker based e2e tests. There's a target in the Makefile that correlates to this.

**Comment by k124k3n** [comment]
Seem's like AWS SDK v2 require `protocol://` in Endpoint.

When I set `export ATHENS_MINIO_ENDPOINT="127.0.0.1:9001"`, it fails on `s3_test.go`:
``` bash
s3_test.go:104: operation error S3: CreateBucket, resolve auth scheme: resolve endpoint: endpoint rule error, Custom endpoint `127.0.0.1:9001` was not a valid URI
```

When I set `export ATHENS_MINIO_ENDPOINT="http://127.0.0.1:9001"`, it fails on `minio_test.go`:
``` bash
--- FAIL: TestBackend (0.00s)
    minio_test.go:107: address http://127.0.0.1:9001: too many colons in address
--- FAIL: TestNewStorageExists (0.00s)
    minio_test.go:39: TestNewStorageExists failed for bucketname:  testbucket, error: address http://127.0.0.1:9001: too many colons in address
```

Should we add `protocol://` in `aws.Config.Endpoint`?

**Comment by matt0x6F** [comment]
@k124k3n since Minio is the only one that expects there not to be a protocol in the address could we make part of the function trim prefixes for `http://` and `https://`?

**Comment by k124k3n** [comment]
Sure, also, we should update Athens S3 documentation to refer into AWS SDK v2 docs.
