### ISSUE TITLE
Github token to access private github repos is not working

### ISSUE THREAD

**Issue by midestefanis** [gomods/athens#1967]
**Describe the bug**
I'm running Athens in ECS following this docs: https://docs.gomods.io/install/install-on-aws-ecs-fargate/
It's working fine but now i need to authenticate Athens to my private repos in Github. I've created a token with **read access** but Athens is throwing an error. 

Token DOCS i'm following: https://docs.gomods.io/install/install-on-kubernetes/index.html#give-athens-access-to-private-repositories-via-github-token-optional

Can I ask to specify in the [documentation](https://docs.gomods.io/install/install-on-kubernetes/index.html#give-athens-access-to-private-repositories-via-github-token-optional) exactly what permissions the token needs? read only should be enough but it doesn't work. Or is the problem something else?

**Error Message**

<pre>
```console
DEBUG[11:59AM]: saving github.com/******@v1.4.4 to storage... http-method=GET http-path=/github.com/******/@v/v1.4.4.info request-id=cc739af0-f9f4-4963-9c6e-4000f4a4e8b2

INFO[11:59AM]: github.com/****@v1.4.4: verifying go.mod: github.com/*****@v1.4.4/go.mod: reading https://sum.golang.org/lookup/github.com/******@v1.4.4: 404 Not Found

server response: not found: github.com/*******@v1.4.4: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/5cc9286f0292dc9cd4e251beead17ca2ab46fab2217db5b6c7ed289e794c81a2: exit status 128:

fatal: could not read Username for 'https://github.com': terminal prompts disabled

Confirm the import path was entered correctly.

```
</pre>

**Expected behavior**
I'm expecting a successfull ansswer with a read only token

**Environment (please complete the following information):**

- OS: [e.g. Linux 64bit] : Alpine Linux amd64
- Go version : go1.20.14
- Proxy version : v0.14.0
- Storage (fs/mongodb/s3 etc.) : s3

**Comment by midestefanis** [comment]
Hi @matt0x6F, can i ask you to take a look please? this is blocking me. Thank you in advance

**Comment by midestefanis** [comment]
I also tried with a token with read and write access and it doesn’t work either.

**Comment by midestefanis** [comment]
similar to -> https://github.com/gomods/athens/issues/1718

**Comment by matt0x6F** [comment]
@midestefanis I can take a look at this when I get some time but I have some serious doubts that our GitHub token integration is broken. There are new token formats for GitHub, which could be an issue, but generally issues like this come down to configuration.

Can you do some tests with your existing token and see if you can pull repository files from a private repository using it? There should be some examples via `curl` to speed you along in validating this. If the token works just fine on a private repository let me know and I'll test it on my end with new and legacy tokens.

**Comment by midestefanis** [comment]
@matt0x6F I've solved it by using **ATHENS_GONOSUM_PATTERNS**, i think we can close this ticket
