### ISSUE TITLE
Storage limiting per-path

### ISSUE THREAD

**Issue by senpro-ingwersenk** [gomods/athens#1970]
Hello there,

**Is your feature request related to a problem? Please describe.**
I am working to establish a Go development environment at my company and I would like to use Athens to allow our workers here to access go modules published to private Github repositories (`github.com/senpro-it/...`). However, our storage is a little tight; so it would be very useful if we could TTL older modules out of the local storage.

**Describe the solution you'd like**
A configuration/environment flag that globally sets either a TTL or overall size limit per module path; or, that only modules from a specific path are stored and the rest is fetched from upstream.

**Describe alternatives you've considered**
Using the HCL formatted file, specify which modules should go to disk and which should not.

**Additional context**
I am still somewhat new to Go, but it is important to me that our code stays private for a while up untill it is either ready for release or dies off in a corner. ;)
Athens will be hosted in a k3s cluster, custom deployment.

Thank you and kind regards!

**Comment by matt0x6F** [comment]
Hello! Can you read https://github.com/gomods/athens/issues/1899 and see if this is a duplicate? They sound very similar.
