### ISSUE TITLE
Default homepage URL incorrect behind reverse proxy

### ISSUE THREAD

**Issue by tbnguyen1407** [gomods/athens#1979]
**Describe the bug**

When deploying athens behind a reverse proxy with TLS termination, the scheme shows on homepage as `http` instead of `https`

```
[client] --https--> [proxy] --http--> [athens]
```

**Error Message**

Proxy URL shown as `http://myproxy.com`

**To Reproduce**

1. Deploy athens behind TLS-terminating reverse proxy
2. See wrong URL proto on homepage

**Expected behavior**

Proxy URL should show as `https://myproxy.com`

`X-Forwarded-*` headers of incoming request should be considered when determining public URL host and scheme to display.

**Environment (please complete the following information):**
 - OS: Docker
 - Go version: 1.23
 - Proxy version: 1.14.1
 - Storage: fs

**Additional context**

**Comment by matt0x6F** [comment]
@tbnguyen1407 The server uses a default template that when behind a reverse proxy won't be correct. You can [override](https://github.com/gomods/athens/blob/main/pkg/config/config.go#L45) it using a Go template similar to the one [here](https://github.com/gomods/athens/blob/main/cmd/proxy/actions/home.go#L14-L87).
