### ISSUE TITLE
go mod download show 404

### ISSUE THREAD

**Issue by ahkui** [gomods/athens#1983]
**Error Message**
Client side
![image](https://github.com/user-attachments/assets/f746457b-2526-4141-9e8c-0cfcbc9b99e8)

server side
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/3b92ab88-a0c0-4f84-9dd1-cc4a7e696dd3">

**To Reproduce**
1. create a new go project
2. install package in local env -> `go get github.com/hairyhenderson/gomplate/v4`
3. push commit to remote git
4. ci run go mod download and get 404

**Comment by matt0x6F** [comment]
@ahkui there's not really enough information here to go on. We'd need to be aware of how your installation of Athens is configured. It looks like it was fetching other modules perfectly fine, even ones that have vanity URLs. I suspect there's something else going on with v0.9.2
