### ISSUE TITLE
Please add Topics to repo

### ISSUE THREAD

**Issue by markbates** [gomods/athens#203]
Hi, I working on a project that will be announced soon to help with the discovery of these sorts of tools. Would you please mind adding some "Topics" to this repo? Thanks.

On GitHub you can use the "Topics" feature of your repository to tag your projects with `gobuffalo` and other category tags.

There are a few more tags that you can use that will help the Buffalo Toolkit better categorize your project. You can add as many of this tags to your project as is suitable. Please try to refrain from using more than just a few tags.

* `plugin` - Plugins
* `generator` - Generators
* `middleware` - Middleware
* `pop` - Pop/Soda
* `templating` - Templating
* `grifts` - Grift Tasks
* `deployment` - Deployment
* `testing` - Testing
* `example` - Example Apps
* `worker` - Workers/Adapters
* `webpack` - Webpack/Front-End

**Comment by arschles** [comment]
Hey Mark - I added a few more topics to describe this project, including `gobuffalo`. Screenshot below.

![screen shot 2018-06-29 at 10 38 50 am](https://user-images.githubusercontent.com/70865/42106359-a17c38de-7b88-11e8-9027-49d7ba9814ab.png)

I'm gonna close this issue now, but please comment here or open a new one if you have ideas for more.

**Comment by markbates** [comment]
Thanks! Please update any other repos you think are appropriate to Buffalo developers. :)
