### ISSUE TITLE
Finish GCP storage

### ISSUE THREAD

**Issue by robjloranger** [gomods/athens#205]
Should also implement the `Lister`, `Getter` and `Checker` interfaces to round out the driver. After which it can be used as a back end for both Olympus and Zeus.

**Comment by arschles** [comment]
@robjloranger I think it only needs the `Saver` and `Getter` interface to be used for the registry, right?

I think we'd need those interface implementations for the proxy though...

**Comment by robjloranger** [comment]
I was wondering about that. Should the driver implement both and provide two different generators? I can write up a datastore (GCP database) driver for the proxy stuff.

I just remembered the fs driver implements all of it.

**Comment by robjloranger** [comment]
now in progress #208

**Comment by robjloranger** [comment]
closed via #208
