### ISSUE TITLE
Allow private modules

### ISSUE THREAD

**Issue by robjloranger** [gomods/athens#206]
This was going to be an issue specific to GCP storage but I think it will probably be a lot bigger than that.

The configuration ability for just that driver is easy enough but having the saver know when something should be uploaded as private or not is another issue. I think it would require modification to the `Saver` interface.

The metadata would probably also store whether a module is private or not as well.

**Comment by robjloranger** [comment]
I've been thinking if it does need modification, perhaps it could take a `(./pkg/storage).Module` and a bool for private. At the moment it takes a parameter for all the same fields as a `Module` so a change like this would be easier to read.

**Comment by arschles** [comment]
@robjloranger did #212 address this?

**Comment by robjloranger** [comment]
I think it should. It originally came up for me working on cloud storage and Olympus storing module files as publicly viewable. There was a thought about having the option to upload some modules as private but I'm not sure it is necessary. With a filter Olympus should never have a reason to store a private/internal module.

Let's close it and revisit of it comes up.

**Comment by michalpristas** [comment]
I will copy comment from another PR: Maybe this issue can cover this?

> private modules. in v2 we will allow uploading of custom packages, right now it should be all discoverable. so private means it sits in private VCS (private gitlab instance).
so you host your code in gitlab instance deployed within companys VPN.
your private proxy is deployed in same VPN
so it is all visible.
another way how to understand private is as a private repo in github visible to organization. in this case we need to provide a way how to make this package available through proxy. we don't really have this scenario thought through.
