### ISSUE TITLE
Stream zip up to Azure CDN/Blob Storage

### ISSUE THREAD

**Issue by marpio** [gomods/athens#210]
PR #200 changes the `storage.Saver` interface so that it accepts zip as `io.Reader` but the Azure CDN storage impl. uses `ioutil.ReadAll` to get a byte slice which gets then uploaded.

Change the implementation so it's possible to stream the zip directly to the CDN/Blob storage.
Reference:
https://godoc.org/github.com/Azure/azure-storage-blob-go/2017-07-29/azblob#UploadStreamToBlockBlob
UploadSteamToBlockBlob reads from an io.ReadCloser into 1+buffers (configurable) and then writes them with full resiliency via retry support.

**Comment by robjloranger** [comment]
Closed per #200
