### ISSUE TITLE
Stream zip up to AWS S3 storage

### ISSUE THREAD

**Issue by marpio** [gomods/athens#211]
PR #200 changes the `storage.Saver` interface so that it accepts zip as `io.Reader` but the AWS S3 storage impl. uses `ioutil.ReadAll` to get a byte slice which gets then uploaded.

This could probably help:
https://docs.aws.amazon.com/sdk-for-go/api/service/s3/s3manager/#Uploader

**Comment by arschles** [comment]
@marpio now that #200 is merged, is this issue completed?

**Comment by robjloranger** [comment]
Not yet. The s3 and gcp storages still pass a byte slice to their clients.

**Comment by marpio** [comment]
@robjloranger gcp is using Io.reader

**Comment by robjloranger** [comment]
Oh nice 😊, I missed the io copy

**Comment by marpio** [comment]
I talked to Michal. I'll take this one.

**Comment by michalpristas** [comment]
assigned to you @marpio
