### ISSUE TITLE
Update CI/CD to deploy to development instance of the proxy

### ISSUE THREAD

**Issue by robjloranger** [gomods/athens#213]
_We still need to get up and running first._

After which we can have a continuous deployment from the tip of master.

A few things to consider:

1. Which type of deployment would be best? Using cloud based storage/database?
2. Where will we host the Olympus instance?
3. How will we handle breaking changes?

**Comment by arschles** [comment]
As of #772, we're not going to try and build a registry for the time being.

@robjloranger I've updated the title of this issue and put it into the `preview` milestone so that we can move toward #772

**Comment by chriscoffee** [comment]
I'd like to take over on this one.

**Comment by chriscoffee** [comment]
Just a quick update on this that we're waiting for a new subscription and access. This can take a while. We last discussed this around 29th October.

**Comment by arschles** [comment]
I'm closing this for the same reason as #735
