### ISSUE TITLE
Make the registry implement the download protocol

### ISSUE THREAD

**Issue by arschles** [gomods/athens#228]
I said I would do this a while ago, and then it slipped my mind 😦 

@marwan-at-work I know you had interest in doing this? Let me know, and zero problems if not - I'll take care of it in that case.

**Comment by marwan-at-work** [comment]
will take a stab at it : )

**Comment by marwan-at-work** [comment]
Fixed by by https://github.com/gomods/athens/pull/238

However, the one endpoint that remains unimplemented by both the registry and the proxy, is the `/@latest` endpoint which is pending input from the Go team via https://github.com/golang/go/issues/26334

**Comment by robjloranger** [comment]
thanks @marwan-at-work
