### ISSUE TITLE
Look for "dead code"

### ISSUE THREAD

**Issue by arschles** [gomods/athens#232]
Continuation of https://github.com/gomods/athens/pull/229#issuecomment-403620039

cc/ @michalpristas

**Comment by michalpristas** [comment]
Thank you 💙

**Comment by komuw** [comment]
@michalpristas 
regarding;
`Totaly unrelated: I would like to scan codebase for unused packages and code to clean it up a bit (not everything unused is not needed)`
Do you have ideas on how to go about doing that? 

I would like to help with athens and I'm looking for "easy" issues to start with & get my feet wet.

**Comment by arschles** [comment]
Hey @komuw! Thanks for getting in touch. One great place to check out is the `./pkg/user` package (https://github.com/gomods/athens/tree/master/pkg/user). We don't manage users in the system and don't plan to in the near future, but I'm not sure if any of that code is used anywhere. Anyway, if you feel like going to check it out, absolutely go for it and [ask questions](https://github.com/gomods/athens#getting-involved) whenever you have them. Pull requests welcome 😄

**Comment by komuw** [comment]
thanks I will

**Comment by arschles** [comment]
👍

**Comment by michalpristas** [comment]
oh I wrote a reply and forgot to send it :D
my plan with this was to write a simple tool, creating map packages in the solution
then scanning for imports and counting occurrences.
next step would be to manually check packages and decide whether or not they are needed.
please feel free to ping me directly if you need any help. I usually respond faster on Slack.

**Comment by komuw** [comment]
@michalpristas hi, have a look at ; https://github.com/gomods/athens/pull/267
let me know if you think I missed something
