### ISSUE TITLE
Implement cdn.Download

### ISSUE THREAD

**Issue by marpio** [gomods/athens#240]
At the moment the impl. looks  like this:
```
func Download(url, module, version string) (*storage.Version, error) {
	// TODO
	return nil, nil
}
```
It should download module from the cdn.

**Comment by robjloranger** [comment]
Do you think this was meant to be an interface declaration like the Deleter in the same pkg?

**Comment by marpio** [comment]
I think a simple function is okay. We could pass it to mergedb so it can be substituted in a unit test.
