### ISSUE TITLE
GoFish and Athens

### ISSUE THREAD

**Issue by gedw99** [gomods/athens#242]
There is a nice golang system that replaces Homebrew and works on all Desktops.
https://github.com/fishworks/gofish

I know Athens is all about source packages, but its interesting that Gofish can be used for Binary Package management too.

At the moment lots of the tools gopherjs use if supported by Gofish.  They call the packages "Food" - Fish food - get it :)
https://github.com/fishworks/fish-food/tree/master/Food

i figured it was were mentioned as it ties things up nicely.

**Comment by arschles** [comment]
@gedw99 thanks for bringing that up! Do you think there'd be any overlap between the two systems? It would be really cool to see if you can think of something

**Comment by arschles** [comment]
Ref https://github.com/fishworks/gofish/issues/97

**Comment by arschles** [comment]
@gedw99 I am going to close this for now. Feel free to comment here if you can clarify how this would work or give some more ideas on https://github.com/gomods/athens/issues/242#issuecomment-404251560
