### ISSUE TITLE
Deleter should return ErrVersionNotFound

### ISSUE THREAD

**Issue by robjloranger** [gomods/athens#244]
Currently the (./pkg/storage).Deleter is expected to return the error `ErrNotFound` which is for a module that is not found. I think it makes more sense to return `ErrVersionNotFound` as the Deleter is attempting to delete a specific version.

for reference https://github.com/gomods/athens/blob/3504476fa17d779cc4f3df8f1861f819915a0539/pkg/storage/deleter.go#L5
https://github.com/gomods/athens/blob/3504476fa17d779cc4f3df8f1861f819915a0539/pkg/storage/not_found_err.go#L7
https://github.com/gomods/athens/blob/3504476fa17d779cc4f3df8f1861f819915a0539/pkg/storage/not_found_err.go#L17

current implementations of `Deleter` which are missing the check/return not found:
- [x] minio
- [x] rdbms
- [x] fs
- [x] mongo

**Comment by robjloranger** [comment]
current implementations of `Deleter` which are missing the check/return not found:
- [ ] minio
- [ ] rdbms
- [ ] fs
- [ ] mongo

**Comment by tbpg** [comment]
I'm interested in this. I'll send a PR for `fs` first.

**Comment by robjloranger** [comment]
Just a heads up, after these are complete the tests will need to be refactored to align with #76.

We can't change the common test while doing one at a time or the other storages will fail. I will create a second issue for this. The smaller PRs are much easier to review.

**Comment by tbpg** [comment]
:+1: Sounds good! I'd be happy to take that one, too.

**Comment by robjloranger** [comment]
closed by #294, #295, #297, #298
