### ISSUE TITLE
Common testing ground for CDN storages

### ISSUE THREAD

**Issue by michalpristas** [gomods/athens#245]
Follow #215 as an example and introduce common testing ground for CDN storages
this covers: azure blob storage, s3 and GCP

**Comment by robjloranger** [comment]
note: GCP will require an authentication key file so the tests should skip if the env variable `ATHENS_STORAGE_GCP_SA` is not set. This name may change, I think `SA` for service account is not descriptive enough.

**Comment by marpio** [comment]
Small hint - the client interface and the newWithClient function aren't exported. They would need to be to be used in a common suite.

**Comment by robjloranger** [comment]
There is no `newWithClient` in GCP, and the new `Bucket` interface is exported. After #263 my above comment will not be as relevant. There will be a `NewMock` or similar function to return a mock implementation for GCP tests.

**Comment by marpio** [comment]
@robjloranger you're right. I was thinking about the azure CDN implementation.

**Comment by fedepaol** [comment]
I will take this one!

**Comment by marpio** [comment]
I think CDN storages could have a separate suite since they have some functionality that other storages don't have i.e. getting the URL. So maybe this could be done without implementing the full Backend interface for azure and s3 before @robjloranger ?

**Comment by robjloranger** [comment]
@marpio I *believe* this is for the whole `Backend` interface. If #215 is an example. Are not all sub packages of (./pkg/storage) meant to be a `Backend`? Maybe @michalpristas can clarify?

**Comment by michalpristas** [comment]
cdn is for metadata storage and should have separate test suite. what i had in mind with this issue are implementations of module storages

**Comment by michalpristas** [comment]
closing as CDN storage is not used
