### ISSUE TITLE
Add build status to README.md?

### ISSUE THREAD

**Issue by robjloranger** [gomods/athens#259]
I think this would be cool, I like the little badges for projects.

The markdown is:
```markdown
[![Build Status](https://travis-ci.org/gomods/athens.svg?branch=master)](https://travis-ci.org/gomods/athens)
```

Which results in [![Build Status](https://travis-ci.org/gomods/athens.svg?branch=master)](https://travis-ci.org/gomods/athens)

Maybe this could go under the "Project Status" section in the readme?

**Comment by komuw** [comment]
I can work on this

**Comment by michalpristas** [comment]
go ahead @komuw
