### ISSUE TITLE
deprecated redis client

### ISSUE THREAD

**Issue by komuw** [gomods/athens#260]
Athens is using redigo[1]
But from that packages github repo[2], it is marked as `This repository has been archived by the owner`. Development has moved to[3]

1. https://github.com/gomods/athens/blob/5addd3304a940c4f39042b2e1581b60aafdd4210/Gopkg.toml#L101

2. https://github.com/garyburd/redigo

3. https://github.com/gomodule/redigo

**Comment by komuw** [comment]
I would like to work on this.

**Comment by michalpristas** [comment]
yes please move it to gomodule/redigo. 
maybe gocraft work adapter will make some troubles, but they will have a pack in moving to [3] as well

**Comment by michalpristas** [comment]
if you have the issue with adapter, just raise a PR mark it as wip, and once adapter is aligned, 
we will update PR and push it in.
