### ISSUE TITLE
Make 'env.Timeout' more specific

### ISSUE THREAD

**Issue by arschles** [gomods/athens#261]
I think we should have separate timeouts for different services. For example, mongo connection timeouts (see https://github.com/gomods/athens/pull/216), HTTP timeouts, etc...

Continuation of https://github.com/gomods/athens/pull/254#discussion_r202407219

**Comment by robjloranger** [comment]
Agreed, I thought that as well but forgot to create the follow up.

Web requests and DB connections should have more sane defaults, maybe 60s?
