### ISSUE TITLE
Add build step to prevent merging conflicts

### ISSUE THREAD

**Issue by robjloranger** [gomods/athens#273]
conflicts = the artifacts marking the conflicts. ie:
```
<<<<<< HEAD
```

A grep in bash should do the trick, like `^[<>=]{7}` would check for lines beginning with any of the `<<<<<<<`, `=======`, `>>>>>>>`

This way the build would fail when these are hiding somewhere in a toml or other 'diff collapsed by default' file.

**Comment by michalpristas** [comment]
can we consider this fixed indirectly by #268 ?
will dep ensure fail if Gopkg files are incorrect and contain `>>>>`?

**Comment by robjloranger** [comment]
It would fail, however it won't check any other files. Go files are ok because lint will catch those. This would catch the odd edges like `.travis.yaml`, or `.md` files.

I suppose most of those file types should be show expanded diffs, so we should catch them in reviews.

What does everyone think?

**Comment by michalpristas** [comment]
i'm afraid that expanding all will result in collapsing gopkg.* manually as conflicts there are super long and unreadable

**Comment by michalpristas** [comment]
but i'm not against expanding

**Comment by robjloranger** [comment]
I would rather not have them expand either, so the existing check for those could stay. It doesn't check for conflicts that were committed just for errors on `dep ensure`.

But should we bother to check for conflicts committed in other non `.go` files?

**Comment by robjloranger** [comment]
updated the OP for clarity.

**Comment by robjloranger** [comment]
I'll get this done today, I will have it omit `*.go` and `go.{mod,sum}` files as those will fail builds during lint and dependency checks respectively.
