### ISSUE TITLE
Investigate Netlify deploy connection resets

### ISSUE THREAD

**Issue by robjloranger** [gomods/athens#277]
This might just be something on Netlify's end but it makes pull requests appear to have failed.

We are experiencing an intermittent error during the put request to https://api.netlify.com/api/v1/sites/ of `read: connection reset by peer`.

**Comment by robjloranger** [comment]
It could be rate limiting but I think we get 200 reqs per minute.

**Comment by robjloranger** [comment]
I'm not sure there is much we can do on our end, closing

**Comment by michalpristas** [comment]
could you sum up your investigation? or is it mentioned throttling?

**Comment by robjloranger** [comment]
I started by checking the status page[1] which reports nothing unusual.
I then checked the toml config options[2] to see if we were setting, or not, something that could affect this with no luck.
Then digging around on Netlify docs I found there is a rate limit[3] of 200 requests per minute whose status is returned in the HTTP response which we likely can not check as it's Travis making the request. Maybe we could write a script to print out the error response.

[1] https://netlifystatus.com/
[2] https://www.netlify.com/docs/netlify-toml-reference/
[3] https://www.netlify.com/docs/api/#rate-limiting

**Comment by robjloranger** [comment]
I'm happy to reopen if you think we can find something else.

**Comment by michalpristas** [comment]
Thanks @robjloranger much appreciated 👍

**Comment by snxq** [comment]
have the same problem. and server has no rate limit. 

then I found this. https://github.com/golang/go/issues/20960 I don't know if it's related to this.
but I still not successful.

**Comment by arschles** [comment]
@snxq are you trying to request pages from netlify using Go?

We haven't seen these resets in a while on pull request status reports
