### ISSUE TITLE
Implement download protocol on top of Github API

### ISSUE THREAD

**Issue by michalpristas** [gomods/athens#281]
The goal is to provide an adapter to github api so we can redirect in case of cache miss or a request for non-version ref (commit hash)

The flow should be like this (for zip endpoint) for module mod version v1.0.0 owned by gomods:
1. GET athens/github.com/gomods/mod/@v/v1.0.0.zip is hit and detects a CACHE MISS
1. reports cache miss to olympus
1. redirects to  athens/adapter/github/gomods/mod/@v/v1.0.0.zip
1. this gets tar from api.github.com (_GET api/github.com/repos/gomods/mod/tarball/v1.0.0_)
1. github api responds with 302 and redirect location. 
1. repack stream from GIT serving TAR into resp.Body using ZIP writer

we process the input stream to output zip writer (writes to resp.Body) in a way that we will
serve content of input _gomods-mod-{sha}_ directory into _github.com/gomods/mod/@v/v1.0.0_ directory created and placed inside output zip

**This task requires some playing around for this to work. As it is highly experimental. Based on results and perf may or may not make it to the upstream.**

example: 
tar input stream from git API:
```
gomods-mod-e3458ae/
   cmd
      main.go
   go.mod
```

zip output to resp.body
```
github.com/
   gomods/
      mod/
        @v/
           v1.0.0/
              cmd/
                 main.go
              go.mod
```

Similiar approach should be done for _athens/adapter/github/gomods/mod/@v/v1.0.0.mod_ endpoint but it would process tar stream from github and return content of go.mod to resp.body

_athens/adapter/github/gomods/mod/@v/v1.0.0.info_ needs to verify that tag {version} exists and then consturct and serve RevInfo 

Note: it's important to process streams and not load entire content of archive into memory.

Please ping me directly using Slack for review

**Comment by arschles** [comment]
We are going to do synchronous cache fills (see #290), so redirecting will be less necessary and IMO we should prefer to be the authoritative source of module source code and metadata.

Streaming from Github would be an interesting optimization if we can do it, though - we could stream to the client as we also fill the cache. We'll need to measure that against just `go get`-ing code onto disk and then streaming that to the client

**Comment by arschles** [comment]
Closing this issue, as it's no longer relevant to the current design of Athens
