### ISSUE TITLE
The fs lister lists directories, not versions

### ISSUE THREAD

**Issue by arschles** [gomods/athens#287]
See https://github.com/gomods/athens/blob/eb0768f3fe476dd68f4635a7ad60c3e059d0ff44/pkg/storage/fs/lister.go#L9 - it is hooked up to `/@v/list`, which should list the versions

**Comment by fedepaol** [comment]
Hey, can I grab this to start cutting my teeth?

**Comment by robjloranger** [comment]
Please do, let us know if you have any trouble.

**Comment by robjloranger** [comment]
Thanks so much, sorry for the confusion.
