### ISSUE TITLE
Make the CLI ignore unnecessary files when zipping source code

### ISSUE THREAD

**Issue by arschles** [gomods/athens#3]
The [does it work](https://github.com/gomods/athens#does-it-work) section shows that the default "upload" command in the CLI zips source code that then fails when `vgo` downloads it:

```console
$ vgo get arschles.com/testmodule@v1.0.0
vgo: downloading arschles.com/testmodule v1.0.0
vgo: import "arschles.com/testmodule": zip for arschles.com/testmodule@v1.0. has unexpected file testmodule/.DS_Store
```

It should ignore at least the `.git` and `.DS_Store` files, but probably more. At least to make `vgo get` succeed in downloading modules for now

**Comment by bketelsen** [comment]
maybe just follow the .gitignore?

**Comment by arschles** [comment]
+1 - https://github.com/sabhiram/go-gitignore could help with that (h/t @bketelsen for the reference)
