### ISSUE TITLE
Proposal: Module filter should have `ShouldSkip` or similar

### ISSUE THREAD

**Issue by robjloranger** [gomods/athens#306]
When we use the (./pkg/module).Filter method `ShouldProcess` to check that we should not process something. i.e.

```go
if !mf.ShouldProcess(mod) {
    return nil, fmt.Err...
}
```

I'm thinking we add a second method to improve readability like `mf.ShouldSkip(mod)`, which could even just call `ShouldProcess` and return the inverse result.

**Comment by marpio** [comment]
@robjloranger I think the ShouldProcess isn't used anymore and will be removed so we can close this issue.
Ref: https://github.com/gomods/athens/pull/461/files

**Comment by robjloranger** [comment]
:+1: Thanks @marpio
