### ISSUE TITLE
proxy: go get should return different errors for "not found" vs "on blacklist"

### ISSUE THREAD

**Issue by bketelsen** [gomods/athens#307]
proxy should return a not found error for a package that isn't found
the error for a package that is on the blacklist should be different from the "not found" error, to allow the go client to discriminate properly between non-existing packages and packages prohibited by proxy policy.

**Comment by arschles** [comment]
Agree. Personally I think we should make 403 Forbidden the standard for anything on the exclude list in the proxy

**Comment by marwan-at-work** [comment]
We should close this issue since we don't return 404s anymore. However, for better performance, we should open a new issue titled "return 404 and asynchronously fill cache" once cmd/go resolves this issue: https://github.com/golang/go/issues/26334

**Comment by michalpristas** [comment]
Closing as blacklist returns `StatusForbidden`
