### ISSUE TITLE
We should have a private module filter for the proxy

### ISSUE THREAD

**Issue by arschles** [gomods/athens#309]
We have an exclude list which tells the proxy to not return a module that matches a pattern on the list now. We also need to implement a list of patterns that the proxy can use to determine if a module is "private" - this means that it shouldn't ask for the module from upstream (the registry) and instead should directly fetch them from the VCS (with `go get`)

**Comment by marpio** [comment]
@fedepaol relevant issue: https://github.com/gomods/athens/issues/96 and PR https://github.com/gomods/athens/pull/212

**Comment by arschles** [comment]
@fedepaol please do! and unlike last time, this one is not going to go away or become obsolete 😄

**Comment by fedepaol** [comment]
I gave a quick look at https://github.com/gomods/athens/pull/212 . What I would try to do is to extend the domain of the current filter (now +/- ) with a p maybe?

Something like
- a
+ a/b/c
p a/b/c/d

Would mean that a/b/c/d will never be looked for in olympus an fetched directly from the vcs.
Does it make sense? To me it feels better than having a different filter file.

Can I try to proceed with this implementation?

**Comment by fedepaol** [comment]
New question, sorry @arschles :-( 

I am looking at https://github.com/gomods/athens/blob/db7a318a6f1944640b4474f3df3a83332d74f271/cmd/proxy/actions/app_proxy.go#L21 and https://github.com/gomods/athens/blob/db7a318a6f1944640b4474f3df3a83332d74f271/cmd/proxy/actions/cache_miss_handler.go#L25 

My understanding of the current status of the proxy is that when there is a miss in the local storage, alignments (notify and fetch from the registry) are queued asynchronously but the request that caused the miss gets a 404.

Is that correct? 
If so, what part should I implement with this issue? Just leaving the thing as they are (trying to asynchronously fill the local cache directly from the vcs) or something different?

**Comment by arschles** [comment]
Hey Federico - I’m traveling today and going to be offline tomorrow morning
so hopefully someone else can give more detail.

We’re going to begin filling caches synchronously soon, so if there’s any
way you can design the filter so that it can be applied later after the
synchronous implementation gets merged, that would be the best option.

There are a few PRs open that show how the async => sync work is coming but
I’m on my phone so I don’t have them handy

**Comment by fedepaol** [comment]
Grazie!
Also, does my suggestion of extending the current configuration instead of
adding a new one make sense (
https://github.com/gomods/athens/issues/309#issuecomment-406823918)?

Il lun 23 lug 2018, 21:26 Aaron Schlesinger <notifications@github.com> ha
scritto:

**Comment by fedepaol** [comment]
Update: I gave a look at all the stuff attached to the big Kahuna (https://github.com/gomods/athens/issues/290) and after discussing with @marpio I am pretty convinced that the big stuff is not implementing the new filter but putting the feeding the proxy with the local vcs in place.
For this reason, I would try to pick something else and wait for this one.

PS: thought that first bugs were easier :-)

**Comment by fedepaol** [comment]
Lol no worries! I won't give up!

Il mar 24 lug 2018, 16:27 Aaron Schlesinger <notifications@github.com> ha
scritto:

**Comment by arschles** [comment]
@fedepaol #290 is done now - sorry for not mentioning that sooner. you're clear to work on this if you still want to!
