### ISSUE TITLE
Implement a proxy 'admission controller'

### ISSUE THREAD

**Issue by ryancox** [gomods/athens#311]
Allow users of the proxy to implement a webhook that codifies their policies for allowed packages. Prior to populating the cache, the webhook would be consulted and the request would either be allowed or failed and a 403 or something similar returned.

Examples of policy rules:

- No GPL enforced via a library like https://github.com/ryanuber/go-license
- No high entropy string enforced via a library like https://github.com/securego/gosec

**Comment by arschles** [comment]
Thanks for bringing this up @ryancox! It would be a great addition to the proxy. 

Related issues: 

- https://github.com/gomods/athens/issues/96
- https://github.com/gomods/athens/issues/309

**Comment by robjloranger** [comment]
Please do
