### ISSUE TITLE
Remove the fetch route, handler & gomod parser

### ISSUE THREAD

**Issue by arschles** [gomods/athens#312]
The fetch route is [here](https://github.com/gomods/athens/blob/b1f178072f482cf69b7111a6366db383ad62c0c2/cmd/proxy/actions/app_proxy.go#L25) and the handler is [here](https://github.com/gomods/athens/blob/b1f178072f482cf69b7111a6366db383ad62c0c2/cmd/proxy/actions/fetch.go#L20)

This handler was used by the CLI (which is obsolete and was removed), and we don't need it anymore. This issue is for removing the fetch handler, the fetch route, and the gomod parser which was used by the fetch handler

**Comment by ryancox** [comment]
is there a gomod parser library elsewhere that could be used / improved?

**Comment by arschles** [comment]
@ryancox yes, it's in a package inside `golang/go`, I think an `internal` package. We're going to delegate as much of this as possible to calling the `go` CLI so we don't have to depend on code inside of the go toolchain

cc/ @rsc @marwan-at-work, both of whom have been part of discussions on this topic

**Comment by arschles** [comment]
This is a subset of #335, closing
