### ISSUE TITLE
Support a push to registry model

### ISSUE THREAD

**Issue by ryancox** [gomods/athens#315]
Rather than operating only as a pull-through cache, populate the registry via an explicit push operation.

![untitled drawing](https://user-images.githubusercontent.com/111244/43019383-9ef82ca0-8c11-11e8-9f43-3dcd9838e5e5.jpg)

This would be conceptually similar to artifactory's [go-publish command](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-PublishingGoPackagestoArtifactory) or a [pypi sdist upload](https://pypicloud.readthedocs.io/en/latest/topics/getting_started.html#uploading-packages)

**Comment by arschles** [comment]
@ryancox are you thinking the package deployer component would build the zip, `go.mod` and `.info` files? or would the registry do that?

**Comment by ryancox** [comment]
The deployer would do that... It would be a totally separate concern.

**Comment by michalpristas** [comment]
@ryancox  can we close this as a dup of #10

**Comment by ryancox** [comment]
Duplicate of #10
