### ISSUE TITLE
`make test` doesn't run tests in ./pkg

### ISSUE THREAD

**Issue by arschles** [gomods/athens#317]
There's a lot of logic in there, and `make test` should run it. It will need to set some environment variables

**Comment by vagruchi** [comment]
Hi. Does somebody work on it? I'm interested in.

**Comment by robjloranger** [comment]
Please go ahead @vagruchi, let us know in slack if you run into problems. We are usually quicker to answer questions there.

**Comment by robjloranger** [comment]
@vagruchi are you still interested in working on this?

**Comment by sauvaget** [comment]
If not, I would give it a go

**Comment by vagruchi** [comment]
Sorry. I unexpectedly busy. 
@sauvaget feel free to take it.
