### ISSUE TITLE
Make disk refs clean up their entire gopath

### ISSUE THREAD

**Issue by arschles** [gomods/athens#318]
After https://github.com/gomods/athens/pull/291, there will be a `diskRef` type that implements `(./pkg/module).Ref`. These `diskRef` types are intended to read a mod, zip and info from disk into memory and return them to the caller. They're also used to clean those files up but they don't do so completely. This issue is for making their `Clean` method able to clean up the entire path that they own

**Comment by rchakra3** [comment]
I'd like to work on this!

**Comment by marwan-at-work** [comment]
I believe this is fixed.
