### ISSUE TITLE
Proposal: hosting docs

### ISSUE THREAD

**Issue by arschles** [gomods/athens#33]
Proxies will host multiple versions of a module, and I think it would be very helpful to the community for proxies to also host documentation for each version. This is similar to what godoc.org or the `godoc` CLI does, except docs would be versioned. I could also imagine this being great for private code 😄

**Comment by bketelsen** [comment]
interesting idea

**Comment by arschles** [comment]
Hopefully this will be solved by the open sourcing of `pkg.go.dev` (#1546). [moddoc](https://github.com/marwan-at-work/moddoc) is an option too.

Regardless, I am going to close this because I'd like to keep a doc server out of the core Athens codebase
