### ISSUE TITLE
Proposal: get rid of the storage.Connector

### ISSUE THREAD

**Issue by arschles** [gomods/athens#330]
I'm not sure about this one. Do we need a separate `Connect()` function, or is it ok to connect automatically when we create a new `Saver`, `Lister`, etc...?

**Comment by robjloranger** [comment]
I like just connecting on creation, this gives the caller a ready to use `Saver` etc

**Comment by kteb** [comment]
I'll work on this one.

**Comment by michalpristas** [comment]
Closing #457  is in
