### ISSUE TITLE
Remove tracing spans added to handlers

### ISSUE THREAD

**Issue by robjloranger** [gomods/athens#339]
I want to verify with @bketelsen before moving on this.

The documentation for buffet say's that the buffalo middleware handles instrumenting tracing spans in the handlers. If that is the case we should remove the added spans. They were however added by Brian so I am confused :smile: Lets discuss.

ref: https://github.com/bketelsen/buffet#usage

**Comment by bketelsen** [comment]
You should add child spans when you want visibility into the child function.  If you don't add a new span, you'll see the parent span with timing, logs, etc for the whole execution.  If you add children, you'll get visibility into each called function.

**Comment by arschles** [comment]
I think we should add to child functions wherever possible. We're going to have this code running in the wild in lots of different contexts (no pun intended 😆) so the more visibility the better

**Comment by robjloranger** [comment]
I talked with Brian in slack and he cleared it up. Because we are calling functions to return our handlers the span and operation has to be manually set.
