### ISSUE TITLE
Convenience package to wrap tracing & logging (and metrics?)

### ISSUE THREAD

**Issue by arschles** [gomods/athens#348]
@bketelsen @manugupt1 @carolynvs @Kunde21 @marwan-at-work and I discussed today building something that can combine our logger and opentracing (and https://github.com/bketelsen/buffet)

Maybe something similar to https://github.com/bketelsen/trace

**Comment by carolynvs** [comment]
`allthethings.doit()`

**Comment by arschles** [comment]
Ref #392

**Comment by arschles** [comment]
We are using opencensus now, and have merged our error handling with logging. So far, this seems to be working fine. I'm going to close this now.
