### ISSUE TITLE
Security sections in the design documents

### ISSUE THREAD

**Issue by andybons** [gomods/athens#351]
There don’t appear to be sections for security (threat models, mitigation, etc.) in the design documents (https://github.com/gomods/athens/blob/master/REGISTRY.md and https://github.com/gomods/athens/blob/master/PROXY.md).

I heard from @carolynvs that @erikstmartin has been thinking extensively about this. It would be great to get those thoughts “down on paper” and in the public domain.

Thank you!

**Comment by arschles** [comment]
Thanks for bringing this up @andybons. You are absolutely right, we have only talked in very high level terms on video chats that were completely not in the public domain, and we need to get those thoughts down on paper.

Until we can get some precise language down, here's a really rough summary of what I remember we've talked about. None of this is final and I might have forgotten things or plain gotten them wrong. Super helpful, right 😆? Anyway, here's a start:

- We need a way for a package author to sign and verify ownership
- ^^ is probably going to be especially useful for package provenance
- We need secure (authenticated and authorized) communication between official registry hosts
- Part of the cloud <=> cloud registry protocol needs to include module hashes/signatures (both?)
    - We might need to communicate `go.mod` signatures as well as entire module signatures, just like the `go.sum` includes individual `go.mod` hashes as well as entire package hashes.
    - I forgot off the top of my head exactly why the `go.sum` does this but I think the `go.mod` hash is used to determine when transitive dependencies change and the entire module hash is used for module changes
- We need the registry as a whole to be something like a certificate authority, and the go toolchain to embed its root key(s)
- We need to let people override the root keys in the go toolchain to approximately allow self-signed certs
    - ^^ is most likely especially useful in corporate environments that run proxies

**Comment by empijei** [comment]
Since you talked about the fact that there is going to be some sort of public key infrastructure, I was wondering if there will be anything to allow for key revocation and key expiration.

**Comment by arschles** [comment]
Note that as of #772, we're not going to try and build a registry for the time being. I'm leaving this issue open because security is still an open discussion for the proxy.

**Comment by arschles** [comment]
also @empijei I don't know of anything that will allow for key revocation / expiration right now, but design hasn't moved much since the OP

**Comment by empijei** [comment]
Shouldn't this be labeled as "security"?

**Comment by arschles** [comment]
@empijei yep, you're right - I've labeled it with security, thank you!

I'm going to close this issue now, primarily because we're not designing or intending to build a registry-like system. We can revisit the security model for intra-organizational use cases if needed later
