### ISSUE TITLE
Add end-to-end test for the proxy to CI

### ISSUE THREAD

**Issue by arschles** [gomods/athens#353]
Now that #290 is done, a `GOPROXY=proxyurl go get stuff` works against a running proxy. We should totally do that in our CI tests!

cc/ @carolynvs since you were interested in this

**Comment by carolynvs** [comment]
As part of this I'm going to submit some extra PRs to "de-travisify" so that people can use make or call bash scripts directly to check everything locally, instead of having to copy/pasta from the `.travis` file.

**Comment by arschles** [comment]
👍👍👍👍❤️❤️❤️❤️
