### ISSUE TITLE
Make the zip's io.ReadCloser delete the entire goPath

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#355]
Currently the buffalo handlers don't know anything about disks and refs as they are low level implementations of getting modules. However, we need a way to ensure things are cleaned up once a module is fully used. 

Therefore when `diskRef` returns a *storage.Version, we should have the io.ReadCloser of its zip be able to delete the entire temp gopath since there's practically no need for that path once the client downloads the zip, all other fields are in memory so we're good.

**Comment by rchakra3** [comment]
Does this mean the expected behavior would be:
```
ref := fetcher.Fetch(..)
ref.zip.Read()
ref.zip.Close()
```
I thought the expectation was that the caller calls ref.Clear() ? Something like:
```
ref := fetcher.Fetch(..)
ref.zip.Read()
ref.zip.Close()
ref.Clear()
```

Which would actually delete everything on disk

**Comment by rchakra3** [comment]
Gotcha, that makes sense. 
I just went through the various calls and I personally think it would be cleaner to remove Clear from the Ref interface and let zip.Close() handle cleanup. 

The alternative would be that we read the zip file into memory and pass that around (which is mentioned in the comments for diskref) - that way the flow would be to call `ref.Clear()` right after `ref.Read()`. That would be nice to have but could possibly end up using large amounts of memory

**Comment by marwan-at-work** [comment]
@rchakra3 yes with the alternative we would run out of memory very fast. Feel free to remove the Clear method from the interface definition. Thank you!

**Comment by arschles** [comment]
All good with me. Can you add really good docs (with code samples hopefully
😊) that explain how to clean up? Thank you thank you!
