### ISSUE TITLE
Check "go" exists in your path before running server

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#372]
We should have gogetfetcher.New() stat the goBinPath and returns an error if go cannot be found.

**Comment by devdinu** [comment]
I can pick this up. `(gg *goget) Version()` would this return a custom error when called?

**Comment by marwan-at-work** [comment]
@devdinu if `goget.New` returns an error, then we should just `log.Fatal` and the app wouldn't even start in the first place for Version or List to work.
