### ISSUE TITLE
PR Review Requirements

### ISSUE THREAD

**Issue by arschles** [gomods/athens#386]
We should have a document that describes what we expect from PR reviewers and how we do PR reviews. Ideas:

- At least one review before a PR is merged (we do this already)
- CI run against the PR that is even with tip of master
- codeowners file (we haven't done this yet. we can integrate with minimum number of reviews)

Others?

**Comment by robjloranger** [comment]
Partial reference conversion started in slack around here https://gophers.slack.com/archives/C9LRAQN8N/p1533660895000065

**Comment by arschles** [comment]
We already have GitHub enforcing rules for us, closing
