### ISSUE TITLE
Create FAQ, Guidelines For Athens

### ISSUE THREAD

**Issue by devdinu** [gomods/athens#390]
We could use go [FAQ](https://golang.org/doc/faq) as a reference.

1. What's the purpose of the project, what does it solve.
2. Architectural Decisions (this could be separate too)
3. Conventions for code PR's [Effective Go](https://golang.org/doc/effective_go.html) helps at high level, this is very customised 
- For each package
- the way we pull out interfaces
- errors, logging, tracing
- benchmark 

The faq is helpful for newcomer to understand, and the guidelines will help folks to create a better PR with less conversation, and making review effective.

**Comment by michalpristas** [comment]
I will prepare something.
Im just going to poll a survey here: about architectural decisions, what format do you prefer?

I was thinking about some overview of current state followed by Decision log - explaining how we got there in form of short tweets (?), so it's clear what was rejected on the way
@arschles @bketelsen @robjloranger @devdinu

**Comment by michalpristas** [comment]
How is it with associating logs with spans in opentracing

**Comment by robjloranger** [comment]
I like this @michalpristas, starting with overview of the current state. How we ended up there.

**Comment by arschles** [comment]
@michalpristas for current state and architectural decisions, do you think that [REGISTRY.md](./REGISTRY.md) and [PROXY.md](./PROXY.md) can be updated?

**Comment by michalpristas** [comment]
yes i was planning to draw some communication diagrams, more detailed models maybe
+ history what we've been through ever since 3-phase-commit model

**Comment by michalpristas** [comment]
@robjloranger FAQ and WALKTHROUGH are done right. can we close

**Comment by arschles** [comment]
@devdinu given what you see on https://docs.gomods.io, do you think everything you were asking for is written down clearly?

**Comment by manugupt1** [comment]
Closing this as we have FAQs and walkthrough now
