### ISSUE TITLE
Create Twitter Account

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#391]
Because all official things have a twitter account. 

Name suggestions welcome: `@athensproj`, `@athensproject`, `@goathens`, `@athensproxy`

**Comment by michalpristas** [comment]
i'm for goathens

**Comment by arschles** [comment]
+1 for goathens - it matches gobuffalo. I’ll take care of this

**Comment by robjloranger** [comment]
Goathens is taken already too https://twitter.com/goathens?s=09

**Comment by arschles** [comment]
😢

**Comment by arschles** [comment]
How about `@gomodsio` or `@athensapp`? Both are available

**Comment by michalpristas** [comment]
gomods 👍

**Comment by robjloranger** [comment]
Yes to `gomods` or `gomodsio`

**Comment by bketelsen** [comment]
I thought I got gomods already

**Comment by bketelsen** [comment]
edit: Nope

**Comment by bketelsen** [comment]
gomodsio is my vote

**Comment by arschles** [comment]
Ok, vote here for `gomodsio`

**Comment by arschles** [comment]
And vote here for `athensapp`

**Comment by arschles** [comment]
Done!

https://twitter.com/gomodsio

🎉 😄
