### ISSUE TITLE
Proxy use-case for offline, secure development environments

### ISSUE THREAD

**Issue by nicknezis** [gomods/athens#395]
Will the proxy support the use case in which Go development happens in a totally offline environment? An enterprise could setup a process to manually sync modules to the offline repo in which an instance of the proxy is able to serve up the modules to internal Go developers.

**Comment by arschles** [comment]
The proxy can work completely behind a firewall, without access to the
public internet. The current limitation in that case is that it can only
serve modules that exist in another internal proxy, or a vcs.

We don’t currently have functionality to “manually” sync - other than
exposing the proxy to the public internet and running a bunch of “go get”
commands against it.

Can you give some more details on what you’re trying to do?

**Comment by nicknezis** [comment]
@marpio Yes I believe I'm good for now. Thanks.
