### ISSUE TITLE
Split backend's storage.Getter interface

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#396]
I'd like to get up/down votes to get a sense of what's preferred: 

Should we split the backend's storage.Getter interface into three independent methods? 

Currently this is the interface: 

```golang
type Getter interface {
	Get(ctx context.Context, module, vsn string) (*Version, error)
}
```

Should we make it like this: 

```golang
type Getter interface {
	Info(ctx context.Context, module, vsn string) ([]byte, error)
	GoMod(ctx context.Context, module, vsn string) ([]byte, error)
	Zip(ctx context.Context, module, vsn string) (io.ReadCloser, error)
}
```

### Motivation: 
1. `cmd/go` never asks for all three files at the same time, so why load them up? 
2. We have to be very careful when to close and when *not* to close a zip reader. This can easily introduce memory/disk leaks.

**Comment by arschles** [comment]
Big ups from me for this. Your point about having to be careful to close the zip really resonates with me.
