### ISSUE TITLE
some scripts are not portable

### ISSUE THREAD

**Issue by fhs** [gomods/athens#397]
Few issues with `get_buffalo.sh`:
* It uses `$TMPDIR`, which is not always set in Linux
* It downloads Linux binary only
* It doesn't clean up temporary directory after it's done
* Maybe it should be updated to use 0.12.4 instead of 0.12.3? It seem like extra maintenance keeping the version up to date when one can just `get get` the latest.

**Comment by arschles** [comment]
@fhs would you be up for cleaning the script up?

**Comment by fhs** [comment]
> @fhs would you be up for cleaning the script up?

Looks like robjloranger has started the work (PR #410).

It seems that these scripts were expected to be run in travis. The main issue is that `CONTRIBUTING.md` and `DEVELOPMENT.md` asks the reader to run `make setup-dev-env`. So, either the docs need to be updated or the scripts need to become portable.

**Comment by robjloranger** [comment]
I'm pretty sure this is fixed, between the buffalo script changes, temp directory fix and power shell scripts.
