### ISSUE TITLE
Remove Lister from storage.Backend

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#402]
/@v/list goes directly to upstream. Is there a reason not to remove it from the backend.Storage interface?

**Comment by arschles** [comment]
I think it's useful to keep for debugging purposes - I could see us [building a UI](https://github.com/gomods/athens/issues/360) for the proxy and/or registry that lists the modules/versions we have for example

**Comment by michalpristas** [comment]
true that @arschles i used that as well for verification, does not harm anything to keep it here

**Comment by marwan-at-work** [comment]
@arschles nice yeah that totally makes sense. Closing the issue :)

**Comment by robjloranger** [comment]
Good point, let's hang on to it for now
