### ISSUE TITLE
e2e test: buffalo dev doesn't like GO111MODULE=on

### ISSUE THREAD

**Issue by robjloranger** [gomods/athens#412]
For some reason the check for http status code in our e2e test script never succeeds if we set `GO111MODULE` to `on` _before_ we run buffalo dev.

If set after the script runs fine.

**Comment by robjloranger** [comment]
ref: https://github.com/gobuffalo/buffalo/issues/1075

**Comment by michalpristas** [comment]
👍

**Comment by arschles** [comment]
@robjloranger now that gobuffalo/buffalo#1075 is closed, is this still a bug?

**Comment by robjloranger** [comment]
I can test this evening

**Comment by robjloranger** [comment]
I can't reproduce this anymore. I don't even see us using `buffalo dev` anywhere in our scripts so not sure where I got this from.

### From tip of master w/ GO111MODULE=on
## Steps Tried w/ Buffalo v0.12.7
- ran `buffalo dev` from `cmd/proxy`
- ran make targets for `test`, `test-unit`, `test-e2e` and `build`
## w/ Buffalo v0.12.6 (current version we are using)
- ran `make test test-unit test-e2e build`
- ran `buffalo dev` from `cmd/proxy`

**Comment by robjloranger** [comment]
I'll call it resolved by magic and we can open a new ticket if it resurfaces.
