### ISSUE TITLE
Update development docs

### ISSUE THREAD

**Issue by robjloranger** [gomods/athens#413]
The CI tests are now using `go1.11beta3`, we should update our docs to let developers know they are expected to have the same version installed.

I used the following to install:
```console
go get golang.org/dl/go1.11beta3
go1.11beta3 download
```
Then when working on the project, set an alias at the start of a session:
```fish
# fish alias
alias go go1.11beta3
```
```bash
# bash alias
alias go="go1.11beta3"
```

**Comment by robjloranger** [comment]
I'm usually strongly against it. Requiring anything unusual to be installed. In this case though, as we require the behaviour of this version, it might be necessary. And temporary, 1.11 stable should be out soon.

**Comment by robjloranger** [comment]
As well the method above is trivial if go is installed. It can be removed really really when no longer needed, and the alias is session only.

**Comment by manugupt1** [comment]
I really like this! I was tripped up for a while that I can use go1.10 on athens since everything was in shell scripts! If it is a go ahead, I can put it in the docs!
