### ISSUE TITLE
Remove olympus package from pkg/storage

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#414]
From https://github.com/gomods/athens/issues/309 and https://github.com/gomods/athens/issues/349, it looks like we're never gonna use Olympus as a storage backend to Proxy. We either *redirect* to Olympus, or use it as a download.Protocol interface in which case we save to storage first then stream back from storage.

**Comment by VineethReddy02** [comment]
I would like to work on this. How should i get onto this ?

**Comment by michalpristas** [comment]
@VineethReddy02 
there is a package `/pkg/storage/olympus` which needs to be removed
then in each storage generation you need to revisit switch cases and remove olympus case together with any other olympus storage reference. build (or go vet ./...) will fail so it will be easy

**Comment by adyach** [comment]
@VineethReddy02 are you still on that? if not I would like to grab it

**Comment by adyach** [comment]
sorry it was already addressed in https://github.com/gomods/athens/pull/513
