### ISSUE TITLE
MVP: should the Proxy store Olympus modules or just Redirect?

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#416]
1. This is just an MVP question, not long term solution.
2. It's agreed upon that it's a desired feature to be able to duplicate modules from Olympus to Proxy. 

The question is: in the MVP implementation of Athens, should we store Olympus modules into the Proxy storage? Or should we *just* have the Proxy *redirect* cmd/go to `Olympus/CDN`? The latter is easier to implement because it can just be a Buffalo middleware as is being implemented here: https://github.com/gomods/athens/issues/309

I am asking this because this affects the work being done in 309 as well as https://github.com/gomods/athens/issues/349

We should have a strategy for all of this so that our contributor folks are not confused :)

**Comment by arschles** [comment]
We discussed two options in the Aug 9, 2018 meeting, so let's vote on there in here:

**Comment by arschles** [comment]
Vote here if you'd like the proxy to always redirect to Olympus and never store in its cache

**Comment by arschles** [comment]
Vote here if you'd like the proxy to redirect to Olympus and fill its cache in the background. This would mean that future `go get` calls to the proxy (for the same module) would be read out of the cache

**Comment by robjloranger** [comment]
I think MVP could just redirect. We can always add caching to the proxy as a feature down the road.

**Comment by arschles** [comment]
We decided to always redirect (https://github.com/gomods/athens/issues/416#issuecomment-411861110). Note that if you "exclude" everything in the proxy, it will work as if there is no upstream, never redirect, and always download/store modules from the VCS

**Comment by arschles** [comment]
I've created https://github.com/gomods/athens/issues/495 to track the work to do redirects and I'm gonna close this now. Thanks everyone for voting!! ❤️
