### ISSUE TITLE
Specify go binary as an env var and use it when provided for pkg/module/go_get_fetcher

### ISSUE THREAD

**Issue by manugupt1** [gomods/athens#417]
Currently, 

https://github.com/gomods/athens/blob/master/pkg/module/go_get_fetcher.go#L22-L31 defaults to `go`

A user who has multiple installations of go should be able to specify
a `GO_BIN_PATH` and we should be able to use it directly. If it is not present, it should default to `go` and if a `go` installation is not present it, it should error out.

`GoBinPath` is mentioned in https://github.com/gomods/athens/issues/284

**Comment by rchakra3** [comment]
@manugupt1 is this different from the `GO_BINARY_PATH` environment variable?

**Comment by manugupt1** [comment]
@rchakra3 Nope! I just realized that it is the same. 

I think we can close this off. However, I have also updated the docs to reflect the same in the PR.
https://github.com/gomods/athens/pull/418
