### ISSUE TITLE
Build background workers to allow the proxy to fetch source code

### ISSUE THREAD

**Issue by arschles** [gomods/athens#42]
When a package is requested by the proxy, it should check if the module is in storage. If it is not, then it should respond with a 404 and kick off a fetch operation in the background

**Comment by arschles** [comment]
Architecturally, here's how I think this should work:

- We use the buffalo [background workers api](https://gobuffalo.io/en/docs/workers) to submit background jobs
    - It is pluggable, with an in-memory and a gocraft/work (redis) implementation
    - We can build more if necessary
- We build one or more [grift](https://gobuffalo.io/en/docs/tasks)s to consume the queue as necessary

cc/ @michalpristas

**Comment by michalpristas** [comment]
this is done closing
