### ISSUE TITLE
Write up helm charts for the proxy

### ISSUE THREAD

**Issue by arschles** [gomods/athens#421]
For those not familiar with [helm](https://helm.sh), it's a tool that lets you package up a bunch of [Kubernetes](https://kubernetes.io) resources so that you can deploy your application all at once to Kubernetes. The package is called a "chart".

I'm planning on deploying the proxy to a Kubernetes cluster, and intending to use Helm to do it, so we should have the chart in this repo! 

I'll take this one on 😄

**Comment by berndverst** [comment]
Depends on #81

**Comment by marpio** [comment]
@arschles I'm closing it since #547 is merged.
