### ISSUE TITLE
pkg/module: switch from go get to go mod download

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#425]
`go get` attempts to traverse all dependencies and downloads them and so 
1. it blows up in certain cases where a dependency has a build error. 
2. it's slow because you don't need to download all deps from the Proxy perspective, nor do you need to compile anything. 

Once CL 128355 goes in (or a new beta is released), we should switch `go mod download`. We should also look into the error field in the struct it returns to see if we can better use error handling in our fetcher.

**Comment by michalpristas** [comment]
good catch @marwan-at-work
