### ISSUE TITLE
Have storage.Checker's Exists method return an error

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#427]
The storage.Exists method makes a remote call to the backend to see if a module exists. Things could fail in different ways so that we need to be able to say "we're not sure if this exists or not because there's an error in storage right now".

**Comment by adyach** [comment]
@marwan-at-work did I understand correct, that we want to change Checker interface to
`Exists(ctx context.Context, module, version string) (bool, error)` ?

**Comment by marwan-at-work** [comment]
@adyach yes. This function illustrates why we need the error https://github.com/gomods/athens/blob/master/pkg/storage/gcp/bucket_cloud.go#L59

**Comment by adyach** [comment]
Can I grab it for work?

**Comment by marwan-at-work** [comment]
@adyach it's yours :)
