### ISSUE TITLE
Include scripts for windows

### ISSUE THREAD

**Issue by robjloranger** [gomods/athens#429]
continuing from: https://github.com/gomods/athens/pull/415#issuecomment-410953621

We should add batch or powershell scripts for windows users.

Can we have make select the script based on OS?

**Comment by marpio** [comment]
I will take this one. 
Not sure about the `make` selecting the script @robjloranger since make is not available on Windows without an effort.

**Comment by robjloranger** [comment]
awesome, we could look at something like [task](https://github.com/go-task/task) in the future. But just having the scripts available will be great.

**Comment by michalpristas** [comment]
on hold in favor of #486

**Comment by marpio** [comment]
#486 has been closed - removing 'on hold'
