### ISSUE TITLE
Project GH short description

### ISSUE THREAD

**Issue by robjloranger** [gomods/athens#431]
Currently the short description of our project is `A distributed proxy server for Go`.

This should probably better reflect the project's actual purpose and function. It's not just a proxy, the proxy is an extra tool we provide. The big fish is the registry. But it's not actually a registry, more of an immutable repository that is globally distributed.

**Comment by arschles** [comment]
@robjloranger we can use "Globally distributed proxy" in place of "registry"

**Comment by robjloranger** [comment]
Athens: `A globally distributed module cache and proxy`

**Comment by arschles** [comment]
Sounds good to me!

**Comment by arschles** [comment]
Err, actually we're not really globally distributed yet, so how about `A Golang module cache and proxy`?

**Comment by robjloranger** [comment]
Very true. `A Go module cache and proxy` or `Golang` I prefer `Go` but that's me.

**Comment by robjloranger** [comment]
After we _are_ distributed we can call it `The globally distributed..`

**Comment by arschles** [comment]
@robjloranger I'm good with the one you said - `A Go module cache and proxy`. Mind changing it when you get a chance?

**Comment by robjloranger** [comment]
done
