### ISSUE TITLE
Document the process for earning commit bit

### ISSUE THREAD

**Issue by carolynvs** [gomods/athens#439]
Let's chat here about how people can work towards becoming a regular contributor and eventually someone who can merge pull requests.

**Comment by arschles** [comment]
@carolynvs I wrote a very rough draft in #444 - looking forward to comments!

**Comment by robjloranger** [comment]
Can we close this with #444?

**Comment by michalpristas** [comment]
@carolynvs

**Comment by arschles** [comment]
Yes, I think #444 closes this. Here is the page that describes community roles and how to earn the commit bit: https://docs.gomods.io/contributing/community/participating/
