### ISSUE TITLE
Make the GoGet middleware configurable

### ISSUE THREAD

**Issue by arschles** [gomods/athens#44]
You should be able to configure it to redirect to any DNS name or IP - including the proxy IP/name, if running in proxy mode. Right now, it's hard-coded to `gomods.io`

**Comment by bketelsen** [comment]
I have some thoughts here, I need to formalize, I think there's more to this.

**Comment by arschles** [comment]
Continuing conversation on slack, @bketelsen you formalized all (we think) of the possible CLI workflows (copied to [here](https://github.com/gomods/athens/wiki/CLI-Workflows)). The question that remains is whether 2.i will cause `vgo` to hit the `http://athensproxywhatever//githublcim/bketelsen/captainhook/@v/...` endpoints directly, or still go through the `?go-get=1` flow

**Comment by bketelsen** [comment]
here's the code from vgo:
```
func (p *proxyRepo) Versions(prefix string) ([]string, error) {
	var data []byte
	err := web.Get(p.url+"/@v/list", web.ReadAllBody(&data))
	if err != nil {
		return nil, err
	}
```

**Comment by arschles** [comment]
thanks @bketelsen - confirms my understanding too. reading the code cemented it too - good idea :)

the GoGet middleware still needs to be configurable for registry use, but not for proxy usage
