### ISSUE TITLE
Proposal: Set up Issue and PR templates?

### ISSUE THREAD

**Issue by arschles** [gomods/athens#442]
[Here](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/) is a description of what these templates do. I think if we do them, we should keep them basic at first to learn what kinds of things we should put in them.

What do folks think? Do we need them/should we try them?

**Comment by robjloranger** [comment]
I like them, I think some contributors look for them before trying to contribute. As well as we grow we may decide there are more specific things we require in either.

I think PRs should always proceed an issue, I know I'm bad for this too sometimes. So each issue or bug can be discussed before work begins. This will help avoid people wasting time working a solution we may not need.

re: issue template I'm wondering about having two. One for bugs and one for features or proposals. For example in a bug issue we would like to know the system/deployment specifics, what was expected and what happened. With feature or proposal we might just want the overview, why the author wants it or thinks we need it and then maybe any more verbose details.

**Comment by michalpristas** [comment]
I like Problem-Solution-Fixes (with issue linked) combination.
I've seen sections on 'how this was tested' but I think that at this point ^ 3 things is enough for now
