### ISSUE TITLE
Add documentation on the code review process

### ISSUE THREAD

**Issue by arschles** [gomods/athens#467]
Goal is so that reviewers know the things that need to happen before a merge can happen (i.e. "the road to merge") and so that contributors know what to expect after they submit their PR

- How many reviewers are required (right now we've configured GH to require at least 1)
- CI/CD must pass
- Codeowners file (ref https://github.com/gomods/athens/issues/466)
- Must be up to date with master

**Comment by robjloranger** [comment]
ref: #386

**Comment by robjloranger** [comment]
No force pushes please :grin:

Someone correct me but I think a rebase requires a force push after.

This would be _after_ the pull request has started, any reorganizing of the branch history _before_ pushing is fine but changes to the history that has been pushed cause issues with the GH UI for changes.
