### ISSUE TITLE
Serve public requests using the local storage of the proxy

### ISSUE THREAD

**Issue by fedepaol** [gomods/athens#471]
With https://github.com/gomods/athens/pull/456 requests for public (as in non filtered, non private) modules are redirected to olympus (see https://github.com/gomods/athens/pull/456/files/41a50de690a15ad25492c09c500c595e76cfbfbb#diff-581919e80b55b72ad097364f147d4dd1R44 )

To make use of the local storage, the proxy should : 
- redirect only if the storage does not contain the module requested 
- spin up a worker to fill the storage

If the storage contains the module requested, it should be used to serve the request instead of redirecting to olympus

That _could_ be done by implementing a custom protocol https://github.com/gomods/athens/blob/master/pkg/download/download.go#L13-L31

and maybe leveraging the `fillCache` function https://github.com/gomods/athens/blob/master/pkg/download/download.go#L49-L64

**Comment by michalpristas** [comment]
Closing in favor of #474
