### ISSUE TITLE
What should the public/include filter be called?

### ISSUE THREAD

**Issue by arschles** [gomods/athens#473]
Follow-up on https://github.com/gomods/athens/pull/456/files#r209554785

Right now, it's called `Include` in the code. If we are planning to keep it that way, we can close this.

cc/ @marpio @michalpristas since you were in that discussion

**Comment by michalpristas** [comment]
To sum up discussion: my mind settled on
- Include
- Exclude 
- Direct

so it is easily readable
`+ github/a/b` as Include a/b
`- github/a/b` as Exclude a/b
`P github/a/b` as Directly download a/b 

the other idea was to have it as
- Public - will always download
- Private  - will treat as private
- Exclude - does not download

**Comment by marpio** [comment]
I like `Direct` as well, it makes the difference between those two more clear.
