### ISSUE TITLE
Tidy up Makefile

### ISSUE THREAD

**Issue by robjloranger** [gomods/athens#476]
continuing my verbose response for #452  https://github.com/gomods/athens/issues/452#issuecomment-412725709

---

The Makefile should not call the target `dev` during `setup-dev-env`, it is insufficient for running unit tests or buffalo tests. <strike>The target `dev` is not used anywhere, so could be removed.</strike> see: https://github.com/gomods/athens/issues/476#issuecomment-412730391

The target `down` is identical to `dev-teardown`, since `dev-teardown` is analogous to `dev` I propose we remove `down`, rename `alldeps` to `dev` and update docs to reflect.

https://github.com/gomods/athens/blob/5a445aacf8bafc32bb40d9245121979ad8059a6e/Makefile#L15-L17
https://github.com/gomods/athens/blob/5a445aacf8bafc32bb40d9245121979ad8059a6e/Makefile#L69-L71
https://github.com/gomods/athens/blob/5a445aacf8bafc32bb40d9245121979ad8059a6e/Makefile#L74-L76

**Comment by robjloranger** [comment]
I lied, the target `dev` is sufficient for running the e2e tests only. I still feel we could drop it in favor of `alldeps`, which would be better renamed to `dev`.

**Comment by robjloranger** [comment]
so many thoughts: what about `make dev-install` which installs the dev deps?
and `make dev-run` that starts up the services?

**Comment by marwan-at-work** [comment]
@robjloranger I'm happy with any changes to make file, but I personally like `make dev` the way it is. This is because when working on Athens on my local machine, it's much slower to "up" `alldeps`. Upping just the minimum dependencies makes it *much* faster to iterate on the feature you're working on because you have to take them down and build them up multiple times in ~2 seconds as opposed to ~8.

**Comment by robjloranger** [comment]
My only problem is the minimum for running unit tests includes minio, which is not part of `dev`. Maybe we should just add minio? I think Aaron has something going in #487

**Comment by robjloranger** [comment]
for reference see:
https://github.com/gomods/athens/blob/cdab5c515cbe8a442a863f36819f701b359b1eac/.travis.yml#L18-L24

`make setup-dev-env` runs the `dev` target and then travis installs and runs minio before running test scripts.

**Comment by michalpristas** [comment]
Removing on hold

**Comment by natefinch** [comment]
Anyone interested in a PR to replace the makefile with Mage?

**Comment by robjloranger** [comment]
We decided against it in #486 unfortunately.

**Comment by natefinch** [comment]
Powershell? Man, y'all crazy :)

**Comment by robjloranger** [comment]
lol I know, I was excited to switch to mage

**Comment by robjloranger** [comment]
closed with #561
