### ISSUE TITLE
Proposal: use Mage?

### ISSUE THREAD

**Issue by arschles** [gomods/athens#486]
Another option besides the Makefile is [mage](https://magefile.org/). It would let us write all our targets in Go.

Looking forward to hearing thoughts?

**Comment by robjloranger** [comment]
I've never used it, can we branch logic on host OS? That would be amazing for windows users.

**Comment by michalpristas** [comment]
Docs states that 

> Mage has no dependencies (aside from go) and runs just fine on all major operating systems

We should rename this issue to: "Use Mage!"

**Comment by marpio** [comment]
I will try it out see if mage can work for us.

**Comment by bketelsen** [comment]
please no.

**Comment by michalpristas** [comment]
@bketelsen what do you say about using mage for Win and make as a standard solution for UNIX?

**Comment by marpio** [comment]
In that case I would rather go with powershell as it's installed on every Windows machine and doesn't introduce any new dependency.
We could observe how often the bash and powershell scripts get out of sync and look for a different solution i.e mage if necessary.l

**Comment by michalpristas** [comment]
Closing, we settle for PS script for windows and traditional Makefiles for unix
