### ISSUE TITLE
Use Go Cloud to Merge S3/Cloud Storage

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#489]
Go recently came out with a library that abstracts different cloud implementations under one interface: https://blog.golang.org/go-cloud

We can use this to have one storage implementation for both pkg/storage/s3 and pkg/storage/gcp, and potentially Azure, but I'm not sure. 

I haven't tried Go Cloud yet myself, so I just wanted to open an issue and see what people think.

**Comment by marpio** [comment]
This looks awesome @marwan-at-work !
It seems like azure support is underway:
https://github.com/google/go-cloud/issues/76
The only concern is that it's still in alpha.

**Comment by michalpristas** [comment]
I would wait with this one. it is 0.0.x version so it will change a lot which will put more work on us trying to stay on track, which is quite the opposite of the reason why we would consider to use this. 
Also, our use case is not that difficult, using API directly gives you faster cycles in terms of changes and improvements of API. 
So at least for now, I would stick to standard APIs, later we will see, but I don't see a reason for a switch just yet.

**Comment by marpio** [comment]
Moving to the milestone v2. We can revisit this later when go-cloud gets stable.

**Comment by marwan-at-work** [comment]
@manugupt1 per @marpio 's comment as well as @michalpristas. This is on hold until we release beta and probably v1 as well.

**Comment by arschles** [comment]
oops, sorry I suggested this @manugupt1! I forgot that we were holding off on this until go-cloud becomes more stable. ping me on slack if you want more help finding a good issue to work on

**Comment by arschles** [comment]
Looks like go-cloud is `v0.19.0` at the moment, so I'm going to close this. If someone wants us to pursue moving over, I'm cool with it. I just didn't want to have this issue hanging around for more years 😉
