### ISSUE TITLE
Can we remove NewRDBMSStorageWithConn?

### ISSUE THREAD

**Issue by arschles** [gomods/athens#491]
Continuation of https://github.com/gomods/athens/pull/457/files#r210026175

cc/ @kteb

**Comment by michalpristas** [comment]
This was added so tests can inject conn, let's get rid of this

**Comment by manugupt1** [comment]
Once we remove RDBMS storage, this is no longer necessary
https://github.com/gomods/athens/issues/494

**Comment by marpio** [comment]
Closing. Will be taken care of in #494
