### ISSUE TITLE
Make the proxy redirect to an upstream download protocol (i.e. Olympus) with HTTP 301s

### ISSUE THREAD

**Issue by arschles** [gomods/athens#495]
We voted in https://github.com/gomods/athens/issues/423#issuecomment-411862230 to make the proxy issue HTTP 301 redirects to the CLI when the proxy datastore doesn't have the given module@version.

_Note that we're going to do this for our first released version_. We can add local caching/storage after that.

**Comment by arschles** [comment]
Also, this means that if you make the proxy "exclude" all modules in its exclude list, then it will act as if there is no upstream, fetch everything from the VCS (using `go get` on the backend), and store it all in its datastore.

**Comment by marwan-at-work** [comment]
@arschles did you mean "include" all modules? "excluding" all modules would return status forbidden.

**Comment by michalpristas** [comment]
exclude should break the communication.
Include goes upstream (whatever it is, for proxy its olympus, for olympus it's VCS)
direct goes to VCS without caring about upstream

**Comment by fedepaol** [comment]
Can I take this one?

**Comment by michalpristas** [comment]
This was discussed as post-MVP but sure @fedepaol

**Comment by michalpristas** [comment]
@marwan-at-work you self-assigned this few days ago, are you ok with @fedepaol working on this?

**Comment by marwan-at-work** [comment]
This is already done through the filter middleware and the global switch. Will close the issue and open a new one for cache filling.
