### ISSUE TITLE
Proposal: have someone "triage" issues each week?

### ISSUE THREAD

**Issue by arschles** [gomods/athens#506]
I saw that the Helm project has a ["triager"](https://github.com/helm/helm/blob/master/CONTRIBUTING.md#the-triager) who goes through issues and PRs each week. If we did something like this in Athens, the triager might add labels to issues / PRs, prompt discussions in threads if they are "stale", maybe start votes for issues that have concrete options, and maybe some other things?

What do people think about the idea of having a triager?

**Comment by robjloranger** [comment]
I do, I was trying to do this periodically.

**Comment by carolynvs** [comment]
I love this idea!

**Comment by manugupt1** [comment]
Love this! Triaging can be good first issues also!

**Comment by michalpristas** [comment]
❤️ this idea, we should also include this in #444

**Comment by marpio** [comment]
:+1:

**Comment by michalpristas** [comment]
Related to triage, i really like how Helm, and probably others, use labels for PRs.
While having WIP in a title is nice, it is a bummer to filter on top of that.
So maybe as part of the triager routing, person can go through PRs, and assign following labels (stolen from Helm):

awaiting review | The PR has been triaged and is ready for someone to review
in progress | Indicates that a maintainer is looking at the PR, even if no review has been posted yet

on top of that, we have 1on-hold1 and `blocked`

So it would look like this:
Contributor opens a PR and adds in-progress if it is a wip
Once it's not a wip, contributor adds `awaiting review`
Community reviews and if any changes are requested, the status will be switched to `in-progress`
Once the contributor addresses the comments, cycle repeats

**Comment by robjloranger** [comment]
I love that idea @michalpristas
