### ISSUE TITLE
Cleanup the CSS for our docs code blocks

### ISSUE THREAD

**Issue by carolynvs** [gomods/athens#510]
The CSS for our inline code blocks always includes a copy button, which isn't helpful

![screen shot 2018-08-17 at 5 29 46 pm](https://user-images.githubusercontent.com/1368985/44291338-4e010b80-a243-11e8-9d10-57e294c3f2bc.png)

The most common case when we inline code something is that we are referring to a command, or an environment variable, but aren't telling people to run that code. Runnable code is almost always in a full code block, and even then we often include output of the commands, so a copy/paste button is probably not as helpful as we'd like.

I suggest that we just remove the copy/paste icon/button behavior from all our docs codeblocks for now.

**Comment by robjloranger** [comment]
I agree, copy paste is somewhat bad practice anyway. I feel like I learn more when I have to type everything in.
