### ISSUE TITLE
Ensure goget is part of tracing

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#526]
Once https://github.com/gomods/athens/issues/392 is resolved, let's ensure that concurrent go-gets are properly traced as part of the entire request. This is because the request Context is not being passed to the cacheFill/storageFill operations which is a good thing because if the user abandons a request, we want to continue doing the cacheFill/storageFill. However, I'm not sure if we want to copy values from the old context to the new one (or if OpenCensus doesn't care about CancelledContexts)

**Comment by arschles** [comment]
@manugupt1 was this done as part of https://github.com/gomods/athens/pull/604?

**Comment by marwan-at-work** [comment]
This is a follow up to 604. I can work on it.
