### ISSUE TITLE
Suggest best practices for running a proxy in production

### ISSUE THREAD

**Issue by carolynvs** [gomods/athens#534]
This will need to evolve over time, so at first it may just document how to run it and not lose data. Then we can iterate and improve it from there.

**Comment by marwan-at-work** [comment]
yeah 531 seems like a dup of this. @carolynvs should I close it or is this a little different?

**Comment by marwan-at-work** [comment]
PS. I deployed the Proxy to our GCP cluster and aggressively pushed a few prs to make it work lol. But there's still some work to be done, so let me know how I can help

**Comment by carolynvs** [comment]
oops, thanks for calling that out I didn't see 531. Closing in favor of that
