### ISSUE TITLE
Propagate Log.Entry down to all the middleware functions / handlers

### ISSUE THREAD

**Issue by fedepaol** [gomods/athens#537]
With https://github.com/gomods/athens/pull/492 and https://github.com/gomods/athens/pull/456 we have two middleware functions in addition to the type safe one implemented as `LogEntryHandler` .

Since the `log.Entry` parameters are bound to the request that traverses all the middleware functions (and the handler) it would be nice to have a way to instantiate it in the top level middleware and propagate it down to all the subsequent calls.

**Comment by arschles** [comment]
@fedepaol would you be interested in creating a small PR that propagates `log.Entry` down to one middleware function, so that we can get started on it and other folks can pick up other middlewares/handlers afterward?

**Comment by manugupt1** [comment]
@fedepaol  @marwan-at-work  @arschles Is this fixed, can we close it?

**Comment by marwan-at-work** [comment]
yep
