### ISSUE TITLE
Is it "Athens Proxy" or "Athens proxy"?

### ISSUE THREAD

**Issue by carolynvs** [gomods/athens#539]
Let's decide on a style guide for referring to the proxy and then update the docs to match, examples below:

* Athens Proxy, Proxy
* Athens Proxy, proxy
* Athens proxy, proxy

**Comment by michalpristas** [comment]
I'm for Athens proxy, proxy
as Proxy evokes something like proxy of the proxies, uber-proxy, what might sound sniffy

**Comment by carolynvs** [comment]
I also like "Athens proxy, proxy". 👍

**Comment by robjloranger** [comment]
I'm with both of you, only Athens title case. Proxy should be lower case.

**Comment by arschles** [comment]
As said in https://github.com/gomods/athens/issues/664#issuecomment-432024563, let's do "Athens proxy" with a lowercase 'p'

Closing
