### ISSUE TITLE
Support for custom CAs

### ISSUE THREAD

**Issue by michalpristas** [gomods/athens#540]
Lots of companies have their own CA, and it's not a trusted root by default. 
Let's allow them to set this CA as trusted.

**Comment by timraymond** [comment]
@michalpristas Just to clarify—is this for olympus or proxy? Also, if it's for the proxy, did you mean allowing a custom CA for the module download API (where `GOPROXY` is pointed at) ? Or did you mean upstream of the proxy? (like internal vanity URLs maybe?)

**Comment by michalpristas** [comment]
as we parked olympus let's focus on proxy.
the idea was born with PR allowing TLS for mongo #527 
we use InsecureSkipVerify = true which is not really ideal way how to treat prod, i would start with this scenario
