### ISSUE TITLE
Fix the following dep ensure warning on CI

### ISSUE THREAD

**Issue by manugupt1** [gomods/athens#552]
When you run dep ensure on travis, you get the following warning

+dep ensure -dry-run
Warning: the following project(s) have [[constraint]] stanzas in Gopkg.toml:
  ✗  github.com/pkg/errors
However, these projects are not direct dependencies of the current project:
they are not imported in any .go files, nor are they in the 'required' list in
Gopkg.toml. Dep only applies [[constraint]] rules to direct dependencies, so
these rules will have no effect.
Either import/require packages from these projects so that they become direct
dependencies, or convert each [[constraint]] to an [[override]] to enforce rules
on these projects, if they happen to be transitive dependencies.

We should fix it!

**Comment by robjloranger** [comment]
Can you point me to a PR that is experiencing this error?

It looks like you need to run dep ensure before pushing to the branch and resolve any errors there. Commit the change and then push, this should clear up the issue.

That check ensures we do not commit mismatching dep toml/lock and vendor.

**Comment by manugupt1** [comment]
If you check logs on this : https://travis-ci.org/gomods/athens/builds/418968846
You can see the warning. It is not really an error.

**Comment by marpio** [comment]
We probably don't use github.com/pkg/errors anymore and should remove this dependency.

**Comment by robjloranger** [comment]
interesting, that should actually have failed the CI. We don't want to commit changes that have not properly updated the vendored dependencies.

**Comment by manugupt1** [comment]
These are just warnings, even `dep ensure` does not fail. So, removing the package should suffice.

**Comment by robjloranger** [comment]
But the idea of the script is to fail CI under this type of circumstance. It should prevent merging something that removed the errors package. I'll investigate more tomorrow.
