### ISSUE TITLE
Host charts

### ISSUE THREAD

**Issue by robjloranger** [gomods/athens#566]
continuing the discussion from: https://github.com/gomods/athens/pull/547#discussion_r212679915

We should decide where to host our helm charts, maybe docker compose too?

@arschles suggested starting with an Azure storage container, which as @carolynvs mentioned we could then point a sub domain like `charts.gomods.io`.

**Comment by carolynvs** [comment]
Yeah, based on previous experience, it's easy for people to come on/off a project and then the project ends up needing to switch hosting providers, or scale out across more than one. So if we start off with a subdomain, we will save ourselves trouble down the road. Also this will give ourselves more options later for maybe doing something more complicated than static file hosting, like chart museum.

**Comment by arschles** [comment]
Another thing to keep in mind for the future: https://azure.microsoft.com/en-us/updates/azure-container-registry-helm-repositories-public-preview/

It's in preview now so I think we probably shouldn't use it now, however.

**Comment by chriscoffee** [comment]
Whilst we wait for the Azure hosted helm charts, we could host them on GitHub Pages with actions to release them https://medium.com/@stefanprodan/automate-helm-chart-repository-publishing-with-github-actions-and-pages-8a374ce24cf4 

Again, we'll need actions..

**Comment by carolynvs** [comment]
How can I help host charts on Azure? I can setup a bucket and a script to update the index and upload the chart and index to the bucket? @arschles Would that help?

**Comment by arschles** [comment]
@carolynvs that would be amazing! Either what you said or [ACR helm repos](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos) are the options I can see, that we don't have to pay $$ for. Totally up to do

Either way you go, I can put them under my Azure account for Athens. Let me know if/when you do this and I'll add you to the Azure resource group

**Comment by carolynvs** [comment]
If I do this as a bucket, then we can host with a cname and be able to move around later if we need to. I'm a bad MS employee but I thought that ACR was for private authenticated access only? I have time on Friday and can quickly setup the domain name and bucket approach since I've done it so many times on other projects. So I guess I vote for that?

**Comment by arschles** [comment]
I'm also a bad MS employee and don't know if you can do public chart repos with ACR chart repo!

The bucket approach sounds great to me! 🎉
