### ISSUE TITLE
Add docs on how to deploy Athens to ACI

### ISSUE THREAD

**Issue by arschles** [gomods/athens#57]
This would increase the options for folks who want to deploy Athens to the cloud

ACI docs: https://azure.microsoft.com/en-us/services/container-instances/

**Comment by arschles** [comment]
Changed title - copy/paste error in the first place

**Comment by arschles** [comment]
This would be a great way to get a quick test up and running for a proxy and/or a hosted registry (ACI has auto DNS support)

**Comment by michalpristas** [comment]
@arschles any progress here? can we consider deployment by @marstr and his team final and close this?
If so maybe the output could be blog post/docs what needs to be done to deploy Athens to ACI, any caveats...

**Comment by marstr** [comment]
@joshgav for awareness.

We haven't looked into ACI in particular, but it shouldn't be much different from all of the other "run a Container in Azure" solutions.

**Comment by arschles** [comment]
We should add docs for how to deploy Athens to ACI, but I don't think we should run an official athens instance on ACI because that overlaps with #772 

I'll update labels and title accordingly
