### ISSUE TITLE
Proposal: Use WIP(Github App) to prevent merging WIP-PRs

### ISSUE THREAD

**Issue by marpio** [gomods/athens#584]
Use https://github.com/apps/wip to prevent merge of a WIP-PR in a automated fashion.

**Comment by arschles** [comment]
![screen shot 2018-10-11 at 2 32 51 pm](https://user-images.githubusercontent.com/70865/46835301-9aa82500-cd62-11e8-8a84-d32d887e545d.png)

Done - I love this idea @marpio  🎉 ❤️
