### ISSUE TITLE
Go get returns 500 after the repository is deleted

### ISSUE THREAD

**Issue by arschles** [gomods/athens#590]
I created `github.com/arschles/throwaway1`, did a `go get` on it with `GOPROXY` set to `https://microsoftgoproxy.azurewebsites.net`, and then deleted the repository. The next `go get` returns this:

```console
arschles ~/Desktop/hellogc $ GO111MODULE=on GOPROXY=https://microsoftgoproxy.azurewebsites.net go get github.com/arschles/throwaway1@v1
go get github.com/arschles/throwaway1@v1: unexpected status (https://microsoftgoproxy.azurewebsites.net/github.com/arschles/throwaway1/@v/list): 500 Internal Server Error
```

I think this violates immutable builds? What do folks think?

**Comment by marpio** [comment]
Makes sense. We use go to get the list of versions. We should probably merge it with what we have in storage.

**Comment by arschles** [comment]
@marpio which do you think we should check first - `go` or storage?

**Comment by marpio** [comment]
Couldn't we just return a merger list from the /list endpoint?
So if storage gives us 
Mod@v1.0.0
Mod@v1.0.1
Mod@v1.0.2
and go list gives us
Mod@v1.0.0
Mod@v1.0.2
Mod@v1.0.3
Then the proxy /list endpoint would return
Mod@v1.0.0
Mod@v1.0.1
Mod@v1.0.2
Mod@v1.0.3
What do you think @arschles ?

**Comment by arschles** [comment]
I agree, that sounds good to me. If go list fails, would we just returns what storage gives?

**Comment by marpio** [comment]
Yes, and if storage finds nothing we would just propagate the go error since the module doesn't exist (or possibly was deleted from VCS before proxy ever saw it)

**Comment by arschles** [comment]
That sounds like a good plan to me. @marwan91 what do you think? I remember
you implemented that upstream go list logic?

**Comment by robjloranger** [comment]
That should definitely not be happening, Olympus should have that stored.

**Comment by marpio** [comment]
@robjloranger I think the proxy has it in it's storage but `go list -version` which we use under the hood checks only the VCS.

**Comment by marpio** [comment]
I will like to work on that if that's fine with everyone.

**Comment by marwan-at-work** [comment]
We're starting to hit a few of the downsides of using the go binary in the background: can we gracefully handle errors such as "repository deleted" vs "unexpected error". Meaning, if a repo is deleted, we should gracefully ignore that error. But if there's a true error of some kind, we should probably error out. 

The go binary doesn't return structured errors, so we're gonna have to parse the text. Here's what the go command returns when a repository is deleted: 

```
$ go list -m -versions -json github.com/pkg/fakerepo@latest
go list -m github.com/pkg/fakerepo: git ls-remote -q https://github.com/pkg/fakerepo in /Users/me/go/pkg/mod/cache/vcs/f515d433f0460174c81da03b4c26d60d540854bb3dfad2fbf0798881fe72b6c7: exit status 128:
	remote: Repository not found.
	fatal: repository 'https://github.com/pkg/fakerepo/' not found
```

**Comment by arschles** [comment]
@marwan-at-work do you think it's time we ask for structured output from the Go CLI?

**Comment by marwan-at-work** [comment]
@arschles yes that'd be nice.
