### ISSUE TITLE
Proposal: Move "participating in the athens community"

### ISSUE THREAD

**Issue by arschles** [gomods/athens#602]
I noticed that [this page](http://docs.gomods.io/intro/community-roles/) has tips on how to get involved as well as the different community member definitions.

I was thinking that it would be nice to make the "tips on how to get involved" page be basically a welcome page with links to the slack, dev meeting doc, etc...  and then have another page with the community roles.

At the GopherSource workshop and generally around GopherCon, folks had asked me how to get involved and it would have been great to be able to tell them to go to a single "getting involved" page that lists all the ways, but doesn't have extraneous information.

What do people think about this?

**Comment by robjloranger** [comment]
I think this is great, I was thinking along these lines in https://github.com/gomods/athens/pull/570#issuecomment-417901075. While trying to decide on a folder/menu structure.

If we are agreeable on moving the doc I'm happy to split out the tips section into a welcome page. Should it be the first page in the contributing section? Or somewhere closer to the homepage of the docs?

**Comment by timraymond** [comment]
Hey @arschles and @robjloranger ! I'm doing some issue gardening this evening. Do you think this issue is sufficiently resolved by https://docs.gomods.io/contributing/community/participating/ ? It seems to cover the original intents.

**Comment by arschles** [comment]
@timraymond I was just going through issues and saw how long I let this issue sit (octobox.io FTW) - sorry for that!

I definitely think that https://docs.gomods.io/contributing/community/participating/  resolves this (http://docs.gomods.io/intro/community-roles/ is gone anyway), so I'm going to close.

@robjloranger I'm going to close this, but if you still have ideas on splitting parts/all of that page out, can you open a new issue or PR for that? If you think it'll make it easier for newcomers to decide how to get involved, I'm all for it!
