### ISSUE TITLE
Proposal: Add module registry to proxy for non supported VCS

### ISSUE THREAD

**Issue by tw1nk** [gomods/athens#606]
Go only supports a small set of VCS (git, mercurial, svn...). A lot of companies (and individuals) use other VCS systems. 

My proposal is to add an endpoint that uploads a new version to the proxy / registry so that it doesn't need to rely on an underlying VCS.

My idea is to add an endpoint that accept a zip file (the same that would be downloaded when you the get the version)

Proposed endpoint
`POST /baseURL/module/@v/version`

**Comment by michalpristas** [comment]
If you check very initial design docs: https://docs.google.com/document/d/1F0cVKxX7kEzxjrr09moqFzRQ7FoNc-Z2igfsEIkp7mc/edit?usp=sharing
You can see the third component named Sparta, this is basically it. Currently, this functionality is postponed and will be addressed with V2

**Comment by arschles** [comment]
As of #772, we're not going to try and build a registry for the time being, so I'm closing this issue
