### ISSUE TITLE
Wiki: Update broken link for registry

### ISSUE THREAD

**Issue by kaxcode** [gomods/athens#613]
**Describe the bug**
In the wiki there is a link to read more about registry. 
https://github.com/gomods/athens/wiki/The-Central-Package-Registry-(Olympus)
This link is broken and should be updated to be https://docs.gomods.io/design/registry/

**Comment by marpio** [comment]
Do we even need wiki now that we have https://docs.gomods.io ?
cc @arschles

**Comment by marpio** [comment]
I have updated wiki for now but we should consider removing it since it's better to have the docs in one place.
