### ISSUE TITLE
Drop Github wiki

### ISSUE THREAD

**Issue by marpio** [gomods/athens#617]
Now that we have https://docs.gomods.io we could drop wiki so that the docs are in one place.
What do folks think?

**Comment by robjloranger** [comment]
Vote here to **REMOVE** the GitHub Wiki.

**Comment by robjloranger** [comment]
Vote here to **KEEP** the GitHub Wiki.

**Comment by robjloranger** [comment]
I think we _could_ keep it, but just update the existing pages to state that the documentation has moved and link to the new page on the docs site. It's all very out of date.

**Comment by carolynvs** [comment]
Closing this out as resolved. The wiki now points people to our new docs site.
