### ISSUE TITLE
500 Error: Temp directory not being created; source unable to be fetched

### ISSUE THREAD

**Issue by zkry** [gomods/athens#631]
I was trying to start up the proxy and use it to get a go source (following the tutorial on https://docs.gomods.io/) but I would always encounter the following error message (formated for e:

<pre>
ERRO[0008] v1.0.0.mod not found in /var/folders/lk/jcz905h51p128q0xwk2z4_zh0000gn/T/athens240694464/pkg/mod/cache/download/github.com/athens-artifacts/samplelib/@v
http-method=GET
http-path=/github.com/athens-artifacts/samplelib/@v/v1.0.0.info
http-url=/github.com/athens-artifacts/samplelib/@v/v1.0.0.info
kind="Internal Server Error"
module=github.com/athens-artifacts/samplelib
operation=download.versionInfoHandler
ops="[
   download.versionInfoHandler
   pool.Info
   protocol.Info
   stash.Pool
   stasher.Stash
   stasher.fetchModule
   goGetFetcher.Fetch
   module.getSources
   module.checkFiles
]"
version=v1.0.0
</pre>

After doing further investigation it seems to be due to the fact the creation of the temp directory (ex: /var/folders/lk/jcz905h51p128q0xwk2z4_zh0000gn/T/athens415457267) used for the source is not being created for some reason. Also, a number of unit tests are failing for me that seem to be related to this:
```
--- FAIL: TestList (0.43s)
    --- FAIL: TestList/happy_tags (0.18s)
    --- FAIL: TestList/no_tags (0.17s)
--- FAIL: TestConcurrentLists (0.29s)
--- FAIL: TestLatest (0.39s)
    --- FAIL: TestLatest/happy_path (0.17s)
    --- FAIL: TestLatest/tagged_latest (0.18s)
--- FAIL: TestInfo (0.37s)
    --- FAIL: TestInfo/happy_path (0.17s)
    --- FAIL: TestInfo/pseudo_version (0.16s)
```

**To Reproduce**
I followed the steps here https://docs.gomods.io/ as well as the instructions https://github.com/gomods/athens/blob/master/DEVELOPMENT.md.

**Expected behavior**
I expected the proxy to correctly create the temp directory for athens and get the correct source. 

**Environment (please complete the following information):**
 - OS: darwin 64
 - Go version : 1.11
 - Buffalo Version : v0.12.4
 - Olympus or proxy version: master

 I assume this is something obvious that I am missing but I couldn't figure it out.

**Comment by arschles** [comment]
@zkry I am going to close this now. If you're able to reproduce it with the current, can you comment in here?
