### ISSUE TITLE
Switch to go build -mod=vendor instead of buffalo dev in test_e2e.sh

### ISSUE THREAD

**Issue by marpio** [gomods/athens#632]
**Describe the bug**
At the moment we use 'buffalo dev' in the `test_e2e.sh` script to start the proxy. Since `buffalo dev` downloads the packages on the fly we're having problems each time a tag is force pushed or disappears. 

**Error Message**
```
go: verifying github.com/gobuffalo/suite@v2.1.5+incompatible: checksum mismatch
    downloaded: h1:bNsqms032vutuSyznscA5s2pwv/RdsDYhE3m4ChOLXA=
    go.sum:     h1:u3fPfi47UUm656kCvXNm4R9L0Rn8tN0SYFW4F51lVhE=
buffalo: 2018/09/06 17:02:20 === Error! ===
buffalo: 2018/09/06 17:02:20 === exit status 1
```

We should use `go build -mod=vendor` instead so that we use the pkgs from the vendor directory.

**Comment by penDerGraft** [comment]
@marpio I'd be up for tackling this one if no one else was planning on it. Is [this the line in question?](https://github.com/gomods/athens/blob/ea96158f8fb13e43b8cce6952dc95d312dd2a399/scripts/test_e2e.sh#L28)

**Comment by robjloranger** [comment]
@penDerGraft Your welcome to it and you've got the right place in the script. :+1:

**Comment by penDerGraft** [comment]
Thanks @robjloranger 👍 Anything else that is affected by this change that I should look out for?
