### ISSUE TITLE
could not find assets/application.852998aa3b53a0897008.css

### ISSUE THREAD

**Issue by elvizlai** [gomods/athens#637]
**Describe the bug**
docker run

**Error Message**
```console
could not find assets/application.852998aa3b53a0897008.css
```

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. Linux 64bit]
 - Go version :
 - Buffalo Version :
 - Olympus or proxy version :

**Additional context**

**Comment by robjloranger** [comment]
@elvizlai Thanks for the bug report.

Is this for the proxy or olympus?

In both cases this is a known issue, there is no front end for either the proxy or olympus at this time. So no assets are present.

It would be great to somehow disable the application from trying to find them, perhaps we missed something during the removal? Are you interested in trying to take that on?

Small note: in the future if there are portions of the bug report template that you feel are not related to your issue, you can just remove them entirely.

**Comment by elvizlai** [comment]
the proxy report this err log.
it looks like when packing go bin using `github.com/gobuffalo/packr` missing the generated css.

**Comment by manugupt1** [comment]
@gomods/maintainers we can close this!

**Comment by marpio** [comment]
Assets have been removed. Closing.
