### ISSUE TITLE
PORT env is actually for setting the address

### ISSUE THREAD

**Issue by robbert229** [gomods/athens#638]
**Describe the bug**
The *PORT* environment variable is not used to set the port, but the address. This seems unintuitive and might throw new users and new developers for a loop.

**Error Message**

<pre>
```
INFO[0000] Starting application at http://127.0.0.1:8080 
ERRO[0000] listen tcp: address 8080: missing port in address 
buffalo: Starting Simple Background Worker
2018/09/07 13:07:10 context canceled
exit status 1
```
</pre>

**To Reproduce**

A user wants to run athens on port 8080 so the could potentially run the following...
```bash
PORT=8080 go run ./cmd/proxy
```

**Expected behavior**

I would exect that the port environment variable just sets the port, or that we used an ADDR environment variable to set the address. Currently we use PORT to set the address. 

**Environment (please complete the following information):**
 - OS: N/A
 - Go version : N/A
 - Buffalo Version : N/A
 - Olympus or proxy version : master

**Additional context**
This is a user experience *bug* if a bug at all. (I haven't encountered any bugs so far, and the proxy looks great!)

**Comment by robjloranger** [comment]
This is a somewhat related to #610, but you are correct that we should be using something like `ATHENS_ADDR` _if_ we intend to keep allowing full address assignment.

However, I'm wondering in what situation we would want to set the running application's address to anything other than localhost. I'm not super familiar with that part of running applications so am not sure if it is ever needed.

If it is **not** needed to ever set the application address to an IP other than the local host, we could instead do two things.

1. Change the name of the variable to address #610 
2. Internally only use that value as a port, not a string with a `:`.

**Comment by robbert229** [comment]
I think that listening on a non localhost address is a big deal for the
enterprise. I think a big use case of athens is hosting a single proxy
inside the enterprise and having developers use that single one. That's a
major use case for me at least.

**Comment by robjloranger** [comment]
I'd love to hear about how that even works, maybe in slack sometime? :grinning: 

So then, maybe let's go with changing the variable name to `ATHENS_ADDR` or similar. And document that for localhost we can just set a port prefixed with `:` otherwise the full ip/port can be set. Using our config package we can default to something typical like `:3000` when the variable is not set.

**Comment by scriptonist** [comment]
I can attempt to fix this :smiley:

**Comment by michalpristas** [comment]
@robbert229 isn't container supposed to be paired with some public IP or sit behind a load balancer with ports correctly mapped? I can hardly imagine somebody will run Athens on bare metal, especially in enterprise

**Comment by arschles** [comment]
@scriptonist sorry for the long delay. If you're still interested in trying this, you're more than welcome to.

**Comment by arschles** [comment]
Now that someone can specify the proxy port (we do this in the buffalo config in code), this is done. Closing
