### ISSUE TITLE
Proposal: create a proposal issue type

### ISSUE THREAD

**Issue by arschles** [gomods/athens#641]
**Is your feature request related to a problem? Please describe.**

I wanted to create an issue to propose a feature, but when I clicked "new issue", GH gave me the choice to create a new bug or feature request. It also gave me the option to open a new regular issue. I would love if we could have a proposal issue type

**Describe the solution you'd like**

When I click "new issue", I would like to have an option to create a new "proposal" issue, where the issue template has sections for me to fill out related to a proposal. I think the template could be pretty simple to start with, and have:

- context: a problem that the issue author is trying to solve, a change that the user wants to make
- other stuff?

**Describe alternatives you've considered**

Maybe we don't need this issue type, and we can just use new issue templates for proposals too?

**Additional context**

I haven't thought this through completely, but I wanted to throw it out there to see what others think.

**Comment by robjloranger** [comment]
I think it's a great idea.
