### ISSUE TITLE
Tracing exporter for Stackdriver

### ISSUE THREAD

**Issue by manugupt1** [gomods/athens#642]
**Is your feature request related to a problem? Please describe.**
Currently, our observability stacks supports jaeger as the only UI. It would be nice to have the same for stackdriver as well as @marwan-at-work is using it at NYtimes

**Describe the solution you'd like**

https://opencensus.io/guides/exporters/supported-exporters/go/stackdriver/

**Comment by marwan-at-work** [comment]
I'd like to pick this up since I'm hoping to deploy this in the next few days.
