### ISSUE TITLE
Spans should also have response status

### ISSUE THREAD

**Issue by manugupt1** [gomods/athens#643]
Currently when we trace a span, there are spans that return an http response. It will be nice to store the HTTP status code in the span as well.

Proxy
Opencensus
observ package

**Comment by marwan-at-work** [comment]
@manugupt1 can you explain more or point to documentation as to what this issue really is? Thanks!

**Comment by manugupt1** [comment]
@marwan-at-work Yes sure! 
If you open the spans, you can find that the spans have a status field which is basically the trace status.

It would be nice to record the http status in the status field so that we can know what exactly happened in that span.

https://opencensus.io/quickstart/go/tracing/

**Comment by marwan-at-work** [comment]
Got it, we need to wrap the http.ResponseWriter in this case which Buffalo doesn't make it very trivial because you have to wrap the entire Context.

**Comment by manugupt1** [comment]
Yep!

I think we should ask folks at opencensus on how they would do it. Ochttp does the same but it is not trivial to make it work with Buffalo again

Cheers
Manu
________________________________
