### ISSUE TITLE
Observability - Try implementing ochttp plugin

### ISSUE THREAD

**Issue by manugupt1** [gomods/athens#644]
**Is your feature request related to a problem? Please describe.**
Ochttp plugin is a plugin from OpenCensus that traces http requests. It also comes with a set of metrics that we can directly use to capture.

**Describe the solution you'd like**
Try out ochttp from 
1. https://godoc.org/go.opencensus.io/plugin/ochttp
2. See if the metrics are logged in or not.

**Describe alternatives you've considered**
We can also choose to write our own metrics

**Additional context**

**Comment by scriptonist** [comment]
Hey @manugupt1, I've no Idea about the stuff mentioned here 😅  but I would like to take this as an opportunity to learn and understand that. With that in mind, Would you recommend me to try to tackle this?

**Comment by manugupt1** [comment]
Hi

I am not sure. I am traveling, can I have a look at the code and see where we are and get back to you?

Cheers
Manu

________________________________

**Comment by scriptonist** [comment]
Sure, please 👍

**Comment by scriptonist** [comment]
@manugupt1 please close the issue, I'll look at the existing implementation in the meantime and open another issue if I find some room for improvement. 😄

**Comment by manugupt1** [comment]
thanks @scriptonist
