### ISSUE TITLE
Use spf13/afero for InMemory and Disk Storage

### ISSUE THREAD

**Issue by marpio** [gomods/athens#65]
It would be possible to use the same code for both backends and automatically enable others i.e. sftp
https://github.com/spf13/afero

**Comment by arschles** [comment]
@marpio great idea. thanks!

**Comment by marpio** [comment]
@arschles I don't have that much experience with go but I would like to try to implement this if that's ok.

**Comment by michalpristas** [comment]
@marpio go ahead, we have PR reviews for that. 
also we have slack channel on gophers slack called athens. feel free to join and ask questions

**Comment by arschles** [comment]
@marpio +1 to what @michalpristas said

feel free to fork & submit a PR for this. The dev guide for this project is [here](https://github.com/gomods/athens#development), and hopefully that should get you set up to run locally, do development, etc... Let us know if something is not working for you and we can fix it in the guide 😄

**Comment by marpio** [comment]
Thanks! I'll give it a try.
