### ISSUE TITLE
Visiting https://gomods.io produces a certificate warning

### ISSUE THREAD

**Issue by timraymond** [gomods/athens#651]
When visiting https://gomods.io, users are presented with a certificate warning because a self-signed certificate for `bryankellar.com` is being served. Visiting the HTTP version at http://gomods.io yields the following error page from a cPanel instance:

<img width="1420" alt="default_web_site_page" src="https://user-images.githubusercontent.com/288061/45438550-73880600-b685-11e8-9d0e-186edbaa2361.png">

The same issue is present with the `www` subdomain as well. It's possible that this is a DNS misconfiguration.

**To Reproduce**
- Visit https://gomods.io , https://www.gomods.io, to see the TLS issues and http://gomods.io, http://www.gomods.io in any browser for the cPanel error showed above.
- `openssl s_client -connect gomods.io:443` can help verify that the right cert is being served

**Expected behavior**
I expect to be presented with an official landing page, or redirected to https://docs.gomods.io

**Comment by robjloranger** [comment]
I'm very in favor of redirecting for now. Until we have a proper front end.

**Comment by arschles** [comment]
I'm also in favor. @robjloranger I remember you said on slack you might be able to take this on. are you still planning to?

**Comment by chamilad** [comment]
This is still there. Now a cert for SANs for a bunch of *.br names is offered.

![image](https://user-images.githubusercontent.com/505989/58846388-1c263c00-86d3-11e9-8d2b-190f259eb35e.png)

**Comment by arschles** [comment]
@chamilad thanks for bringing it back up! I'll take it now

**Comment by arschles** [comment]
update: it requires me to update the dns records of the gomods.io domain. I'm working on that now, might take a bit of time
