### ISSUE TITLE
Specify a list of endpoints that should not be traced

### ISSUE THREAD

**Issue by manugupt1** [gomods/athens#654]
**Describe the bug**
Currently, there is no way to filter out specific endpoints to our traces in our middleware
It will be nice to have a way to filter those out

**Example**
`/healthz` endpoint is hit a lot of times and is definitely not useful for tracing functionality

**Comment by marwan-at-work** [comment]
@manugupt1 OpenCensus v0.15.0 explicitly skips `/healthz` -- how were you getting them?

**Comment by manugupt1** [comment]
Did not realize that. I looked at ochttp plugin and they did it, so I thought it will be a good idea anyway.  I did not see on the trace though.


Cheers
Manu
________________________________

**Comment by manugupt1** [comment]
I am closing this issue as we the healthz endpoint is automatically excluded and I can't think of anything else

**Comment by michalpristas** [comment]
just a side note that it is common to use `/healtz` for liveness checks and `/ready` for readiness, we will cross that bridge when we get to it though

**Comment by chriscoffee** [comment]
> just a side note that it is common to use `/healtz` for liveness checks and `/ready` for readiness, we will cross that bridge when we get to it though

Just a quick addition to that, if we're going with `/healthz` we should probably also do `/readyz`. It's a Google practice to avoid collisions
