### ISSUE TITLE
Add Athens to codetriage.com

### ISSUE THREAD

**Issue by timraymond** [gomods/athens#656]
In support of helping triage open issues, we discussed adding Athens to [codetriage.com](https://www.codetriage.com) during the weekly development meeting on 9/13/18. This would involve submitting the project to codetriage.com, and updating related onboarding documentation to direct newcomers to sign up on CodeTriage to receive issues (if they want to).

They also have a fun button for the README we can include:

<img width="762" alt="help_contribute_to_gobuffalo_buffalo_-_go___codetriage" src="https://user-images.githubusercontent.com/288061/45508226-4a897300-b762-11e8-88bc-491f67a8fe76.png">

**Comment by arschles** [comment]
I'll take this one!
