### ISSUE TITLE
Add a Code of Conduct file and PR templates

### ISSUE THREAD

**Issue by arschles** [gomods/athens#658]
We have a CoC, but it's written down in [the README](https://github.com/gomods/athens#code-of-conduct), so we should split it out into a new file

PR templates are helpful too, and show up in the community profile (below)

![screen shot 2018-09-13 at 12 23 08 pm](https://user-images.githubusercontent.com/70865/45510743-fd9ca100-b74f-11e8-95e3-ed924d47a1b6.png)

**Comment by brainsnail** [comment]
I'd like to work on these two items, if that's alright.

**Comment by robjloranger** [comment]
closing with #707 and we have a PR template now.

**Comment by arschles** [comment]
what @robjloranger said ❤️
