### ISSUE TITLE
Minio Port conflict with vscode extensions server

### ISSUE THREAD

**Issue by scriptonist** [gomods/athens#671]
When we run `make alldeps` to do some `docker-compose` magic to bring up the services, Minio tries to bind to port `9000` which is being used by vscode for Its extension server. Which In turn will cause,
```
Starting athensdev_minio_1 ... error

ERROR: for athensdev_minio_1  Cannot start service minio: driver failed programming external connectivity on endpoint athensdev_minio_1 (b060df5b66108f320faf15e484a1036ea543b257a4c720c3e0839b17279cfa6a): Error starting userland proxy: listen tcp 0.0.0.0:9000: bind: address already in use
```
If we kill the process on port `9000 `
```
07:02:52 ▶ fuser -k 9000/tcp
9000/tcp:             4710
```
In vscode
![vscode](https://user-images.githubusercontent.com/8335904/45725853-5fd72500-bbda-11e8-99a2-40715205c7c8.png)

**Environment**
##### OS 
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

Linux drogon 4.15.0-33-generic Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 ##### Athens Commit Hash
c740fcb26cc0192391c10b4b0185d62b78c1410b

**Additional context**
If this is faced by many people, The port which is bound for minio can be changed to improve the UX.

**Comment by marpio** [comment]
I will take this one
