### ISSUE TITLE
Making configuration files that are loaded on the server only readable  to the user that it is hosted on

### ISSUE THREAD

**Issue by manugupt1** [gomods/athens#700]
**Is your feature request related to a problem? Please describe.**
We have a configuration file (like exclude/ include filter) stored as a conf file. Currently,  the permissions for the file are set by the user and the same set of permissions are carried over to Athens proxy. The result is if a user has 777 permissions on the file, the same will go on proxy making the proxy server vulnerable.

**Describe the solution you'd like**
We can check in the proxy code to make sure that the permissions are either 0400 or 0600 as per Unix and only then read from it or start throwing an error. This is similar to what Github does.

**Describe alternatives you've considered**
I have not really considered any other alternatives.

**Comment by manugupt1** [comment]
Vote for 0400 pre-beta

**Comment by manugupt1** [comment]
Vote for 0400 post-beta

**Comment by manugupt1** [comment]
Vote for 0600 pre-beta

**Comment by manugupt1** [comment]
Vote for 0600 post-beta

**Comment by manugupt1** [comment]
Please leave comments and suggestions if you can suggest anything

**Comment by arschles** [comment]
@manugupt1 since this has been open 17+ days, I've put it into v0.1.0 and assigned you. thanks for opening 🎉 !!
