### ISSUE TITLE
Implement storage.Backend for Azure Blob storage

### ISSUE THREAD

**Issue by michalpristas** [gomods/athens#703]
**Is your feature request related to a problem? Please describe.**
Azure Blob Storage is missing implementation

**Describe the solution you'd like**
- Rename `azurecdn` to `azureblob`
- Implement storage.Backend interface (`Lister`, `Getter`, `Checker`, `Deleter`). `Saver` is already implemented
- Let `azure` storage join the fun in `/pkg/storage/storage_tests`

**Comment by michalpristas** [comment]
For grab, preferring new contributors

**Comment by scriptonist** [comment]
@michalpristas Can I take this up?

**Comment by michalpristas** [comment]
Yes, of course, @scriptonist if you have question shoot it here ;-)

**Comment by scriptonist** [comment]
I was wondering why we are using `github.com/Azure/azure-storage-blob-go` instead of `https://godoc.org/github.com/Azure/azure-sdk-for-go/storage`

**Comment by michalpristas** [comment]
@scriptonist 
if you go to: https://github.com/Azure/azure-sdk-for-go/tree/master/storage
you can find information saying that: This package is in maintenance only and will be deprecated in the future

**Comment by scriptonist** [comment]
@michalpristas Thank you, I didn't catch that.

**Comment by marpio** [comment]
@scriptonist are you still on it? Do you need any help?

**Comment by scriptonist** [comment]
Hey @marpio, Sorry go stuck up at work! Is this high on priority? 
Yes, I would Always love some help :smiley:

**Comment by marpio** [comment]
No problem @scriptonist we're all busy! 
It would be nice to have it ready for beta so that we cover all the major clouds. ATM we implement only part of the storage.Backend interface.
If you have any questions just ask here or on Slack (athens channel).

**Comment by chriscoffee** [comment]
I'm also happy to help if needed, I meant to mention that I'd be happy to work on it with you if you wanted to split the tasks up or pair or something. 👍 Thanks for taking the ticket btw

**Comment by marpio** [comment]
I think that the issue title isn't accurate because it's more about adding azure blob storage support to Athens just like we support aws s3 and gcp blob storage.
Correct me if I'm wrong @michalpristas

**Comment by michalpristas** [comment]
Yes, it is for blob storage, will update right away. thanks for pointing out
