### ISSUE TITLE
Proxy home page image is huge

### ISSUE THREAD

**Issue by gcstang** [gomods/athens#705]
**Describe the bug**
After starting the latest pull from the docker hub and going to the 3000 port on the container you're met with a HUGE image of "The Athens Project" so large you have to scroll to see more than one letter.

**Error Message**
buffalo: could not find assets/application.852998aa3b53a0897008.css

**To Reproduce**
Pull latest image from docker hub registry
Image ID: 027e580061f7

**Expected behavior**
Expected an image that was viewable in a regular full screen browser.

**Environment (please complete the following information):**
 - OS: Mac OSX using Docker 18.06.1-ce-mac74 (26766)
 - Go version : internal to docker image
 - Buffalo Version :internal to docker image
 - Olympus or proxy version :  Image ID: 027e580061f7

**Comment by manugupt1** [comment]
Can you review it on master? It may not be reproduced on Master and we may
not have updated the image which will be updated in the next version most
likely.

Cheers,

Manu Gupta

**Comment by gcstang** [comment]
I don't see any image on master.

**Comment by manugupt1** [comment]
Yep! So, we are removing the landing page in the next version. We will
revisit the landing page in the future to show which modules are stored in
the proxy.


Cheers,

Manu Gupta

**Comment by marpio** [comment]
Can we close this @gcstang ?

**Comment by gcstang** [comment]
@marpio yes this is ok in master
