### ISSUE TITLE
Athens for Outreachy and Google summer of code (GSOC) . I feel it's time for athens to participate in open source community driven programs. We need to check whether only OS organisations or projects like athens can participate ?

### ISSUE THREAD

**Issue by VineethReddy02** [gomods/athens#706]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by arschles** [comment]
@manugupt1 would you be willing to investigate Google Summer of Code?

**Comment by arschles** [comment]
I will check out Outreachy. Looks like the deadline for submitting a project there is 10/2/2018 (according to [here](https://www.outreachy.org/communities/cfp/))

**Comment by manugupt1** [comment]
@arschles Sure! will update you

**Comment by arschles** [comment]
I wasn't able to get us into Outreachy this year. Sorry for this folks.

@manugupt1 did you have any luck with GSoC?

**Comment by manugupt1** [comment]
On my list to do over this weekend!


Cheers,

Manu Gupta

**Comment by manugupt1** [comment]
GSoC applications open in January.
To get a rough idea, here is this years timeline. https://summerofcode.withgoogle.com/how-it-works/#timeline

The second thing, we would want to decide earlier is how much projecs would we want to have. Typically, smaller orgs get 1 project assigned and afaik Google recommends applying with twice the number of projects that you can have. We will have to consider 
To estimate the number of projects, we will have to
A) Commitment from mentors to work for 3 - 4 months.
B) Have backup mentors just in case life happens.

One more alternative is this if we are tied for bandwidth and can't do admin stuff, we would want to leave admin stuff to a bigger org like FSF, CloudNative or other orgs and request them to guarantee at least 1 slot. This leads to greater collaboration and also removes a lot of headache. 

Finally, GSoC will give an org some money for participating. This can either be taken by us if we have a foundation or ask Google to donate it to a bigger open source org.

Let me know if you have questions!

**Comment by VineethReddy02** [comment]
Hey!!

Sorry i was bit occupied with my exams couldn't followup the thread. As manu mentioned, It's true for the first time as an organisation we might get 1 or 2 projects approved. Last year .net foundation has applied for GSOC for the first time but it didn't get approved as most of the projects were documentation related. The quality of project plays a major role in terms of approval.

Aaron you can look into the below link last year 34 projects where completed belonging to organisation called FOSSASIA. That means they got 40+ projects have been approved by GSOC in which few are eliminated during application review and few students couldn't complete them. The projects mentioned here might give you guys better understanding in making Athens projects for GSOC.


https://summerofcode.withgoogle.com/organizations/4799958788603904/?sp-page=4#projects
[https://summerofcode.withgoogle.com/static/img/og-image.png]<https://summerofcode.withgoogle.com/organizations/4799958788603904/?sp-page=4#projects>

Google Summer of Code<https://summerofcode.withgoogle.com/organizations/4799958788603904/?sp-page=4#projects>
/
summerofcode.withgoogle.com



I would love to help in this regard for athens as i was looking into this from last on year.

Thanks
Vineeth

________________________________

**Comment by arschles** [comment]
@VineethReddy02 I am going to close this issue for now. If you're interested in helping with GSoC this year, please comment in here or open a new issue. If you do the former, I'll still get the notification and come and open this issue back up.
