### ISSUE TITLE
Can we get the Microsoft t-shirt from Hacktoberfest?

### ISSUE THREAD

**Issue by arschles** [gomods/athens#713]
**Is your feature request related to a problem? Please describe.**

Hacktoberfest is described [here](https://hacktoberfest.digitalocean.com/). The TL;DR is that if you submit 5+ PRs between 10/1 and 10/31 (that you actually authored), then Digital Ocean will ship you a rad shirt. Microsoft is also [sponsoring](https://open.microsoft.com/2018/09/30/join-hacktoberfest-2018-celebration-microsoft/). If you submit 5 PRs to a Microsoft repository, you get a Microsoft T-Shirt (designed by the famous @ashleymcnamara).

Athens isn't a Microsoft repository though, so PRs here aren't eligible toward the MS t-shirts 😦 

**Describe the solution you'd like**

I'd like for people to get Microsoft t-shirts (in addition to DigitalOcean ones) if they submit PRs to Athens.

**Describe alternatives you've considered**

I haven't considered anything else really. I guess just not getting MS t-shirts?

**Additional context**

I work at Microsoft, so I've asked the Hacktoberfest organizers if PRs here will be eligible for MS T-Shirts.

I really want peeps to get MS t-shirts because Ashley is rad (as are her designs).

**Comment by arschles** [comment]
I'll take this one

**Comment by arschles** [comment]
I just followed up with some folks at Microsoft. They're not going to be sponsoring GitHub projects outside of the Microsoft related GitHub organizations (`/Microsoft`, `/Azure` and so on) this year.

The DigitalOcean shirts are still available though 😄

**Comment by Hamthannuel** [comment]
I submitted a pull request towards microsoft visual studio code and have not received a t-shirt or an email saying I would be recieving one yet..

**Comment by robjloranger** [comment]
@Hamthannuel you will have to get in touch with Microsoft regarding that. This project is not under Microsoft. If you check out this [post](https://open.microsoft.com/2018/11/07/hacktoberfest-2018-results-thank-you/) you will see they are in the process of reviewing submissions.
