### ISSUE TITLE
Helm install broken

### ISSUE THREAD

**Issue by fedepaol** [gomods/athens#715]
**Describe the bug**
Can't install athens with helm following the instructions on the docs

**Error Message**
helm install ./charts/proxy -n athens
Error: render error in "athens-proxy/templates/deployment.yaml": template: athens-proxy/templates/deployment.yaml:36:28: executing "athens-proxy/templates/deployment.yaml" at <.Values.redis.addres...>: can't evaluate field address in type interface {}

**To Reproduce**
Just try to install athens with helm
`helm install ./charts/proxy -n athens`

**Expected behavior**
Athens should be deployed to k8s

      
**Environment (please complete the following information):**
 - OS: Linux 64bit
 - Helm: Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
 - Olympus or proxy version: latest from github

**Comment by fedepaol** [comment]
Close with merge of https://github.com/gomods/athens/pull/717

**Comment by arschles** [comment]
Looks like this is working now, according to @fedeapol
