### ISSUE TITLE
Support .hgrc files to access private Mercurial repos

### ISSUE THREAD

**Issue by marpio** [gomods/athens#716]
**Is your feature request related to a problem? Please describe.**
Authorize proxy to access a private Mercurial repo.

**Describe the solution you'd like**
Proxy supports .netrc file to access a private repo.
Mercurial has its own RC file - `.hgrc` - which can be used to store credentials.
We should add support for that similar to `.netrc`

Ref: https://github.com/gomods/athens/pull/528

**Comment by t-tomalak** [comment]
I would like to work on this :slightly_smiling_face:
