### ISSUE TITLE
Requirements for Beta?

### ISSUE THREAD

**Issue by arschles** [gomods/athens#725]
We have had discussions about basic requirements for Beta. As far as I remember, the basic requirement for beta is that we have the proxy -> VCS auth story figured out.

Anything else to add?

cc/ @marwan-at-work @robjloranger @fedepaol

**Comment by michalpristas** [comment]
Just for reference, quoting meeting notes:
Beta:
- More docs for how to deploy the athens proxy
- Solid deployment = building and pushing the docker image from CI/CD
- Nice to have: integration tests that run against a newly built docker image (i.e. on a tag release)

**Comment by robjloranger** [comment]
I'm with Michal. I think with authentication, docs and more tests we should be good to go for beta.

**Comment by arschles** [comment]
Update:

- all of the docs issues we need to do for beta are in the [v0.1.0 milestone](https://github.com/gomods/athens/milestone/2)
- deployment issues are all done. docker images are currently being pushed from our CI/CD system (thanks to @carolynvs for telling me about this!)
- integration tests we aren't going to complete for v0.1.0. we've pushed this to v0.2.0 (https://github.com/gomods/athens/issues/262 is part of this work, for example)

**Comment by arschles** [comment]
we've broken this issue down into several smaller, more focused issues. most ended up in either the v0.1.0 or v0.2.0 milestone. since this was a "meta" issue and it's already broken down, I'm going to close
