### ISSUE TITLE
Update the "communication" page on the docs site

### ISSUE THREAD

**Issue by arschles** [gomods/athens#728]
**Is your feature request related to a problem? Please describe.**

The docs at https://docs.gomods.io/design/communication/ are out of date. We should update them to reflect how the proxy works

**Describe the solution you'd like**

I'd like them to not mention Olympus because the proxy does not involve olympus

**Describe alternatives you've considered**

None

**Additional context**

We discussed this in the [October 4 Athens dev meeting](https://docs.google.com/document/d/1xpvgmR1Fq4iy1j975Tb4H_XjeXUQUOAvn0FximUzvIk/edit#heading=h.f24qbjkyfv6v)

**Comment by michalpristas** [comment]
Will work on this one
