### ISSUE TITLE
The documentation homepage should have information on the Athens dev meeting

### ISSUE THREAD

**Issue by arschles** [gomods/athens#730]
**Is your feature request related to a problem? Please describe.**

The Athens dev meeting happens weekly but we have to continuously tell people how to find it because it's only discoverable on the README but not the documentation.

**Describe the solution you'd like**

For new community members who see the docs first, I'd like them to be able to discover the dev meeting from the homepage. So, I'd like a new page that briefly describes the dev meeting and has links to the agenda and how to find the zoom, etc... I'd also like the homepage to link to the dev meeting.

**Describe alternatives you've considered**

None

**Additional context**

We talked about this in the [October 4, 2018 Dev Meeting](https://docs.google.com/document/d/1xpvgmR1Fq4iy1j975Tb4H_XjeXUQUOAvn0FximUzvIk/edit#heading=h.f24qbjkyfv6v)

**Comment by chriscoffee** [comment]
I'd like to take this please! 👍

**Comment by michalpristas** [comment]
Hey @chriscoffee go ahead please

**Comment by chriscoffee** [comment]
Can I suggest that we move _participating in the athens community_ under a _athens community_ breadcrumb like maintainers/new contributors to sit alongside a page on the developer meetup. I think this would be more digestable to the reader?

**Comment by robjloranger** [comment]
I think that's a great idea @chriscoffee , I would vote for `Community` for brevity in the menu.

As we continue to expand our docs site we will likely have a lot more nesting and reorganizing.

**Comment by arschles** [comment]
This was closed by #755
