### ISSUE TITLE
We should move the .netrc Auth Documentation

### ISSUE THREAD

**Issue by arschles** [gomods/athens#731]
**Is your feature request related to a problem? Please describe.**

The "Authenticate private repositories via .netrc" documentation is at https://docs.gomods.io/design/proxy/, but that's not a good fit because it's not related to high level design.

**Describe the solution you'd like**

I think we should move this information to the pages under https://docs.gomods.io/install/

**Describe alternatives you've considered**

None

**Additional context**

We talked about this in the [October 4, 2018 Dev Meeting](https://docs.gomods.io/install/)

**Comment by fedepaol** [comment]
Taking this one
