### ISSUE TITLE
Scrub the docs of Olympus information

### ISSUE THREAD

**Issue by arschles** [gomods/athens#732]
**Is your feature request related to a problem? Please describe.**

We have a lot of Olympus-related documentation on the documentation site, but Olympus is not built. So, the docs are confusing because they make it seem like Olympus is a finished or close-to-finished product.

**Describe the solution you'd like**

I'd like us to remove the Olympus-related documentation from the docs site.

**Describe alternatives you've considered**

None

**Additional context**

We talked about this in the [October 4, 2018 Dev Meeting](https://docs.gomods.io/install/)

**Comment by marpio** [comment]
I'll take this one.
