### ISSUE TITLE
Add dev meeting notes to the docs site

### ISSUE THREAD

**Issue by arschles** [gomods/athens#734]
**Is your feature request related to a problem? Please describe.**

Currently, our agenda is in the [Google Doc](https://aka.ms/athensdevmeeting). Sometimes we take meeting notes in that doc too. It's hard to find the agenda for a specific day and it's hard to find meeting notes, if they exist.

**Describe the solution you'd like**

I'd like at least the meeting notes to go onto the docs site. We could probably put them under the dev meeting section mentioned in https://github.com/gomods/athens/issues/730

**Describe alternatives you've considered**

None

**Additional context**

We talked about this in the [October 4, 2018 Dev Meeting](https://docs.gomods.io/install/), and decided it would be a nice to have for v0.1.0 but we would put it in v0.2.0

**Comment by chriscoffee** [comment]
If you're happy for me to take this one too if that's cool, I can drop in after the other tickets' sorted? Also don't mind attending and maintaining them until we decide to automate it.

**Comment by robjloranger** [comment]
You're welcome to it. Also if your interested in attending the meetings, all are welcome and we would encourage you to do so.

**Comment by arschles** [comment]
Sadly we're not doing dev meetings reliably anymore, so I'm closing this
