### ISSUE TITLE
Add more documentation around "why does it matter"

### ISSUE THREAD

**Issue by arschles** [gomods/athens#749]
**Is your feature request related to a problem? Please describe.**

After #740 is merged, there will be a "why does it matter" section on the homepage that briefly explains why Athens matters for better dependency management, but it leaves out vendor directory problems, auth, and more (see [here](https://github.com/gomods/athens/pull/740/files#r222852546) for the full list by @marwan-at-work)

**Describe the solution you'd like**

I think we should create a full new page (maybe under the "intro" section) that has details on each reason why Athens matters. We should do a quick TL;DR of each of those on the homepage and then link to that new page.

**Describe alternatives you've considered**

We could put everything on the home page, but then it's not really an elevator pitch. Probably more like a walk-up-the-stairs pitch 😆 

**Additional context**

Follow-up on [this thread](https://github.com/gomods/athens/pull/740/files#r222852546)

**Comment by arschles** [comment]
I"d like to take this one

**Comment by chriscoffee** [comment]
@arschles What do you feel is missing here? I'd like to help out today/tonight, then we can get v0.1.0 out 🎆 🍰

**Comment by marwan-at-work** [comment]
I'll pick this up real quick 😄
