### ISSUE TITLE
Add "Make a pull request" badge?

### ISSUE THREAD

**Issue by arschles** [gomods/athens#752]
**Is your feature request related to a problem? Please describe.**

We as a community are growing, and it seems like as a new contributor it's easy to get started with a PR or similar. I think that's in large part because we're welcoming, our documentation makes that fact clear, and that we have good instructions on how to get going, both with Athens and with open source on GitHub in general.

I think there's room to make that last part even stronger.

**Describe the solution you'd like**

I think we should add the  [![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square)](http://makeapullrequest.com) badge to our README (and maybe docs site), and also add the contributing instructions on http://makeapullrequest.com/ to our contributing documentation. 

**Describe alternatives you've considered**

We could possibly just add the badge and not add the instructions.

**Additional context**

I just stumbled on http://makeapullrequest.com/ 😆

**Comment by gabrielSchneider100** [comment]
I'll take this one.

Just started contributing here and I found the contributing instructions very helpful to my first PR here.

**Comment by gabrielSchneider100** [comment]
I think there's already too much resources in the contributing instructions. I think it's better if we just reference it like @bketelsen 's video.
