### ISSUE TITLE
Factor all storage tests into a common suite

### ISSUE THREAD

**Issue by arschles** [gomods/athens#76]
We have a lot of `./pkg/storage/*/all_test.go` files that exercise pretty much the same functionality for all the drivers. We should just factor them all out into one suite

**Comment by arschles** [comment]
@michalpristas you did some work on this, right? I think it's done? If so, can you close?

**Comment by robjloranger** [comment]
Just missing the clouds: azure, GCP and s3. Azure and s3 are incomplete implementations so could be skipped leaving the contributor who finishes them to add their tests to the suite. Only GCP has full tests but is waiting on #263 before we can move the tests over to the common suite.

**TL;DR** we can probably close and enforce using the suite on future PRs.

**Comment by michalpristas** [comment]
i agree with closing this. later on this week i will skim the code and create more granular issues if needed
