### ISSUE TITLE
Implement Distributed Deduplication Mechanisms

### ISSUE THREAD

**Issue by arschles** [gomods/athens#760]
**Is your feature request related to a problem? Please describe.**

#308 was for making Athens not do two `go get` calls for the same `module@version` at the same time. That meant that if N `go get mod@ver` calls came in at the same time, only one `go get` would get issues on the backend. https://github.com/gomods/athens/pull/573 went and fixed #308 by introducing "single flight" - a kind of mutual exclusion mechanism built in memory.

Now, we have an Athens that will only run `go get` once for a given `mod@ver`, but if you want to run a fleet of Athens servers (i.e. behind a load balancer in the cloud, in pods in a Kubernetes cluster, etc...), the different Athens processes don't all single-flight together. If a `go get mod@ver` request goes to athensA and another `go get mod@ver` request goes to athensB at exactly the same time, they will both still run `go get mod@ver`.

**Describe the solution you'd like**

We should build new `download.Wrapper`s (like the one [here](https://github.com/gomods/athens/pull/573/files#diff-8176b6031aa0a1b5e293d0ce973a0cdfR40)) that use distributed mutual exclusion mechanisms, so that a fleet of Athens servers can single-flight together.

I'd like us to have multiple drivers eventually. Some ideas:

- [etcd](https://coreos.com/etcd/) locks
- [Consul](https://www.consul.io/) locks
- Cloud proprietary solutions

**Describe alternatives you've considered**

I tried to think of other ways to de-duplicate `go get`s across lots of Athens servers, but can't think of others besides distributed mutual exclusion.

**Additional context**

**Comment by marwan-at-work** [comment]
I'd like to work on this (I've done in implementation for it back in the day so I just need to dig it up). 

I'd like to emphasize that this should only be worked on, reviewed, and merged after beta. So that we focus our efforts on achieving the beta milestone :v:
