### ISSUE TITLE
Update helm charts to include tracing from jaeger

### ISSUE THREAD

**Issue by manugupt1** [gomods/athens#762]
**Is your feature request related to a problem? Please describe.**
Currently, helm charts do not have any way of letting the users know about tracing. We would want Jaeger to be used as a tracing library since it is open source.

This is because helm charts have been used to deploy the public proxy afaik.

**Describe the solution you'd like**
Update helm charts to include jaeger as the tracing library

**Comment by t-tomalak** [comment]
Is anyone on this? I would like to take on this. I never done anything with helm but I probably need few answers to make it done.
1. Do we wanna use jaeger/all-in-one image?
2. Do we wanna any customization of ports on this image?
3. Should we also add in deployment.yml this two env variables? First one will be `ATHENS_TRACE_EXPORTER` and this is just set to `jaeger` probably. Second one `ATHENS_TRACE_EXPORTER_URL` but I don't know what value it should had. Wild guess would be service name so probably also `jaeger`. Could someone help? :slightly_smiling_face:

**Comment by manugupt1** [comment]
@t-tomalak 
1. Yes, we want to have jaeger/all-in-one image because that simplifies a lot of things.

For 2 and 3, I think we just specify the ports that the image maps to with the full URL. I would do what you feel like and we can take it from there.

**Comment by manugupt1** [comment]
This has been fixed by @t-tomalak! Thank you!
