### ISSUE TITLE
Update proxy Dockerfile to 1.11.1-alpine

### ISSUE THREAD

**Issue by gcstang** [gomods/athens#765]
Proxy Dockerfile is now out of date that 1.11.1 has been released.
Update to build on the latest GO release prior to image creation.

FROM golang:1.11-alpine AS builder
to
FROM golang:1.11.1-alpine AS builder

**Comment by HannanSolo** [comment]
I got ya ;)

**Comment by manugupt1** [comment]
This issue can be closed @gomods/maintainers
