### ISSUE TITLE
Major version control authentication support for bzr

### ISSUE THREAD

**Issue by gcstang** [gomods/athens#770]
**Is your feature request related to a problem? Please describe.**
Lack of authentication support for bzr

**Describe the solution you'd like**
Authentication support added for bzr

**Comment by gcstang** [comment]
I'm going to work on this one @gcstang

**Comment by arschles** [comment]
@gcstang let us know if you'd like any help navigating the codebase or anything else! excited you're doing this 😄

**Comment by arschles** [comment]
#795 fixed this, closing.

Thanks @gcstang for doing that PR!
