### ISSUE TITLE
Implement storage.Backend for Alibaba OSS

### ISSUE THREAD

**Issue by chriscoffee** [gomods/athens#775]
**Is your feature request related to a problem? Please describe.**
Alibaba Object Storage Service is missing implementation.

**Describe the solution you'd like**
- Implement storage.Backend interface (`Lister`, `Getter`, `Checker`, `Deleter`). `Saver` is already implemented
- Let OSS join the fun in `/pkg/storage/storage_tests`

**Additional context**
Related issues: #704, #703

For further reference the SDK is here https://github.com/aliyun/aliyun-oss-go-sdk

**Comment by korrat** [comment]
I would like to work on this

**Comment by manugupt1** [comment]
Hi @korrat Alibaba OSS is supported by minio as well, would you want to add docs for it?
