### ISSUE TITLE
Add docs on how to deploy to Google App Engine Flexible Environment

### ISSUE THREAD

**Issue by arschles** [gomods/athens#776]
**Is your feature request related to a problem? Please describe.**

We have a limited amount of docs right now on how to deploy Athens to clouds.

**Describe the solution you'd like**

Adding docs for how to deploy to [GAE's flex environment](https://cloud.google.com/appengine/docs/flexible/) would give more options for people to deploy

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by chriscoffee** [comment]
I'd like to pick this one up tomorrow.

**Comment by michalpristas** [comment]
Thank you @chriscoffee it's yours

**Comment by arschles** [comment]
@chriscoffee still up for this one? If not I wonder if @marwan-at-work you could do it b/c you do a lot of GCP work? Let me know if not and I'll pick it up after I finish up the preview deployment work

**Comment by arschles** [comment]
I'm going to close this now. We can always re-open if folks are actively deploying to GAE flexible env.  We have GAE standard environment [docs](https://docs.gomods.io/install/install-on-gae/) now as well.
