### ISSUE TITLE
Remove olympus code

### ISSUE THREAD

**Issue by arschles** [gomods/athens#777]
**Is your feature request related to a problem? Please describe.**

As of #772 we're focusing on a global proxy and not on a registry. the code in `cmd/proxy` is the former and `cmd/olympus` is the latter.

**Describe the solution you'd like**

I'd like us to remove the code in `cmd/olympus` and other related things that only the `cmd/olympus` code relied on.

**Describe alternatives you've considered**

None

**Additional context**

Ref #612

**Comment by steakunderscore** [comment]
I can take this on as a first PR :)

**Comment by michalpristas** [comment]
@steakunderscore feel free to split it into multiple PRs if it makes it easier
