### ISSUE TITLE
TODO: Registry architecture and considerations

### ISSUE THREAD

**Issue by arschles** [gomods/athens#79]
We need an issue that lays out the current architecture of the registry and considerations we need to think through in the near future for the registry (similar to #78).

To start, I know we'll need to figure out how to save the CDN metadata and upload module metadata & code to the CDN, atomically. A bit more detail about that in https://github.com/gomods/athens/issues/50

**Comment by michalpristas** [comment]
@arschles probably for closing as well

**Comment by arschles** [comment]
@michalpristas 👍 

Background for other readers: as of #772, we're not going to try and build a registry for the time being, so we don't need docs for that
