### ISSUE TITLE
Can we somehow auto-merge PRs?

### ISSUE THREAD

**Issue by arschles** [gomods/athens#793]
We currently have some criteria that GH enforces for when we can merge PRs: 

- Our 3 status checks: netlify builds, travis-CI builds and the WIP bot (see #792 for details on the bot)
- we need 1 reviewer to sign off

Even after all of our criteria have been met, a maintainer still has to go and manually merge the PR, and that's just extra waiting and work that would be great if we didn't have to do. I'm not sure if there's a service out there that can do auto-merges for us. Otherwise, we could build something or wait for [GH Actions](https://github.com/features/actions) to be enabled on our organization

**Comment by robjloranger** [comment]
I think the only problem is how to differentiate between reviews that should have a longer period so more people can review. Really big changes and the like.

**Comment by arschles** [comment]
yep absolutely. I haven't thought this through much, maybe in the comments a reviewer can say something like `add @someone` to indicate that there needs to be another reviewer?

**Comment by robjloranger** [comment]
I was thinking that way as well, or maybe on bigger PRs reviewers should only comment until they are certain they should be the final approval. Like if I see for people have commented approval and I review plus ensure all contents were addressed, then I can approve which triggers the auto merge.

Or something along those lines.

**Comment by michalpristas** [comment]
I think @carolynvs mentioned they have a good process in Helm(?) with one approver writing LGTM another one Approved and it gets merged. Maybe we can think of something like this. Don't know how much their solution is configurable but might be worth to look into that.

**Comment by robjloranger** [comment]
I like that, require x LGTMs and then the next approval can merge.

**Comment by arschles** [comment]
[mergeable](https://github.com/jusx/mergeable) could help us automate this

**Comment by marpio** [comment]
Mergable looks awesome!

**Comment by robjloranger** [comment]
:+1: for mergeable, it looks perfect

**Comment by michalpristas** [comment]
mergable looks awesome 👍

**Comment by chriscoffee** [comment]
+1 for mergeable. It clearly has the coolest logo which is the biggest factor in my choice.

**Comment by robjloranger** [comment]
I think once we get this set up it should also block `do-not-merge` and `frozen` (if we add that tag)

**Comment by arschles** [comment]
Closing because we’re doing pretty well with reviews and manually merging.
