### ISSUE TITLE
Feature: Serve as vanity host

### ISSUE THREAD

**Issue by bketelsen** [gomods/athens#8]
as a registry service, provide vanity hosting for modules under a given set of domain names.

Using this service, VCS would be insulated from the end user.  As an example if we host at gomods.io, users can register modules with vanity domain names -- also serving as the canonical import path for the module.

```
package captainhook // import "gomods.io/captainhook"
```
This functionality is separate from, and in addition to the proxy service.

**Comment by arschles** [comment]
I've been just calling this a "registry" - because in theory it wouldn't just need to be vanity names.

We could choose to serve VCS package names (i.e. `gomods.io/github.com/mything/awesomerepo`) if we wanted to in the registry. I proposed some naming rules at https://github.com/gomods/athens/blob/master/DETAILS.md#the-registry

**Comment by arschles** [comment]
Edit: in #19 we added language that says that modules will be available at `gomods.io/$NAME`, where `NAME` is the module name defined in the `go.mod` file. I think this functionality eliminates the need to differentiate between vanity and repository names.

**Comment by robjloranger** [comment]
I agree, can we close this one?

**Comment by michalpristas** [comment]
this was planned to overcome tight coupling between import path and VCS, for example, you have pretty/printer hosted on github. so your import path is `github.com/pretty/printer`
but you don't want that. so using registry you can say I want to use gomods.io. and then we will resolve this to `gomods.io/pretty/printer`
at the point you decide to migrate to gitlab there will be no changes required nor at your nor at dependent packages. 
I dont think we support this. we can register it under the name of module name specified at go.mod - yes for that.
but we're missing the first part. mapping vcs to the domain.
imagine someone asks for gomods.io/pretty/printer for the first time
we don't know its github at this moment, we will try gomods.io and fail

**Comment by arschles** [comment]
I am going to leave this open for now, as this is a planned feature for the longer team. I'm even assigning a milestone to it!

**Comment by arschles** [comment]
we're not going to focus on vanity domains or registry functionality right now. closing now, we'll reopen this in the future if we decide to go there
