### ISSUE TITLE
Host Olympus / Athens

### ISSUE THREAD

**Issue by arschles** [gomods/athens#80]
I'd like us to host the gomods.io (and all of the other hostnames!) inside a Kubernetes cluster. I'd also like to provide the option for anyone else to host their own registry or proxy in their own Kubernetes cluster. By providing all the artifacts someone needs to install Athens (proxy or registry) on their cluster, we can do both at once 🎉!

This is a umbrella ticket for hosting Athens (both the registry and proxy server) -- and providing everything other needs to host Athens -- in Kubernetes:

- Build docker images (#81)
- Create helm charts
    - And uploading to a helm repo? When Athens gets some stability (#82) we might consider putting it into the [official incubator repo](https://github.com/kubernetes/charts/tree/master/incubator)
    - Another option for a place to host is [chart museum](https://github.com/kubernetes-helm/chartmuseum)
- Connect Athens to required external services (CDN, Databases, etc...)

**Comment by arschles** [comment]
This issue is a little bit out of date, but I am leaving the OP as-is. Changes to it:

- We are likely only going to host Olympus
- I am still gonna run the Azure part of the Olympus deployment on Kubernetes long-term. Other deployments, of course, might use some other method of deployment. I just ❤️ Kube
    - Initially, I'm gonna use [azure container instances](https://azure.microsoft.com/en-us/services/container-instances/) because it's easier to get something running quick

**Comment by michalpristas** [comment]
I think this hosts, athens only. Issue want both to be online

**Comment by marpio** [comment]
Btw could we use https://microsoftgoproxy.azurewebsites.net/ for our builds?

**Comment by michalpristas** [comment]
@arschles

**Comment by michalpristas** [comment]
@arschles can we consider this a dupl of #57

**Comment by arschles** [comment]
This is a duplicate of #772 so I'm closing. Also note that we're not going to build a registry (see #777 for more on that).

Also, @michalpristas I've changed #57 to indicate that we just want to do docs for ACI
