### ISSUE TITLE
Ability to go to a another proxy if not found

### ISSUE THREAD

**Issue by gcstang** [gomods/athens#800]
**Is your feature request related to a problem? Please describe.**
Need a way to point to the public repository and if it’s not found default to another i.e. like an internal ?
Or if not found in private point to public repository.

**Describe the solution you'd like**
When you setup a GOPROXY modules should resolve in your private or a public repository.
If you have a private repository then you should be able to have some sort of fall back to another repository. 

Currently:
Developer -> Public Proxy

Possible other Scenarios:
1. Developer -> Private Proxy -> Public Proxy (this could be accomplished in Athens)
2. Developer -> Public Proxy -> Private Proxy  (most likely this would require a local go change)

If this has already been accomplished then documentation should be added to the project.

**Comment by marwan-at-work** [comment]
@gcstang what do you mean by repository? Are you talking about a backend? An actual github repository? VCS vs backend?

**Comment by gcstang** [comment]
by repository I mean a VCS

**Comment by marwan-at-work** [comment]
@gcstang can you provide an example? 
If say you have a dependency called `github.com/userA/pkgB`. This exist in only one domain: github. Why would we go to another VCS if it's not found in github? 

Even so, it wouldn't be possible because the `go` command only knows to go to github.com

**Comment by morya** [comment]
I think it would be a very useful feature.

if working like this.

Athens-A deployed inside company
Athens-B some big website dedicated as public available.
C Final-vcs github and others

So go cmd talks to A, A try B if it doesn’t have it, and B will talk to github if needed.
All working together as a big distributed network.

The client only need to find the right sever to trust.

**Comment by arschles** [comment]
@gcstang do you have any other thoughts on this? Specifically I'm interested in option (2). It looks like you'd like to tell Athens to check a public proxy first, then fall back to a private proxy or VCS?

If so, can you write down a use case?

**Comment by gcstang** [comment]
@arschles basically what I was trying to accomplish by this train of thought was not having to change a proxy all the time on local machines, I'm not sure if that's possible.

First Example: (private -> public)
I'm working on my machine and my proxy internally has one fqdn int.proxy.domain.com:4000  to the company I work at on their network or VPN.  When I leave there and need to use the public repository I have to change to that GOPROXY setting i.e. proxy.domain.com:4000 . It would be nice if we could instead setup the proxy maybe running on a local docker instance to have a fallback instead.  

Second Example: (public -> private)
I'm working on my machine at home and using the public hosted proxy from Microsoft, now I need access to a private repository for work projects.  I would have to either disable the proxy I've been using or change to an internal proxy.  What would be nice here is again some sort of fallback so I can say use the public proxy but also pull from a private one if it's available.  Obviously the private proxy could pull from public VCS's i.e. Github and so on if it's allowed but again when I'm off the company network I would need to change the proxy.

Ideally it would be nice to have some sort of secondary, tertiary proxy or just run a local proxy that I can configure with fallbacks.  Previously I've used Gradle and Ivy that allowed this sort of configuration and it was pretty convenient.

**Comment by arschles** [comment]
@gcstang it seems like the major concern is having to change the `GOPROXY` environment variable when you're at home vs. at work?

If that's the case, could you use `direnv` for now to set that environment variable based on which directory you're in?

Alternatively, if there's enough demand for it, we could extend `ATHENS_GLOBAL_ENDPOINT` to make requests to upstream proxies behind the scenes instead of redirecting. That would allow Athens to try the VPN proxy first, and then the public one second. That is a pretty complex solution though, so I'd like to see if you can solve this issue on your machine first.

**Comment by gcstang** [comment]
@arschles It sounds like you may have answered my issue in slack on 11/29/18
I commented: it would be nice if it would fall back to going direct or if we could run a local copy of athens(via docker for example) that could point at my main athens and if not available fallback

you responded: we have the option to have Athens to fall back to another (we call it “upstream”) Athens so you certainly could run one locally like you said

maybe you could provide more details or a documentation link?

**Comment by arschles** [comment]
@gcstang super sorry for the delay here! Almost 4 months later, here is the documentation for the upstream: https://docs.gomods.io/configuration/upstream/

**Comment by arschles** [comment]
I am going to close this issue for now, but @gcstang if you have more questions or this upstream functionality won't work, can you please comment here or open a new issue? You can as always talk to us on Slack if you like too
