### ISSUE TITLE
There's no link to our GitHub repo from the Documentation site

### ISSUE THREAD

**Issue by arschles** [gomods/athens#804]
**Describe the bug**

We don't have a link to https://github.com/gomods/athens (this repo 😄) from the [docs site](https://docs.gomods/io)

**Expected behavior**

We should have a link at least on the home page, so that people who want to get started, look at code, contribute, etc... can do so

**Comment by monsij** [comment]
I'm in. May I be assigned to it?

**Comment by monsij** [comment]
> **Describe the bug**
> 
> We don't have a link to https://github.com/gomods/athens (this repo 😄) from the [docs site](https://docs.gomods/io)
> 
> **Expected behavior**
> 
> We should have a link at least on the home page, so that people who want to get started, look at code, contribute, etc... can do so

the docs site doesn't have a hyperlink :-)

**Comment by arschles** [comment]
@monsij yes, you absolutely may take this!

And yea, the docs site is docs.gomods.io. I'm not sure I understand your question though - did I answer it?

**Comment by monsij** [comment]
@arschles yes

**Comment by arschles** [comment]
This is done after #936, closing
