### ISSUE TITLE
Should we do windows builds?

### ISSUE THREAD

**Issue by arschles** [gomods/athens#807]
We have a lot of powershell in our repo for doing builds and tests. I don't think we test any of that in Travis-CI, so should we do that? I think we can use [Appveyor](https://www.appveyor.com/) for that

**Comment by michalpristas** [comment]
you also was looking for an exercise for Azure DevOps. Does this seems like a good candidate?

**Comment by marpio** [comment]
@michalpristas yes! azure pipelines has free plan for open source projects (also on windows).

**Comment by kaylangan** [comment]
I'm a Program Manager for Azure Pipelines. Let me know if you have any questions or suggestions. I'm happy to help!
