### ISSUE TITLE
GitHub Actions Ideas Thread

### ISSUE THREAD

**Issue by arschles** [gomods/athens#808]
Personally I can't wait until we can use [GitHub Actions](https://github.com/features/actions) on this project! My TL;DR on actions: a hosted (by GitHub) system where you can run any code (in Docker containers) to respond to any webhook that the repo fires

We don't have access to actions on this repo yet, but I have some ideas on what we can do with them when we do. They're super flexible and I bet we as a community have ALL KINDS of ideas what we can do with them.

Let's keep our ideas in here so we can go and do them when the time comes!

**Comment by arschles** [comment]
Top of my head ideas:

- We can obviously run our tests in an action, and replace Travis-CI (we probably don't need to do this, but it'd be fun methinks)
- We could deploy an Athens server on each commit to a PR, and tear it down after that PR is closed
- We could crawl the docs site to look for dead links
- We could publish a tweet to the [@gomodsio](https://twitter.com/gomodsio) Twitter account when we publish a new GitHub release
- We could build changelogs for new GH releases automatically from commit messages

**Comment by chriscoffee** [comment]
* Check if there's any diff in the docs and deploy only if changes been made.
* Spellcheck/grammar check of docs.
* Probe endpoints on previews
> We could publish a tweet to the @gomodsio Twitter account when we publish a new GitHub release
* This could also include what's been changed with the changelog action you mention below that.

**Comment by arschles** [comment]
@chriscoffee do you have a link to Azurite?

**Comment by marpio** [comment]
@arschles https://github.com/Azure/Azurite

**Comment by chriscoffee** [comment]
Thanks @marpio I was afk! 👍

**Comment by michalpristas** [comment]
@arschles  we talked about Release notes yesterday. so I was thinking maybe we can automate it with actions?
with each tag, we can publish a release notes with a list of Issues (not PRs as PR may fix a typo or another very minor thing)

**Comment by arschles** [comment]
This repository now has actions enabled. I'm going to open a new issue to add some actions alongside our drone / appveyor setup and see how it goes

**Comment by arschles** [comment]
Closing in favor of #1460
