### ISSUE TITLE
Can we pass loggers down the stack via closures?

### ISSUE THREAD

**Issue by arschles** [gomods/athens#809]
**Is your feature request related to a problem? Please describe.**

#537 calls for passing log contexts down the stack (i.e. from handlers down to storage drivers).

I took a try at doing that in #645 but it wasn't too great.

**Describe the solution you'd like**

@fedepaol and @marwan-at-work talked about solving this by passing closures down the stack (see [here](https://github.com/gomods/athens/pull/645#issuecomment-427249684)), so I wanted to create this issue to remind us that's a possibility

**Describe alternatives you've considered**

**Additional context**

I added help wanted and hacktoberfest labels to this issue because I think it would be a good project for someone wanting to get familiar with the codebase. And since this can be done iteratively, we can break the refactor up into small pieces.

**Comment by penDerGraft** [comment]
@arschles I'd like to work on at least a part of this. Is there a way I could get a little more context into the idea here?

**Comment by penDerGraft** [comment]
@chriscoffee we may want to wait until the new entry is actually being used `pkg/download`. I should be able to make a PR for that tonight.
