### ISSUE TITLE
Build and publish docker images for the Athens server 

### ISSUE THREAD

**Issue by arschles** [gomods/athens#81]
We'll need to do this on the road to #57 and #80

**Comment by chrispickard** [comment]
both olympus and the proxy have dockerfiles, what else needs to happen for this issue?

**Comment by michalpristas** [comment]
I think this issue covers official docker images on docker repo available for anybody to download.

**Comment by arschles** [comment]
@chrispickard sorry for the extremely late response on this. What @michalpristas said is correct - it would be adding something to CI/CD in order to build/push our docker images up to dockerhub

**Comment by arschles** [comment]
Ref #421

**Comment by arschles** [comment]
Also, note that https://github.com/gomods/athens/pull/475 is setting the default storage to in-memory, so that users can have a good first-time experience (i.e. no need to set up directory structures, no need to set up Mongo, etc...)

Once docker images are published, maybe we could make the (or one of the) first-time setup tutorials use `docker run` with a different storage driver (like disk?)

**Comment by mydiemho** [comment]
I would like to take this on.  How do I get access to our CI/CD?

**Comment by robjloranger** [comment]
For CI you can add a script, preferably to the `./scripts` directory, and then add a step to the `.travis.yml` for build and deployment. You will 

For details on deployment see https://docs.travis-ci.com/user/deployment

For an example `.travis.yml` used for docker deployment and testing check out the [travis docs](https://docs.travis-ci.com/user/build-stages/share-docker-image/).

You will need to talk to @arschles or maybe someone else about getting credentials for the docker hub account. These credentials will need to be encrypted for security, see https://docs.travis-ci.com/user/encryption-keys/

**Comment by carolynvs** [comment]
I'll get the credentials for the docker registry into our travis build if it's not there already. @mydiemho Ping me if you need help on this! 😀

**Comment by carolynvs** [comment]
@mydiemho I apologize for jumping on this but it rose in priority with GopherCon getting close, and because it simplifies our documentation so much. I'll be opening a PR shortly to get this implemented, and would appreciate your comments on it!

**Comment by mydiemho** [comment]
@carolynvs no worry, this will be a good learning experience for me.  Would love to pair with you on another issue next time :D
