### ISSUE TITLE
Clean Up Config File

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#813]
Now that Olympus is out of the code base and we have a good idea of what the Proxy looks like, I'd like to do some cleaning up of the Config.go file: 

- [x] Remove CSRF middleware/option (the Proxy is just an API)
- [x] Remove unnecessary functions in the config parser: `setRuntimeDefaults` and `deleteInvalidStorageConfigs`
- [x] Include one Timeout instead of many? For simplicity sake. 
- [ ] Simplify tests: we don't need to test every single field in the config, we just wanna test behavior: env > toml. That's it. 

Please let me know if you'd like to change any of the above or add more to the list :)

**Comment by marpio** [comment]
Are you on it @marwan-at-work ? If not I would like to take this one.
One question though - `deleteInvalidStorageConfigs` removes the empty structs which `envconfig` creates so that config validation in the next step doesn't fail.
Did you mean to exclude the storage field from validation or validate only if i.e. `s.Minio != Minioconfig{}` ?

**Comment by marwan-at-work** [comment]
@marpio I keep forgetting that weird thing about envconfig affecting validations...We can do two things: 
1. Maybe let's just a big comment on top of `deleteInvalidStorageConfigs` that says "we do this because envconfig instantiates all storages and therefore their validations will fail"
2. Remove that function, and only validate the storage once we know what "storage type" is present.

**Comment by marwan-at-work** [comment]
@marpio I'm already working on the tests part, so that shouldn't affect the rest of the check boxes if you wanna take em. Lemme know!

**Comment by arschles** [comment]
This looks to be done after #860, closing
