### ISSUE TITLE
Support for Metrics using Prometheus

### ISSUE THREAD

**Issue by bhaveshpraveen** [gomods/athens#816]
**Is your feature request related to a problem? Please describe.**
Only Tracing is currently supported. It'd be nice to also track metrics.
**Describe the solution you'd like**
Export metrics to prometheus 
Reference: https://opencensus.io/guides/exporters/supported-exporters/go/prometheus/

**Comment by bhaveshpraveen** [comment]
I'd like to work on this.

**Comment by bhaveshpraveen** [comment]
Ok. Will do.

**Comment by manugupt1** [comment]
Let me know if you need help and I can chime in!

**Comment by arschles** [comment]
@bhaveshpraveen are you still interested in tackling this?

**Comment by bhaveshpraveen** [comment]
Yeah. I've been a bit occupied with my university work. I'd still like to work on it. It's totally fine if someone else wants to work on this. Peace.

**Comment by arschles** [comment]
@bhaveshpraveen it's totally fine for you to work on it. If you can, let us know if you're still interested
