### ISSUE TITLE
Build other CDN drivers

### ISSUE THREAD

**Issue by arschles** [gomods/athens#83]
There are two pieces of CDN storage:

- Functionality that uploads stuff to the CDN itself ("storage drivers")
- Functionality that saves and fetches metadata about the CDN ("metadata drivers")

Storage drivers and metadata drivers can be mixed and matched. For example, you can use Azure CDN storage drivers with MySQL metadata drivers, Google Cloud Storage with Mongo, and so on...

The issue for adding more metadata drivers is #147. This issue is about adding more storage drivers for CDNs.

We're initially planning to use Azure CDN (https://github.com/gomods/athens/issues/29), but it would be nice to implement other [CDN drivers](https://github.com/gomods/athens/tree/master/pkg/cdn). They will need to support something like the atomicity features described in https://github.com/gomods/athens/issues/50

Ones I think we should do:

- Azure CDN (#29)
- Google Cloud Storage (#158)
- AWS S3 (#159)

**Comment by arschles** [comment]
Azure CDN is done! 🎉

**Comment by robjloranger** [comment]
I'm not sure about s3 but the gcp driver currently does not apply any atomicity precautions so leaving this open as a reminder

**Comment by michalpristas** [comment]
closing, we're not using cdn storage anymore
