### ISSUE TITLE
Proposal: build separate binaries for proxy & registry

### ISSUE THREAD

**Issue by arschles** [gomods/athens#84]
We have a growing set of logic that's basically `if proxy { ... } else { ... }` which will be growing over time. I believe we're better served building separate binaries (i.e. having two `main()` functions), one for the proxy and one for the registry (and others for components to come if necessary). We already have a `cmd` directory, so my proposal is to create a `cmd/proxy` and a `cmd/registry`, and to house buffalo app inside of each directory. Common code should still be shared via the packages inside `pkg/`. Finally, I want to keep proxy, registry, and other code inside of a single repository.

**Comment by bketelsen** [comment]
how could we keep the existing "buffalo dev" workflow?

**Comment by bketelsen** [comment]
we can experiment and see how much "buffalo dev" is tied to the layout of the project.

**Comment by arschles** [comment]
My original thought was to put a full buffalo application into each of `cmd/proxy` and `cmd/registry`, so you would run `buffalo dev` inside of either directory. This fits nicely into the standard buffalo tooling without any modifications.

The only thing that I'm sure of with `buffalo dev` itself is that it needs the `.buffalo.dev.yml` to run, and I think it needs a `main`. I know you and @markbates figured some things out and I'm not caught up on that.

I'd just advocate for keeping plain `buffalo dev` without any additional setup (besides DB setup) on the machine. In other words, I'd like to keep the workflow this:


```console
# do this once
$ git clone git@github.com:gomods/athens.git
$ cd athens
$ docker-compose up -d
$ buffalo db migrate up

# now do this as many times as you want
$ buffalo dev
```

(note - our README describes almost all of this flow, except for the `buffalo db migrate up` part)

**Comment by markbates** [comment]
I agree with Aaron. Also, you could make a grift task in Athens that did all the docker, migration, seed, etc… then no matter happens the docks say run `buffalo t setup` the first tome. :)

**Comment by arschles** [comment]
ooooh, the grift for all the migration etc... is an _awesome_ idea. thanks @markbates!

**Comment by arschles** [comment]
I'll take this one

**Comment by bketelsen** [comment]
See #87, close together

**Comment by michalpristas** [comment]
#91 fixes this, closing
