### ISSUE TITLE
Build the commit SHA / Tag into the built Athens binary

### ISSUE THREAD

**Issue by arschles** [gomods/athens#842]
**Is your feature request related to a problem? Please describe.**

#830 has some doubt whether we're building and pushing the right docker image on CI builds. We can kinda sorta try and figure out whether there's a problem with trial and error and hand-inspecting the script that pushes, but it's not ideal and it's hard to be sure/

**Describe the solution you'd like**

It would be ideal if the binary could tell us what commit it was built from. That way we could go into GH and find the code that built it. Added bonus if we can also build with the tag, if there was one. We can then print out the SHA/tag on the homepage of the proxy (and/or other pages) and maybe build a `version` command into the CLI too

**Describe alternatives you've considered**

Nothing much. I've seen this done in lots of other Go programs so it's tried and true.

**Additional context**

#830 got me thinking about this.

**Comment by robjloranger** [comment]
This sounds fun.

Can we assume git is installed, or should we use a library?

Would an endpoint that returns json be most useful? I'm thinking so as then the eventual front end and any other services that wish to report the information can use it as they like.

:+1: for the cli `version` option

**Comment by robjloranger** [comment]
I'll work on this
