### ISSUE TITLE
Is there a better time for dev meetings?

### ISSUE THREAD

**Issue by arschles** [gomods/athens#852]
We hold the [weekly development meeting](https://aka.ms/athendevmeeting) in the mid-morning time for the western US. This is in the evening for european community members and in the afternoon for the eastern US. People have jobs & lives, so I'd like to find out if there is:

1. A better single time for the dev meetings
1. A need/want for a second dev meeting that's better for folks in non-western-US time zones
1. No need to change anything, the recordings/async workflow/etc... is ok

I am gonna put these options below.

**If you want to have your say, can you please vote on one of them?**

**Comment by arschles** [comment]
I think there's a better single time for the dev meetings (we'll figure out the better time if this gets the most votes)

**Comment by arschles** [comment]
Vote here if you would like a second dev meeting that's better for folks in non-western-US time zones (we'll figure out when it should happen if this gets the most votes)

**Comment by arschles** [comment]
Vote here if you think there's no need to change anything, the recordings/async workflow/etc... is ok

**Comment by michalpristas** [comment]
I would be very strongly against the second meeting. i think it might lead to exclusion rather than inclusion. 
i would like to hear @Kunde21 opinion as well on this. 
Maybe we could set up a biweekly schedule where one week would be more suitable for west-us another week for people from eastern europe/asia

**Comment by arschles** [comment]
regarding the second meeting, that makes sense @michalpristas

**Comment by chriscoffee** [comment]
I'm personally happy with the current developer meeting time (GMT). I'd also be happy to have a rotating schedule that @michalpristas suggested, just a bit of calendar changes

**Comment by nunix** [comment]
same as @michalpristas, it would be nice to have only one meeting and concerning the time, with the winter time, I think it will fit pretty well everyone

**Comment by Kunde21** [comment]
In ASEAN, the current meeting time is unworkable (around midnight) and I've found it quite difficult to stay in the communication loop.  

@michalpristas idea of a two-week schedule is probably the best solution to cover more timezones.

**Comment by arschles** [comment]
I'll close this and open up a new issue regarding doing the two-week rotation of times
