### ISSUE TITLE
Test_checkFilePerms fails on Windows

### ISSUE THREAD

**Issue by marpio** [gomods/athens#879]
**Describe the bug**
Test_checkFilePerms fails on Windows

**Error Message**
https://dev.azure.com/gomods/athens/_build/results?buildId=12&view=logs

**To Reproduce**
Execute tests on Windows

**Environment (please complete the following information):**
 - OS: Windows Server 2016

**Comment by marpio** [comment]
`os.Chmod(...) ` doesn't work on Windows so the Test is failing because of that.
The question is, would it be okay to disable the test on Win? Or should we set the permissions manually?

**Comment by michalpristas** [comment]
Let's disable until we find a workaround. 
According to the docs: 
> 0200 owner writable, 0400 for a read-only file and 0600 for a readable+writable file.

maybe, as a workaround we can have different implementation for win/unix
unix is what we have 
win would require 0200 
then we would have a switch on runtime.GOOS 
same with tests

**Comment by manugupt1** [comment]
Can I give a hotfix to this one?
