### ISSUE TITLE
Add support for aws credentials file

### ISSUE THREAD

**Issue by t-tomalak** [gomods/athens#882]
**Is your feature request related to a problem? Please describe.**
Some users when running Athens with S3 storage want to use aws default configuration aka `.aws/credentials`. Unfortunately we can't omit validation of our storage parameters from configuration file (or could we in that case?)

**Describe the solution you'd like**
1. We can drop `required` flag on every parameter of `S3config` and check config inside `New` method in `storage/s3`. 
2. We can create alternative s3 storage which will don't require any configuration(what name should it have?), also we will add seperate `New` method inside S3 storage for that.

**Describe alternatives you've considered**
We could also move this credentials as we do with .netrc and .hgrc files https://github.com/gomods/athens/issues/716

**Additional context**
https://gophers.slack.com/archives/C9LRAQN8N/p1541454892427000

**Comment by markopotamus** [comment]
I'd like to work on this.

**Comment by markopotamus** [comment]
Do you just want access to the default profile in the credentials file, or do you want to be able to specify any profile?

**Comment by manugupt1** [comment]
Hi @markopotamus Welcome! 

What do you think of this flow:

If the proper env vars are not defined,
then look for the default to start off with. 

We need to think about the order of
env var, profile, default (the easiest understandable format)

Until then, let us just go with the default unless you have worked with any of these and have an idea on how to proceed with it.

**Comment by markopotamus** [comment]
I'll prefer the access key id and secret access key if they're specified in the S3 config.  I'll add an optional profile field to the config (it maps to the AWS_PROFILE env var).  If it's left blank, I'll use the default profile.

**Comment by manugupt1** [comment]
Let us not have profile for now please. Too many options for the user, imo.
