### ISSUE TITLE
Create an HTTP endpoint that outputs the build version of the proxy

### ISSUE THREAD

**Issue by arschles** [gomods/athens#886]
**Is your feature request related to a problem? Please describe.**

#866 compiles the build date and version into the proxy binary. There's no way to get that from a running proxy, though

**Describe the solution you'd like**

We should expose the build info via an HTTP method.

**Additional context**

Follow-up from https://github.com/gomods/athens/pull/866#issuecomment-436134211

cc/ @marpio @robjloranger @manugupt1

**Comment by robjloranger** [comment]
This could possibly be part of the health endpoint, it just needs to return 200 for health check so could combine with some json or simple string info.

**Comment by marpio** [comment]
I would rather create an explicit endpoint for the version info, just to make it clear.
We could also return versions of the components we're using i.e. go, VCSs, storage.

**Comment by robjloranger** [comment]
I'll work on this. How about a `/version` endpoint that lists the server version for now and we can add more fields to the response body as we implement the availability of other data.

I'm thinking JSON response.
