### ISSUE TITLE
Add documentation on how you can build a proxy binary with your own version & build date

### ISSUE THREAD

**Issue by arschles** [gomods/athens#887]
**Is your feature request related to a problem? Please describe.**

#866 automatically compiles the build version and date into the proxy binary. Some folks might want to build their own binaries with their own version/date though.

**Describe the solution you'd like**

We should add docs on how to do that.

**Additional context**

Follow-up on https://github.com/gomods/athens/pull/866#issuecomment-437212928

cc/ @manugupt1 @robjloranger @marpio

**Comment by marpio** [comment]
I would like to take that.

**Comment by robjloranger** [comment]
@marpio note that the date is set in the dockerfile. And may change, I'm working on fixing an issue with docker builds failing on Travis.
