### ISSUE TITLE
Cookies are being sent to the client

### ISSUE THREAD

**Issue by arschles** [gomods/athens#890]
**Describe the bug**

When an API request is sent to the proxy, it responds with `Set-Cookie` headers, for example:

```console
➜  proxy git:(compose-all) ✗ curl -v localhost:3000/github.com/arschles/assert/@v/list
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 3000 (#0)
> GET /github.com/arschles/assert/@v/list HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: no-cache, no-store, must-revalidate
< Content-Type: text/plain; charset=utf-8
< Set-Cookie: _athens_session=MTU0MTgwNTYyM3xEdi1CQkFFQ180SUFBUkFCRUFBQU1QLUNBQUVHYzNSeWFXNW5EQTRBREhKbGNYVmxjM1J2Y2w5cFpBWnpkSEpwYm1jTURBQUtWSFp5V2tWNWFIUnBWUT09fMDRCneo54iwmrpMwsUD0bljIqMupTiDbSWPOAL90wDV; Path=/; Expires=Sun, 09 Dec 2018 23:20:23 GMT; Max-Age=2592000
< Set-Cookie: _athens_session=MTU0MTgwNTYyNHxEdi1CQkFFQ180SUFBUkFCRUFBQVVQLUNBQUlHYzNSeWFXNW5EQWtBQjE5bWJHRnphRjhIVzExMWFXNTBPQW9FQUFKN2ZRWnpkSEpwYm1jTURnQU1jbVZ4ZFdWemRHOXlYMmxrQm5OMGNtbHVad3dNQUFwVWRuSmFSWGxvZEdsVnyURG4GqaGXxQq_YUcK-_PPlKtf7FTESYuipl1VGjM3-Q==; Path=/; Expires=Sun, 09 Dec 2018 23:20:24 GMT; Max-Age=2592000
< Vary: Origin
< Date: Fri, 09 Nov 2018 23:20:24 GMT
< Content-Length: 6
< 
* Connection #0 to host localhost left intact
v1.0.0%
```

**To Reproduce**

Run the `curl` command (or equivalent with other tools) above in the example console output, and notice the `Set-Cookie` headers in the response.

**Expected behavior**

I don't think we have any technical reason to return cookies from our API calls, and I don't think that the proxy should return `Set-Cookie` headers from any API request.

Some cloud-based caching proxies, like [Google Cloud CDN](https://cloud.google.com/cdn/docs/caching) will refuse to cache responses that include `Set-Cookie` headers. Other cloud-based and open source caching proxies vary on their behavior for cookie based responses.

**Environment (please complete the following information):**
 - OS: Mac OS X, 64 Bit
 - Go version: 1.11.1
 - Buffalo Version : 0.13.0
 - Proxy version : a44291793d195015d14406ffa927200837dc3d86

**Additional Context**

I am doing some research & prep for #772. Caching proxies will help us out a lot because we can cache lots of our API responses for a long time. That caching could take a tremendous amount of request load off of proxy servers for a global deployment, so I think it's really important for us to be able to take advantage of caching proxies.

**Comment by manugupt1** [comment]
Since we have an API based interface and plan to return JSON responses, I would think that this is a bug.
