### ISSUE TITLE
Add liveness and readiness probes for Kubernetes

### ISSUE THREAD

**Issue by arschles** [gomods/athens#891]
**Describe the solution you'd like**

The proxy can implement an endpoint that Kubernetes [liveness / readiness probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/) can use to figure out if the proxy is running and healthy.

I think we should implement the endpoint in the proxy and configure the helm chart to use it.

**Additional context**

I'm researching and preparing for #772 and found that this would be really helpful for us.

**Comment by marpio** [comment]
@arschles we already have the `/healthz` endpoint. Do we need to modify it somehow or do we need something different additionally?

**Comment by robjloranger** [comment]
I think the `/healthz` endpoint covers the `liveness` probe.

I'm uncertain what we would do different for a `readiness` probe. Maybe an enpoint that checks outgoing network connectivity or backing storage availability.

**Comment by manugupt1** [comment]
Would it not be different if you have several proxy server's running and one of them s down, but others are running on the same cluster?
