### ISSUE TITLE
Add support for Azure App Insights

### ISSUE THREAD

**Issue by arschles** [gomods/athens#895]
**Is your feature request related to a problem? Please describe.**

Our distributed tracing setup doesn't support [Application Insights](https://cda.ms/JT), and it looks like we don't use the default exporter either.

**Describe the solution you'd like**

I'd like to add support specifically for Azure AppInsights, but in doing so we'd also start using the default exporter (according to https://opencensus.io/exporters/supported-exporters/go/applicationinsights/)

**Describe alternatives you've considered**

Not much

**Additional context**

In order to get this to work, we'll need a few things besides the new code:

- The local forwarder (described [here](https://cda.ms/JT), and dockerized by @bketelsen [here](https://github.com/bketelsen/censusai))
    - We'd add this to our docker-compose file for local testing
- Add the local forwarder as a sidecar to our pods in production, or as a single pod like we do with Jaeger

**Comment by arschles** [comment]
Resources to checkout:

- https://github.com/bketelsen/censusai
- https://docs.microsoft.com/en-us/azure/application-insights/opencensus-go

**Comment by jedruniu** [comment]
I'll take this one.

**Comment by chriscoffee** [comment]
Awesome @jedruniu! 

It looks like @arschles has already done some stuff if you want to look at that or build from it.

@arschles you still working on this or cool for @jedruniu to pick it up?

**Comment by arschles** [comment]
@chriscoffee sorry for the delay, I'm not actively doing anything on this

@jedruniu it's all yours!

**Comment by jedruniu** [comment]
Great!

**Comment by DrPsychick** [comment]
closing as "gone cold", please reopen if it's still an issue
