### ISSUE TITLE
Fix golint issues

### ISSUE THREAD

**Issue by marpio** [gomods/athens#90]
At the moment, golint $(go list ./...) reports quite a few issues (missing  comments and stutters).
We should run golint with -set_exit_status flag after they are fixed - see #85

**Comment by michalpristas** [comment]
calling dibs on this one, unless @marpio you want to work on this one

**Comment by marpio** [comment]
@michalpristas to be honest I don't think I have a good enough overview to write meaningful  comments so take it please! It would be great if you could modify travis.yaml to run with -set_exit_status as well so that we don't have to repeat this.

**Comment by arschles** [comment]
@marpio if you'd like we can chat offline about writing meaningful comments and I can help! comment here or DM me on Gophers Slack (I'm arschles) if you're interested. Would love to help

**Comment by michalpristas** [comment]
depending on timezone you can do the same exercise with me, whatever suits you better

**Comment by michalpristas** [comment]
depending on timezone you can do the same exercise with me, whatever suits you better, i'm central europe, aaron is pacific timezone

**Comment by marpio** [comment]
@michalpristas  Ok, great! I'll do my best. I'm also in the central europe timezone so I will probably ask you.

**Comment by michalpristas** [comment]
great! i'm on slack most of the time. we can even schedule a call if you have questions
