### ISSUE TITLE
Temporarily Turn Off Automatic Docker Push For Tagging/Releases

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#905]
### Issue

Our push-to-dockerhub-on-merge has been more buggy than functional. So I suspect the same can happen when we fire up a release. 

If the next release doesn't work (screws up the docker push && tag process), our only two options to mitigate are: 

1. Fix the problem, and force-push the same tag. 
2. Fix the problem, and create a new tag. 

Both are not good options. 

### Solution

At least for the first few releases, we should make things manual. We should just build the Dockerfile locally, and push a new tag to the `gomods` organization on Docker Hub.

**Comment by marpio** [comment]
I think it would be okay to do this manually for the first release but it shouldn't be a long term solution. Doing things manually isn't less error prone from my experience (i.e. it's easy to forget to pass the version ARG to the docker build).
We should find a way to test the process (at least most of it) on PRs.
@carolynvs added the docker build make target to the PR build here:
https://github.com/gomods/athens/pull/903/commits/15d406d2b95cd257ae0d3e4fe9fb3a3c674df78e

Maybe we could split the `push-docker-images.sh` and execute everything until `docker push` on each PR?

**Comment by carolynvs** [comment]
I'm the evil turd who wrote the docker push on merge. 😀 Can I help? If you let me know what's buggy, I'm sure it's fixable. I'd really hate to turn that functionality off (permanently).

**Comment by marwan-at-work** [comment]
Good point, I definitely didn't mean permanently (updated the issue title). 
@marpio if we forgot the build-arg, then we can catch that locally before pushing the new tag to docker hub. In other words, whoever issues the release should actually test things before pushing the tag. 

@carolynvs there's nothing in mind about why it's not working, but you can see over time here that it hasn't been very stable: https://github.com/gomods/athens/issues?utf8=%E2%9C%93&q=is%3Aissue+fix+ci (not all issues in the search results, just the ones that mention docker push) 

@carolynvs If you're comfortable with the scripts in place, let's definitely keep them. Maybe I can bother you during the release in case I don't know why something failed?

**Comment by carolynvs** [comment]
I volunteer as tribute for today's release on-call if docker push fails.

**Comment by robjloranger** [comment]
I'm free through the day today as well. It's a holiday for me.

**Comment by marwan-at-work** [comment]
@robjloranger @carolynvs thank you both!
