### ISSUE TITLE
Ability to set MongoDB database name

### ISSUE THREAD

**Issue by chriscoffee** [gomods/athens#906]
**Is your feature request related to a problem? Please describe.**

I deployed athens to heroku. If I wanted to use the sandbox mLab offering of mongoDB for example I'd have to take their automatically generated database name (something like `heroku_aowd89adw` which wouldn't be `athens`. `athens` is currently required by this storage driver implementation.

At the moment we hardcode the database name as [`athens`](https://github.com/gomods/athens/blob/f776bc66671f5d58e6346ed7d540b989c84d9709/pkg/storage/mongo/mongo.go#L59) and there's a `TODO` to make a better solution.
 
**Describe the solution you'd like**

Either creating environment variables for the database inline with our current environment variable naming or my preffered solution is reading the `[/database]` from `mgo.ParseURL` 

**Describe alternatives you've considered**

Leave it as it'd be and force users to have `athens` as their database name.

**Additional context**

Some discussion around the subject https://gophers.slack.com/archives/C9LRAQN8N/p1542026809792000

**Comment by michalpristas** [comment]
I would go with this
- use mgo to parse out db name in mongo pkg so we don't bloat config package with unnecessary dependencies 
- if info.db is not set then use newly introduced `config.Mongo.DefaultDBName` which is set by ENV, is not required and defaults to `athens`

this way we give a solution for people preferring one way or another at the same time

**Comment by chriscoffee** [comment]
I'll take this for myself!

**Comment by manugupt1** [comment]
@chriscoffee Are you still on this?

**Comment by chriscoffee** [comment]
@manugupt1 yeah mate I'll put the PR in tomorrow or later tonight, just been busy recently sorry.
