### ISSUE TITLE
DropDups is silently ignored after MongoDB >2.8

### ISSUE THREAD

**Issue by chriscoffee** [gomods/athens#907]
After some discussion in [#athens](https://gophers.slack.com/archives/C9LRAQN8N/p1542027520801700) we figured out that dropDupes is [no longer available after 3.0](https://docs.mongodb.com/manual/release-notes/3.0-compatibility/#remove-dropdups-option) for `createIndex()`, `ensureIndex()`, and `createIndexes.`

The latest stable version of MongoDB is 4.0.

Should we consider dropping this or continue to support it to allow some backwards compatibility? And should it be true?

For those wanting to know what DropDups does:
`DropDups   bool     // Drop documents with the same index key as a previously indexed one`

**Comment by michalpristas** [comment]
i think with other storage implementations we return error with module already exists we should do the same here
