### ISSUE TITLE
Update default path for proxy config file

### ISSUE THREAD

**Issue by leitzler** [gomods/athens#914]
The current default path to the config file is `../../config.dev.toml` regardless from where you start the proxy.

I'd suggest to use a more generic name for the file, as `config.toml` and also either skip the path entirely or even better use (per OS) specific config path. E.g.:

 OS | Path |
 ---- | ---- |
 Linux | `$XDG_CONFIG_HOME` |
 macOS | `~/Library/Application Support/` ([details](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/MacOSXDirectories/MacOSXDirectories.html)) |
 Windows | `%LOCALAPPDATA%` |

**Comment by robjloranger** [comment]
`$XDG_CONFIG_HOME` should probably just be `$HOME` as not all Linux distros support the base directory specification.

**Comment by michalpristas** [comment]
what about multiple valid paths with priority, on load config init would check each of them
```
./config.toml
{homeDir}/config.toml - {homeDir} resolved based on OS
/etc/athens/config.toml - on linux
../../config.toml
```

I do not mind to rename to `athens.config.toml` especially with homedir involved

**Comment by robjloranger** [comment]
For Linux if it's in the home directory, priority should be [`.athens.config.toml`, `.config/athens/config.toml`, `/etc/athens/config.toml`] or similar but in that order. Home then home relative config directory then system level. However system level config directories are not standardized across distributions.
