### ISSUE TITLE
Link to https://docs.gomods.io/public_proxy results in 404

### ISSUE THREAD

**Issue by mewmew** [gomods/athens#915]
The link to https://docs.gomods.io/public_proxy from https://docs.gomods.io/ results in a 404 error.

> We also run an experimental server for public use, so you can get started with Athens without even installing it. For details, see [here](https://docs.gomods.io/public_proxy).

**Comment by chriscoffee** [comment]
Hey @mewmew. Thanks for opening this ticket! We're currently running a public version of it at https://athens.azurefd.net but this may change as it may become unstable or disappear completely as we release v0.2.0/0.3.0

I'll get the docs update now, unless you'd like to do it? 👍

**Comment by mewmew** [comment]
Hi @chriscoffee!

Thanks for the note. Feel free to update the docs :) I couldn't find a gh-pages branch, or which specific repo handled the site (only skimmed briefly).

Cheers,
Robin

**Comment by chriscoffee** [comment]
No worries @mewmew Thanks. 

I'll get those updated.

**Comment by robjloranger** [comment]
Hey @chriscoffee, just checking in on this one. If your busy, would you prefer someone else to take it for you?

**Comment by chriscoffee** [comment]
Apologies @robjloranger. I've put in the PR now.

**Comment by robjloranger** [comment]
no apology needed, just checking in 😀
