### ISSUE TITLE
better reference documentation is needed

### ISSUE THREAD

**Issue by rogpeppe** [gomods/athens#921]
There are some helpful examples in the introductory web page, but there should really be a full definitive reference for all the Athens configuration and command line syntax. For example, the only place to find out what environment variables are supported is [this page](https://github.com/gomods/athens/blob/master/config.dev.toml) which doesn't seem to be linked to anywhere.

**Comment by arschles** [comment]
@rogpeppe do you think that linking to https://github.com/gomods/athens/blob/master/config.dev.toml would be a good first pass at this? I ask because it's the source of truth for our config vars - we make sure to add documentation for each new config variable we add

**Comment by rogpeppe** [comment]
Thanks, that's certainly a good start, thanks, although I think ideally it would be nicer to have the possible values nicely formatted in the main documentation, and with appropriate links to external resources (for example FilterFile could point to the docs for the filter file syntax; DownloadMode could point to the docs for whatever an HCL file is (I don't know...))

**Comment by arschles** [comment]
Sounds good. I updated the PR to reflect what you said, thanks @rogpeppe !
