### ISSUE TITLE
Pull module feed periodically from Olympus

### ISSUE THREAD

**Issue by michalpristas** [gomods/athens#93]
Prepare a long-running background task which will periodically ask Olympus what's new providing last synchronization point

Proxy needs to makes initial sync request to olympus.golang.org to learn its affinity to Olympus deployment e.g amazon.olympus.golang.org

Olympus recognizes that proxy is asking for the first time and responds with following information:
- entire log
- sequence_id: which serves as a pointer to latest served entry of the log
- olympus_host: with DNS entry of OM 

Prereq: #100

**Comment by arschles** [comment]
Note that for production deployments, this should be a separate process and not just a goroutine - we should not run it in the same process (i.e. as a goroutine) as the olympus server
