### ISSUE TITLE
Goreleaser failed on v0.2.0 tag build

### ISSUE THREAD

**Issue by marpio** [gomods/athens#931]
**Describe the bug**
Goreleaser failed on v0.2.0 tag build. See: https://travis-ci.org/gomods/athens/builds/454139475#L1637

**Error Message**

<pre>
release failed after 0.03s error=git is currently in a dirty state:
?? .minio.sys/
?? codecov
?? gomods/
?? gomodsaws/
?? minio
</pre>

**Expected behavior**
Raw binaries should be created and published to GH.

**Comment by arschles** [comment]
In the Dec 6, 2018 meeting we discussed this:

- Removing goreleaser and favoring the docker images as the way to run Athens (or on Kubernetes/etc systems that run Docker images)
- Adding docs for how to build versioned binaries from source
- Adding a makefile target for building a versioned binary from source
- Closing this issue
