### ISSUE TITLE
Error With Beta Deployment On Microsoft Cloud

### ISSUE THREAD

**Issue by marwan-at-work** [gomods/athens#935]
If you run the following from a given project (make sure your local cache is removed) 

```
GOPROXY=https://athens.azurefd.net go get github.com/gobuffalo/buffalo-pop@v1.1.2
```

You get this error

```
go: github.com/gobuffalo/buffalo-pop@v1.1.2: unexpected EOF
go: error loading module requirements
```

This error shouldn't happen I think. 

It would be great for whoever has access to see how this error happened since it's potentially an Athens bug in beta. 

cc @arschles

**Comment by PascalDierich** [comment]
following the instructions I get this error
```
go: github.com/gobuffalo/buffalo-pop@v1.1.2: unexpected EOF
go: github.com/gobuffalo/genny@v0.0.0-20181019144442-df0a36fdd146: unexpected EOF
go: github.com/gobuffalo/genny@v0.0.0-20181007153042-b8de7d566757: unexpected EOF
go: github.com/gobuffalo/buffalo@v0.12.8-0.20181004233540-fac9bb505aa8: unexpected EOF
go: github.com/gobuffalo/buffalo-plugins@v1.6.1: unexpected EOF
go: error loading module requirements
```

**Comment by marpio** [comment]
`GOPROXY=http://localhost:3000 go get github.com/gobuffalo/buffalo-pop@v1.1.2`
This work fine with `v0.2.0` and `mongodb`

**Comment by marwan-at-work** [comment]
@marpio works ok locally, but broken on the deployment. I'm curious how/why.

**Comment by arschles** [comment]
The MS deployment is having a lot of problems right now. I'm not sure the extent of them, but I'll look into this as soon as I can.

**Comment by DrPsychick** [comment]
closing as "gone cold", please reopen if it's still an issue
