### ISSUE TITLE
Create test that ensures the stored modules are immutable

### ISSUE THREAD

**Issue by marpio** [gomods/athens#946]
It would be nice to have a test described in #885 - `go get` a module by commit, then delete that commit and try to `go get` it again. This should work since the version should be stored.
We could use the https://github.com/athens-artifacts repo.

/cc @manugupt1

**Comment by marpio** [comment]
Alternatively we could write a unit test that checks just that as mentioned on Slack [here](https://gophers.slack.com/archives/C9LRAQN8N/p1543431320470200)

**Comment by manugupt1** [comment]
👍

Cheers
Manu
________________________________
