### ISSUE TITLE
Add support for disabling communication with Olympus

### ISSUE THREAD

**Issue by michalpristas** [gomods/athens#95]
If proxy is used as private there might need to disable communication with Olympus.	
Provide configuration settings with the possibility to change value during runtime. Each following operation will use new configuration value

Check before contacting Olympus	 

Disabling means not reporting cache-misses. Proxy will still try to fetch data from olympus on regular basis and pull modules which pass the filter

**Comment by robjloranger** [comment]
did #212 get us closer to this?

**Comment by michalpristas** [comment]
yes and no, this one should be FCB which disables it without using filters.

**Comment by michalpristas** [comment]
also you cant modify filters during runtime as for now

**Comment by arschles** [comment]
As of #772, we're not going to try and build a registry for the time being, so closing.
