### ISSUE TITLE
Rotation of times for the dev meetings?

### ISSUE THREAD

**Issue by arschles** [gomods/athens#954]
In https://github.com/gomods/athens/issues/852, we talked about changing the time for the dev meeting or having two of them. We decided that we shouldn't change the time and we shouldn't hold two every week.

But the idea did come up to have a rotating time so that the meeting is at a reasonable time on week W for time zone X, and at a reasonable time on week W+1 for time zone Y. For example, we can move from UTC to the east over the month:

| Week | Convenient Time Zones |
| - | - |
| 1 | UTC 0 to 6 |
| 2 | UTC 7 to 12 |
| 3 | UTC -8 to -5 _*_ |

cc/ @michalpristas @chriscoffee @nunix @Kunde21 since you were all active on #852 

_* I skipped over some of the pacific ocean here since we don't have anyone in the community on the east side of the international date line until North American pacific time (currently UTC-8). If that changes, we should add another slot_

**Comment by arschles** [comment]
@fedepaol you mentioned in slack that one hour later than our current time would be doable for you. Is that still the case?

**Comment by arschles** [comment]
I posted a twitter poll to find some other times that work for folks: https://azure-advocacy.slack.com/archives/CADD7EPKL/p1551823850054600

It lasts 7 days (so until March 12, 2019), and when it's done hopefully we'll find another time that we can add to the rotation 🎉

**Comment by chriscoffee** [comment]
I think we should still do the one tomorrow an hour later and see how the poll turns out. It also looks like you linked Azure devrel massive Slack chat Aaron, rather than a twitter link 😄 

> I posted a twitter poll to find some other times that work for folks: https://azure-advocacy.slack.com/archives/CADD7EPKL/p1551823850054600

**Comment by chriscoffee** [comment]
Moving this into v0.4.0 Planning. This is the Twitter link @arschles mentioned https://twitter.com/gomodsio/status/1103055161855959040

**Comment by arschles** [comment]
Here's the link to the tweet about today's meeting being one hour later: https://twitter.com/gomodsio/status/1103696159112028160

**Comment by arschles** [comment]
Ok, the poll at https://twitter.com/gomodsio/status/1103055161855959040 is over. The vote breakdown was:

- 43% for 20:00 UTC
- 34% for 22:00 UTC
- 23% 18:00 UTC

How do folks feel about rotating between 22:00 UTC on odd week numbers and 20:00 on even week numbers each month?

**Comment by fedepaol** [comment]
Sounds great to me

**Comment by arschles** [comment]
I am going to leave this vote open until the [next dev meeting](https://docs.google.com/document/d/1xpvgmR1Fq4iy1j975Tb4H_XjeXUQUOAvn0FximUzvIk/edit#heading=h.4mawhy3zg5im). We'll finalize what to do then

**Comment by Kunde21** [comment]
Something closer to 12UTC would be more workable for the ASEAN region.  Bangalore, Jakarta, Singapore, China, and Manila have a lot of developers and big/growing interest in Go.

**Comment by arschles** [comment]
ok, we finalized the vote for 22:00 UTC and 20:00 UTC rotating between weeks

I've created the following meetups to keep track:

- 20:00 UTC: https://www.meetup.com/The-Athens-Developer-Meeting/events/txvjvqyzgbhb/
- 22:00 UTC: https://www.meetup.com/The-Athens-Developer-Meeting/events/bdwjvqyzgbqb/

@Kunde21 This rotation is just a start, and I am going to start working on adding an ASEAN time as well. I'm going to close this ticket and open a new one focused on figuring out that rotation. I'll also DM you on Slack for some more advice on times, making it work, etc...
