### ISSUE TITLE
Add catalog method to missing storages

### ISSUE THREAD

**Issue by fedepaol** [gomods/athens#961]
**Is your feature request related to a problem? Please describe.**
With https://github.com/gomods/athens/pull/955 a new catalog endpoint has been introduced. 
Together with that, the Backend interface was enriched with a Cataloger interface.
That was implemented for file system backend, s3 and gcp. Azure, mongo and minio currently return a not implemented error.

**Describe the solution you'd like**
Implement the catalog method for the missing storages

**Comment by arschles** [comment]
It looks like the only storage backend that doesn't have a cataloger is azure storage, so I'm closing this in favor of #995
