### ISSUE TITLE
Add Deprecation tag

### ISSUE THREAD

**Issue by michalpristas** [gomods/athens#98]
Deprecation flag marks version as deprecated so it's not considered during minimal version selection process.

**Comment by michalpristas** [comment]
i think we can close this. it relates to event log
@arschles

**Comment by robjloranger** [comment]
Is this done? I've wondered about this, and the tombstone for deleted/deprecated. Olympus should also know what has been deprecated or deleted as well.

AFAIK this is not yet recorded anywhere for either Olympus or the Proxy.
