### ISSUE TITLE
Vote: Should we use : latest tag on docker hub

### ISSUE THREAD

**Issue by marpio** [gomods/athens#980]
At the moment the script that's pushing to docker hub sets :latest tag on every release:
 https://github.com/gomods/athens/blob/5ab820de96fa69c1a9e69119d9ca9e171b33667f/scripts/push-docker-images.sh#L25
There are pros and cons of using :latest and we should decide if we want to use it.

**Comment by marpio** [comment]
Yes, we should use :latest

**Comment by marpio** [comment]
No, we should not.

**Comment by marpio** [comment]
My take is that latest is ok as long as we release frequently and the gap between master and release isn't big.

**Comment by arschles** [comment]
@marpio I opened #989 to fix the script to push `latest` on pushes to `master` and `stable` on tag releases. We can merge if we vote yes on this issue 👍

**Comment by arschles** [comment]
@marpio @michalpristas @carolynvs I think we can close this because of the same reason we discussed https://github.com/gomods/athens/pull/989#issuecomment-454546871, what do you think?

**Comment by marpio** [comment]
:+1:
