### ISSUE TITLE
Proposal: Add filter rule for direct vcs fetch

### ISSUE THREAD

**Issue by leitzler** [gomods/athens#984]
I added a `D` filter rule with the impression that it would fetch all filtered repos directly from vcs source and not cache them. Apparently that not how `D` works.

The proposal is to add another filter rule to make athens skip caching certain repos. My use case is that I have an on-prem private repo that I don't want to be cached on my athens server. Since it is local it won't be much faster to cache it on another local server, and the repos might also contain sensitive code.

**Comment by michalpristas** [comment]
This would require a small redesign as the flow currently is
singleflight -> dp -> goget -> save to storage -> serve from storage

**Comment by marwan-at-work** [comment]
We can avoid a redesign by relying on https://github.com/golang/go/issues/26334 -- this way the proxy can have a filter wrapper that just 404s on given modules.

**Comment by lopezator** [comment]
@marwan-at-work the problem is that feature won't come until `1.13` (several months ago until then).  In case someone arrives here looking for a solution, the most feasible way in meantime is:

1. Cache private also repos
2. Add basic auth (if you need some privacy inside your network for your private repositories)

**Comment by arschles** [comment]
I'm removing this from v0.3.0 because this has some dependencies on the go toolchain (see above and https://github.com/golang/go/issues/26334)

**Comment by mwf** [comment]
Hi guys!

golang/go/issues/26334 is done now, but it doesn't help without some modification in Athens.

Now Athens responds with 500 on any error occurs, but the proxy switch will work only if proxy returns 404/410 status (according to commit message details in https://go-review.googlesource.com/c/go/+/173441/)

Could you please take it into account and modify error handling inside Athens?

**Comment by marwan-at-work** [comment]
@mwf there's an open PR that lets you specify for all not-found modules to return 404 or even based on import path patterns: https://github.com/gomods/athens/pull/1230

Thanks for reminding to tag this issue in my PR :)

**Comment by marwan-at-work** [comment]
@mwf this is now ready to be tested in the `canary` build. See https://docs.gomods.io/configuration/download/
