### ISSUE TITLE
How to remove a package from storage for security concern in a public proxy

### ISSUE THREAD

**Issue by flibustenet** [gomods/athens#993]
When packages are immutable and recorded in a public proxy/cdn, how will we do to remove one for security concern ?
For example I've my own repository with vanity import path. I use a public proxy. 
And now I've seen that i commited a password, how will I remove this repository ?

I've tested that when I remove a repository completely `@v/list` of the proxy doesn't answer anymore. But the `.zip` is still there.

Sorry for my english and also forgotten to edit the issue before validation.

**Comment by manugupt1** [comment]
Hi, While it is not possible to delete it. It is possible to exclude it altogether using a filter module

The docs are here:
https://docs.gomods.io/configuration/filter/

If this does not work, let us know!

**Comment by flibustenet** [comment]
@manugupt1 sorry i didn't explain my concern...

**Comment by manugupt1** [comment]
Do you mean that you have committed your password to public proxy? As of now, there is no way to delete it.

I will strongly recommend you to change the password. I will ask the maintainers about this use case.

**Comment by flibustenet** [comment]
No worry, it's just a question

**Comment by marpio** [comment]
Closing since it's replaced by #1004
