### ISSUE TITLE
Add catalog method to azure storage

### ISSUE THREAD

**Issue by fedepaol** [gomods/athens#995]
**Is your feature request related to a problem? Please describe.**
With #955 a new catalog endpoint has been introduced.
#961 was opened to add missing storages and mongo is on its way to be merged.

This issue is for implementing the cataloger interface in Azure

**Describe the solution you'd like**
Implement the cataloger in azure.

**Comment by Zyqsempai** [comment]
@scriptonist How is you progress with this one? I can take it if you changed your mind or doesn't have enough time.

**Comment by michalpristas** [comment]
@scriptonist ping ping. any progress here? if you're out of time let's allow @Zyqsempai to continue

**Comment by scriptonist** [comment]
Extremely Sorry for the delay @Zyqsempai @michalpristas, got caught up at work. @Zyqsempai please take this up because It will be difficult for me to find time in the next two weeks.

**Comment by Zyqsempai** [comment]
@scriptonist No worries. I will take care of it from here.

**Comment by michalpristas** [comment]
@scriptonist thanks for the reply. take care ;-)

**Comment by jamesgeorge007** [comment]
@Zyqsempai @michalpristas I'm new here. It would be great if I was allowed to take this up :+1: 
Also, can you guys guide me since I'm unaware of the code base :smile:

**Comment by jamesgeorge007** [comment]
@Zyqsempai @michalpristas I'm new here. It would be great if I was allowed to take this up :+1: 
Also, can you guys guide me since I'm not thataware of the code base :smile:

**Comment by jamesgeorge007** [comment]
@Zyqsempai @michalpristas I'm new here. It would be great if I was allowed to take this up :+1: 
Also, can you guys guide me since I'm not that aware of the code base :smile:

**Comment by jamesgeorge007** [comment]
@Zyqsempai @michalpristas I'm new here. It would be great if I was allowed to take this up :+1: 
Also, can you guys guide me as I'm not that aware of the code base :smile:

**Comment by jamesgeorge007** [comment]
@Zyqsempai @michalpristas I'm new here. It would be great if I was allowed to take this up :+1: 
Also, can you guys guide me as I'm not familiar with the code base :smile:

**Comment by manugupt1** [comment]
@jamesgeorge007 There is another issue that has not been claimed so far, can you please let @Zyqsempai take this while you work on the other one as he had already claimed it?

**Comment by jamesgeorge007** [comment]
@manugupt1 Ok fine :+1:

**Comment by jamesgeorge007** [comment]
@manugupt1 fine :+1:

**Comment by Zyqsempai** [comment]
Guys, any idea on: how we can test azure storage? We don't have any test for it currently,

**Comment by Zyqsempai** [comment]
@marpio Cool, can you reference this issue in that PR to monitor status. Coz i am kind of blocked here.

**Comment by arschles** [comment]
@Zyqsempai sorry for the delay on this. https://github.com/gomods/athens/pull/821 adds azurite for tetsting. I asked @chriscoffee if he's available to finish it. if he's busy I'll take it up so you can continue

**Comment by Zyqsempai** [comment]
@arschles Great. looking forward to finish this one.

**Comment by arschles** [comment]
@Zyqsempai now that #821 is merged, do you have everything you need? I know that there aren't any azure tests at all yet, so if you'd like we can work together there. Let me know what you think, and thanks for waiting 😁

**Comment by Zyqsempai** [comment]
@arschles Great news, I need to check what the status of my PR, it's been a while since I worked on it. I will come back to you with updates.

**Comment by arschles** [comment]
thanks @Zyqsempai! ❤️

**Comment by gowdabas** [comment]
I would like to work on this. Let me know if I can take this up:)

**Comment by marpio** [comment]
Please do @gowdabas ! 🎉 
Also while you're at it, take a look at https://github.com/gomods/athens/issues/1186
We are considering using the same format as https://index.golang.org/ for the V2 of our catalog endpoint.

**Comment by gowdabas** [comment]
Sure, thanks for pointing that out , @marpio .

**Comment by arschles** [comment]
FYI, if anyone needs to test this, you can use https://github.com/Azure/Azurite for local testing
