### ISSUE TITLE
Add catalog method to minio storage 

### ISSUE THREAD

**Issue by fedepaol** [gomods/athens#996]
**Is your feature request related to a problem? Please describe.**
With #955 a new catalog endpoint has been introduced.
#961 was opened to add missing storages and mongo is on its way to be merged.

This issue is for implementing the cataloger interface in minio.
It should be pretty straightforward since s3 is already implemented.

**Describe the solution you'd like**
Implement the cataloger in minio.

**Comment by Zyqsempai** [comment]
I can take it;)

**Comment by fedepaol** [comment]
Great. You could give a look at the S3 implementation to take inspiration
from.


Il giorno sab 29 dic 2018, 19:21 Boris Popovschi <notifications@github.com>
ha scritto:

**Comment by Zyqsempai** [comment]
@fedepaol I faced few difficulties on my way to implement Catalog method:
First, one I mentioned above in new issue, the second is that fact that minioClient.ListObjectsV2 and ListObjects, don't want to continue list from specific key(module version), so we easily can fetch 1001 item but we can't continue from last module and fetch for example next 5.

**Comment by fedepaol** [comment]
Not sure I understood.
Can you provide a failing test?

**Comment by fedepaol** [comment]
Sorry for the late reply and for the dismissive reply I gave before.
I gave a look at the minio client. Even if the docs describes only the Client struct with its method, looking at the sources there is also this Core struct that exposes lower level methods such one similar to the one we are using against S3. I'd suggest you to try to use [Core.ListObjectsV2](https://github.com/minio/minio-go/blob/master/core.go#L54)

**Comment by Zyqsempai** [comment]
Thanks, I will try it and get with feedback.

**Comment by Zyqsempai** [comment]
@fedepaol So, i opened PR, but it still has one big problem, performance.
Honestly, have no clue why every minio function works so slow.
274.693178ms
368.370131ms
346.225552ms

Here is a few examples, this is minioCore.ListObjectsV2 function, but minioClient.ListObjectsV2 doesn't show the better results.

**Comment by manugupt1** [comment]
Does ListObjectV2 download entire object, if so that can explain the slowness?
Which storage did you use against minio to take these benchmarks?

**Comment by Zyqsempai** [comment]
@manugupt1 Sorry, i didn't make it clear, those benchmarks above are from simple unit test.
That's why i am so frustrated.
Maybe i am missing something.

**Comment by Zyqsempai** [comment]
Yeah, but other storages handle 1000+ without any trouble, fast enough.
