### ISSUE TITLE
Official MongoDB Go Driver

### ISSUE THREAD

**Issue by chriscoffee** [gomods/athens#998]
The official MongoDB Go driver just hit beta. Looking forward we could look to replace the current globalsign/mgo package we use.

https://github.com/mongodb/mongo-go-driver/releases/tag/v0.1.0

**Comment by arpitgogia** [comment]
Hi @chriscoffee I would like to take up on the `good-first-issue` badge and volunteer for this task 😅

**Comment by marpio** [comment]
Awesome @arpitgogia ! It's yours!

**Comment by robstrong** [comment]
Can this issue be closed now that #1042 is merged?

**Comment by marpio** [comment]
Yes. Thank for the reminder.
